import type { StoryTree } from "./types";

// Branching story tree for the "candy" template (El País de los Dulces).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es source of truth + ca/en/fr). {name} = child's name.

export const candyTree: StoryTree = {
  templateId: "candy",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} cruza la Puerta de Caramelo y entra en el País de los Dulces, donde el aire huele a vainilla y chocolate. Tres sorpresas dulces asoman en el camino. ¿Cuál descubre primero?",
        ca: "{name} creua la Porta de Caramel i entra al País dels Dolços, on l'aire fa olor de vainilla i xocolata. Tres sorpreses dolces apareixen pel camí. Quina descobreix primer?",
        en: "{name} steps through the Candy Gate into the Land of Sweets, where the air smells of vanilla and chocolate. Three sweet surprises appear along the path. Which one to discover first?",
        fr: "{name} franchit la Porte en Caramel et entre au Pays des Bonbons, où l'air sent la vanille et le chocolat. Trois douces surprises apparaissent sur le chemin. Laquelle découvrir en premier ?",
      },
      options: [
        {
          id: "gummy-bear",
          title: {
            es: "El osito de gominola",
            ca: "L'osset de gominola",
            en: "The gummy bear",
            fr: "L'ourson gélifié",
          },
          desc: {
            es: "Un osito de gominola rojo suspira sentado en una seta de malvavisco.",
            ca: "Un osset de gominola vermell sospira assegut sobre un bolet de núvol de sucre.",
            en: "A little red gummy bear sighs, sitting on a marshmallow mushroom.",
            fr: "Un petit ourson gélifié rouge soupire, assis sur un champignon de guimauve.",
          },
          imageSeed: "candy-c1-gummy",
          icon: "cruelty_free",
          narrative: {
            es: "{name} se acerca despacito a un osito de gominola rojo que suspira sentado en una seta de malvavisco.",
            ca: "{name} s'acosta a poc a poc a un osset de gominola vermell que sospira assegut sobre un bolet de núvol de sucre.",
            en: "{name} walks up gently to a little red gummy bear sighing on a marshmallow mushroom.",
            fr: "{name} s'approche tout doucement d'un petit ourson gélifié rouge qui soupire, assis sur un champignon de guimauve.",
          },
          next: "c2_gummy",
        },
        {
          id: "flavor-jar",
          title: {
            es: "El tarro de los mil sabores",
            ca: "El pot dels mil sabors",
            en: "The jar of a thousand flavours",
            fr: "Le pot aux mille saveurs",
          },
          desc: {
            es: "Un tarro de cristal brilla con lucecitas de colores sobre un pedestal de turrón, casi vacío.",
            ca: "Un pot de vidre brilla amb llumetes de colors sobre un pedestal de torró, gairebé buit.",
            en: "A glass jar glows with little coloured lights on a nougat pedestal, almost empty.",
            fr: "Un pot en verre brille de petites lumières colorées sur un socle de nougat, presque vide.",
          },
          imageSeed: "candy-c1-jar",
          icon: "science",
          narrative: {
            es: "{name} descubre un tarro de cristal que parpadea con lucecitas de colores sobre un pedestal de turrón.",
            ca: "{name} descobreix un pot de vidre que parpelleja amb llumetes de colors sobre un pedestal de torró.",
            en: "{name} discovers a glass jar blinking with little coloured lights on a nougat pedestal.",
            fr: "{name} découvre un pot en verre qui clignote de petites lumières colorées sur un socle de nougat.",
          },
          next: "c2_jar",
        },
        {
          id: "candy-bridge",
          title: {
            es: "El puente de bastón de caramelo",
            ca: "El pont de bastó de caramel",
            en: "The candy cane bridge",
            fr: "Le pont en sucre d'orge",
          },
          desc: {
            es: "Un puente de rayas rojas y blancas cruza el río de chocolate hacia un pueblecito dulce.",
            ca: "Un pont de ratlles vermelles i blanques creua el riu de xocolata cap a un poblet dolç.",
            en: "A red-and-white striped bridge crosses the chocolate river towards a sweet little village.",
            fr: "Un pont rayé rouge et blanc traverse la rivière de chocolat vers un petit village sucré.",
          },
          imageSeed: "candy-c1-bridge",
          icon: "signpost",
          narrative: {
            es: "{name} pisa con cuidado el puente de bastón de caramelo que cruza el río de chocolate caliente hacia el Pueblo de Caramelo.",
            ca: "{name} trepitja amb cura el pont de bastó de caramel que creua el riu de xocolata calenta cap al Poble de Caramel.",
            en: "{name} steps carefully onto the candy cane bridge crossing the warm chocolate river towards Candy Village.",
            fr: "{name} pose le pied avec précaution sur le pont en sucre d'orge qui traverse la rivière de chocolat chaud vers le Village des Bonbons.",
          },
          next: "c2_bridge",
        },
      ],
    },
    c2_gummy: {
      id: "c2_gummy",
      chapter: 2,
      question: {
        es: "El osito dice que se llama Gomi. Está triste: esta noche es la Gran Merienda Compartida y debe tocar la Campana de Azúcar para invitar a todos, ¡pero la perla de caramelo de la campana ha rodado y se ha perdido! ¿Dónde la buscan {name} y Gomi?",
        ca: "L'osset diu que es diu Gomi. Està trist: aquesta nit és el Gran Berenar Compartit i ha de tocar la Campana de Sucre per convidar tothom, però la perla de caramel de la campana ha rodolat i s'ha perdut! On la busquen {name} i en Gomi?",
        en: "The little bear says his name is Gomi. He is sad: tonight is the Great Sharing Picnic and he must ring the Sugar Bell to invite everyone, but the bell's caramel pearl has rolled away and is lost! Where do {name} and Gomi look for it?",
        fr: "Le petit ourson dit qu'il s'appelle Gomi. Il est triste : ce soir, c'est le Grand Goûter Partagé et il doit sonner la Cloche de Sucre pour inviter tout le monde, mais la perle de caramel de la cloche a roulé et s'est perdue ! Où {name} et Gomi vont-ils la chercher ?",
      },
      options: [
        {
          id: "marshmallow-hill",
          title: {
            es: "La colina de malvaviscos",
            ca: "El turó de núvols de sucre",
            en: "Marshmallow Hill",
            fr: "La colline de guimauve",
          },
          desc: {
            es: "Una colina blandita donde todo lo que cae rebota y rebota sin parar.",
            ca: "Un turó tou on tot el que hi cau rebota i rebota sense parar.",
            en: "A squishy hill where everything that lands bounces and bounces without stopping.",
            fr: "Une colline toute molle où tout ce qui tombe rebondit et rebondit sans s'arrêter.",
          },
          imageSeed: "candy-c2gummy-hill",
          icon: "landscape",
          narrative: {
            es: "{name} y Gomi suben a la colina de malvaviscos, donde cada paso rebota como en un colchón gigante.",
            ca: "{name} i en Gomi pugen al turó de núvols de sucre, on cada pas rebota com en un matalàs gegant.",
            en: "{name} and Gomi climb Marshmallow Hill, where every step bounces like on a giant mattress.",
            fr: "{name} et Gomi montent sur la colline de guimauve, où chaque pas rebondit comme sur un matelas géant.",
          },
          next: "c3_gummy_a",
        },
        {
          id: "chocolate-river",
          title: {
            es: "El río de chocolate",
            ca: "El riu de xocolata",
            en: "The chocolate river",
            fr: "La rivière de chocolat",
          },
          desc: {
            es: "Algo redondo y brillante descansa en una islita de malvavisco en medio del río.",
            ca: "Alguna cosa rodona i brillant descansa en una illeta de núvol de sucre al mig del riu.",
            en: "Something round and shiny rests on a little marshmallow island in the middle of the river.",
            fr: "Quelque chose de rond et de brillant repose sur une petite île de guimauve au milieu de la rivière.",
          },
          imageSeed: "candy-c2gummy-river",
          icon: "waves",
          narrative: {
            es: "{name} y Gomi siguen el río de chocolate caliente y ven la perla brillando en una islita de malvavisco.",
            ca: "{name} i en Gomi segueixen el riu de xocolata calenta i veuen la perla brillant en una illeta de núvol de sucre.",
            en: "{name} and Gomi follow the warm chocolate river and spot the pearl shining on a little marshmallow island.",
            fr: "{name} et Gomi suivent la rivière de chocolat chaud et aperçoivent la perle qui brille sur une petite île de guimauve.",
          },
          next: "c3_gummy_b",
        },
        {
          id: "candy-market",
          title: {
            es: "El mercado de los dulces",
            ca: "El mercat dels dolços",
            en: "The sweets market",
            fr: "Le marché aux bonbons",
          },
          desc: {
            es: "Un caracol de caramelo colecciona cositas redondas y brillantes en su puestecito.",
            ca: "Un cargol de caramel col·lecciona cosetes rodones i brillants a la seva parada.",
            en: "A caramel snail collects round, shiny little things at its market stall.",
            fr: "Un escargot en caramel collectionne de petites choses rondes et brillantes sur son étal.",
          },
          imageSeed: "candy-c2gummy-market",
          icon: "storefront",
          narrative: {
            es: "{name} y Gomi llegan al mercado de los dulces y descubren la perla brillando en el puestecito de un caracol de caramelo.",
            ca: "{name} i en Gomi arriben al mercat dels dolços i descobreixen la perla brillant a la parada d'un cargol de caramel.",
            en: "{name} and Gomi reach the sweets market and discover the pearl shining on a caramel snail's little stall.",
            fr: "{name} et Gomi arrivent au marché aux bonbons et découvrent la perle qui brille sur l'étal d'un escargot en caramel.",
          },
          next: "c3_gummy_c",
        },
      ],
    },
    c2_jar: {
      id: "c2_jar",
      chapter: 2,
      question: {
        es: "El tarro susurra: 'Soy el Tarro de los Mil Sabores y doy su sabor a todos los dulces del país... pero me estoy quedando vacío. Solo el azúcar de estrella puede llenarme'. {name} decide encontrarlo. ¿Por dónde empieza?",
        ca: "El pot xiuxiueja: 'Soc el Pot dels Mil Sabors i dono el seu sabor a tots els dolços del país... però m'estic quedant buit. Només el sucre d'estrella em pot omplir'. {name} decideix trobar-lo. Per on comença?",
        en: "The jar whispers: 'I am the Jar of a Thousand Flavours and I give every sweet in the land its taste... but I am running empty. Only star sugar can fill me up.' {name} decides to find it. Where to start?",
        fr: "Le pot chuchote : « Je suis le Pot aux Mille Saveurs et je donne son goût à tous les bonbons du pays... mais je me vide. Seul le sucre d'étoile peut me remplir. » {name} décide d'en trouver. Par où commencer ?",
      },
      options: [
        {
          id: "caramel-waterfall",
          title: {
            es: "La cascada de caramelo",
            ca: "La cascada de caramel",
            en: "The caramel waterfall",
            fr: "La cascade de caramel",
          },
          desc: {
            es: "Cada atardecer, una gota dorada de azúcar de estrella baja brillando por la cascada.",
            ca: "Cada capvespre, una gota daurada de sucre d'estrella baixa brillant per la cascada.",
            en: "Every sunset, a golden drop of star sugar slides down the waterfall, sparkling.",
            fr: "Chaque soir, une goutte dorée de sucre d'étoile descend la cascade en scintillant.",
          },
          imageSeed: "candy-c2jar-waterfall",
          icon: "water_drop",
          narrative: {
            es: "{name} camina hasta la gran cascada de caramelo dorado, donde el aire huele a azúcar tostado.",
            ca: "{name} camina fins a la gran cascada de caramel daurat, on l'aire fa olor de sucre torrat.",
            en: "{name} walks to the great golden caramel waterfall, where the air smells of toasted sugar.",
            fr: "{name} marche jusqu'à la grande cascade de caramel doré, où l'air sent le sucre grillé.",
          },
          next: "c3_jar_a",
        },
        {
          id: "sugar-bees",
          title: {
            es: "Las abejas de azúcar",
            ca: "Les abelles de sucre",
            en: "The sugar bees",
            fr: "Les abeilles de sucre",
          },
          desc: {
            es: "En su panal de barquillo guardan miel de estrella, la más dulce del país.",
            ca: "Al seu rusc de neula hi guarden mel d'estrella, la més dolça del país.",
            en: "In their wafer hive they keep star honey, the sweetest in the land.",
            fr: "Dans leur ruche en gaufrette, elles gardent du miel d'étoile, le plus doux du pays.",
          },
          imageSeed: "candy-c2jar-hive",
          icon: "hive",
          narrative: {
            es: "{name} llega al panal de barquillo donde las abejas de azúcar zumban haciendo su miel de estrella.",
            ca: "{name} arriba al rusc de neula on les abelles de sucre brunzeixen fent la seva mel d'estrella.",
            en: "{name} arrives at the wafer hive where the sugar bees buzz, making their star honey.",
            fr: "{name} arrive à la ruche en gaufrette où les abeilles de sucre bourdonnent en préparant leur miel d'étoile.",
          },
          next: "c3_jar_b",
        },
        {
          id: "crystal-cave",
          title: {
            es: "La cueva de cristales de azúcar",
            ca: "La cova de cristalls de sucre",
            en: "The sugar crystal cave",
            fr: "La grotte aux cristaux de sucre",
          },
          desc: {
            es: "Entre cientos de cristales dulces se esconde uno con forma de estrella.",
            ca: "Entre centenars de cristalls dolços s'hi amaga un amb forma d'estrella.",
            en: "Among hundreds of sweet crystals hides one shaped like a star.",
            fr: "Parmi des centaines de cristaux sucrés se cache un cristal en forme d'étoile.",
          },
          imageSeed: "candy-c2jar-cave",
          icon: "diamond",
          narrative: {
            es: "{name} entra en una cueva donde brillan cientos de cristales de azúcar de todos los colores.",
            ca: "{name} entra en una cova on brillen centenars de cristalls de sucre de tots els colors.",
            en: "{name} enters a cave where hundreds of sugar crystals glow in every colour.",
            fr: "{name} entre dans une grotte où brillent des centaines de cristaux de sucre de toutes les couleurs.",
          },
          next: "c3_jar_c",
        },
      ],
    },
    c2_bridge: {
      id: "c2_bridge",
      chapter: 2,
      question: {
        es: "Al otro lado del puente, {name} llega a la plaza del Pueblo de Caramelo... ¡pero la Gran Fuente de Chocolate se ha parado! Esta noche todos llenan juntos sus tazas en la Fiesta de la Merienda. Una pastelera de mazapán le pide ayuda. ¿Por dónde empiezan?",
        ca: "A l'altra banda del pont, {name} arriba a la plaça del Poble de Caramel... però la Gran Font de Xocolata s'ha aturat! Aquesta nit tothom omple les tasses plegats a la Festa del Berenar. Una pastissera de massapà li demana ajuda. Per on comencen?",
        en: "On the other side of the bridge, {name} reaches the square of Candy Village... but the Great Chocolate Fountain has stopped! Tonight everyone fills their cups together at the Snack-time Feast. A marzipan baker asks for help. Where do they begin?",
        fr: "De l'autre côté du pont, {name} arrive sur la place du Village des Bonbons... mais la Grande Fontaine de Chocolat s'est arrêtée ! Ce soir, tout le monde remplit sa tasse ensemble à la Fête du Goûter. Une pâtissière en massepain demande de l'aide. Par où commencer ?",
      },
      options: [
        {
          id: "cocoa-windmill",
          title: {
            es: "El molino de cacao",
            ca: "El molí de cacau",
            en: "The cocoa windmill",
            fr: "Le moulin à cacao",
          },
          desc: {
            es: "Sus aspas de galleta remueven el chocolate, pero se han quedado quietas.",
            ca: "Les seves aspes de galeta remenen la xocolata, però s'han quedat quietes.",
            en: "Its cookie sails stir the chocolate, but they have stopped still.",
            fr: "Ses ailes en biscuit remuent le chocolat, mais elles se sont arrêtées.",
          },
          imageSeed: "candy-c2bridge-windmill",
          icon: "wind_power",
          narrative: {
            es: "{name} y la pastelera suben al molino de cacao, cuyas aspas de galleta están quietas y pegajosas.",
            ca: "{name} i la pastissera pugen al molí de cacau, que té les aspes de galeta quietes i enganxoses.",
            en: "{name} and the baker climb up to the cocoa windmill, whose cookie sails sit still and sticky.",
            fr: "{name} et la pâtissière montent au moulin à cacao, dont les ailes en biscuit sont immobiles et collantes.",
          },
          next: "c3_bridge_a",
        },
        {
          id: "licorice-pipes",
          title: {
            es: "Las tuberías de regaliz",
            ca: "Les canonades de regalèssia",
            en: "The licorice pipes",
            fr: "Les tuyaux de réglisse",
          },
          desc: {
            es: "Las tuberías que llevan el chocolate hacen 'glu-glu': algo está atascado dentro.",
            ca: "Les canonades que porten la xocolata fan 'glu-glu': alguna cosa hi ha quedat encallada dins.",
            en: "The pipes that carry the chocolate go 'glug-glug': something is stuck inside.",
            fr: "Les tuyaux qui transportent le chocolat font « glou-glou » : quelque chose est coincé à l'intérieur.",
          },
          imageSeed: "candy-c2bridge-pipes",
          icon: "plumbing",
          narrative: {
            es: "{name} y la pastelera siguen las tuberías de regaliz hasta encontrar el tramo que hace 'glu-glu'.",
            ca: "{name} i la pastissera segueixen les canonades de regalèssia fins a trobar el tram que fa 'glu-glu'.",
            en: "{name} and the baker follow the licorice pipes until they find the part that goes 'glug-glug'.",
            fr: "{name} et la pâtissière suivent les tuyaux de réglisse jusqu'à trouver le tronçon qui fait « glou-glou ».",
          },
          next: "c3_bridge_b",
        },
        {
          id: "milk-cloud",
          title: {
            es: "La nube de leche",
            ca: "El núvol de llet",
            en: "The milk cloud",
            fr: "Le nuage de lait",
          },
          desc: {
            es: "La nubecita que vierte la leche en la fuente se ha ido a lo alto de la Montaña de Helado.",
            ca: "El nuvolet que aboca la llet a la font se n'ha anat a dalt de la Muntanya de Gelat.",
            en: "The little cloud that pours milk into the fountain has drifted to the top of Ice Cream Mountain.",
            fr: "Le petit nuage qui verse le lait dans la fontaine est parti en haut de la Montagne de Glace.",
          },
          imageSeed: "candy-c2bridge-cloud",
          icon: "cloud",
          narrative: {
            es: "{name} y la pastelera miran hacia la Montaña de Helado, donde la nubecita de leche flota sola y despacito.",
            ca: "{name} i la pastissera miren cap a la Muntanya de Gelat, on el nuvolet de llet flota solet i a poc a poc.",
            en: "{name} and the baker look up at Ice Cream Mountain, where the little milk cloud floats alone and slow.",
            fr: "{name} et la pâtissière regardent vers la Montagne de Glace, où le petit nuage de lait flotte tout seul, tout doucement.",
          },
          next: "c3_bridge_c",
        },
      ],
    },
    c3_gummy_a: {
      id: "c3_gummy_a",
      chapter: 3,
      question: {
        es: "¡Allí está la perla! Pero rebota de malvavisco en malvavisco sin parar ni un segundo. ¿Cómo la atrapa {name}?",
        ca: "Allà hi ha la perla! Però rebota de núvol en núvol sense parar ni un segon. Com l'atrapa {name}?",
        en: "There's the pearl! But it bounces from marshmallow to marshmallow without stopping for a second. How does {name} catch it?",
        fr: "Voilà la perle ! Mais elle rebondit de guimauve en guimauve sans s'arrêter une seconde. Comment {name} va l'attraper ?",
      },
      options: [
        {
          id: "bounce-along",
          title: {
            es: "Saltar a su ritmo",
            ca: "Saltar al seu ritme",
            en: "Bounce along with it",
            fr: "Sauter à son rythme",
          },
          desc: {
            es: "Quien rebota igual que la perla puede cogerla en el aire.",
            ca: "Qui rebota igual que la perla la pot agafar a l'aire.",
            en: "Whoever bounces just like the pearl can catch it mid-air.",
            fr: "Qui rebondit comme la perle peut l'attraper en plein vol.",
          },
          imageSeed: "candy-c3gummya-jump",
          icon: "sports_gymnastics",
          narrative: {
            es: "{name} salta de malvavisco en malvavisco siguiendo el ritmo de la perla y la atrapa en el aire con las dos manos.",
            ca: "{name} salta de núvol en núvol seguint el ritme de la perla i l'atrapa a l'aire amb les dues mans.",
            en: "{name} bounces from marshmallow to marshmallow in rhythm with the pearl and catches it mid-air with both hands.",
            fr: "{name} saute de guimauve en guimauve au rythme de la perle et l'attrape en plein vol à deux mains.",
          },
          next: "ending",
        },
        {
          id: "statue-game",
          title: {
            es: "Jugar a las estatuas",
            ca: "Jugar a les estàtues",
            en: "Play the statue game",
            fr: "Jouer aux statues",
          },
          desc: {
            es: "Si los malvaviscos se quedan quietos como estatuas, la perla dejará de rebotar.",
            ca: "Si els núvols de sucre es queden quiets com estàtues, la perla deixarà de rebotar.",
            en: "If the marshmallows stand still like statues, the pearl will stop bouncing.",
            fr: "Si les guimauves restent immobiles comme des statues, la perle cessera de rebondir.",
          },
          imageSeed: "candy-c3gummya-freeze",
          icon: "back_hand",
          narrative: {
            es: "{name} propone jugar a las estatuas y, cuando todos los malvaviscos se quedan quietos, la perla rueda suavemente hasta sus pies.",
            ca: "{name} proposa jugar a les estàtues i, quan tots els núvols de sucre es queden quiets, la perla rodola suaument fins als seus peus.",
            en: "{name} starts a game of statues and, when all the marshmallows freeze, the pearl rolls gently right up to their feet.",
            fr: "{name} propose de jouer aux statues et, quand toutes les guimauves s'immobilisent, la perle roule doucement jusqu'à ses pieds.",
          },
          next: "ending",
        },
        {
          id: "cotton-candy-net",
          title: {
            es: "Una red de algodón de azúcar",
            ca: "Una xarxa de cotó de sucre",
            en: "A cotton candy net",
            fr: "Un filet de barbe à papa",
          },
          desc: {
            es: "Con hilos de algodón de azúcar se puede tejer la red más suave del mundo.",
            ca: "Amb fils de cotó de sucre es pot teixir la xarxa més suau del món.",
            en: "With cotton candy threads you can weave the softest net in the world.",
            fr: "Avec des fils de barbe à papa, on peut tisser le filet le plus doux du monde.",
          },
          imageSeed: "candy-c3gummya-net",
          icon: "blur_on",
          narrative: {
            es: "{name} y Gomi tejen una red rosa de algodón de azúcar y recogen la perla en pleno rebote, blandita y a salvo.",
            ca: "{name} i en Gomi teixeixen una xarxa rosa de cotó de sucre i recullen la perla en ple rebot, tova i fora de perill.",
            en: "{name} and Gomi weave a pink cotton candy net and scoop up the pearl mid-bounce, soft and safe.",
            fr: "{name} et Gomi tissent un filet rose de barbe à papa et recueillent la perle en plein rebond, toute douce et bien à l'abri.",
          },
          next: "ending",
        },
      ],
    },
    c3_gummy_b: {
      id: "c3_gummy_b",
      chapter: 3,
      question: {
        es: "La perla brilla en la islita, pero el río de chocolate es ancho y baja calentito y deprisa. ¿Cómo llega {name} hasta ella?",
        ca: "La perla brilla a l'illeta, però el riu de xocolata és ample i baixa calentó i de pressa. Com hi arriba {name}?",
        en: "The pearl shines on the little island, but the chocolate river is wide and runs warm and fast. How does {name} reach it?",
        fr: "La perle brille sur la petite île, mais la rivière de chocolat est large et coule, chaude et rapide. Comment {name} va l'atteindre ?",
      },
      options: [
        {
          id: "gummy-raft",
          title: {
            es: "Una balsa de gominolas",
            ca: "Un rai de gominoles",
            en: "A gummy raft",
            fr: "Un radeau de bonbons gélifiés",
          },
          desc: {
            es: "Las gominolas gigantes flotan de maravilla sobre el chocolate.",
            ca: "Les gominoles gegants floten d'allò més bé sobre la xocolata.",
            en: "Giant gummies float wonderfully on chocolate.",
            fr: "Les gros bonbons gélifiés flottent à merveille sur le chocolat.",
          },
          imageSeed: "candy-c3gummyb-raft",
          icon: "sailing",
          narrative: {
            es: "{name} ata gominolas gigantes con hilos de regaliz, rema hasta la islita y recoge la perla brillante.",
            ca: "{name} lliga gominoles gegants amb fils de regalèssia, rema fins a l'illeta i recull la perla brillant.",
            en: "{name} ties giant gummies together with licorice strings, paddles to the little island and picks up the shining pearl.",
            fr: "{name} attache de gros bonbons gélifiés avec des fils de réglisse, pagaie jusqu'à la petite île et ramasse la perle brillante.",
          },
          next: "ending",
        },
        {
          id: "cookie-stepping-stones",
          title: {
            es: "Pasitos de galleta",
            ca: "Passets de galeta",
            en: "Cookie stepping stones",
            fr: "Des pas de biscuit",
          },
          desc: {
            es: "Galleta a galleta se puede cruzar hasta el centro del río.",
            ca: "Galeta a galeta es pot creuar fins al centre del riu.",
            en: "Cookie by cookie you can cross to the middle of the river.",
            fr: "Biscuit après biscuit, on peut traverser jusqu'au milieu de la rivière.",
          },
          imageSeed: "candy-c3gummyb-cookies",
          icon: "construction",
          narrative: {
            es: "{name} coloca galletas grandotas una a una sobre el chocolate, cruza pasito a pasito y alcanza la perla con la mano.",
            ca: "{name} col·loca galetes grosses una a una sobre la xocolata, creua passet a passet i agafa la perla amb la mà.",
            en: "{name} lays big cookies one by one across the chocolate, crosses step by little step and grabs the pearl.",
            fr: "{name} pose de grands biscuits un à un sur le chocolat, traverse à tout petits pas et attrape la perle avec la main.",
          },
          next: "ending",
        },
        {
          id: "gummy-fish",
          title: {
            es: "Pedir ayuda a los peces de gominola",
            ca: "Demanar ajuda als peixos de gominola",
            en: "Ask the gummy fish for help",
            fr: "Demander de l'aide aux poissons gélifiés",
          },
          desc: {
            es: "Los peces de gominola saltan y nadan mejor que nadie en el chocolate.",
            ca: "Els peixos de gominola salten i neden millor que ningú a la xocolata.",
            en: "The gummy fish jump and swim better than anyone in the chocolate.",
            fr: "Les poissons gélifiés sautent et nagent mieux que personne dans le chocolat.",
          },
          imageSeed: "candy-c3gummyb-fish",
          icon: "waves",
          narrative: {
            es: "{name} invita a los peces de gominola a la Gran Merienda y ellos, contentísimos, nadan hasta la islita y traen la perla de vuelta.",
            ca: "{name} convida els peixos de gominola al Gran Berenar i ells, contentíssims, neden fins a l'illeta i porten la perla de tornada.",
            en: "{name} invites the gummy fish to the Great Picnic and, delighted, they swim to the little island and bring the pearl back.",
            fr: "{name} invite les poissons gélifiés au Grand Goûter et, tout contents, ils nagent jusqu'à la petite île et rapportent la perle.",
          },
          next: "ending",
        },
      ],
    },
    c3_gummy_c: {
      id: "c3_gummy_c",
      chapter: 3,
      question: {
        es: "Al caracol de caramelo le encanta la perla: '¡Rueda tan bonito!', dice. No quiere dársela así como así. ¿Qué hace {name}?",
        ca: "Al cargol de caramel li encanta la perla: 'Rodola tan bonic!', diu. No la vol donar així com així. Què fa {name}?",
        en: "The caramel snail loves the pearl: 'It rolls so beautifully!' it says. It won't just hand it over. What does {name} do?",
        fr: "L'escargot en caramel adore la perle : « Elle roule si joliment ! » dit-il. Il ne veut pas la donner comme ça. Que fait {name} ?",
      },
      options: [
        {
          id: "shiny-trade",
          title: {
            es: "Cambiarla por una canica de caramelo",
            ca: "Canviar-la per una bala de caramel",
            en: "Trade it for a candy marble",
            fr: "L'échanger contre une bille en sucre",
          },
          desc: {
            es: "Una canica brillante de mil colores rueda incluso mejor que la perla.",
            ca: "Una bala brillant de mil colors rodola encara millor que la perla.",
            en: "A shiny thousand-colour marble rolls even better than the pearl.",
            fr: "Une bille brillante aux mille couleurs roule encore mieux que la perle.",
          },
          imageSeed: "candy-c3gummyc-trade",
          icon: "swap_horiz",
          narrative: {
            es: "{name} encuentra una canica de caramelo de mil colores y se la cambia al caracol por la perla de la campana.",
            ca: "{name} troba una bala de caramel de mil colors i la canvia al cargol per la perla de la campana.",
            en: "{name} finds a thousand-colour candy marble and trades it with the snail for the bell's pearl.",
            fr: "{name} trouve une bille en sucre aux mille couleurs et l'échange avec l'escargot contre la perle de la cloche.",
          },
          next: "ending",
        },
        {
          id: "tidy-stall",
          title: {
            es: "Ordenar su puestecito",
            ca: "Endreçar la seva parada",
            en: "Tidy its little stall",
            fr: "Ranger son étal",
          },
          desc: {
            es: "El puesto del caracol está patas arriba y él va muy despacito.",
            ca: "La parada del cargol està potes enlaire i ell va molt a poc a poc.",
            en: "The snail's stall is upside down and the snail moves very slowly.",
            fr: "L'étal de l'escargot est sens dessus dessous et lui avance très lentement.",
          },
          imageSeed: "candy-c3gummyc-tidy",
          icon: "inventory_2",
          narrative: {
            es: "{name} ayuda al caracol a ordenar todos sus tesoros brillantes y él, agradecido, le regala la perla de caramelo.",
            ca: "{name} ajuda el cargol a endreçar tots els seus tresors brillants i ell, agraït, li regala la perla de caramel.",
            en: "{name} helps the snail tidy all its shiny treasures and, grateful, it gifts the caramel pearl.",
            fr: "{name} aide l'escargot à ranger tous ses trésors brillants et celui-ci, reconnaissant, lui offre la perle de caramel.",
          },
          next: "ending",
        },
        {
          id: "invite-snail",
          title: {
            es: "Invitarlo a la Gran Merienda",
            ca: "Convidar-lo al Gran Berenar",
            en: "Invite it to the Great Picnic",
            fr: "L'inviter au Grand Goûter",
          },
          desc: {
            es: "El caracol nunca llega a tiempo a las fiestas porque va despacito.",
            ca: "El cargol mai no arriba a temps a les festes perquè va a poc a poc.",
            en: "The snail never gets to parties on time because it moves so slowly.",
            fr: "L'escargot n'arrive jamais à temps aux fêtes parce qu'il avance lentement.",
          },
          imageSeed: "candy-c3gummyc-invite",
          icon: "volunteer_activism",
          narrative: {
            es: "{name} invita al caracol a la Gran Merienda y promete llevarlo a hombros; él, feliz, entrega la perla para que la campana suene.",
            ca: "{name} convida el cargol al Gran Berenar i promet portar-lo a coll; ell, feliç, entrega la perla perquè la campana soni.",
            en: "{name} invites the snail to the Great Picnic and promises to carry it there; overjoyed, it hands over the pearl so the bell can ring.",
            fr: "{name} invite l'escargot au Grand Goûter et promet de le porter sur ses épaules ; tout heureux, il donne la perle pour que la cloche sonne.",
          },
          next: "ending",
        },
      ],
    },
    c3_jar_a: {
      id: "c3_jar_a",
      chapter: 3,
      question: {
        es: "Cada atardecer, una sola gota dorada de azúcar de estrella baja por la cascada... ¡y va rapidísima! ¿Cómo la consigue {name}?",
        ca: "Cada capvespre, una sola gota daurada de sucre d'estrella baixa per la cascada... i va rapidíssima! Com l'aconsegueix {name}?",
        en: "Every sunset, a single golden drop of star sugar slides down the waterfall... and it goes so fast! How does {name} catch it?",
        fr: "Chaque soir, une seule goutte dorée de sucre d'étoile descend la cascade... et elle va très vite ! Comment {name} va la récupérer ?",
      },
      options: [
        {
          id: "waterfall-lullaby",
          title: {
            es: "Cantarle una nana a la cascada",
            ca: "Cantar una cançó de bressol a la cascada",
            en: "Sing the waterfall a lullaby",
            fr: "Chanter une berceuse à la cascade",
          },
          desc: {
            es: "Con una canción tranquila, el caramelo baja despacito, como dormido.",
            ca: "Amb una cançó tranquil·la, el caramel baixa a poc a poc, com adormit.",
            en: "With a calm song, the caramel flows down slowly, as if asleep.",
            fr: "Avec une chanson calme, le caramel descend lentement, comme endormi.",
          },
          imageSeed: "candy-c3jara-lullaby",
          icon: "music_note",
          narrative: {
            es: "{name} canta una nana suave y la cascada de caramelo baja tan despacito que la gota dorada se posa en su mano.",
            ca: "{name} canta una cançó de bressol suau i la cascada de caramel baixa tan a poc a poc que la gota daurada es posa a la seva mà.",
            en: "{name} sings a soft lullaby and the caramel waterfall slows down so much that the golden drop lands in their hand.",
            fr: "{name} chante une douce berceuse et la cascade de caramel ralentit tellement que la goutte dorée se pose dans sa main.",
          },
          next: "ending",
        },
        {
          id: "wafer-cone",
          title: {
            es: "Un cucurucho de barquillo",
            ca: "Un cucurutxo de neula",
            en: "A wafer cone",
            fr: "Un cornet de gaufrette",
          },
          desc: {
            es: "En el momento justo, un cucurucho puede recoger la gota al vuelo.",
            ca: "En el moment just, un cucurutxo pot recollir la gota al vol.",
            en: "At just the right moment, a cone can catch the drop in mid-fall.",
            fr: "Au bon moment, un cornet peut recueillir la goutte au vol.",
          },
          imageSeed: "candy-c3jara-cone",
          icon: "icecream",
          narrative: {
            es: "{name} espera con un cucurucho de barquillo bien sujeto y recoge la gota dorada justo cuando pasa brillando.",
            ca: "{name} espera amb un cucurutxo de neula ben agafat i recull la gota daurada just quan passa brillant.",
            en: "{name} waits with a wafer cone held tight and catches the golden drop just as it flashes past.",
            fr: "{name} attend avec un cornet de gaufrette bien tenu et recueille la goutte dorée juste quand elle passe en brillant.",
          },
          next: "ending",
        },
        {
          id: "behind-waterfall",
          title: {
            es: "Pasar detrás de la cascada",
            ca: "Passar per darrere de la cascada",
            en: "Step behind the waterfall",
            fr: "Passer derrière la cascade",
          },
          desc: {
            es: "Unas piedras de turrón llevan justo detrás de la cortina dorada.",
            ca: "Unes pedres de torró porten just darrere de la cortina daurada.",
            en: "Nougat stones lead right behind the golden curtain.",
            fr: "Des pierres de nougat mènent juste derrière le rideau doré.",
          },
          imageSeed: "candy-c3jara-behind",
          icon: "footprint",
          narrative: {
            es: "{name} pasa de piedra en piedra hasta detrás de la cascada y atrapa la gota dorada cuando cruza la cortina de caramelo.",
            ca: "{name} passa de pedra en pedra fins darrere de la cascada i atrapa la gota daurada quan creua la cortina de caramel.",
            en: "{name} steps from stone to stone behind the waterfall and catches the golden drop as it crosses the caramel curtain.",
            fr: "{name} passe de pierre en pierre jusque derrière la cascade et attrape la goutte dorée quand elle traverse le rideau de caramel.",
          },
          next: "ending",
        },
      ],
    },
    c3_jar_b: {
      id: "c3_jar_b",
      chapter: 3,
      question: {
        es: "Las abejas de azúcar solo regalan su miel de estrella a los buenos amigos. ¿Qué hace {name} para ganarse su amistad?",
        ca: "Les abelles de sucre només regalen la seva mel d'estrella als bons amics. Què fa {name} per guanyar-se la seva amistat?",
        en: "The sugar bees only gift their star honey to good friends. What does {name} do to win their friendship?",
        fr: "Les abeilles de sucre n'offrent leur miel d'étoile qu'à leurs bons amis. Que fait {name} pour gagner leur amitié ?",
      },
      options: [
        {
          id: "lollipop-flowers",
          title: {
            es: "Llevarles flores de piruleta",
            ca: "Portar-los flors de piruleta",
            en: "Bring them lollipop flowers",
            fr: "Leur apporter des fleurs sucettes",
          },
          desc: {
            es: "Las flores de piruleta recién cogidas son su merienda favorita.",
            ca: "Les flors de piruleta acabades de collir són el seu berenar preferit.",
            en: "Freshly picked lollipop flowers are their favourite snack.",
            fr: "Les fleurs sucettes fraîchement cueillies sont leur goûter préféré.",
          },
          imageSeed: "candy-c3jarb-flowers",
          icon: "local_florist",
          narrative: {
            es: "{name} recoge un ramo de flores de piruleta y las abejas, encantadas, le regalan una cucharadita de miel de estrella.",
            ca: "{name} cull un ram de flors de piruleta i les abelles, encantades, li regalen una cullaradeta de mel d'estrella.",
            en: "{name} picks a bunch of lollipop flowers and the delighted bees gift a little spoonful of star honey.",
            fr: "{name} cueille un bouquet de fleurs sucettes et les abeilles, ravies, offrent une petite cuillerée de miel d'étoile.",
          },
          next: "ending",
        },
        {
          id: "fan-the-hive",
          title: {
            es: "Abanicar el panal",
            ca: "Ventar el rusc",
            en: "Fan the hive",
            fr: "Éventer la ruche",
          },
          desc: {
            es: "Hace una tarde calurosa y el panal de barquillo necesita aire fresquito.",
            ca: "Fa una tarda calorosa i el rusc de neula necessita aire fresquet.",
            en: "It's a hot afternoon and the wafer hive needs some cool air.",
            fr: "C'est un après-midi très chaud et la ruche en gaufrette a besoin d'air frais.",
          },
          imageSeed: "candy-c3jarb-fan",
          icon: "mode_fan",
          narrative: {
            es: "{name} abanica el panal con una hoja de menta gigante hasta que las abejas, fresquitas y agradecidas, comparten su miel de estrella.",
            ca: "{name} venta el rusc amb una fulla de menta gegant fins que les abelles, fresquetes i agraïdes, comparteixen la seva mel d'estrella.",
            en: "{name} fans the hive with a giant mint leaf until the cool, grateful bees share their star honey.",
            fr: "{name} évente la ruche avec une feuille de menthe géante jusqu'à ce que les abeilles, rafraîchies et reconnaissantes, partagent leur miel d'étoile.",
          },
          next: "ending",
        },
        {
          id: "bee-dance",
          title: {
            es: "Bailar su baile redondo",
            ca: "Ballar el seu ball rodó",
            en: "Dance their round dance",
            fr: "Danser leur danse ronde",
          },
          desc: {
            es: "Las abejas saludan a sus amigos bailando en circulitos.",
            ca: "Les abelles saluden els seus amics ballant en cercles petits.",
            en: "The bees greet their friends by dancing in little circles.",
            fr: "Les abeilles saluent leurs amis en dansant en petits cercles.",
          },
          imageSeed: "candy-c3jarb-dance",
          icon: "celebration",
          narrative: {
            es: "{name} baila en circulitos junto al panal y las abejas, felices, bailan alrededor y le ofrecen su miel de estrella.",
            ca: "{name} balla en cercles petits al costat del rusc i les abelles, felices, ballen al voltant i li ofereixen la seva mel d'estrella.",
            en: "{name} dances in little circles beside the hive and the happy bees dance around and offer their star honey.",
            fr: "{name} danse en petits cercles près de la ruche et les abeilles, heureuses, dansent autour et offrent leur miel d'étoile.",
          },
          next: "ending",
        },
      ],
    },
    c3_jar_c: {
      id: "c3_jar_c",
      chapter: 3,
      question: {
        es: "En la cueva brillan cientos de cristales, pero solo uno es el cristal de estrella que huele a vainilla. ¿Cómo lo encuentra {name}?",
        ca: "A la cova brillen centenars de cristalls, però només un és el cristall d'estrella que fa olor de vainilla. Com el troba {name}?",
        en: "Hundreds of crystals glow in the cave, but only one is the star crystal that smells of vanilla. How does {name} find it?",
        fr: "Des centaines de cristaux brillent dans la grotte, mais un seul est le cristal d'étoile qui sent la vanille. Comment {name} le trouve ?",
      },
      options: [
        {
          id: "vanilla-scent",
          title: {
            es: "Seguir el olor a vainilla",
            ca: "Seguir l'olor de vainilla",
            en: "Follow the vanilla scent",
            fr: "Suivre l'odeur de vanille",
          },
          desc: {
            es: "Con los ojos cerrados, la nariz sabe encontrar el camino más dulce.",
            ca: "Amb els ulls tancats, el nas sap trobar el camí més dolç.",
            en: "With eyes closed, the nose knows how to find the sweetest path.",
            fr: "Les yeux fermés, le nez sait trouver le chemin le plus doux.",
          },
          imageSeed: "candy-c3jarc-scent",
          icon: "spa",
          narrative: {
            es: "{name} cierra los ojos, sigue el olorcito a vainilla paso a paso y encuentra el cristal de estrella detrás de una columna de azúcar.",
            ca: "{name} tanca els ulls, segueix l'oloreta de vainilla pas a pas i troba el cristall d'estrella darrere d'una columna de sucre.",
            en: "{name} closes their eyes, follows the sweet vanilla scent step by step and finds the star crystal behind a sugar column.",
            fr: "{name} ferme les yeux, suit la petite odeur de vanille pas à pas et trouve le cristal d'étoile derrière une colonne de sucre.",
          },
          next: "ending",
        },
        {
          id: "lollipop-lantern",
          title: {
            es: "Un farolillo de piruleta",
            ca: "Un fanalet de piruleta",
            en: "A lollipop lantern",
            fr: "Une lanterne sucette",
          },
          desc: {
            es: "Cuando su luz toca el cristal de estrella, este responde con destellos rosas.",
            ca: "Quan la seva llum toca el cristall d'estrella, aquest respon amb espurnes roses.",
            en: "When its light touches the star crystal, it answers with pink sparkles.",
            fr: "Quand sa lumière touche le cristal d'étoile, celui-ci répond par des éclats roses.",
          },
          imageSeed: "candy-c3jarc-lantern",
          icon: "flashlight_on",
          narrative: {
            es: "{name} levanta una piruleta que brilla como un farolillo y, al fondo de la cueva, un cristal responde con destellos rosas.",
            ca: "{name} aixeca una piruleta que brilla com un fanalet i, al fons de la cova, un cristall respon amb espurnes roses.",
            en: "{name} holds up a lollipop glowing like a lantern and, deep in the cave, one crystal answers with pink sparkles.",
            fr: "{name} lève une sucette qui brille comme une lanterne et, au fond de la grotte, un cristal répond par des éclats roses.",
          },
          next: "ending",
        },
        {
          id: "marzipan-mice",
          title: {
            es: "Preguntar a los ratoncitos de mazapán",
            ca: "Preguntar als ratolinets de massapà",
            en: "Ask the marzipan mice",
            fr: "Demander aux petites souris en massepain",
          },
          desc: {
            es: "Los ratoncitos conocen cada rincón dulce de la cueva.",
            ca: "Els ratolinets coneixen cada racó dolç de la cova.",
            en: "The little mice know every sweet corner of the cave.",
            fr: "Les petites souris connaissent chaque recoin sucré de la grotte.",
          },
          imageSeed: "candy-c3jarc-mice",
          icon: "pets",
          narrative: {
            es: "{name} comparte un trocito de galleta con los ratoncitos de mazapán y ellos, en fila, le enseñan el camino hasta el cristal de estrella.",
            ca: "{name} comparteix un trosset de galeta amb els ratolinets de massapà i ells, en filera, li ensenyen el camí fins al cristall d'estrella.",
            en: "{name} shares a piece of cookie with the marzipan mice and they line up to show the way to the star crystal.",
            fr: "{name} partage un morceau de biscuit avec les petites souris en massepain et celles-ci, en file, montrent le chemin jusqu'au cristal d'étoile.",
          },
          next: "ending",
        },
      ],
    },
    c3_bridge_a: {
      id: "c3_bridge_a",
      chapter: 3,
      question: {
        es: "¡Las aspas del molino están pegadas con caramelo pegajoso y no pueden girar! ¿Cómo las pone en marcha {name}?",
        ca: "Les aspes del molí estan enganxades amb caramel enganxós i no poden girar! Com les posa en marxa {name}?",
        en: "The windmill's sails are stuck with sticky caramel and can't turn! How does {name} get them going?",
        fr: "Les ailes du moulin sont collées par du caramel tout collant et ne peuvent plus tourner ! Comment {name} va les remettre en marche ?",
      },
      options: [
        {
          id: "peppermint-wind",
          title: {
            es: "Llamar al viento de menta",
            ca: "Cridar el vent de menta",
            en: "Call the peppermint wind",
            fr: "Appeler le vent de menthe",
          },
          desc: {
            es: "Un viento fresquito de menta puede despegar el caramelo y empujar las aspas.",
            ca: "Un vent fresquet de menta pot desenganxar el caramel i empènyer les aspes.",
            en: "A cool peppermint wind can unstick the caramel and push the sails.",
            fr: "Un vent frais à la menthe peut décoller le caramel et pousser les ailes.",
          },
          imageSeed: "candy-c3bridgea-wind",
          icon: "air",
          narrative: {
            es: "{name} silba hacia las colinas y el viento de menta llega fresquito, despega el caramelo y hace girar las aspas de galleta.",
            ca: "{name} xiula cap als turons i el vent de menta arriba fresquet, desenganxa el caramel i fa girar les aspes de galeta.",
            en: "{name} whistles towards the hills and the peppermint wind arrives cool and fresh, unsticking the caramel and spinning the cookie sails.",
            fr: "{name} siffle vers les collines et le vent de menthe arrive tout frais, décolle le caramel et fait tourner les ailes en biscuit.",
          },
          next: "ending",
        },
        {
          id: "fizzy-lemonade",
          title: {
            es: "Limonada burbujeante",
            ca: "Llimonada amb bombolles",
            en: "Fizzy lemonade",
            fr: "Limonade pétillante",
          },
          desc: {
            es: "Sus burbujas deshacen el caramelo pegajoso haciéndole cosquillas.",
            ca: "Les seves bombolles desfan el caramel enganxós fent-li pessigolles.",
            en: "Its bubbles dissolve the sticky caramel by tickling it.",
            fr: "Ses bulles font fondre le caramel collant en le chatouillant.",
          },
          imageSeed: "candy-c3bridgea-fizz",
          icon: "bubble_chart",
          narrative: {
            es: "{name} vierte limonada burbujeante sobre los engranajes y las burbujas deshacen el caramelo pegajoso hasta que las aspas giran de nuevo.",
            ca: "{name} aboca llimonada amb bombolles sobre els engranatges i les bombolles desfan el caramel enganxós fins que les aspes tornen a girar.",
            en: "{name} pours fizzy lemonade over the gears and the bubbles dissolve the sticky caramel until the sails turn again.",
            fr: "{name} verse de la limonade pétillante sur les engrenages et les bulles font fondre le caramel collant jusqu'à ce que les ailes tournent à nouveau.",
          },
          next: "ending",
        },
        {
          id: "push-together",
          title: {
            es: "Empujar todos juntos",
            ca: "Empènyer tots junts",
            en: "Push all together",
            fr: "Pousser tous ensemble",
          },
          desc: {
            es: "Con muchos amigos del pueblo, hasta el molino más pegajoso se mueve.",
            ca: "Amb molts amics del poble, fins i tot el molí més enganxós es mou.",
            en: "With lots of friends from the village, even the stickiest windmill moves.",
            fr: "Avec plein d'amis du village, même le moulin le plus collant se met à bouger.",
          },
          imageSeed: "candy-c3bridgea-push",
          icon: "groups",
          narrative: {
            es: "{name} reúne a los vecinos del pueblo y, empujando todos a la vez, las aspas se despegan y el molino vuelve a remover el chocolate.",
            ca: "{name} reuneix els veïns del poble i, empenyent tots alhora, les aspes es desenganxen i el molí torna a remenar la xocolata.",
            en: "{name} gathers the villagers and, pushing all at once, the sails come unstuck and the windmill stirs the chocolate again.",
            fr: "{name} rassemble les voisins du village et, en poussant tous en même temps, les ailes se décollent et le moulin remue à nouveau le chocolat.",
          },
          next: "ending",
        },
      ],
    },
    c3_bridge_b: {
      id: "c3_bridge_b",
      chapter: 3,
      question: {
        es: "Dentro de la tubería hay un caramelo de toffee gigante atascado. ¿Cómo lo saca {name}?",
        ca: "Dins de la canonada hi ha un caramel tou gegant encallat. Com el treu {name}?",
        en: "A giant toffee is stuck inside the pipe. How does {name} get it out?",
        fr: "Un caramel mou géant est coincé dans le tuyau. Comment {name} va le déloger ?",
      },
      options: [
        {
          id: "cinnamon-warmth",
          title: {
            es: "Una bufanda de canela calentita",
            ca: "Una bufanda de canyella calentona",
            en: "A warm cinnamon scarf",
            fr: "Une écharpe à la cannelle toute chaude",
          },
          desc: {
            es: "Con un poquito de calor suave, el toffee se vuelve blandito y resbala.",
            ca: "Amb una mica d'escalfor suau, el caramel es torna tou i rellisca.",
            en: "With a little gentle warmth, the toffee turns soft and slides along.",
            fr: "Avec un peu de douce chaleur, le caramel mou devient tout tendre et glisse.",
          },
          imageSeed: "candy-c3bridgeb-warm",
          icon: "favorite",
          narrative: {
            es: "{name} envuelve la tubería con una bufanda de canela calentita y el toffee, blandito, resbala hasta salir con un '¡plop!'.",
            ca: "{name} embolica la canonada amb una bufanda de canyella calentona i el caramel, tou, rellisca fins a sortir amb un 'plop!'.",
            en: "{name} wraps the pipe in a warm cinnamon scarf and the toffee, soft at last, slides out with a 'plop!'.",
            fr: "{name} enroule une écharpe à la cannelle toute chaude autour du tuyau et le caramel, devenu tendre, glisse et sort avec un « plop ! ».",
          },
          next: "ending",
        },
        {
          id: "pipe-song",
          title: {
            es: "Tocar una canción en la tubería",
            ca: "Tocar una cançó a la canonada",
            en: "Play a song on the pipe",
            fr: "Jouer une chanson sur le tuyau",
          },
          desc: {
            es: "Un ritmo alegre hace bailar hasta al caramelo más atascado.",
            ca: "Un ritme alegre fa ballar fins i tot el caramel més encallat.",
            en: "A happy rhythm makes even the most stuck toffee dance.",
            fr: "Un rythme joyeux fait danser même le caramel le plus coincé.",
          },
          imageSeed: "candy-c3bridgeb-song",
          icon: "queue_music",
          narrative: {
            es: "{name} tamborilea un ritmo alegre sobre la tubería de regaliz y el toffee baila dentro hasta soltarse y salir rodando.",
            ca: "{name} tamborineja un ritme alegre sobre la canonada de regalèssia i el caramel balla a dins fins que es deixa anar i surt rodant.",
            en: "{name} drums a happy rhythm on the licorice pipe and the toffee dances inside until it pops free and rolls out.",
            fr: "{name} tambourine un rythme joyeux sur le tuyau de réglisse et le caramel danse à l'intérieur jusqu'à se libérer et rouler dehors.",
          },
          next: "ending",
        },
        {
          id: "warm-cocoa",
          title: {
            es: "Un chorrito de cacao caliente",
            ca: "Un rajolí de cacau calent",
            en: "A trickle of warm cocoa",
            fr: "Un filet de cacao chaud",
          },
          desc: {
            es: "El cacao calentito derrite el toffee poquito a poquito.",
            ca: "El cacau calentó fon el caramel a poquet a poquet.",
            en: "Warm cocoa melts the toffee little by little.",
            fr: "Le cacao chaud fait fondre le caramel petit à petit.",
          },
          imageSeed: "candy-c3bridgeb-cocoa",
          icon: "emoji_food_beverage",
          narrative: {
            es: "{name} vierte un chorrito de cacao caliente por la tubería y el toffee se derrite poquito a poco hasta que el chocolate vuelve a correr.",
            ca: "{name} aboca un rajolí de cacau calent per la canonada i el caramel es fon a poc a poc fins que la xocolata torna a córrer.",
            en: "{name} pours a trickle of warm cocoa down the pipe and the toffee melts little by little until the chocolate flows again.",
            fr: "{name} verse un filet de cacao chaud dans le tuyau et le caramel fond petit à petit jusqu'à ce que le chocolat coule à nouveau.",
          },
          next: "ending",
        },
      ],
    },
    c3_bridge_c: {
      id: "c3_bridge_c",
      chapter: 3,
      question: {
        es: "La nubecita de leche está en lo alto de la Montaña de Helado, triste porque cree que nadie la necesita. ¿Cómo la invita {name} a volver?",
        ca: "El nuvolet de llet és a dalt de la Muntanya de Gelat, trist perquè es pensa que ningú no el necessita. Com el convida {name} a tornar?",
        en: "The little milk cloud sits at the top of Ice Cream Mountain, sad because it thinks nobody needs it. How does {name} invite it back?",
        fr: "Le petit nuage de lait est en haut de la Montagne de Glace, triste parce qu'il croit que personne n'a besoin de lui. Comment {name} va l'inviter à revenir ?",
      },
      options: [
        {
          id: "wafer-kite",
          title: {
            es: "Una cometa de barquillo",
            ca: "Un estel de neula",
            en: "A wafer kite",
            fr: "Un cerf-volant en gaufrette",
          },
          desc: {
            es: "Una cometa puede subir muy alto llevando una invitación escrita con chocolate.",
            ca: "Un estel pot pujar molt amunt portant una invitació escrita amb xocolata.",
            en: "A kite can fly high carrying an invitation written in chocolate.",
            fr: "Un cerf-volant peut monter très haut avec une invitation écrite au chocolat.",
          },
          imageSeed: "candy-c3bridgec-kite",
          icon: "mail",
          narrative: {
            es: "{name} escribe '¡Te esperamos en la fiesta!' con chocolate en una cometa de barquillo y la hace volar hasta la nubecita, que baja dando volteretas de alegría.",
            ca: "{name} escriu 'T'esperem a la festa!' amb xocolata en un estel de neula i el fa volar fins al nuvolet, que baixa fent tombarelles d'alegria.",
            en: "{name} writes 'We're waiting for you at the party!' in chocolate on a wafer kite and flies it up to the little cloud, which tumbles down with joy.",
            fr: "{name} écrit « On t'attend à la fête ! » au chocolat sur un cerf-volant en gaufrette et le fait voler jusqu'au petit nuage, qui descend en faisant des galipettes de joie.",
          },
          next: "ending",
        },
        {
          id: "village-song",
          title: {
            es: "Cantar la canción de la merienda",
            ca: "Cantar la cançó del berenar",
            en: "Sing the snack-time song",
            fr: "Chanter la chanson du goûter",
          },
          desc: {
            es: "Es la canción favorita de la nube: todo el pueblo la canta junto.",
            ca: "És la cançó preferida del núvol: tot el poble la canta plegat.",
            en: "It's the cloud's favourite song: the whole village sings it together.",
            fr: "C'est la chanson préférée du nuage : tout le village la chante ensemble.",
          },
          imageSeed: "candy-c3bridgec-song",
          icon: "music_note",
          narrative: {
            es: "{name} reúne a todo el pueblo en la plaza y cantan juntos la canción de la merienda, y la nubecita baja flotando para no perdérsela.",
            ca: "{name} reuneix tot el poble a la plaça i canten plegats la cançó del berenar, i el nuvolet baixa flotant per no perdre-se-la.",
            en: "{name} gathers the whole village in the square and they sing the snack-time song together, and the little cloud floats down so it won't miss it.",
            fr: "{name} rassemble tout le village sur la place et tous chantent ensemble la chanson du goûter, et le petit nuage descend en flottant pour ne pas la manquer.",
          },
          next: "ending",
        },
        {
          id: "first-cup",
          title: {
            es: "Prometerle la primera taza",
            ca: "Prometre-li la primera tassa",
            en: "Promise it the first cup",
            fr: "Lui promettre la première tasse",
          },
          desc: {
            es: "La primera taza de chocolate de la fiesta es el premio más dulce.",
            ca: "La primera tassa de xocolata de la festa és el premi més dolç.",
            en: "The first cup of chocolate at the party is the sweetest prize.",
            fr: "La première tasse de chocolat de la fête est la plus douce des récompenses.",
          },
          imageSeed: "candy-c3bridgec-cup",
          icon: "local_cafe",
          narrative: {
            es: "{name} sube por la ladera de helado y promete a la nubecita la primera taza de chocolate de la fiesta, y ella vuelve feliz a su sitio sobre la fuente.",
            ca: "{name} puja pel vessant de gelat i promet al nuvolet la primera tassa de xocolata de la festa, i ell torna feliç al seu lloc sobre la font.",
            en: "{name} climbs the ice cream slope and promises the little cloud the first cup of chocolate at the party, and it happily returns to its place above the fountain.",
            fr: "{name} grimpe le versant de glace et promet au petit nuage la première tasse de chocolat de la fête, et celui-ci retourne tout heureux à sa place au-dessus de la fontaine.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "", en: "", fr: "" },
      options: [],
    },
  },
};
