import type { StoryTree } from "./types";

// Branching story tree for the "castle" template (El Castillo de los Sueños).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es source of truth + ca/en/fr). {name} = child's name.

export const castleTree: StoryTree = {
  templateId: "castle",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} cruza las puertas del Castillo de los Sueños, donde cada noche nacen los sueños de todo el reino. En el gran salón de entrada, tres maravillas esperan. ¿Cuál descubre primero?",
        ca: "{name} creua les portes del Castell dels Somnis, on cada nit neixen els somnis de tot el regne. Al gran saló d'entrada, tres meravelles esperen. Quina descobreix primer?",
        en: "{name} walks through the gates of the Castle of Dreams, where every dream in the kingdom is born each night. In the grand entrance hall, three wonders are waiting. Which one to discover first?",
        fr: "{name} franchit les portes du Château des Rêves, où naissent chaque nuit les rêves de tout le royaume. Dans le grand hall d'entrée, trois merveilles attendent. Laquelle découvrir en premier ?",
      },
      options: [
        {
          id: "dragon",
          title: {
            es: "El dragón bebé",
            ca: "El drac bebè",
            en: "The baby dragon",
            fr: "Le bébé dragon",
          },
          desc: {
            es: "Un dragoncito recién salido de un huevo dorado estornuda chispas de colores.",
            ca: "Un dragonet acabat de sortir d'un ou daurat esternuda espurnes de colors.",
            en: "A tiny dragon fresh out of a golden egg sneezes sparks of every colour.",
            fr: "Un petit dragon tout juste sorti d'un œuf doré éternue des étincelles de toutes les couleurs.",
          },
          imageSeed: "castle-c1-dragon",
          icon: "local_fire_department",
          narrative: {
            es: "{name} se acerca despacito a un dragoncito recién nacido que estornuda chispas de colores junto a su huevo dorado.",
            ca: "{name} s'acosta a poc a poc a un dragonet acabat de néixer que esternuda espurnes de colors al costat del seu ou daurat.",
            en: "{name} slowly approaches a newly hatched little dragon sneezing colourful sparks beside its golden egg.",
            fr: "{name} s'approche tout doucement d'un petit dragon tout juste éclos qui éternue des étincelles colorées à côté de son œuf doré.",
          },
          next: "c2_dragon",
        },
        {
          id: "mirror",
          title: {
            es: "El espejo de los sueños",
            ca: "El mirall dels somnis",
            en: "The mirror of dreams",
            fr: "Le miroir des rêves",
          },
          desc: {
            es: "Un gran espejo de marco plateado susurra secretos desde lo alto de la pared.",
            ca: "Un gran mirall de marc platejat xiuxiueja secrets des de dalt de la paret.",
            en: "A great silver-framed mirror whispers secrets from high on the wall.",
            fr: "Un grand miroir au cadre argenté chuchote des secrets du haut du mur.",
          },
          imageSeed: "castle-c1-mirror",
          icon: "image",
          narrative: {
            es: "{name} se acerca a un gran espejo de marco plateado que susurra bajito desde la pared del salón.",
            ca: "{name} s'acosta a un gran mirall de marc platejat que xiuxiueja fluixet des de la paret del saló.",
            en: "{name} walks up to a great silver-framed mirror whispering softly from the wall of the hall.",
            fr: "{name} s'approche d'un grand miroir au cadre argenté qui chuchote tout bas depuis le mur du hall.",
          },
          next: "c2_mirror",
        },
        {
          id: "stairs",
          title: {
            es: "La escalera que canta",
            ca: "L'escala que canta",
            en: "The singing staircase",
            fr: "L'escalier qui chante",
          },
          desc: {
            es: "Cada peldaño de la escalera de caracol suena como una nota de música y sube más allá de las nubes.",
            ca: "Cada esglaó de l'escala de cargol sona com una nota de música i puja més enllà dels núvols.",
            en: "Every step of the spiral staircase rings like a musical note and climbs beyond the clouds.",
            fr: "Chaque marche de l'escalier en colimaçon sonne comme une note de musique et monte au-delà des nuages.",
          },
          imageSeed: "castle-c1-stairs",
          icon: "stairs",
          narrative: {
            es: "{name} pone un pie en la escalera de caracol y cada peldaño canta una nota distinta mientras sube hacia las nubes.",
            ca: "{name} posa un peu a l'escala de cargol i cada esglaó canta una nota diferent mentre puja cap als núvols.",
            en: "{name} steps onto the spiral staircase and every step sings a different note on the way up towards the clouds.",
            fr: "{name} pose un pied sur l'escalier en colimaçon et chaque marche chante une note différente en montant vers les nuages.",
          },
          next: "c2_stairs",
        },
      ],
    },
    c2_dragon: {
      id: "c2_dragon",
      chapter: 2,
      question: {
        es: "El dragoncito dice que se llama Chispa. Está preocupado: su primer sueño se le ha escapado volando, y esta es la Noche de los Sueños, cuando cada dragón regala el suyo al reino. ¿Dónde lo buscan {name} y Chispa?",
        ca: "El dragonet diu que es diu Chispa. Està preocupat: el seu primer somni se li ha escapat volant, i aquesta és la Nit dels Somnis, quan cada drac regala el seu al regne. On el busquen {name} i en Chispa?",
        en: "The little dragon says his name is Chispa. He is worried: his very first dream has flown away, and tonight is the Night of Dreams, when every dragon gifts theirs to the kingdom. Where do {name} and Chispa look for it?",
        fr: "Le petit dragon dit qu'il s'appelle Chispa. Il est inquiet : son tout premier rêve s'est envolé, et c'est la Nuit des Rêves, quand chaque dragon offre le sien au royaume. Où {name} et Chispa vont-ils le chercher ?",
      },
      options: [
        {
          id: "library",
          title: {
            es: "La biblioteca voladora",
            ca: "La biblioteca voladora",
            en: "The flying library",
            fr: "La bibliothèque volante",
          },
          desc: {
            es: "Cientos de libros vuelan como pájaros entre estanterías altísimas.",
            ca: "Centenars de llibres volen com ocells entre prestatgeries altíssimes.",
            en: "Hundreds of books fly like birds between towering shelves.",
            fr: "Des centaines de livres volent comme des oiseaux entre des étagères immenses.",
          },
          imageSeed: "castle-c2dragon-library",
          icon: "auto_stories",
          narrative: {
            es: "{name} y Chispa entran en la biblioteca del castillo, donde cientos de libros vuelan como pájaros entre las estanterías.",
            ca: "{name} i en Chispa entren a la biblioteca del castell, on centenars de llibres volen com ocells entre les prestatgeries.",
            en: "{name} and Chispa enter the castle library, where hundreds of books fly like birds between the shelves.",
            fr: "{name} et Chispa entrent dans la bibliothèque du château, où des centaines de livres volent comme des oiseaux entre les étagères.",
          },
          next: "c3_dragon_a",
        },
        {
          id: "kitchen",
          title: {
            es: "La cocina de las nubes",
            ca: "La cuina dels núvols",
            en: "The cloud kitchen",
            fr: "La cuisine des nuages",
          },
          desc: {
            es: "Los cocineros del castillo hornean pasteles con nubes de azúcar que huelen a vainilla.",
            ca: "Els cuiners del castell fornegen pastissos amb núvols de sucre que fan olor de vainilla.",
            en: "The castle cooks bake cakes with sugar clouds that smell of vanilla.",
            fr: "Les cuisiniers du château font des gâteaux avec des nuages de sucre qui sentent la vanille.",
          },
          imageSeed: "castle-c2dragon-kitchen",
          icon: "cake",
          narrative: {
            es: "{name} y Chispa bajan a la cocina del castillo, donde flotan nubes de azúcar y huele a pastel recién hecho.",
            ca: "{name} i en Chispa baixen a la cuina del castell, on floten núvols de sucre i fa olor de pastís acabat de fer.",
            en: "{name} and Chispa go down to the castle kitchen, where sugar clouds float in the air and it smells of freshly baked cake.",
            fr: "{name} et Chispa descendent à la cuisine du château, où flottent des nuages de sucre et où ça sent le gâteau tout chaud.",
          },
          next: "c3_dragon_b",
        },
        {
          id: "ballroom",
          title: {
            es: "El salón de baile",
            ca: "El saló de ball",
            en: "The ballroom",
            fr: "La salle de bal",
          },
          desc: {
            es: "Las velas bailan un vals en el aire y la música suena sola.",
            ca: "Les espelmes ballen un vals a l'aire i la música sona tota sola.",
            en: "The candles waltz in the air and the music plays all by itself.",
            fr: "Les bougies dansent une valse dans les airs et la musique joue toute seule.",
          },
          imageSeed: "castle-c2dragon-ballroom",
          icon: "music_note",
          narrative: {
            es: "{name} y Chispa se asoman al gran salón de baile, donde las velas bailan un vals flotando en el aire.",
            ca: "{name} i en Chispa treuen el cap al gran saló de ball, on les espelmes ballen un vals flotant a l'aire.",
            en: "{name} and Chispa peek into the grand ballroom, where the candles waltz floating in the air.",
            fr: "{name} et Chispa jettent un œil dans la grande salle de bal, où les bougies dansent une valse en flottant dans les airs.",
          },
          next: "c3_dragon_c",
        },
      ],
    },
    c2_mirror: {
      id: "c2_mirror",
      chapter: 2,
      question: {
        es: "El espejo susurra: 'Soy la puerta del reino de los sueños, pero he perdido mi piedra de luna y mi cristal se ha quedado dormido'. {name} decide encontrarla. ¿Por dónde empieza a buscar?",
        ca: "El mirall xiuxiueja: 'Soc la porta del regne dels somnis, però he perdut la meva pedra de lluna i el meu vidre s'ha quedat adormit'. {name} decideix trobar-la. Per on comença a buscar?",
        en: "The mirror whispers: 'I am the door to the kingdom of dreams, but I have lost my moonstone and my glass has fallen asleep.' {name} decides to find it. Where to start looking?",
        fr: "Le miroir chuchote : « Je suis la porte du royaume des rêves, mais j'ai perdu ma pierre de lune et mon verre s'est endormi. » {name} décide de la retrouver. Par où commencer ?",
      },
      options: [
        {
          id: "fountain",
          title: {
            es: "La fuente de los deseos",
            ca: "La font dels desitjos",
            en: "The wishing fountain",
            fr: "La fontaine aux souhaits",
          },
          desc: {
            es: "En los jardines encantados hay una fuente donde brillan las cosas perdidas.",
            ca: "Als jardins encantats hi ha una font on brillen les coses perdudes.",
            en: "In the enchanted gardens there is a fountain where lost things glimmer.",
            fr: "Dans les jardins enchantés, il y a une fontaine où brillent les choses perdues.",
          },
          imageSeed: "castle-c2mirror-fountain",
          icon: "water",
          narrative: {
            es: "{name} sale a los jardines encantados y se asoma a la fuente de los deseos, donde algo blanco brilla en el fondo.",
            ca: "{name} surt als jardins encantats i s'aboca a la font dels desitjos, on alguna cosa blanca brilla al fons.",
            en: "{name} goes out to the enchanted gardens and peers into the wishing fountain, where something white glimmers at the bottom.",
            fr: "{name} sort dans les jardins enchantés et se penche sur la fontaine aux souhaits, où quelque chose de blanc brille au fond.",
          },
          next: "c3_mirror_a",
        },
        {
          id: "armor",
          title: {
            es: "La armadura encantada",
            ca: "L'armadura encantada",
            en: "The enchanted armour",
            fr: "L'armure enchantée",
          },
          desc: {
            es: "Una vieja armadura duerme de pie en el pasillo con algo brillante en su guante.",
            ca: "Una vella armadura dorm dreta al passadís amb alguna cosa brillant al seu guant.",
            en: "An old suit of armour sleeps standing in the corridor with something shiny in its glove.",
            fr: "Une vieille armure dort debout dans le couloir avec quelque chose de brillant dans son gant.",
          },
          imageSeed: "castle-c2mirror-armor",
          icon: "shield",
          narrative: {
            es: "{name} recorre el pasillo de las armaduras y descubre una piedra blanca brillando dentro del guante de una armadura dormida.",
            ca: "{name} recorre el passadís de les armadures i descobreix una pedra blanca brillant dins del guant d'una armadura adormida.",
            en: "{name} walks down the corridor of armours and spots a white stone shining inside the glove of a sleeping suit of armour.",
            fr: "{name} parcourt le couloir des armures et découvre une pierre blanche qui brille dans le gant d'une armure endormie.",
          },
          next: "c3_mirror_b",
        },
        {
          id: "attic",
          title: {
            es: "El desván de los juguetes",
            ca: "Les golfes de les joguines",
            en: "The toy attic",
            fr: "Le grenier aux jouets",
          },
          desc: {
            es: "Todo lo que rueda por el castillo acaba en el desván, entre juguetes olvidados.",
            ca: "Tot el que roda pel castell acaba a les golfes, entre joguines oblidades.",
            en: "Everything that rolls through the castle ends up in the attic, among forgotten toys.",
            fr: "Tout ce qui roule dans le château finit au grenier, parmi les jouets oubliés.",
          },
          imageSeed: "castle-c2mirror-attic",
          icon: "roofing",
          narrative: {
            es: "{name} sube al desván del castillo, donde los juguetes olvidados guardan montañitas de canicas y cosas que ruedan.",
            ca: "{name} puja a les golfes del castell, on les joguines oblidades guarden muntanyetes de bales i coses que roden.",
            en: "{name} climbs up to the castle attic, where the forgotten toys keep little piles of marbles and rolling things.",
            fr: "{name} monte au grenier du château, où les jouets oubliés gardent des petits tas de billes et de choses qui roulent.",
          },
          next: "c3_mirror_c",
        },
      ],
    },
    c2_stairs: {
      id: "c2_stairs",
      chapter: 2,
      question: {
        es: "La escalera termina en la torre más alta, por encima de las nubes. Allí, una estrella tejedora teje los sueños del reino en un gran telar... ¡pero se ha quedado sin hilo mágico! ¿Qué hilo van a buscar {name} y la estrella?",
        ca: "L'escala acaba a la torre més alta, per sobre dels núvols. Allà, una estrella teixidora teixeix els somnis del regne en un gran teler... però s'ha quedat sense fil màgic! Quin fil van a buscar {name} i l'estrella?",
        en: "The staircase ends at the tallest tower, above the clouds. There, a weaver star weaves the kingdom's dreams on a great loom... but she has run out of magic thread! Which thread do {name} and the star go looking for?",
        fr: "L'escalier se termine dans la plus haute tour, au-dessus des nuages. Là, une étoile tisseuse tisse les rêves du royaume sur un grand métier... mais elle n'a plus de fil magique ! Quel fil {name} et l'étoile vont-ils chercher ?",
      },
      options: [
        {
          id: "moon-thread",
          title: {
            es: "Hilo de luna",
            ca: "Fil de lluna",
            en: "Moon thread",
            fr: "Fil de lune",
          },
          desc: {
            es: "De la luna cuelgan hebras de luz plateada, finas como cabellos.",
            ca: "De la lluna pengen brins de llum platejada, fins com cabells.",
            en: "Strands of silver light hang from the moon, fine as hair.",
            fr: "Des brins de lumière argentée pendent de la lune, fins comme des cheveux.",
          },
          imageSeed: "castle-c2stairs-moon",
          icon: "bedtime",
          narrative: {
            es: "{name} y la estrella tejedora suben a la azotea de la torre, donde las hebras de luz de luna cuelgan del cielo como cabellos de plata.",
            ca: "{name} i l'estrella teixidora pugen al terrat de la torre, on els brins de llum de lluna pengen del cel com cabells de plata.",
            en: "{name} and the weaver star climb to the tower rooftop, where strands of moonlight hang from the sky like silver hair.",
            fr: "{name} et l'étoile tisseuse montent sur le toit de la tour, où les brins de lumière de lune pendent du ciel comme des cheveux d'argent.",
          },
          next: "c3_stairs_a",
        },
        {
          id: "rainbow-thread",
          title: {
            es: "Hilo de arcoíris",
            ca: "Fil d'arc de Sant Martí",
            en: "Rainbow thread",
            fr: "Fil d'arc-en-ciel",
          },
          desc: {
            es: "Las vidrieras del gran salón guardan hilos de todos los colores cuando les llega la luz.",
            ca: "Els vitralls del gran saló guarden fils de tots els colors quan els arriba la llum.",
            en: "The stained-glass windows of the great hall hold threads of every colour when light touches them.",
            fr: "Les vitraux de la grande salle gardent des fils de toutes les couleurs quand la lumière les touche.",
          },
          imageSeed: "castle-c2stairs-rainbow",
          icon: "looks",
          narrative: {
            es: "{name} y la estrella tejedora bajan al gran salón de las vidrieras, donde duermen los hilos de arcoíris esperando un poquito de luz.",
            ca: "{name} i l'estrella teixidora baixen al gran saló dels vitralls, on dormen els fils d'arc de Sant Martí esperant una mica de llum.",
            en: "{name} and the weaver star go down to the great stained-glass hall, where the rainbow threads sleep waiting for a little light.",
            fr: "{name} et l'étoile tisseuse descendent dans la grande salle aux vitraux, où dorment les fils d'arc-en-ciel en attendant un peu de lumière.",
          },
          next: "c3_stairs_b",
        },
        {
          id: "cloud-cotton",
          title: {
            es: "Algodón de nubes",
            ca: "Cotó de núvols",
            en: "Cloud cotton",
            fr: "Coton de nuages",
          },
          desc: {
            es: "Alrededor de la torre pastan nubecitas blancas y esponjosas como ovejas.",
            ca: "Al voltant de la torre pasturen nuvolets blancs i esponjosos com ovelles.",
            en: "Around the tower graze little white clouds, fluffy as sheep.",
            fr: "Autour de la tour paissent de petits nuages blancs, moelleux comme des moutons.",
          },
          imageSeed: "castle-c2stairs-cloud",
          icon: "cloud",
          narrative: {
            es: "{name} y la estrella tejedora se asoman al balcón de la torre, donde las nubecitas pastan alrededor como ovejas esponjosas.",
            ca: "{name} i l'estrella teixidora s'aboquen al balcó de la torre, on els nuvolets pasturen al voltant com ovelles esponjoses.",
            en: "{name} and the weaver star lean out from the tower balcony, where the little clouds graze around like fluffy sheep.",
            fr: "{name} et l'étoile tisseuse se penchent au balcon de la tour, où les petits nuages paissent tout autour comme des moutons moelleux.",
          },
          next: "c3_stairs_c",
        },
      ],
    },
    c3_dragon_a: {
      id: "c3_dragon_a",
      chapter: 3,
      question: {
        es: "¡El sueño está en la biblioteca! Se ha escondido dentro de uno de los miles de libros voladores. ¿Cómo lo encuentra {name}?",
        ca: "El somni és a la biblioteca! S'ha amagat dins d'un dels milers de llibres voladors. Com el troba {name}?",
        en: "The dream is in the library! It has hidden inside one of the thousands of flying books. How does {name} find it?",
        fr: "Le rêve est dans la bibliothèque ! Il s'est caché dans l'un des milliers de livres volants. Comment {name} va le trouver ?",
      },
      options: [
        {
          id: "owl",
          title: {
            es: "Preguntar al búho bibliotecario",
            ca: "Preguntar al mussol bibliotecari",
            en: "Ask the librarian owl",
            fr: "Demander au hibou bibliothécaire",
          },
          desc: {
            es: "Un búho con gafas conoce cada libro y cada rincón de la biblioteca.",
            ca: "Un mussol amb ulleres coneix cada llibre i cada racó de la biblioteca.",
            en: "An owl with glasses knows every book and every corner of the library.",
            fr: "Un hibou à lunettes connaît chaque livre et chaque recoin de la bibliothèque.",
          },
          imageSeed: "castle-c3dragona-owl",
          icon: "raven",
          narrative: {
            es: "{name} pregunta al búho bibliotecario, que vuela directo a un libro de tapas azules donde el sueño duerme acurrucado.",
            ca: "{name} pregunta al mussol bibliotecari, que vola directe a un llibre de tapes blaves on el somni dorm arraulit.",
            en: "{name} asks the librarian owl, who flies straight to a blue-covered book where the dream sleeps curled up.",
            fr: "{name} demande au hibou bibliothécaire, qui vole droit vers un livre à la couverture bleue où le rêve dort blotti.",
          },
          next: "ending",
        },
        {
          id: "glow",
          title: {
            es: "Seguir el brillo",
            ca: "Seguir la lluentor",
            en: "Follow the glow",
            fr: "Suivre la lueur",
          },
          desc: {
            es: "Entre las páginas de un libro asoma una lucecita suave de colores.",
            ca: "Entre les pàgines d'un llibre treu el cap una llumeta suau de colors.",
            en: "A soft, colourful little light peeks out between the pages of one book.",
            fr: "Une petite lumière douce et colorée dépasse entre les pages d'un livre.",
          },
          imageSeed: "castle-c3dragona-glow",
          icon: "travel_explore",
          narrative: {
            es: "{name} camina despacito entre las estanterías siguiendo un brillo suave hasta el libro donde se esconde el sueño.",
            ca: "{name} camina a poc a poc entre les prestatgeries seguint una lluentor suau fins al llibre on s'amaga el somni.",
            en: "{name} walks slowly between the shelves following a soft glow all the way to the book where the dream is hiding.",
            fr: "{name} marche doucement entre les étagères en suivant une douce lueur jusqu'au livre où se cache le rêve.",
          },
          next: "ending",
        },
        {
          id: "story",
          title: {
            es: "Contar un cuento en voz alta",
            ca: "Explicar un conte en veu alta",
            en: "Tell a story out loud",
            fr: "Raconter une histoire à voix haute",
          },
          desc: {
            es: "A los sueños les encantan los cuentos y siempre se asoman a escuchar.",
            ca: "Als somnis els encanten els contes i sempre treuen el cap per escoltar.",
            en: "Dreams love stories and always peek out to listen.",
            fr: "Les rêves adorent les histoires et sortent toujours la tête pour écouter.",
          },
          imageSeed: "castle-c3dragona-story",
          icon: "menu_book",
          narrative: {
            es: "{name} se sienta a contar un cuento en voz alta y el sueño asoma entre las páginas de un libro para escuchar el final.",
            ca: "{name} s'asseu a explicar un conte en veu alta i el somni treu el cap entre les pàgines d'un llibre per escoltar el final.",
            en: "{name} sits down to tell a story out loud and the dream peeks out from between the pages of a book to hear the ending.",
            fr: "{name} s'assoit pour raconter une histoire à voix haute et le rêve sort la tête d'entre les pages d'un livre pour écouter la fin.",
          },
          next: "ending",
        },
      ],
    },
    c3_dragon_b: {
      id: "c3_dragon_b",
      chapter: 3,
      question: {
        es: "¡El sueño está en la cocina! Flota muy alto entre las nubes de azúcar, cerca del techo. ¿Cómo lo invita {name} a bajar?",
        ca: "El somni és a la cuina! Flota molt amunt entre els núvols de sucre, a prop del sostre. Com el convida {name} a baixar?",
        en: "The dream is in the kitchen! It floats high up among the sugar clouds, near the ceiling. How does {name} invite it down?",
        fr: "Le rêve est dans la cuisine ! Il flotte tout en haut parmi les nuages de sucre, près du plafond. Comment {name} l'invite à descendre ?",
      },
      options: [
        {
          id: "cake",
          title: {
            es: "Hornear un pastelito",
            ca: "Fornejar un pastisset",
            en: "Bake a little cake",
            fr: "Préparer un petit gâteau",
          },
          desc: {
            es: "El olor dulce de un pastel recién hecho llega hasta los sueños más altos.",
            ca: "L'olor dolça d'un pastís acabat de fer arriba fins als somnis més alts.",
            en: "The sweet smell of a freshly baked cake reaches even the highest dreams.",
            fr: "La douce odeur d'un gâteau tout chaud monte jusqu'aux rêves les plus hauts.",
          },
          imageSeed: "castle-c3dragonb-cake",
          icon: "bakery_dining",
          narrative: {
            es: "{name} hornea un pastelito de miel con ayuda de los cocineros y el sueño baja flotando, atraído por el olor dulce.",
            ca: "{name} forneja un pastisset de mel amb l'ajuda dels cuiners i el somni baixa flotant, atret per l'olor dolça.",
            en: "{name} bakes a little honey cake with the cooks' help and the dream floats down, drawn by the sweet smell.",
            fr: "{name} prépare un petit gâteau au miel avec l'aide des cuisiniers et le rêve descend en flottant, attiré par la douce odeur.",
          },
          next: "ending",
        },
        {
          id: "sparks",
          title: {
            es: "Los fueguecitos de Chispa",
            ca: "Els foquets d'en Chispa",
            en: "Chispa's little fireworks",
            fr: "Les petits feux de Chispa",
          },
          desc: {
            es: "Los estornudos del dragoncito hacen fuegos artificiales pequeñitos de colores.",
            ca: "Els esternuts del dragonet fan focs artificials petitons de colors.",
            en: "The little dragon's sneezes make tiny, colourful fireworks.",
            fr: "Les éternuements du petit dragon font de minuscules feux d'artifice colorés.",
          },
          imageSeed: "castle-c3dragonb-sparks",
          icon: "flare",
          narrative: {
            es: "{name} pide a Chispa que estornude sus chispas de colores y el sueño baja a mirar los fueguecitos hasta posarse en su hombro.",
            ca: "{name} demana a en Chispa que esternudi les seves espurnes de colors i el somni baixa a mirar els foquets fins a posar-se a la seva espatlla.",
            en: "{name} asks Chispa to sneeze his colourful sparks and the dream floats down to watch the tiny fireworks, landing on {name}'s shoulder.",
            fr: "{name} demande à Chispa d'éternuer ses étincelles colorées et le rêve descend regarder les petits feux, jusqu'à se poser sur son épaule.",
          },
          next: "ending",
        },
        {
          id: "lullaby",
          title: {
            es: "La nana de los cocineros",
            ca: "La cançó de bressol dels cuiners",
            en: "The cooks' lullaby",
            fr: "La berceuse des cuisiniers",
          },
          desc: {
            es: "En esta cocina se canta una nana dulce para que los pasteles suban esponjosos.",
            ca: "En aquesta cuina es canta una cançó de bressol dolça perquè els pastissos pugin esponjosos.",
            en: "In this kitchen they sing a sweet lullaby so the cakes rise soft and fluffy.",
            fr: "Dans cette cuisine, on chante une douce berceuse pour que les gâteaux gonflent bien moelleux.",
          },
          imageSeed: "castle-c3dragonb-lullaby",
          icon: "queue_music",
          narrative: {
            es: "{name} canta con los cocineros la nana de la cocina y el sueño baja bostezando hasta acurrucarse en sus manos.",
            ca: "{name} canta amb els cuiners la cançó de bressol de la cuina i el somni baixa badallant fins a arraulir-se a les seves mans.",
            en: "{name} sings the kitchen lullaby with the cooks and the dream drifts down yawning, curling up in {name}'s hands.",
            fr: "{name} chante la berceuse de la cuisine avec les cuisiniers et le rêve descend en bâillant, se blottissant dans ses mains.",
          },
          next: "ending",
        },
      ],
    },
    c3_dragon_c: {
      id: "c3_dragon_c",
      chapter: 3,
      question: {
        es: "¡El sueño está bailando! Gira entre las velas del salón tan deprisa que nadie puede alcanzarlo. ¿Qué hace {name}?",
        ca: "El somni està ballant! Gira entre les espelmes del saló tan de pressa que ningú no el pot atrapar. Què fa {name}?",
        en: "The dream is dancing! It spins between the candles of the ballroom so fast that nobody can catch it. What does {name} do?",
        fr: "Le rêve est en train de danser ! Il tourne entre les bougies de la salle si vite que personne ne peut l'attraper. Que fait {name} ?",
      },
      options: [
        {
          id: "dance",
          title: {
            es: "Bailar con él",
            ca: "Ballar amb ell",
            en: "Dance with it",
            fr: "Danser avec lui",
          },
          desc: {
            es: "A los sueños bailarines les encanta tener pareja de baile.",
            ca: "Als somnis balladors els encanta tenir parella de ball.",
            en: "Dancing dreams love having a dance partner.",
            fr: "Les rêves danseurs adorent avoir un partenaire de danse.",
          },
          imageSeed: "castle-c3dragonc-dance",
          icon: "celebration",
          narrative: {
            es: "{name} baila dando vueltas entre las velas hasta que el sueño, encantado, se posa suavemente en su hombro.",
            ca: "{name} balla fent voltes entre les espelmes fins que el somni, encantat, es posa suaument a la seva espatlla.",
            en: "{name} twirls between the candles until the dream, delighted, lands softly on {name}'s shoulder.",
            fr: "{name} danse en tournant entre les bougies jusqu'à ce que le rêve, ravi, se pose doucement sur son épaule.",
          },
          next: "ending",
        },
        {
          id: "piano",
          title: {
            es: "El piano encantado",
            ca: "El piano encantat",
            en: "The enchanted piano",
            fr: "Le piano enchanté",
          },
          desc: {
            es: "El piano del salón toca solo y conoce todas las canciones, hasta las más lentas.",
            ca: "El piano del saló toca sol i coneix totes les cançons, fins i tot les més lentes.",
            en: "The ballroom piano plays by itself and knows every song, even the slowest ones.",
            fr: "Le piano de la salle joue tout seul et connaît toutes les chansons, même les plus lentes.",
          },
          imageSeed: "castle-c3dragonc-piano",
          icon: "piano",
          narrative: {
            es: "{name} pide al piano encantado una melodía lenta y dulce, y el sueño baja meciéndose hasta sus manos.",
            ca: "{name} demana al piano encantat una melodia lenta i dolça, i el somni baixa gronxant-se fins a les seves mans.",
            en: "{name} asks the enchanted piano for a slow, sweet melody, and the dream sways gently down into {name}'s hands.",
            fr: "{name} demande au piano enchanté une mélodie lente et douce, et le rêve descend en se balançant jusqu'à ses mains.",
          },
          next: "ending",
        },
        {
          id: "bow",
          title: {
            es: "Una reverencia",
            ca: "Una reverència",
            en: "A polite bow",
            fr: "Une révérence",
          },
          desc: {
            es: "En este castillo, los bailes siempre empiezan con una reverencia elegante.",
            ca: "En aquest castell, els balls sempre comencen amb una reverència elegant.",
            en: "In this castle, every dance begins with an elegant bow.",
            fr: "Dans ce château, les danses commencent toujours par une révérence élégante.",
          },
          imageSeed: "castle-c3dragonc-bow",
          icon: "waving_hand",
          narrative: {
            es: "{name} hace una reverencia elegante para pedir el siguiente baile y el sueño se acerca girando despacito hasta su mano.",
            ca: "{name} fa una reverència elegant per demanar el següent ball i el somni s'acosta girant a poc a poc fins a la seva mà.",
            en: "{name} makes an elegant bow to ask for the next dance and the dream spins slowly closer, settling into {name}'s hand.",
            fr: "{name} fait une révérence élégante pour demander la prochaine danse et le rêve s'approche en tournant doucement jusqu'à sa main.",
          },
          next: "ending",
        },
      ],
    },
    c3_mirror_a: {
      id: "c3_mirror_a",
      chapter: 3,
      question: {
        es: "¡Es la piedra de luna! Brilla en el fondo de la fuente de los deseos, bajo el agua plateada. ¿Cómo la consigue {name}?",
        ca: "És la pedra de lluna! Brilla al fons de la font dels desitjos, sota l'aigua platejada. Com l'aconsegueix {name}?",
        en: "It's the moonstone! It shines at the bottom of the wishing fountain, under the silver water. How does {name} get it?",
        fr: "C'est la pierre de lune ! Elle brille au fond de la fontaine aux souhaits, sous l'eau argentée. Comment {name} va la récupérer ?",
      },
      options: [
        {
          id: "wish",
          title: {
            es: "Pedir un deseo",
            ca: "Demanar un desig",
            en: "Make a wish",
            fr: "Faire un vœu",
          },
          desc: {
            es: "Quien pide un deseo de corazón recibe una sorpresa de la fuente.",
            ca: "Qui demana un desig de tot cor rep una sorpresa de la font.",
            en: "Whoever makes a wish with all their heart gets a surprise from the fountain.",
            fr: "Qui fait un vœu de tout son cœur reçoit une surprise de la fontaine.",
          },
          imageSeed: "castle-c3mirrora-wish",
          icon: "favorite",
          narrative: {
            es: "{name} cierra los ojos, pide su deseo de todo corazón y la fuente eleva la piedra de luna sobre un chorrito de agua.",
            ca: "{name} tanca els ulls, demana el seu desig de tot cor i la font eleva la pedra de lluna sobre un rajolí d'aigua.",
            en: "{name} closes their eyes, wishes with all their heart, and the fountain lifts the moonstone up on a little jet of water.",
            fr: "{name} ferme les yeux, fait un vœu de tout son cœur et la fontaine soulève la pierre de lune sur un petit jet d'eau.",
          },
          next: "ending",
        },
        {
          id: "goldfish",
          title: {
            es: "El pez dorado",
            ca: "El peix daurat",
            en: "The golden fish",
            fr: "Le poisson doré",
          },
          desc: {
            es: "Un pececito dorado vive en la fuente y bucea mejor que nadie.",
            ca: "Un peixet daurat viu a la font i busseja millor que ningú.",
            en: "A little golden fish lives in the fountain and dives better than anyone.",
            fr: "Un petit poisson doré vit dans la fontaine et plonge mieux que personne.",
          },
          imageSeed: "castle-c3mirrora-fish",
          icon: "waves",
          narrative: {
            es: "{name} pide ayuda al pececito dorado, que bucea hasta el fondo y sube la piedra de luna empujándola con el hocico.",
            ca: "{name} demana ajuda al peixet daurat, que busseja fins al fons i puja la pedra de lluna empenyent-la amb el musell.",
            en: "{name} asks the little golden fish for help, and it dives to the bottom and nudges the moonstone all the way up with its nose.",
            fr: "{name} demande de l'aide au petit poisson doré, qui plonge jusqu'au fond et remonte la pierre de lune en la poussant avec son museau.",
          },
          next: "ending",
        },
        {
          id: "bubbles",
          title: {
            es: "Las burbujas mágicas",
            ca: "Les bombolles màgiques",
            en: "The magic bubbles",
            fr: "Les bulles magiques",
          },
          desc: {
            es: "Las burbujas de la fuente pueden abrazar las cosas y subirlas flotando.",
            ca: "Les bombolles de la font poden abraçar les coses i pujar-les flotant.",
            en: "The fountain's bubbles can hug things and float them up.",
            fr: "Les bulles de la fontaine peuvent envelopper les choses et les faire remonter en flottant.",
          },
          imageSeed: "castle-c3mirrora-bubbles",
          icon: "bubble_chart",
          narrative: {
            es: "{name} sopla suavecito sobre el agua y una burbuja baja hasta el fondo, abraza la piedra de luna y la sube flotando hasta sus manos.",
            ca: "{name} bufa suaument sobre l'aigua i una bombolla baixa fins al fons, abraça la pedra de lluna i la puja flotant fins a les seves mans.",
            en: "{name} blows gently over the water and a bubble sinks to the bottom, hugs the moonstone and floats it up into {name}'s hands.",
            fr: "{name} souffle doucement sur l'eau et une bulle descend jusqu'au fond, enveloppe la pierre de lune et la fait remonter en flottant jusqu'à ses mains.",
          },
          next: "ending",
        },
      ],
    },
    c3_mirror_b: {
      id: "c3_mirror_b",
      chapter: 3,
      question: {
        es: "La armadura encantada duerme de pie desde hace cien años con la piedra de luna en su guante. ¿Cómo la despierta {name} sin asustarla?",
        ca: "L'armadura encantada dorm dreta des de fa cent anys amb la pedra de lluna al seu guant. Com la desperta {name} sense espantar-la?",
        en: "The enchanted armour has been sleeping on its feet for a hundred years with the moonstone in its glove. How does {name} wake it without startling it?",
        fr: "L'armure enchantée dort debout depuis cent ans avec la pierre de lune dans son gant. Comment {name} la réveille sans l'effrayer ?",
      },
      options: [
        {
          id: "knight-tale",
          title: {
            es: "Un cuento de caballeros",
            ca: "Un conte de cavallers",
            en: "A tale of knights",
            fr: "Un conte de chevaliers",
          },
          desc: {
            es: "Las armaduras sueñan con torneos y siempre quieren saber cómo acaban.",
            ca: "Les armadures somien amb tornejos i sempre volen saber com acaben.",
            en: "Suits of armour dream of tournaments and always want to know how they end.",
            fr: "Les armures rêvent de tournois et veulent toujours savoir comment ils finissent.",
          },
          imageSeed: "castle-c3mirrorb-tale",
          icon: "history_edu",
          narrative: {
            es: "{name} cuenta en voz alta un cuento de caballeros valientes y la armadura despierta aplaudiendo y abre el guante con la piedra de luna.",
            ca: "{name} explica en veu alta un conte de cavallers valents i l'armadura es desperta aplaudint i obre el guant amb la pedra de lluna.",
            en: "{name} tells a tale of brave knights out loud and the armour wakes up clapping, opening its glove with the moonstone.",
            fr: "{name} raconte à voix haute un conte de chevaliers courageux et l'armure se réveille en applaudissant, ouvrant son gant avec la pierre de lune.",
          },
          next: "ending",
        },
        {
          id: "polish",
          title: {
            es: "Sacarle brillo",
            ca: "Treure-li lluentor",
            en: "Polish it shiny",
            fr: "La faire briller",
          },
          desc: {
            es: "Un buen caballero siempre despierta cuando su armadura brilla como nueva.",
            ca: "Un bon cavaller sempre es desperta quan la seva armadura brilla com a nova.",
            en: "A good knight always wakes when his armour shines like new.",
            fr: "Un bon chevalier se réveille toujours quand son armure brille comme neuve.",
          },
          imageSeed: "castle-c3mirrorb-polish",
          icon: "cleaning_services",
          narrative: {
            es: "{name} frota la armadura con un paño suave hasta que brilla entera, y ella despierta entre risas de cosquillas ofreciendo la piedra de luna.",
            ca: "{name} frega l'armadura amb un drap suau fins que brilla tota, i ella es desperta entre riures de pessigolles oferint la pedra de lluna.",
            en: "{name} rubs the armour with a soft cloth until it shines all over, and it wakes up giggling with tickles, offering the moonstone.",
            fr: "{name} frotte l'armure avec un chiffon doux jusqu'à ce qu'elle brille toute entière, et elle se réveille en riant de chatouilles, offrant la pierre de lune.",
          },
          next: "ending",
        },
        {
          id: "trumpet",
          title: {
            es: "El toque de desayuno",
            ca: "El toc d'esmorzar",
            en: "The breakfast call",
            fr: "La sonnerie du petit-déjeuner",
          },
          desc: {
            es: "Ningún caballero del reino sigue dormido cuando suena la trompeta del desayuno.",
            ca: "Cap cavaller del regne no segueix adormit quan sona la trompeta de l'esmorzar.",
            en: "No knight in the kingdom stays asleep when the breakfast trumpet sounds.",
            fr: "Aucun chevalier du royaume ne reste endormi quand sonne la trompette du petit-déjeuner.",
          },
          imageSeed: "castle-c3mirrorb-trumpet",
          icon: "campaign",
          narrative: {
            es: "{name} tararea bajito el toque de trompeta del desayuno y la armadura despierta de un salto, entregando la piedra de luna con una reverencia.",
            ca: "{name} taral·leja fluixet el toc de trompeta de l'esmorzar i l'armadura es desperta d'un salt, lliurant la pedra de lluna amb una reverència.",
            en: "{name} softly hums the breakfast trumpet call and the armour wakes with a jump, handing over the moonstone with a bow.",
            fr: "{name} fredonne tout bas la sonnerie de trompette du petit-déjeuner et l'armure se réveille d'un bond, remettant la pierre de lune avec une révérence.",
          },
          next: "ending",
        },
      ],
    },
    c3_mirror_c: {
      id: "c3_mirror_c",
      chapter: 3,
      question: {
        es: "En el desván hay cientos de canicas y bolitas brillantes, y la piedra de luna se esconde entre ellas. ¿Cómo la encuentra {name}?",
        ca: "A les golfes hi ha centenars de bales i boletes brillants, i la pedra de lluna s'amaga entre elles. Com la troba {name}?",
        en: "The attic is full of hundreds of marbles and shiny little balls, and the moonstone is hiding among them. How does {name} find it?",
        fr: "Dans le grenier, il y a des centaines de billes et de petites boules brillantes, et la pierre de lune se cache parmi elles. Comment {name} va la trouver ?",
      },
      options: [
        {
          id: "moonlight",
          title: {
            es: "Abrir la ventana redonda",
            ca: "Obrir la finestra rodona",
            en: "Open the round window",
            fr: "Ouvrir la fenêtre ronde",
          },
          desc: {
            es: "La luz de la luna sabe encontrar a su piedra entre mil canicas.",
            ca: "La llum de la lluna sap trobar la seva pedra entre mil bales.",
            en: "Moonlight knows how to find its own stone among a thousand marbles.",
            fr: "La lumière de la lune sait retrouver sa pierre parmi mille billes.",
          },
          imageSeed: "castle-c3mirrorc-moonlight",
          icon: "nightlight",
          narrative: {
            es: "{name} abre la ventana redonda del desván y un rayo de luna entra despacio hasta posarse sobre la piedra, que responde brillando.",
            ca: "{name} obre la finestra rodona de les golfes i un raig de lluna entra a poc a poc fins a posar-se sobre la pedra, que respon brillant.",
            en: "{name} opens the round attic window and a moonbeam glides in slowly, settling on the stone, which answers with a glow.",
            fr: "{name} ouvre la fenêtre ronde du grenier et un rayon de lune entre doucement jusqu'à se poser sur la pierre, qui répond en brillant.",
          },
          next: "ending",
        },
        {
          id: "toys",
          title: {
            es: "Despertar a los juguetes",
            ca: "Despertar les joguines",
            en: "Wake up the toys",
            fr: "Réveiller les jouets",
          },
          desc: {
            es: "Los juguetes olvidados conocen cada rincón del desván.",
            ca: "Les joguines oblidades coneixen cada racó de les golfes.",
            en: "The forgotten toys know every corner of the attic.",
            fr: "Les jouets oubliés connaissent chaque recoin du grenier.",
          },
          imageSeed: "castle-c3mirrorc-toys",
          icon: "toys",
          narrative: {
            es: "{name} despierta con cuidado a los juguetes olvidados y los soldaditos de madera buscan en fila hasta encontrar la piedra de luna.",
            ca: "{name} desperta amb cura les joguines oblidades i els soldadets de fusta busquen en fila fins a trobar la pedra de lluna.",
            en: "{name} gently wakes the forgotten toys and the little wooden soldiers search in a line until they find the moonstone.",
            fr: "{name} réveille avec soin les jouets oubliés et les petits soldats de bois cherchent en file jusqu'à trouver la pierre de lune.",
          },
          next: "ending",
        },
        {
          id: "listen",
          title: {
            es: "Escuchar su nana",
            ca: "Escoltar la seva cançó de bressol",
            en: "Listen for its lullaby",
            fr: "Écouter sa berceuse",
          },
          desc: {
            es: "La piedra de luna canturrea bajito la misma nana que canta la luna.",
            ca: "La pedra de lluna cantusseja fluixet la mateixa cançó de bressol que canta la lluna.",
            en: "The moonstone softly hums the same lullaby the moon sings.",
            fr: "La pierre de lune fredonne tout bas la même berceuse que la lune.",
          },
          imageSeed: "castle-c3mirrorc-listen",
          icon: "hearing",
          narrative: {
            es: "{name} cierra los ojos, escucha un canturreo plateado entre los juguetes y aparta dos canicas para descubrir la piedra de luna.",
            ca: "{name} tanca els ulls, escolta un cantusseig platejat entre les joguines i aparta dues bales per descobrir la pedra de lluna.",
            en: "{name} closes their eyes, hears a silvery hum among the toys and moves two marbles aside to uncover the moonstone.",
            fr: "{name} ferme les yeux, entend un fredonnement argenté parmi les jouets et écarte deux billes pour découvrir la pierre de lune.",
          },
          next: "ending",
        },
      ],
    },
    c3_stairs_a: {
      id: "c3_stairs_a",
      chapter: 3,
      question: {
        es: "Las hebras de luna brillan al alcance de la mano, pero resbalan entre los dedos como agua. ¿Cómo las recoge {name}?",
        ca: "Els brins de lluna brillen a l'abast de la mà, però rellisquen entre els dits com aigua. Com els recull {name}?",
        en: "The moon threads shine within arm's reach, but they slip through fingers like water. How does {name} gather them?",
        fr: "Les fils de lune brillent à portée de main, mais ils glissent entre les doigts comme de l'eau. Comment {name} va les recueillir ?",
      },
      options: [
        {
          id: "moon-song",
          title: {
            es: "Cantar a la luna",
            ca: "Cantar a la lluna",
            en: "Sing to the moon",
            fr: "Chanter pour la lune",
          },
          desc: {
            es: "Si la luna oye una canción bonita, ella misma trenza sus hebras.",
            ca: "Si la lluna sent una cançó bonica, ella mateixa trena els seus brins.",
            en: "If the moon hears a lovely song, she braids her threads herself.",
            fr: "Si la lune entend une jolie chanson, elle tresse elle-même ses fils.",
          },
          imageSeed: "castle-c3stairsa-song",
          icon: "nights_stay",
          narrative: {
            es: "{name} canta una canción a la luna y ella, sonriendo, trenza sus hebras de luz y las deja caer hechas un ovillo plateado.",
            ca: "{name} canta una cançó a la lluna i ella, somrient, trena els seus brins de llum i els deixa caure fets un cabdell platejat.",
            en: "{name} sings a song to the moon and she, smiling, braids her threads of light and lets them fall as a silver ball of yarn.",
            fr: "{name} chante une chanson à la lune et celle-ci, souriante, tresse ses fils de lumière et les laisse tomber en une pelote argentée.",
          },
          next: "ending",
        },
        {
          id: "silver-comb",
          title: {
            es: "El peine de plata",
            ca: "La pinta de plata",
            en: "The silver comb",
            fr: "Le peigne d'argent",
          },
          desc: {
            es: "Peinar la luz de luna despacito la convierte en hilo de seda.",
            ca: "Pentinar la llum de lluna a poc a poc la converteix en fil de seda.",
            en: "Combing moonlight very slowly turns it into silky thread.",
            fr: "Peigner la lumière de lune tout doucement la transforme en fil de soie.",
          },
          imageSeed: "castle-c3stairsa-comb",
          icon: "brush",
          narrative: {
            es: "{name} peina las hebras de luna muy despacito con un peine de plata hasta que se vuelven un hilo suave y brillante.",
            ca: "{name} pentina els brins de lluna molt a poc a poc amb una pinta de plata fins que es tornen un fil suau i brillant.",
            en: "{name} combs the moon threads very slowly with a silver comb until they turn into a soft, shining thread.",
            fr: "{name} peigne les fils de lune tout doucement avec un peigne d'argent jusqu'à ce qu'ils deviennent un fil doux et brillant.",
          },
          next: "ending",
        },
        {
          id: "butterfly-hands",
          title: {
            es: "Manos de mariposa",
            ca: "Mans de papallona",
            en: "Butterfly hands",
            fr: "Des mains de papillon",
          },
          desc: {
            es: "Si las manos se mueven suaves como alas, la luz no resbala.",
            ca: "Si les mans es mouen suaus com ales, la llum no rellisca.",
            en: "If hands move as softly as wings, the light doesn't slip away.",
            fr: "Si les mains bougent aussi doucement que des ailes, la lumière ne glisse pas.",
          },
          imageSeed: "castle-c3stairsa-hands",
          icon: "front_hand",
          narrative: {
            es: "{name} mueve las manos lentas y suaves como alas de mariposa y las hebras de luna se quedan quietecitas en sus palmas.",
            ca: "{name} mou les mans lentes i suaus com ales de papallona i els brins de lluna es queden quiets a les seves palmes.",
            en: "{name} moves both hands slow and soft like butterfly wings and the moon threads lie still in {name}'s palms.",
            fr: "{name} bouge les mains lentes et douces comme des ailes de papillon et les fils de lune restent tout tranquilles dans ses paumes.",
          },
          next: "ending",
        },
      ],
    },
    c3_stairs_b: {
      id: "c3_stairs_b",
      chapter: 3,
      question: {
        es: "Los hilos de arcoíris solo despiertan cuando la luz atraviesa las vidrieras... ¡y es de noche! ¿Cómo ilumina {name} el gran salón?",
        ca: "Els fils d'arc de Sant Martí només es desperten quan la llum travessa els vitralls... i és de nit! Com il·lumina {name} el gran saló?",
        en: "The rainbow threads only wake when light shines through the stained glass... and it's night-time! How does {name} light up the great hall?",
        fr: "Les fils d'arc-en-ciel ne se réveillent que lorsque la lumière traverse les vitraux... et il fait nuit ! Comment {name} va éclairer la grande salle ?",
      },
      options: [
        {
          id: "candles",
          title: {
            es: "Las velas flotantes",
            ca: "Les espelmes flotants",
            en: "The floating candles",
            fr: "Les bougies flottantes",
          },
          desc: {
            es: "Cien velas flotantes viven en el castillo y adoran ayudar.",
            ca: "Cent espelmes flotants viuen al castell i adoren ajudar.",
            en: "A hundred floating candles live in the castle and love to help.",
            fr: "Cent bougies flottantes vivent dans le château et adorent aider.",
          },
          imageSeed: "castle-c3stairsb-candles",
          icon: "emoji_objects",
          narrative: {
            es: "{name} invita a las velas flotantes del castillo a reunirse junto a las vidrieras y los hilos de arcoíris despiertan llenos de colores.",
            ca: "{name} convida les espelmes flotants del castell a reunir-se al costat dels vitralls i els fils d'arc de Sant Martí es desperten plens de colors.",
            en: "{name} invites the castle's floating candles to gather by the stained glass and the rainbow threads wake up full of colours.",
            fr: "{name} invite les bougies flottantes du château à se rassembler près des vitraux et les fils d'arc-en-ciel se réveillent remplis de couleurs.",
          },
          next: "ending",
        },
        {
          id: "lantern",
          title: {
            es: "El farol del guardián",
            ca: "El fanal del guardià",
            en: "The keeper's lantern",
            fr: "La lanterne du gardien",
          },
          desc: {
            es: "El guardián de la torre tiene un farol dorado que brilla como un solecito.",
            ca: "El guardià de la torre té un fanal daurat que brilla com un solet.",
            en: "The tower keeper has a golden lantern that shines like a little sun.",
            fr: "Le gardien de la tour a une lanterne dorée qui brille comme un petit soleil.",
          },
          imageSeed: "castle-c3stairsb-lantern",
          icon: "wb_incandescent",
          narrative: {
            es: "{name} pide prestado el farol dorado del guardián y lo alza frente a las vidrieras, que se encienden de mil colores.",
            ca: "{name} demana prestat el fanal daurat del guardià i l'alça davant dels vitralls, que s'encenen de mil colors.",
            en: "{name} borrows the keeper's golden lantern and holds it up to the stained glass, which lights up in a thousand colours.",
            fr: "{name} emprunte la lanterne dorée du gardien et la lève devant les vitraux, qui s'illuminent de mille couleurs.",
          },
          next: "ending",
        },
        {
          id: "pocket-mirror",
          title: {
            es: "Un espejito de bolsillo",
            ca: "Un mirallet de butxaca",
            en: "A little pocket mirror",
            fr: "Un petit miroir de poche",
          },
          desc: {
            es: "Un espejito puede atrapar la luz de la luna y llevarla a donde haga falta.",
            ca: "Un mirallet pot atrapar la llum de la lluna i portar-la on calgui.",
            en: "A little mirror can catch the moonlight and carry it wherever it's needed.",
            fr: "Un petit miroir peut attraper la lumière de la lune et l'emporter là où il faut.",
          },
          imageSeed: "castle-c3stairsb-mirror",
          icon: "dark_mode",
          narrative: {
            es: "{name} atrapa la luz de la luna con un espejito de bolsillo y la apunta a las vidrieras, despertando un arcoíris en plena noche.",
            ca: "{name} atrapa la llum de la lluna amb un mirallet de butxaca i l'apunta als vitralls, despertant un arc de Sant Martí en plena nit.",
            en: "{name} catches the moonlight with a little pocket mirror and aims it at the stained glass, waking a rainbow in the middle of the night.",
            fr: "{name} attrape la lumière de la lune avec un petit miroir de poche et la dirige vers les vitraux, réveillant un arc-en-ciel en pleine nuit.",
          },
          next: "ending",
        },
      ],
    },
    c3_stairs_c: {
      id: "c3_stairs_c",
      chapter: 3,
      question: {
        es: "Las nubecitas son tímidas como ovejas y se alejan flotando cuando alguien estira la mano. ¿Cómo consigue {name} su algodón?",
        ca: "Els nuvolets són tímids com ovelles i s'allunyen flotant quan algú estira la mà. Com aconsegueix {name} el seu cotó?",
        en: "The little clouds are shy like sheep and float away when anyone reaches out a hand. How does {name} get their cotton?",
        fr: "Les petits nuages sont timides comme des moutons et s'éloignent en flottant dès qu'on tend la main. Comment {name} va obtenir leur coton ?",
      },
      options: [
        {
          id: "shepherd-whistle",
          title: {
            es: "El silbido del pastor",
            ca: "El xiulet del pastor",
            en: "The shepherd's whistle",
            fr: "Le sifflet du berger",
          },
          desc: {
            es: "Las nubes del castillo acuden contentas al silbido suave de un pastor.",
            ca: "Els núvols del castell acudeixen contents al xiulet suau d'un pastor.",
            en: "The castle clouds come along happily at a shepherd's soft whistle.",
            fr: "Les nuages du château accourent joyeusement au doux sifflet d'un berger.",
          },
          imageSeed: "castle-c3stairsc-whistle",
          icon: "music_note",
          narrative: {
            es: "{name} silba suave como un pastor de nubes y las nubecitas se acercan en fila, regalando copitos de algodón blanco.",
            ca: "{name} xiula suau com un pastor de núvols i els nuvolets s'acosten en fila, regalant floquets de cotó blanc.",
            en: "{name} whistles softly like a cloud shepherd and the little clouds line up close, gifting tufts of white cotton.",
            fr: "{name} siffle doucement comme un berger de nuages et les petits nuages s'approchent en file, offrant des touffes de coton blanc.",
          },
          next: "ending",
        },
        {
          id: "wind-tickles",
          title: {
            es: "Cosquillas de viento",
            ca: "Pessigolles de vent",
            en: "Wind tickles",
            fr: "Des chatouilles de vent",
          },
          desc: {
            es: "Una brisita suave hace reír a las nubes hasta que sueltan copitos.",
            ca: "Una brisa suau fa riure els núvols fins que deixen anar floquets.",
            en: "A gentle little breeze makes the clouds laugh until they shed tufts.",
            fr: "Une petite brise douce fait rire les nuages jusqu'à ce qu'ils lâchent des touffes.",
          },
          imageSeed: "castle-c3stairsc-breeze",
          icon: "air",
          narrative: {
            es: "{name} sopla una brisita suave que hace cosquillas a las nubecitas, y ellas ríen soltando copitos de algodón blanco.",
            ca: "{name} bufa una brisa suau que fa pessigolles als nuvolets, i ells riuen deixant anar floquets de cotó blanc.",
            en: "{name} blows a gentle little breeze that tickles the clouds, and they giggle, shedding tufts of white cotton.",
            fr: "{name} souffle une petite brise douce qui chatouille les nuages, et ceux-ci rient en lâchant des touffes de coton blanc.",
          },
          next: "ending",
        },
        {
          id: "smallest-cloud",
          title: {
            es: "La nube más pequeña",
            ca: "El núvol més petit",
            en: "The smallest cloud",
            fr: "Le plus petit nuage",
          },
          desc: {
            es: "La nubecita más pequeña es curiosa y le encanta hacer amigos.",
            ca: "El nuvolet més petit és curiós i li encanta fer amics.",
            en: "The smallest little cloud is curious and loves making friends.",
            fr: "Le plus petit nuage est curieux et adore se faire des amis.",
          },
          imageSeed: "castle-c3stairsc-cloud",
          icon: "filter_drama",
          narrative: {
            es: "{name} saluda a la nubecita más pequeña, que se acerca curiosa y comparte su algodón a cambio de ver el telar de cerca.",
            ca: "{name} saluda el nuvolet més petit, que s'acosta curiós i comparteix el seu cotó a canvi de veure el teler de prop.",
            en: "{name} waves at the smallest little cloud, which drifts closer out of curiosity and shares its cotton in exchange for seeing the loom up close.",
            fr: "{name} salue le plus petit nuage, qui s'approche curieux et partage son coton en échange de voir le métier à tisser de près.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "", en: "", fr: "" },
      options: [],
    },
  },
};
