import type { StoryTree } from "./types";

// Branching story tree for the "chef" template (El Chef Más Pequeño).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es source of truth + ca/en/fr). {name} = child's name.

export const chefTree: StoryTree = {
  templateId: "chef",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} se pone el gorro de chef y entra en la cocina mágica, donde todo huele a pan recién hecho. De pronto, tres sorpresas asoman entre cazuelas y estanterías. ¿Cuál descubre primero?",
        ca: "{name} es posa el barret de xef i entra a la cuina màgica, on tot fa olor de pa acabat de fer. De sobte, tres sorpreses apareixen entre cassoles i prestatges. Quina descobreix primer?",
        en: "{name} puts on a chef's hat and steps into the magic kitchen, where everything smells of freshly baked bread. Suddenly, three surprises peek out between pots and shelves. Which one to discover first?",
        fr: "{name} met sa toque de chef et entre dans la cuisine magique, où tout sent le pain tout chaud. Soudain, trois surprises apparaissent entre les casseroles et les étagères. Laquelle découvrir en premier ?",
      },
      options: [
        {
          id: "dough",
          title: {
            es: "La masa risueña",
            ca: "La massa riallera",
            en: "The giggly dough",
            fr: "La pâte rieuse",
          },
          desc: {
            es: "Una bolita de masa dorada da saltitos y ríe sobre la mesa de madera.",
            ca: "Una boleta de massa daurada fa saltirons i riu sobre la taula de fusta.",
            en: "A little ball of golden dough bounces and giggles on the wooden table.",
            fr: "Une petite boule de pâte dorée sautille et rigole sur la table en bois.",
          },
          imageSeed: "chef-c1-dough",
          icon: "bakery_dining",
          narrative: {
            es: "{name} se acerca despacito a una bolita de masa dorada que da saltitos y ríe a carcajadas sobre la gran mesa de madera.",
            ca: "{name} s'acosta a poc a poc a una boleta de massa daurada que fa saltirons i riu per sota el nas sobre la gran taula de fusta.",
            en: "{name} tiptoes up to a little ball of golden dough bouncing and giggling on the big wooden table.",
            fr: "{name} s'approche tout doucement d'une petite boule de pâte dorée qui sautille et rigole sur la grande table en bois.",
          },
          next: "c2_dough",
        },
        {
          id: "book",
          title: {
            es: "El libro de recetas",
            ca: "El llibre de receptes",
            en: "The recipe book",
            fr: "Le livre de recettes",
          },
          desc: {
            es: "Un libro antiguo de tapas gastadas brilla con una página de letras doradas.",
            ca: "Un llibre antic de tapes gastades brilla amb una pàgina de lletres daurades.",
            en: "An old book with worn covers glows with a page of golden letters.",
            fr: "Un vieux livre aux couvertures usées brille avec une page aux lettres dorées.",
          },
          imageSeed: "chef-c1-book",
          icon: "menu_book",
          narrative: {
            es: "{name} abre un libro de recetas muy antiguo y descubre que una de sus páginas brilla con letras doradas que parecen recién escritas.",
            ca: "{name} obre un llibre de receptes molt antic i descobreix que una de les seves pàgines brilla amb lletres daurades que semblen acabades d'escriure.",
            en: "{name} opens a very old recipe book and discovers that one of its pages glows with golden letters that look freshly written.",
            fr: "{name} ouvre un très vieux livre de recettes et découvre qu'une de ses pages brille avec des lettres dorées qui semblent fraîchement écrites.",
          },
          next: "c2_book",
        },
        {
          id: "pantry",
          title: {
            es: "La despensa secreta",
            ca: "El rebost secret",
            en: "The secret pantry",
            fr: "Le garde-manger secret",
          },
          desc: {
            es: "Detrás de los sacos de harina, una puertecita deja escapar una luz calentita.",
            ca: "Darrere dels sacs de farina, una porteta deixa escapar una llum calentona.",
            en: "Behind the flour sacks, a tiny door lets out a warm little light.",
            fr: "Derrière les sacs de farine, une petite porte laisse échapper une lumière toute chaude.",
          },
          imageSeed: "chef-c1-pantry",
          icon: "door_front",
          narrative: {
            es: "{name} aparta los sacos de harina, empuja una puertecita escondida y encuentra una escalera iluminada por una luz dorada y calentita.",
            ca: "{name} aparta els sacs de farina, empeny una porteta amagada i troba una escala il·luminada per una llum daurada i calentona.",
            en: "{name} pushes aside the flour sacks, opens a hidden tiny door and finds a staircase lit by a warm golden light.",
            fr: "{name} écarte les sacs de farine, pousse une petite porte cachée et trouve un escalier éclairé par une lumière dorée et toute chaude.",
          },
          next: "c2_pantry",
        },
      ],
    },
    c2_dough: {
      id: "c2_dough",
      chapter: 2,
      question: {
        es: "La bolita de masa da un salto y se presenta: se llama Miga. Esta noche quiere convertirse en el pastel de la gran fiesta, pero le falta una pizca de dulzura mágica, el ingrediente que hace soñar a los pasteles. ¿Dónde la buscan {name} y Miga?",
        ca: "La boleta de massa fa un salt i es presenta: es diu Miga. Aquesta nit vol convertir-se en el pastís de la gran festa, però li falta un pessic de dolçor màgica, l'ingredient que fa somiar els pastissos. On la busquen {name} i la Miga?",
        en: "The little ball of dough hops up and introduces herself: her name is Miga. Tonight she wants to become the cake for the big party, but she is missing a pinch of magic sweetness, the ingredient that makes cakes dream. Where do {name} and Miga look for it?",
        fr: "La petite boule de pâte fait un bond et se présente : elle s'appelle Miga. Ce soir, elle veut devenir le gâteau de la grande fête, mais il lui manque une pincée de douceur magique, l'ingrédient qui fait rêver les gâteaux. Où {name} et Miga vont-ils la chercher ?",
      },
      options: [
        {
          id: "candy-garden",
          title: {
            es: "El huerto de caramelo",
            ca: "L'hort de caramel",
            en: "The candy garden",
            fr: "Le potager de bonbons",
          },
          desc: {
            es: "Tras la puerta del jardín crecen flores de piruleta con pétalos de azúcar.",
            ca: "Darrere la porta del jardí creixen flors de piruleta amb pètals de sucre.",
            en: "Behind the garden door grow lollipop flowers with sugar petals.",
            fr: "Derrière la porte du jardin poussent des fleurs-sucettes aux pétales de sucre.",
          },
          imageSeed: "chef-c2dough-candy",
          icon: "filter_vintage",
          narrative: {
            es: "{name} y Miga salen al huerto de caramelo, donde crecen flores de piruleta de colores con pétalos espolvoreados de azúcar.",
            ca: "{name} i la Miga surten a l'hort de caramel, on creixen flors de piruleta de colors amb pètals empolvorats de sucre.",
            en: "{name} and Miga step out into the candy garden, where colourful lollipop flowers grow with petals dusted in sugar.",
            fr: "{name} et Miga sortent dans le potager de bonbons, où poussent des fleurs-sucettes colorées aux pétales saupoudrés de sucre.",
          },
          next: "c3_dough_a",
        },
        {
          id: "golden-hive",
          title: {
            es: "La colmena dorada",
            ca: "El rusc daurat",
            en: "The golden hive",
            fr: "La ruche dorée",
          },
          desc: {
            es: "En el patio, unas abejitas doradas guardan una miel que brilla como el sol.",
            ca: "Al pati, unes abelletes daurades guarden una mel que brilla com el sol.",
            en: "In the courtyard, little golden bees keep a honey that glows like the sun.",
            fr: "Dans la cour, de petites abeilles dorées gardent un miel qui brille comme le soleil.",
          },
          imageSeed: "chef-c2dough-hive",
          icon: "hive",
          narrative: {
            es: "{name} y Miga llegan al patio donde las abejitas doradas zumban alrededor de una colmena llena de miel que brilla como el sol.",
            ca: "{name} i la Miga arriben al pati on les abelletes daurades brunzeixen al voltant d'un rusc ple de mel que brilla com el sol.",
            en: "{name} and Miga reach the courtyard where little golden bees buzz around a hive full of honey that glows like the sun.",
            fr: "{name} et Miga arrivent dans la cour où de petites abeilles dorées bourdonnent autour d'une ruche pleine de miel qui brille comme le soleil.",
          },
          next: "c3_dough_b",
        },
        {
          id: "choco-fountain",
          title: {
            es: "La fuente de chocolate",
            ca: "La font de xocolata",
            en: "The chocolate fountain",
            fr: "La fontaine de chocolat",
          },
          desc: {
            es: "En la bodega duerme una fuente de chocolate calentito que huele a fiesta.",
            ca: "Al celler dorm una font de xocolata calentona que fa olor de festa.",
            en: "In the cellar sleeps a fountain of warm chocolate that smells like a party.",
            fr: "Dans la cave dort une fontaine de chocolat chaud qui sent bon la fête.",
          },
          imageSeed: "chef-c2dough-fountain",
          icon: "coffee",
          narrative: {
            es: "{name} y Miga bajan a la bodega, donde una fuente de chocolate duerme en silencio con su chocolate calentito descansando en el fondo.",
            ca: "{name} i la Miga baixen al celler, on una font de xocolata dorm en silenci amb la seva xocolata calentona descansant al fons.",
            en: "{name} and Miga go down to the cellar, where a chocolate fountain sleeps in silence with its warm chocolate resting at the bottom.",
            fr: "{name} et Miga descendent à la cave, où une fontaine de chocolat dort en silence, son chocolat chaud reposant tout au fond.",
          },
          next: "c3_dough_c",
        },
      ],
    },
    c2_book: {
      id: "c2_book",
      chapter: 2,
      question: {
        es: "La página brillante muestra la receta de la Tarta de las Estrellas: harina, huevos, miel... pero el último ingrediente está escrito en adivinanza: 'Brillo dulce que no viene del sol'. ¿Dónde lo busca {name}?",
        ca: "La pàgina brillant mostra la recepta del Pastís de les Estrelles: farina, ous, mel... però l'últim ingredient està escrit en endevinalla: 'Llum dolça que no ve del sol'. On el busca {name}?",
        en: "The glowing page shows the recipe for the Cake of Stars: flour, eggs, honey... but the last ingredient is written as a riddle: 'A sweet glow that does not come from the sun.' Where does {name} look for it?",
        fr: "La page brillante montre la recette du Gâteau des Étoiles : farine, œufs, miel... mais le dernier ingrédient est écrit en devinette : « Une douce lueur qui ne vient pas du soleil ». Où {name} va le chercher ?",
      },
      options: [
        {
          id: "spice-tower",
          title: {
            es: "La torre de especias",
            ca: "La torre d'espècies",
            en: "The spice tower",
            fr: "La tour aux épices",
          },
          desc: {
            es: "Una estantería altísima llena de tarritos de colores que susurran bajito.",
            ca: "Una prestatgeria altíssima plena de potets de colors que xiuxiuegen fluixet.",
            en: "A very tall shelf full of colourful little jars that whisper softly.",
            fr: "Une étagère très haute pleine de petits pots colorés qui chuchotent tout bas.",
          },
          imageSeed: "chef-c2book-spices",
          icon: "shelves",
          narrative: {
            es: "{name} se acerca a la torre de especias, una estantería altísima donde cientos de tarritos de colores susurran entre ellos.",
            ca: "{name} s'acosta a la torre d'espècies, una prestatgeria altíssima on centenars de potets de colors xiuxiuegen entre ells.",
            en: "{name} approaches the spice tower, a very tall shelf where hundreds of colourful little jars whisper to each other.",
            fr: "{name} s'approche de la tour aux épices, une étagère très haute où des centaines de petits pots colorés chuchotent entre eux.",
          },
          next: "c3_book_a",
        },
        {
          id: "grandpa-oven",
          title: {
            es: "El horno abuelo",
            ca: "El forn avi",
            en: "The grandpa oven",
            fr: "Le four grand-père",
          },
          desc: {
            es: "El horno más viejo de la cocina conoce todas las recetas que se han horneado.",
            ca: "El forn més vell de la cuina coneix totes les receptes que s'hi han enfornat.",
            en: "The oldest oven in the kitchen knows every recipe ever baked.",
            fr: "Le plus vieux four de la cuisine connaît toutes les recettes jamais cuites.",
          },
          imageSeed: "chef-c2book-oven",
          icon: "oven",
          narrative: {
            es: "{name} visita al horno abuelo, el más viejo de la cocina, que canturrea bajito y conoce todas las recetas que se han horneado en el mundo.",
            ca: "{name} visita el forn avi, el més vell de la cuina, que cantusseja fluixet i coneix totes les receptes que s'han enfornat al món.",
            en: "{name} visits the grandpa oven, the oldest in the kitchen, who hums softly and knows every recipe ever baked in the world.",
            fr: "{name} rend visite au four grand-père, le plus vieux de la cuisine, qui fredonne tout bas et connaît toutes les recettes jamais cuites au monde.",
          },
          next: "c3_book_b",
        },
        {
          id: "moon-window",
          title: {
            es: "La ventana de la luna",
            ca: "La finestra de la lluna",
            en: "The moon window",
            fr: "La fenêtre de la lune",
          },
          desc: {
            es: "Por la noche, un polvito plateado cae sobre el alféizar de esa ventana.",
            ca: "A la nit, una polseta platejada cau sobre l'ampit d'aquella finestra.",
            en: "At night, a silvery dust falls on that windowsill.",
            fr: "La nuit, une poussière argentée tombe sur le rebord de cette fenêtre.",
          },
          imageSeed: "chef-c2book-window",
          icon: "window",
          narrative: {
            es: "{name} espera junto a la ventana de la luna, donde cada noche cae un polvito plateado y dulce sobre el alféizar.",
            ca: "{name} espera al costat de la finestra de la lluna, on cada nit cau una polseta platejada i dolça sobre l'ampit.",
            en: "{name} waits by the moon window, where every night a sweet silvery dust falls onto the windowsill.",
            fr: "{name} attend près de la fenêtre de la lune, où chaque nuit une poussière argentée et sucrée tombe sur le rebord.",
          },
          next: "c3_book_c",
        },
      ],
    },
    c2_pantry: {
      id: "c2_pantry",
      chapter: 2,
      question: {
        es: "Al final de la escalera, {name} descubre la Despensa de los Sabores, un pueblecito donde viven los ingredientes... ¡pero todo sabe a nada! Un guisante saltarín explica que la magia de los sabores se está apagando justo antes del gran banquete. ¿Por dónde empiezan?",
        ca: "Al final de l'escala, {name} descobreix el Rebost dels Sabors, un poblet on viuen els ingredients... però tot té gust de no-res! Un pèsol saltador explica que la màgia dels sabors s'està apagant just abans del gran banquet. Per on comencen?",
        en: "At the bottom of the stairs, {name} discovers the Pantry of Flavours, a little village where the ingredients live... but everything tastes of nothing! A bouncy pea explains that the magic of flavours is fading just before the great feast. Where do they begin?",
        fr: "Au bout de l'escalier, {name} découvre le Garde-Manger des Saveurs, un petit village où vivent les ingrédients... mais tout a un goût de rien ! Un petit pois bondissant explique que la magie des saveurs s'éteint juste avant le grand banquet. Par où vont-ils commencer ?",
      },
      options: [
        {
          id: "giant-pot",
          title: {
            es: "La olla gigante",
            ca: "L'olla gegant",
            en: "The giant pot",
            fr: "La marmite géante",
          },
          desc: {
            es: "La gran olla de la plaza está fría y ya no canta su canción de burbujas.",
            ca: "La gran olla de la plaça està freda i ja no canta la seva cançó de bombolles.",
            en: "The great pot in the square is cold and no longer sings its bubble song.",
            fr: "La grande marmite de la place est froide et ne chante plus sa chanson de bulles.",
          },
          imageSeed: "chef-c2pantry-pot",
          icon: "soup_kitchen",
          narrative: {
            es: "{name} y el guisante saltarín llegan a la plaza del pueblecito, donde la olla gigante está fría y en silencio, sin su canción de burbujas.",
            ca: "{name} i el pèsol saltador arriben a la plaça del poblet, on l'olla gegant està freda i en silenci, sense la seva cançó de bombolles.",
            en: "{name} and the bouncy pea reach the village square, where the giant pot sits cold and silent, without its bubble song.",
            fr: "{name} et le petit pois bondissant arrivent sur la place du village, où la marmite géante est froide et silencieuse, sans sa chanson de bulles.",
          },
          next: "c3_pantry_a",
        },
        {
          id: "herb-garden",
          title: {
            es: "El jardín de hierbas",
            ca: "El jardí d'herbes",
            en: "The herb garden",
            fr: "Le jardin d'herbes",
          },
          desc: {
            es: "Las matitas de menta y albahaca están mustias y han perdido su perfume.",
            ca: "Les mates de menta i alfàbrega estan musties i han perdut el seu perfum.",
            en: "The little mint and basil plants are wilted and have lost their perfume.",
            fr: "Les petits plants de menthe et de basilic sont fanés et ont perdu leur parfum.",
          },
          imageSeed: "chef-c2pantry-garden",
          icon: "potted_plant",
          narrative: {
            es: "{name} y el guisante saltarín entran en el jardín de hierbas, donde la menta y la albahaca están mustias y ya no perfuman el aire.",
            ca: "{name} i el pèsol saltador entren al jardí d'herbes, on la menta i l'alfàbrega estan musties i ja no perfumen l'aire.",
            en: "{name} and the bouncy pea step into the herb garden, where the mint and basil are wilted and no longer perfume the air.",
            fr: "{name} et le petit pois bondissant entrent dans le jardin d'herbes, où la menthe et le basilic sont fanés et ne parfument plus l'air.",
          },
          next: "c3_pantry_b",
        },
        {
          id: "flavour-mill",
          title: {
            es: "El molinillo de los sabores",
            ca: "El molinet dels sabors",
            en: "The flavour mill",
            fr: "Le moulin des saveurs",
          },
          desc: {
            es: "El molinillo que muele la especia de la alegría se ha parado del todo.",
            ca: "El molinet que mol l'espècia de l'alegria s'ha aturat del tot.",
            en: "The little mill that grinds the spice of joy has stopped completely.",
            fr: "Le petit moulin qui moud l'épice de la joie s'est complètement arrêté.",
          },
          imageSeed: "chef-c2pantry-mill",
          icon: "cyclone",
          narrative: {
            es: "{name} y el guisante saltarín encuentran el molinillo de los sabores con las aspas quietas, sin moler ni una pizca de la especia de la alegría.",
            ca: "{name} i el pèsol saltador troben el molinet dels sabors amb les aspes quietes, sense moldre ni un pessic de l'espècia de l'alegria.",
            en: "{name} and the bouncy pea find the flavour mill with its sails still, not grinding a single pinch of the spice of joy.",
            fr: "{name} et le petit pois bondissant trouvent le moulin des saveurs aux ailes immobiles, sans moudre la moindre pincée de l'épice de la joie.",
          },
          next: "c3_pantry_c",
        },
      ],
    },
    c3_dough_a: {
      id: "c3_dough_a",
      chapter: 3,
      question: {
        es: "Las flores de piruleta guardan su azúcar mágico dentro de los pétalos cerrados y solo se abren cuando están contentas. ¿Cómo consigue {name} que regalen una pizca a Miga?",
        ca: "Les flors de piruleta guarden el seu sucre màgic dins dels pètals tancats i només s'obren quan estan contentes. Com aconsegueix {name} que regalin un pessic a la Miga?",
        en: "The lollipop flowers keep their magic sugar inside their closed petals and only open when they are happy. How does {name} get them to gift a pinch to Miga?",
        fr: "Les fleurs-sucettes gardent leur sucre magique dans leurs pétales fermés et ne s'ouvrent que lorsqu'elles sont contentes. Comment {name} va les convaincre d'offrir une pincée à Miga ?",
      },
      options: [
        {
          id: "morning-song",
          title: {
            es: "Cantarles por la mañana",
            ca: "Cantar-los al matí",
            en: "Sing them a morning song",
            fr: "Leur chanter une chanson du matin",
          },
          desc: {
            es: "Una canción alegre de buenos días abre hasta la flor más dormilona.",
            ca: "Una cançó alegre de bon dia obre fins i tot la flor més dormilega.",
            en: "A cheerful good-morning song opens even the sleepiest flower.",
            fr: "Une joyeuse chanson de bonjour ouvre même la fleur la plus endormie.",
          },
          imageSeed: "chef-c3dougha-song",
          icon: "music_note",
          narrative: {
            es: "{name} canta una alegre canción de buenos días y las flores de piruleta abren sus pétalos, espolvoreando azúcar mágico sobre Miga.",
            ca: "{name} canta una alegre cançó de bon dia i les flors de piruleta obren els seus pètals, empolvorant sucre màgic sobre la Miga.",
            en: "{name} sings a cheerful good-morning song and the lollipop flowers open their petals, sprinkling magic sugar over Miga.",
            fr: "{name} chante une joyeuse chanson de bonjour et les fleurs-sucettes ouvrent leurs pétales, saupoudrant du sucre magique sur Miga.",
          },
          next: "ending",
        },
        {
          id: "warm-milk",
          title: {
            es: "Regarlas con leche tibia",
            ca: "Regar-les amb llet tèbia",
            en: "Water them with warm milk",
            fr: "Les arroser de lait tiède",
          },
          desc: {
            es: "Un chorrito de leche calentita es el desayuno favorito de estas flores.",
            ca: "Un rajolí de llet calentona és l'esmorzar preferit d'aquestes flors.",
            en: "A trickle of warm milk is these flowers' favourite breakfast.",
            fr: "Un filet de lait bien chaud est le petit déjeuner préféré de ces fleurs.",
          },
          imageSeed: "chef-c3dougha-milk",
          icon: "local_cafe",
          narrative: {
            es: "{name} riega las flores de piruleta con un chorrito de leche tibia y ellas se abren bostezando felices, regalando su azúcar mágico a Miga.",
            ca: "{name} rega les flors de piruleta amb un rajolí de llet tèbia i elles s'obren badallant felices, regalant el seu sucre màgic a la Miga.",
            en: "{name} waters the lollipop flowers with a trickle of warm milk and they open with happy yawns, gifting their magic sugar to Miga.",
            fr: "{name} arrose les fleurs-sucettes d'un filet de lait tiède et elles s'ouvrent en bâillant de bonheur, offrant leur sucre magique à Miga.",
          },
          next: "ending",
        },
        {
          id: "sugar-butterflies",
          title: {
            es: "Pedir ayuda a las mariposas",
            ca: "Demanar ajuda a les papallones",
            en: "Ask the butterflies for help",
            fr: "Demander de l'aide aux papillons",
          },
          desc: {
            es: "Las mariposas de azúcar conocen el cosquilleo secreto de cada flor.",
            ca: "Les papallones de sucre coneixen les pessigolles secretes de cada flor.",
            en: "The sugar butterflies know each flower's secret tickle.",
            fr: "Les papillons de sucre connaissent le chatouillis secret de chaque fleur.",
          },
          imageSeed: "chef-c3dougha-butterfly",
          icon: "emoji_nature",
          narrative: {
            es: "{name} pide ayuda a las mariposas de azúcar, que hacen cosquillas a las flores hasta que se abren riendo y llenan a Miga de azúcar mágico.",
            ca: "{name} demana ajuda a les papallones de sucre, que fan pessigolles a les flors fins que s'obren rient i omplen la Miga de sucre màgic.",
            en: "{name} asks the sugar butterflies for help, and they tickle the flowers until they open laughing and shower Miga with magic sugar.",
            fr: "{name} demande de l'aide aux papillons de sucre, qui chatouillent les fleurs jusqu'à ce qu'elles s'ouvrent en riant et couvrent Miga de sucre magique.",
          },
          next: "ending",
        },
      ],
    },
    c3_dough_b: {
      id: "c3_dough_b",
      chapter: 3,
      question: {
        es: "Las abejitas doradas están atareadísimas preparando la miel para el invierno y son un poco tímidas. ¿Cómo les pide {name} una gotita de miel brillante para Miga?",
        ca: "Les abelletes daurades estan molt enfeinades preparant la mel per a l'hivern i són una mica tímides. Com els demana {name} una goteta de mel brillant per a la Miga?",
        en: "The little golden bees are very busy getting their honey ready for winter and they are a bit shy. How does {name} ask them for a drop of glowing honey for Miga?",
        fr: "Les petites abeilles dorées sont très occupées à préparer le miel pour l'hiver et elles sont un peu timides. Comment {name} va leur demander une goutte de miel brillant pour Miga ?",
      },
      options: [
        {
          id: "bee-dance",
          title: {
            es: "Aprender su baile",
            ca: "Aprendre el seu ball",
            en: "Learn their dance",
            fr: "Apprendre leur danse",
          },
          desc: {
            es: "Las abejas se saludan bailando en círculos y zigzags.",
            ca: "Les abelles se saluden ballant en cercles i zigues-zagues.",
            en: "Bees say hello by dancing in circles and zigzags.",
            fr: "Les abeilles se disent bonjour en dansant en cercles et en zigzags.",
          },
          imageSeed: "chef-c3doughb-dance",
          icon: "celebration",
          narrative: {
            es: "{name} aprende el baile de las abejas y las saluda con círculos y zigzags, y ellas, encantadas, regalan a Miga una gotita de miel brillante.",
            ca: "{name} aprèn el ball de les abelles i les saluda amb cercles i zigues-zagues, i elles, encantades, regalen a la Miga una goteta de mel brillant.",
            en: "{name} learns the bees' dance and greets them with circles and zigzags, and the delighted bees gift Miga a drop of glowing honey.",
            fr: "{name} apprend la danse des abeilles et les salue avec des cercles et des zigzags, et celles-ci, ravies, offrent à Miga une goutte de miel brillant.",
          },
          next: "ending",
        },
        {
          id: "window-flowers",
          title: {
            es: "Llevarles flores",
            ca: "Portar-los flors",
            en: "Bring them flowers",
            fr: "Leur apporter des fleurs",
          },
          desc: {
            es: "Las macetas de la ventana están llenas de flores de cocina perfumadas.",
            ca: "Els testos de la finestra són plens de flors de cuina perfumades.",
            en: "The window pots are full of sweet-smelling kitchen flowers.",
            fr: "Les pots de la fenêtre sont pleins de fleurs de cuisine parfumées.",
          },
          imageSeed: "chef-c3doughb-flowers",
          icon: "local_florist",
          narrative: {
            es: "{name} lleva a las abejitas un ramo de flores perfumadas de la ventana de la cocina y ellas, agradecidas, llenan una cucharita de miel dorada para Miga.",
            ca: "{name} porta a les abelletes un ram de flors perfumades de la finestra de la cuina i elles, agraïdes, omplen una cullereta de mel daurada per a la Miga.",
            en: "{name} brings the little bees a bouquet of sweet-smelling flowers from the kitchen window, and they gratefully fill a tiny spoon with golden honey for Miga.",
            fr: "{name} apporte aux petites abeilles un bouquet de fleurs parfumées de la fenêtre de la cuisine et celles-ci, reconnaissantes, remplissent une petite cuillère de miel doré pour Miga.",
          },
          next: "ending",
        },
        {
          id: "fix-honeycomb",
          title: {
            es: "Arreglar el panal",
            ca: "Arreglar la bresca",
            en: "Mend the honeycomb",
            fr: "Réparer le rayon de miel",
          },
          desc: {
            es: "Una celdita del panal se ha roto y la miel se escapa gota a gota.",
            ca: "Una cel·leta de la bresca s'ha trencat i la mel s'escapa gota a gota.",
            en: "One little cell of the honeycomb has cracked and honey is escaping drop by drop.",
            fr: "Une petite alvéole du rayon s'est fissurée et le miel s'échappe goutte à goutte.",
          },
          imageSeed: "chef-c3doughb-comb",
          icon: "handyman",
          narrative: {
            es: "{name} arregla con cera blandita la celdita rota del panal y las abejitas, agradecidas, regalan a Miga su gota de miel más brillante.",
            ca: "{name} arregla amb cera toveta la cel·leta trencada de la bresca i les abelletes, agraïdes, regalen a la Miga la seva gota de mel més brillant.",
            en: "{name} mends the cracked honeycomb cell with soft wax and the grateful bees gift Miga their most glowing drop of honey.",
            fr: "{name} répare l'alvéole fissurée avec de la cire toute douce et les petites abeilles, reconnaissantes, offrent à Miga leur goutte de miel la plus brillante.",
          },
          next: "ending",
        },
      ],
    },
    c3_dough_c: {
      id: "c3_dough_c",
      chapter: 3,
      question: {
        es: "La fuente de chocolate duerme profundamente y su chocolate descansa quieto en el fondo. ¿Cómo la despierta {name} con dulzura para conseguir un chorrito mágico?",
        ca: "La font de xocolata dorm profundament i la seva xocolata descansa quieta al fons. Com la desperta {name} amb dolçor per aconseguir un rajolí màgic?",
        en: "The chocolate fountain is fast asleep and its chocolate rests quietly at the bottom. How does {name} wake it sweetly to get a little magic trickle?",
        fr: "La fontaine de chocolat dort profondément et son chocolat repose tranquillement au fond. Comment {name} la réveille en douceur pour obtenir un petit filet magique ?",
      },
      options: [
        {
          id: "slow-stir",
          title: {
            es: "Remover despacito",
            ca: "Remenar a poc a poc",
            en: "Stir very slowly",
            fr: "Remuer tout doucement",
          },
          desc: {
            es: "La cuchara de madera más larga dibuja espirales suaves en el chocolate.",
            ca: "La cullera de fusta més llarga dibuixa espirals suaus a la xocolata.",
            en: "The longest wooden spoon draws gentle spirals in the chocolate.",
            fr: "La plus longue cuillère en bois dessine de douces spirales dans le chocolat.",
          },
          imageSeed: "chef-c3doughc-stir",
          icon: "flatware",
          narrative: {
            es: "{name} remueve el chocolate despacito con la cuchara de madera más larga, dibujando espirales hasta que la fuente despierta y mana un chorrito calentito para Miga.",
            ca: "{name} remena la xocolata a poc a poc amb la cullera de fusta més llarga, dibuixant espirals fins que la font es desperta i raja un rajolí calentó per a la Miga.",
            en: "{name} stirs the chocolate slowly with the longest wooden spoon, drawing spirals until the fountain wakes up and pours a warm trickle for Miga.",
            fr: "{name} remue le chocolat tout doucement avec la plus longue cuillère en bois, dessinant des spirales jusqu'à ce que la fontaine se réveille et verse un filet tout chaud pour Miga.",
          },
          next: "ending",
        },
        {
          id: "cinnamon-dust",
          title: {
            es: "Espolvorear canela",
            ca: "Empolvorar canyella",
            en: "Sprinkle cinnamon",
            fr: "Saupoudrer de la cannelle",
          },
          desc: {
            es: "Un poquito de canela hace estornudar de alegría al chocolate dormilón.",
            ca: "Una mica de canyella fa esternudar d'alegria la xocolata dormilega.",
            en: "A little cinnamon makes the sleepy chocolate sneeze with joy.",
            fr: "Un peu de cannelle fait éternuer de joie le chocolat endormi.",
          },
          imageSeed: "chef-c3doughc-cinnamon",
          icon: "grain",
          narrative: {
            es: "{name} espolvorea una pizca de canela sobre la fuente y el chocolate despierta con un estornudo alegre, burbujeando un chorrito mágico para Miga.",
            ca: "{name} empolvora un pessic de canyella sobre la font i la xocolata es desperta amb un esternut alegre, bombollejant un rajolí màgic per a la Miga.",
            en: "{name} sprinkles a pinch of cinnamon over the fountain and the chocolate wakes with a happy sneeze, bubbling up a magic trickle for Miga.",
            fr: "{name} saupoudre une pincée de cannelle sur la fontaine et le chocolat se réveille avec un joyeux éternuement, faisant jaillir un petit filet magique pour Miga.",
          },
          next: "ending",
        },
        {
          id: "strawberry-gift",
          title: {
            es: "Regalarle una fresa",
            ca: "Regalar-li una maduixa",
            en: "Gift it a strawberry",
            fr: "Lui offrir une fraise",
          },
          desc: {
            es: "Una fresa madura es el desayuno favorito de las fuentes de chocolate.",
            ca: "Una maduixa madura és l'esmorzar preferit de les fonts de xocolata.",
            en: "A ripe strawberry is a chocolate fountain's favourite breakfast.",
            fr: "Une fraise bien mûre est le petit déjeuner préféré des fontaines de chocolat.",
          },
          imageSeed: "chef-c3doughc-strawberry",
          icon: "nutrition",
          narrative: {
            es: "{name} deja caer una fresa madura en la fuente y el chocolate sube burbujeando a probarla, regalando a Miga su chorrito más dulce.",
            ca: "{name} deixa caure una maduixa madura a la font i la xocolata puja bombollejant a tastar-la, regalant a la Miga el seu rajolí més dolç.",
            en: "{name} drops a ripe strawberry into the fountain and the chocolate bubbles up to taste it, gifting Miga its sweetest trickle.",
            fr: "{name} laisse tomber une fraise mûre dans la fontaine et le chocolat remonte en bouillonnant pour la goûter, offrant à Miga son filet le plus sucré.",
          },
          next: "ending",
        },
      ],
    },
    c3_book_a: {
      id: "c3_book_a",
      chapter: 3,
      question: {
        es: "Los tarritos susurran que el azúcar de estrellas se esconde en uno solo de los cientos de tarros de la torre. ¿Cómo encuentra {name} el tarro correcto?",
        ca: "Els potets xiuxiuegen que el sucre d'estrelles s'amaga en un sol dels centenars de pots de la torre. Com troba {name} el pot correcte?",
        en: "The little jars whisper that the star sugar hides in just one of the hundreds of jars in the tower. How does {name} find the right jar?",
        fr: "Les petits pots chuchotent que le sucre d'étoiles se cache dans un seul des centaines de pots de la tour. Comment {name} trouve le bon pot ?",
      },
      options: [
        {
          id: "follow-scent",
          title: {
            es: "Seguir el aroma",
            ca: "Seguir l'aroma",
            en: "Follow the scent",
            fr: "Suivre le parfum",
          },
          desc: {
            es: "El azúcar de estrellas huele a vainilla y a noche de verano.",
            ca: "El sucre d'estrelles fa olor de vainilla i de nit d'estiu.",
            en: "Star sugar smells of vanilla and summer nights.",
            fr: "Le sucre d'étoiles sent la vanille et les nuits d'été.",
          },
          imageSeed: "chef-c3booka-scent",
          icon: "spa",
          narrative: {
            es: "{name} cierra los ojos, sigue un aroma de vainilla y noche de verano, y encuentra el tarro de azúcar de estrellas brillando en la balda más alta.",
            ca: "{name} tanca els ulls, segueix una aroma de vainilla i nit d'estiu, i troba el pot de sucre d'estrelles brillant a la lleixa més alta.",
            en: "{name} closes their eyes, follows a scent of vanilla and summer nights, and finds the jar of star sugar glowing on the very top shelf.",
            fr: "{name} ferme les yeux, suit un parfum de vanille et de nuit d'été, et trouve le pot de sucre d'étoiles qui brille sur l'étagère la plus haute.",
          },
          next: "ending",
        },
        {
          id: "pot-stairs",
          title: {
            es: "Una escalera de cazuelas",
            ca: "Una escala de cassoles",
            en: "A staircase of pots",
            fr: "Un escalier de casseroles",
          },
          desc: {
            es: "Cazuela sobre cazuela se puede subir hasta la balda más alta.",
            ca: "Cassola sobre cassola es pot pujar fins a la lleixa més alta.",
            en: "Pot upon pot, you can climb to the very top shelf.",
            fr: "Casserole sur casserole, on peut monter jusqu'à l'étagère la plus haute.",
          },
          imageSeed: "chef-c3booka-stairs",
          icon: "stairs",
          narrative: {
            es: "{name} apila cazuelas con muchísimo cuidado, sube peldaño a peldaño y alcanza el tarro que brilla en lo más alto de la torre de especias.",
            ca: "{name} apila cassoles amb moltíssima cura, puja escaló a escaló i agafa el pot que brilla a dalt de tot de la torre d'espècies.",
            en: "{name} stacks pots very, very carefully, climbs step by step and reaches the glowing jar at the very top of the spice tower.",
            fr: "{name} empile des casseroles avec beaucoup de précaution, monte marche après marche et attrape le pot qui brille tout en haut de la tour aux épices.",
          },
          next: "ending",
        },
        {
          id: "jar-riddles",
          title: {
            es: "Jugar a las adivinanzas",
            ca: "Jugar a les endevinalles",
            en: "Play the riddle game",
            fr: "Jouer aux devinettes",
          },
          desc: {
            es: "Los tarritos adoran las adivinanzas y el premio es su mayor tesoro.",
            ca: "Els potets adoren les endevinalles i el premi és el seu tresor més gran.",
            en: "The little jars love riddles, and the prize is their greatest treasure.",
            fr: "Les petits pots adorent les devinettes, et le prix est leur plus grand trésor.",
          },
          imageSeed: "chef-c3booka-riddle",
          icon: "quiz",
          narrative: {
            es: "{name} juega a las adivinanzas con los tarritos, acierta la más difícil y ellos se pasan de balda en balda el tarro de azúcar de estrellas hasta sus manos.",
            ca: "{name} juga a les endevinalles amb els potets, encerta la més difícil i ells es passen de lleixa en lleixa el pot de sucre d'estrelles fins a les seves mans.",
            en: "{name} plays riddles with the little jars, solves the trickiest one, and they pass the jar of star sugar from shelf to shelf right into {name}'s hands.",
            fr: "{name} joue aux devinettes avec les petits pots, résout la plus difficile, et ils se passent le pot de sucre d'étoiles d'étagère en étagère jusqu'à ses mains.",
          },
          next: "ending",
        },
      ],
    },
    c3_book_b: {
      id: "c3_book_b",
      chapter: 3,
      question: {
        es: "El horno abuelo conoce el ingrediente secreto, pero está frío y adormilado, y su voz es apenas un murmullo. ¿Cómo le anima {name} para que comparta su secreto?",
        ca: "El forn avi coneix l'ingredient secret, però està fred i endormiscat, i la seva veu és tot just un murmuri. Com l'anima {name} perquè comparteixi el seu secret?",
        en: "The grandpa oven knows the secret ingredient, but he is cold and drowsy, and his voice is barely a murmur. How does {name} cheer him up so he shares his secret?",
        fr: "Le four grand-père connaît l'ingrédient secret, mais il est froid et somnolent, et sa voix n'est qu'un murmure. Comment {name} va lui redonner le sourire pour qu'il partage son secret ?",
      },
      options: [
        {
          id: "tasty-story",
          title: {
            es: "Contarle un cuento",
            ca: "Explicar-li un conte",
            en: "Tell him a story",
            fr: "Lui raconter une histoire",
          },
          desc: {
            es: "Los hornos viejos adoran los cuentos sobre pasteles de otros tiempos.",
            ca: "Els forns vells adoren els contes sobre pastissos d'altres temps.",
            en: "Old ovens love stories about cakes from long ago.",
            fr: "Les vieux fours adorent les histoires de gâteaux d'autrefois.",
          },
          imageSeed: "chef-c3bookb-story",
          icon: "auto_stories",
          narrative: {
            es: "{name} le cuenta un cuento sobre el pastel más rico del mundo y el horno abuelo ríe calentito, abre su cajoncito y le entrega el azúcar de estrellas.",
            ca: "{name} li explica un conte sobre el pastís més bo del món i el forn avi riu calentó, obre el seu calaixet i li lliura el sucre d'estrelles.",
            en: "{name} tells him a story about the most delicious cake in the world and the grandpa oven chuckles warmly, opens his little drawer and hands over the star sugar.",
            fr: "{name} lui raconte une histoire sur le plus délicieux gâteau du monde et le four grand-père rit chaleureusement, ouvre son petit tiroir et lui remet le sucre d'étoiles.",
          },
          next: "ending",
        },
        {
          id: "cinnamon-wood",
          title: {
            es: "Leña de canela",
            ca: "Llenya de canyella",
            en: "Cinnamon firewood",
            fr: "Du bois de cannelle",
          },
          desc: {
            es: "Unas ramitas de canela encienden el fueguito más perfumado.",
            ca: "Unes branquetes de canyella encenen el foquet més perfumat.",
            en: "A few cinnamon sticks light the sweetest-smelling little fire.",
            fr: "Quelques bâtons de cannelle allument le petit feu le plus parfumé.",
          },
          imageSeed: "chef-c3bookb-firewood",
          icon: "fireplace",
          narrative: {
            es: "{name} alimenta al horno abuelo con ramitas de canela y su barriga se enciende con un brillo perfumado, y él, feliz, revela dónde guarda el azúcar de estrellas.",
            ca: "{name} alimenta el forn avi amb branquetes de canyella i la seva panxa s'encén amb una lluïssor perfumada, i ell, feliç, revela on guarda el sucre d'estrelles.",
            en: "{name} feeds the grandpa oven cinnamon sticks and his belly glows with a sweet-smelling light, and he happily reveals where he keeps the star sugar.",
            fr: "{name} nourrit le four grand-père de bâtons de cannelle et son ventre s'allume d'une lueur parfumée, et lui, tout heureux, révèle où il garde le sucre d'étoiles.",
          },
          next: "ending",
        },
        {
          id: "shine-polish",
          title: {
            es: "Sacarle brillo",
            ca: "Treure-li lluentor",
            en: "Polish him up",
            fr: "Le faire briller",
          },
          desc: {
            es: "Su puerta y su ventanita llevan años esperando un buen repaso.",
            ca: "La seva porta i la seva finestreta fa anys que esperen una bona repassada.",
            en: "His door and his little window have been waiting years for a good shine.",
            fr: "Sa porte et sa petite vitre attendent un bon coup de chiffon depuis des années.",
          },
          imageSeed: "chef-c3bookb-polish",
          icon: "cleaning_services",
          narrative: {
            es: "{name} limpia la puerta y la ventanita del horno abuelo hasta dejarlas relucientes, y él, orgulloso como un horno nuevo, le confía el azúcar de estrellas.",
            ca: "{name} neteja la porta i la finestreta del forn avi fins a deixar-les lluents, i ell, orgullós com un forn nou, li confia el sucre d'estrelles.",
            en: "{name} polishes the grandpa oven's door and little window until they gleam, and proud as a brand-new oven, he entrusts the star sugar to {name}.",
            fr: "{name} fait briller la porte et la petite vitre du four grand-père, et lui, fier comme un four tout neuf, lui confie le sucre d'étoiles.",
          },
          next: "ending",
        },
      ],
    },
    c3_book_c: {
      id: "c3_book_c",
      chapter: 3,
      question: {
        es: "A medianoche, la luna espolvorea su azúcar plateado sobre el alféizar... pero la brisa lo desparrama por todas partes. ¿Cómo lo atrapa {name}?",
        ca: "A mitjanit, la lluna empolvora el seu sucre platejat sobre l'ampit... però la brisa l'escampa per tot arreu. Com l'atrapa {name}?",
        en: "At midnight, the moon sprinkles its silver sugar onto the windowsill... but the breeze scatters it everywhere. How does {name} catch it?",
        fr: "À minuit, la lune saupoudre son sucre argenté sur le rebord de la fenêtre... mais la brise l'éparpille partout. Comment {name} va l'attraper ?",
      },
      options: [
        {
          id: "silver-spoon",
          title: {
            es: "La cuchara de plata",
            ca: "La cullera de plata",
            en: "The silver spoon",
            fr: "La cuillère en argent",
          },
          desc: {
            es: "Al polvo de luna le encanta posarse sobre las cosas que brillan.",
            ca: "A la pols de lluna li encanta posar-se sobre les coses que brillen.",
            en: "Moon dust loves to land on shiny things.",
            fr: "La poussière de lune adore se poser sur ce qui brille.",
          },
          imageSeed: "chef-c3bookc-spoon",
          icon: "restaurant",
          narrative: {
            es: "{name} levanta la gran cuchara de plata hacia la ventana y el azúcar de luna baja girando hasta posarse en ella como copos de nieve dulce.",
            ca: "{name} aixeca la gran cullera de plata cap a la finestra i el sucre de lluna baixa girant fins a posar-se-hi com volves de neu dolça.",
            en: "{name} holds the big silver spoon up to the window and the moon sugar twirls down to land on it like sweet snowflakes.",
            fr: "{name} lève la grande cuillère en argent vers la fenêtre et le sucre de lune descend en tourbillonnant pour s'y poser comme des flocons de neige sucrée.",
          },
          next: "ending",
        },
        {
          id: "quiet-hum",
          title: {
            es: "Tararear bajito",
            ca: "Taral·larejar fluixet",
            en: "Hum very softly",
            fr: "Fredonner tout bas",
          },
          desc: {
            es: "El polvo de luna baila al compás de las melodías tranquilas.",
            ca: "La pols de lluna balla al compàs de les melodies tranquil·les.",
            en: "Moon dust dances along to quiet melodies.",
            fr: "La poussière de lune danse au rythme des mélodies calmes.",
          },
          imageSeed: "chef-c3bookc-hum",
          icon: "graphic_eq",
          narrative: {
            es: "{name} tararea una melodía tranquila y el azúcar de luna baja bailando despacito hasta caer dentro del cuenco preparado en el alféizar.",
            ca: "{name} taral·lareja una melodia tranquil·la i el sucre de lluna baixa ballant a poc a poc fins a caure dins del bol preparat a l'ampit.",
            en: "{name} hums a quiet melody and the moon sugar drifts down dancing slowly, falling right into the bowl waiting on the windowsill.",
            fr: "{name} fredonne une mélodie calme et le sucre de lune descend en dansant doucement, tombant droit dans le bol posé sur le rebord.",
          },
          next: "ending",
        },
        {
          id: "honey-trail",
          title: {
            es: "Un caminito de miel",
            ca: "Un caminet de mel",
            en: "A little honey trail",
            fr: "Un petit chemin de miel",
          },
          desc: {
            es: "Una línea de miel dorada guía el polvito hasta el tarro abierto.",
            ca: "Una línia de mel daurada guia la polseta fins al pot obert.",
            en: "A line of golden honey guides the dust into the open jar.",
            fr: "Une ligne de miel doré guide la poussière jusqu'au pot ouvert.",
          },
          imageSeed: "chef-c3bookc-trail",
          icon: "route",
          narrative: {
            es: "{name} dibuja un caminito de miel sobre el alféizar y el azúcar de luna se queda pegado brillando, deslizándose dulcemente hasta el tarro abierto.",
            ca: "{name} dibuixa un caminet de mel sobre l'ampit i el sucre de lluna s'hi queda enganxat brillant, lliscant dolçament fins al pot obert.",
            en: "{name} draws a little trail of honey along the windowsill and the moon sugar sticks to it shining, sliding sweetly into the open jar.",
            fr: "{name} dessine un petit chemin de miel sur le rebord et le sucre de lune s'y colle en brillant, glissant tout doucement jusqu'au pot ouvert.",
          },
          next: "ending",
        },
      ],
    },
    c3_pantry_a: {
      id: "c3_pantry_a",
      chapter: 3,
      question: {
        es: "La olla gigante está fría y sus brasas apenas brillan. Sin su canción de burbujas, ningún guiso del banquete tendrá sabor. ¿Cómo la despiertan {name} y el guisante saltarín?",
        ca: "L'olla gegant està freda i les seves brases tot just brillen. Sense la seva cançó de bombolles, cap guisat del banquet tindrà sabor. Com la desperten {name} i el pèsol saltador?",
        en: "The giant pot is cold and its embers barely glow. Without its bubble song, no dish at the feast will have any flavour. How do {name} and the bouncy pea wake it up?",
        fr: "La marmite géante est froide et ses braises brillent à peine. Sans sa chanson de bulles, aucun plat du banquet n'aura de saveur. Comment {name} et le petit pois bondissant vont-ils la réveiller ?",
      },
      options: [
        {
          id: "stir-together",
          title: {
            es: "Remover todos juntos",
            ca: "Remenar tots junts",
            en: "Stir all together",
            fr: "Remuer tous ensemble",
          },
          desc: {
            es: "La cuchara gigante pesa demasiado para un solo par de manos.",
            ca: "La cullera gegant pesa massa per a un sol parell de mans.",
            en: "The giant spoon is far too heavy for one pair of hands.",
            fr: "La cuillère géante est bien trop lourde pour une seule paire de mains.",
          },
          imageSeed: "chef-c3pantrya-team",
          icon: "diversity_3",
          narrative: {
            es: "{name}, el guisante saltarín y todos los ingredientes del pueblecito agarran juntos la cuchara gigante y remueven hasta que la olla despierta cantando burbujas.",
            ca: "{name}, el pèsol saltador i tots els ingredients del poblet agafen junts la cullera gegant i remenen fins que l'olla es desperta cantant bombolles.",
            en: "{name}, the bouncy pea and all the little village ingredients grab the giant spoon together and stir until the pot wakes up singing bubbles.",
            fr: "{name}, le petit pois bondissant et tous les ingrédients du village attrapent ensemble la cuillère géante et remuent jusqu'à ce que la marmite se réveille en chantant des bulles.",
          },
          next: "ending",
        },
        {
          id: "wake-embers",
          title: {
            es: "Soplar las brasas",
            ca: "Bufar les brases",
            en: "Blow on the embers",
            fr: "Souffler sur les braises",
          },
          desc: {
            es: "Bajo la olla, las brasas dormidas solo necesitan un soplido suave.",
            ca: "Sota l'olla, les brases adormides només necessiten una bufada suau.",
            en: "Under the pot, the sleeping embers just need a gentle puff.",
            fr: "Sous la marmite, les braises endormies n'attendent qu'un souffle léger.",
          },
          imageSeed: "chef-c3pantrya-ember",
          icon: "local_fire_department",
          narrative: {
            es: "{name} sopla suavecito las brasas dormidas, una a una, hasta que unas llamitas naranjas bailan bajo la olla y el caldo empieza a burbujear.",
            ca: "{name} bufa suaument les brases adormides, una a una, fins que unes flametes taronges ballen sota l'olla i el brou comença a bombollejar.",
            en: "{name} blows gently on the sleeping embers, one by one, until little orange flames dance under the pot and the broth begins to bubble.",
            fr: "{name} souffle tout doucement sur les braises endormies, une à une, jusqu'à ce que de petites flammes orange dansent sous la marmite et que le bouillon se mette à bouillonner.",
          },
          next: "ending",
        },
        {
          id: "favourite-recipe",
          title: {
            es: "Susurrarle su receta",
            ca: "Xiuxiuejar-li la seva recepta",
            en: "Whisper its recipe",
            fr: "Lui chuchoter sa recette",
          },
          desc: {
            es: "La olla solo necesita recordar la sopa que más le gusta cocinar.",
            ca: "L'olla només necessita recordar la sopa que més li agrada cuinar.",
            en: "The pot just needs to remember the soup it loves cooking most.",
            fr: "La marmite a juste besoin de se rappeler la soupe qu'elle préfère cuisiner.",
          },
          imageSeed: "chef-c3pantrya-recipe",
          icon: "record_voice_over",
          narrative: {
            es: "{name} se acerca al borde de la olla y le susurra su receta favorita, y la olla recuerda su canción y rompe a hervir con burbujas de mil sabores.",
            ca: "{name} s'acosta a la vora de l'olla i li xiuxiueja la seva recepta preferida, i l'olla recorda la seva cançó i arrenca a bullir amb bombolles de mil sabors.",
            en: "{name} leans close to the pot's rim and whispers its favourite recipe, and the pot remembers its song and bursts into a boil with bubbles of a thousand flavours.",
            fr: "{name} se penche au bord de la marmite et lui chuchote sa recette préférée, et la marmite retrouve sa chanson et se met à bouillir avec des bulles aux mille saveurs.",
          },
          next: "ending",
        },
      ],
    },
    c3_pantry_b: {
      id: "c3_pantry_b",
      chapter: 3,
      question: {
        es: "Las hierbas del jardín están mustias y sin perfume, y el banquete necesita su toque verde y fresco. ¿Cómo las anima {name} para que vuelvan a perfumar la despensa?",
        ca: "Les herbes del jardí estan musties i sense perfum, i el banquet necessita el seu toc verd i fresc. Com les anima {name} perquè tornin a perfumar el rebost?",
        en: "The garden herbs are wilted and scentless, and the feast needs their fresh green touch. How does {name} cheer them up so they perfume the pantry again?",
        fr: "Les herbes du jardin sont fanées et sans parfum, et le banquet a besoin de leur touche verte et fraîche. Comment {name} va leur redonner vie pour qu'elles parfument à nouveau le garde-manger ?",
      },
      options: [
        {
          id: "copper-can",
          title: {
            es: "La regadera de cobre",
            ca: "La regadora de coure",
            en: "The copper watering can",
            fr: "L'arrosoir en cuivre",
          },
          desc: {
            es: "Su lluvia finita cae como una caricia sobre las hojas sedientas.",
            ca: "La seva pluja fineta cau com una carícia sobre les fulles assedegades.",
            en: "Its fine rain falls like a caress on the thirsty leaves.",
            fr: "Sa pluie fine tombe comme une caresse sur les feuilles assoiffées.",
          },
          imageSeed: "chef-c3pantryb-water",
          icon: "water_drop",
          narrative: {
            es: "{name} riega las hierbas con la regadera de cobre, gotita a gotita, y la menta y la albahaca se enderezan llenando el aire de perfume fresco.",
            ca: "{name} rega les herbes amb la regadora de coure, goteta a goteta, i la menta i l'alfàbrega es redrecen omplint l'aire de perfum fresc.",
            en: "{name} waters the herbs with the copper can, drop by drop, and the mint and basil straighten up, filling the air with fresh perfume.",
            fr: "{name} arrose les herbes avec l'arrosoir en cuivre, goutte à goutte, et la menthe et le basilic se redressent en remplissant l'air d'un parfum frais.",
          },
          next: "ending",
        },
        {
          id: "round-window",
          title: {
            es: "Abrir la ventana redonda",
            ca: "Obrir la finestra rodona",
            en: "Open the round window",
            fr: "Ouvrir la fenêtre ronde",
          },
          desc: {
            es: "Un rayito de sol espera fuera para abrazar las hojas verdes.",
            ca: "Un raget de sol espera fora per abraçar les fulles verdes.",
            en: "A little sunbeam waits outside to hug the green leaves.",
            fr: "Un petit rayon de soleil attend dehors pour enlacer les feuilles vertes.",
          },
          imageSeed: "chef-c3pantryb-sun",
          icon: "wb_sunny",
          narrative: {
            es: "{name} abre la ventana redonda de la despensa y un rayito de sol entra a abrazar las hierbas, que se estiran felices y vuelven a oler a jardín.",
            ca: "{name} obre la finestra rodona del rebost i un raget de sol entra a abraçar les herbes, que s'estiren felices i tornen a fer olor de jardí.",
            en: "{name} opens the pantry's round window and a little sunbeam comes in to hug the herbs, which stretch up happily and smell like a garden again.",
            fr: "{name} ouvre la fenêtre ronde du garde-manger et un petit rayon de soleil entre enlacer les herbes, qui s'étirent de bonheur et sentent à nouveau le jardin.",
          },
          next: "ending",
        },
        {
          id: "kind-words",
          title: {
            es: "Decirles cosas bonitas",
            ca: "Dir-los coses boniques",
            en: "Say kind things to them",
            fr: "Leur dire des mots doux",
          },
          desc: {
            es: "Las hierbas crecen más verdes cuando alguien las quiere.",
            ca: "Les herbes creixen més verdes quan algú les estima.",
            en: "Herbs grow greener when someone loves them.",
            fr: "Les herbes poussent plus vertes quand quelqu'un les aime.",
          },
          imageSeed: "chef-c3pantryb-words",
          icon: "favorite",
          narrative: {
            es: "{name} susurra algo bonito a cada matita, hoja por hoja, y las hierbas se ponen verdes de alegría y perfuman toda la despensa.",
            ca: "{name} xiuxiueja alguna cosa bonica a cada mata, fulla per fulla, i les herbes es posen verdes d'alegria i perfumen tot el rebost.",
            en: "{name} whispers something kind to every little plant, leaf by leaf, and the herbs turn green with joy and perfume the whole pantry.",
            fr: "{name} chuchote un mot doux à chaque petit plant, feuille après feuille, et les herbes verdissent de joie et parfument tout le garde-manger.",
          },
          next: "ending",
        },
      ],
    },
    c3_pantry_c: {
      id: "c3_pantry_c",
      chapter: 3,
      question: {
        es: "El molinillo de los sabores tiene las aspas quietas y, sin la especia de la alegría, el banquete sabrá soso. ¿Cómo lo ponen en marcha {name} y el guisante saltarín?",
        ca: "El molinet dels sabors té les aspes quietes i, sense l'espècia de l'alegria, el banquet tindrà un gust fat. Com el posen en marxa {name} i el pèsol saltador?",
        en: "The flavour mill's sails are still, and without the spice of joy the feast will taste bland. How do {name} and the bouncy pea get it spinning again?",
        fr: "Les ailes du moulin des saveurs sont immobiles et, sans l'épice de la joie, le banquet sera fade. Comment {name} et le petit pois bondissant vont-ils le remettre en marche ?",
      },
      options: [
        {
          id: "golden-crank",
          title: {
            es: "Buscar la manivela dorada",
            ca: "Buscar la maneta daurada",
            en: "Find the golden crank",
            fr: "Chercher la manivelle dorée",
          },
          desc: {
            es: "La manivela que da cuerda al molinillo se perdió entre los cajones.",
            ca: "La maneta que dona corda al molinet es va perdre entre els calaixos.",
            en: "The crank that winds up the mill got lost among the drawers.",
            fr: "La manivelle qui remonte le moulin s'est perdue dans les tiroirs.",
          },
          imageSeed: "chef-c3pantryc-crank",
          icon: "search",
          narrative: {
            es: "{name} busca cajón por cajón hasta encontrar la manivela dorada bajo un saquito de arroz, le da cuerda al molinillo y las aspas giran de nuevo.",
            ca: "{name} busca calaix per calaix fins a trobar la maneta daurada sota un saquet d'arròs, dona corda al molinet i les aspes giren de nou.",
            en: "{name} searches drawer by drawer until finding the golden crank under a little sack of rice, winds up the mill, and the sails spin once more.",
            fr: "{name} fouille tiroir par tiroir jusqu'à trouver la manivelle dorée sous un petit sac de riz, remonte le moulin, et les ailes tournent à nouveau.",
          },
          next: "ending",
        },
        {
          id: "olive-oil",
          title: {
            es: "Una gota de aceite",
            ca: "Una gota d'oli",
            en: "A drop of oil",
            fr: "Une goutte d'huile",
          },
          desc: {
            es: "Los engranajes chirrían y piden una gotita de aceite de oliva.",
            ca: "Els engranatges grinyolen i demanen una goteta d'oli d'oliva.",
            en: "The gears squeak and ask for a little drop of olive oil.",
            fr: "Les engrenages grincent et réclament une petite goutte d'huile d'olive.",
          },
          imageSeed: "chef-c3pantryc-oil",
          icon: "build",
          narrative: {
            es: "{name} deja caer una gotita de aceite de oliva de la botella alta sobre los engranajes y el molinillo ronronea contento y se pone a girar.",
            ca: "{name} deixa caure una goteta d'oli d'oliva de l'ampolla alta sobre els engranatges i el molinet rondina content i es posa a girar.",
            en: "{name} drips a little olive oil from the tall bottle onto the gears and the mill purrs happily and starts to spin.",
            fr: "{name} fait couler une petite goutte d'huile d'olive de la grande bouteille sur les engrenages et le moulin ronronne de contentement et se met à tourner.",
          },
          next: "ending",
        },
        {
          id: "old-bellows",
          title: {
            es: "Despertar al fuelle",
            ca: "Despertar la manxa",
            en: "Wake the old bellows",
            fr: "Réveiller le vieux soufflet",
          },
          desc: {
            es: "El viejo fuelle de la chimenea sabe soplar vientos suaves y fuertes.",
            ca: "La vella manxa de la llar de foc sap bufar vents suaus i forts.",
            en: "The old fireplace bellows knows how to blow winds soft and strong.",
            fr: "Le vieux soufflet de la cheminée sait souffler des vents doux et forts.",
          },
          imageSeed: "chef-c3pantryc-wind",
          icon: "air",
          narrative: {
            es: "{name} despierta al viejo fuelle con unas palmaditas y él sopla un viento suave sobre las aspas, que giran moliendo la especia de la alegría.",
            ca: "{name} desperta la vella manxa amb uns copets i ella bufa un vent suau sobre les aspes, que giren molent l'espècia de l'alegria.",
            en: "{name} wakes the old bellows with a few gentle pats and it blows a soft wind onto the sails, which spin round grinding the spice of joy.",
            fr: "{name} réveille le vieux soufflet avec quelques petites tapes et il souffle un vent léger sur les ailes, qui tournent en moulant l'épice de la joie.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "", en: "", fr: "" },
      options: [],
    },
  },
};
