import type { StoryTree } from "./types";

// Branching story tree for the "dinosaurs" template (La Tierra de los Dinosaurios).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es source of truth + ca/en/fr). {name} = child's name.

export const dinosaursTree: StoryTree = {
  templateId: "dinosaurs",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} cruza el portal del tiempo y aparece en un valle de helechos gigantes y volcanes lejanos. ¡Es la tierra de los dinosaurios! Tres sorpresas asoman entre los helechos. ¿Cuál descubre primero?",
        ca: "{name} creua el portal del temps i apareix en una vall de falgueres gegants i volcans llunyans. És la terra dels dinosaures! Tres sorpreses apareixen entre les falgueres. Quina descobreix primer?",
        en: "{name} steps through the time portal and lands in a valley of giant ferns and faraway volcanoes. It's the land of the dinosaurs! Three surprises peek out between the ferns. Which one to discover first?",
        fr: "{name} traverse le portail du temps et arrive dans une vallée de fougères géantes et de volcans lointains. C'est le pays des dinosaures ! Trois surprises apparaissent entre les fougères. Laquelle découvrir en premier ?",
      },
      options: [
        {
          id: "egg",
          title: {
            es: "El huevo gigante",
            ca: "L'ou gegant",
            en: "The giant egg",
            fr: "L'œuf géant",
          },
          desc: {
            es: "Un huevo enorme tiembla y hace toc, toc desde dentro.",
            ca: "Un ou enorme tremola i fa toc, toc des de dins.",
            en: "An enormous egg wobbles and goes knock, knock from inside.",
            fr: "Un œuf énorme tremble et fait toc, toc de l'intérieur.",
          },
          imageSeed: "dinosaurs-c1-egg",
          icon: "egg",
          narrative: {
            es: "{name} se acerca despacito a un huevo gigante que tiembla entre los helechos y, ¡crac!, asoma un bebé dinosaurio de cuello largo.",
            ca: "{name} s'acosta a poc a poc a un ou gegant que tremola entre les falgueres i, crac!, treu el cap un bebè dinosaure de coll llarg.",
            en: "{name} tiptoes up to a giant egg wobbling among the ferns and, crack!, a baby long-neck dinosaur pops out.",
            fr: "{name} s'approche tout doucement d'un œuf géant qui tremble entre les fougères et, crac !, un bébé dinosaure au long cou pointe sa tête.",
          },
          next: "c2_egg",
        },
        {
          id: "fossil",
          title: {
            es: "El fósil que brilla",
            ca: "El fòssil que brilla",
            en: "The glowing fossil",
            fr: "Le fossile qui brille",
          },
          desc: {
            es: "Una caracola de piedra brilla y canturrea medio enterrada en la arena.",
            ca: "Una cargola de pedra brilla i cantusseja mig enterrada a la sorra.",
            en: "A stone spiral shell glows and hums, half buried in the sand.",
            fr: "Une coquille de pierre en spirale brille et fredonne, à moitié enterrée dans le sable.",
          },
          imageSeed: "dinosaurs-c1-fossil",
          icon: "diamond",
          narrative: {
            es: "{name} desentierra con cuidado un fósil en espiral que brilla con una luz azulada y canturrea bajito, como si guardara un secreto.",
            ca: "{name} desenterra amb cura un fòssil en espiral que brilla amb una llum blavosa i cantusseja fluixet, com si guardés un secret.",
            en: "{name} carefully digs up a spiral fossil that glows with a soft blue light and hums quietly, as if it kept a secret.",
            fr: "{name} déterre avec soin un fossile en spirale qui brille d'une douce lumière bleutée et fredonne tout bas, comme s'il gardait un secret.",
          },
          next: "c2_fossil",
        },
        {
          id: "footprints",
          title: {
            es: "Las huellas gigantes",
            ca: "Les petjades gegants",
            en: "The giant footprints",
            fr: "Les empreintes géantes",
          },
          desc: {
            es: "Un caminito de huellas enormes se adentra en el valle. ¿De quién serán?",
            ca: "Un caminet de petjades enormes s'endinsa a la vall. De qui deuen ser?",
            en: "A trail of huge footprints leads into the valley. Whose could they be?",
            fr: "Un petit chemin d'empreintes énormes s'enfonce dans la vallée. À qui peuvent-elles bien être ?",
          },
          imageSeed: "dinosaurs-c1-footprints",
          icon: "footprint",
          narrative: {
            es: "{name} descubre un caminito de huellas gigantes que cruza el valle y lo sigue saltando de huella en huella.",
            ca: "{name} descobreix un caminet de petjades gegants que creua la vall i el segueix saltant de petjada en petjada.",
            en: "{name} discovers a trail of giant footprints crossing the valley and follows it, hopping from footprint to footprint.",
            fr: "{name} découvre un petit chemin d'empreintes géantes qui traverse la vallée et le suit en sautant d'empreinte en empreinte.",
          },
          next: "c2_footprints",
        },
      ],
    },
    c2_egg: {
      id: "c2_egg",
      chapter: 2,
      question: {
        es: "El bebé dinosaurio dice que se llama Lulo y mira a todos lados: ¡se ha quedado solo y no encuentra a su familia de cuellos largos! {name} promete ayudarle. ¿Por dónde empiezan a buscar?",
        ca: "El bebè dinosaure diu que es diu Lulo i mira a tot arreu: s'ha quedat sol i no troba la seva família de colls llargs! {name} promet ajudar-lo. Per on comencen a buscar?",
        en: "The baby dinosaur says his name is Lulo and looks all around: he is all alone and can't find his long-neck family! {name} promises to help. Where do they start looking?",
        fr: "Le bébé dinosaure dit qu'il s'appelle Lulo et regarde partout : il est tout seul et ne trouve plus sa famille de longs cous ! {name} promet de l'aider. Par où commencer les recherches ?",
      },
      options: [
        {
          id: "hill",
          title: {
            es: "La colina mirador",
            ca: "El turó mirador",
            en: "The lookout hill",
            fr: "La colline belvédère",
          },
          desc: {
            es: "Desde lo más alto se ve el valle entero.",
            ca: "Des de dalt de tot es veu la vall sencera.",
            en: "From the very top you can see the whole valley.",
            fr: "Tout en haut, on voit la vallée entière.",
          },
          imageSeed: "dinosaurs-c2egg-hill",
          icon: "landscape",
          narrative: {
            es: "{name} y Lulo suben a la colina más alta del valle para buscar a la familia de cuellos largos desde arriba.",
            ca: "{name} i en Lulo pugen al turó més alt de la vall per buscar la família de colls llargs des de dalt.",
            en: "{name} and Lulo climb the tallest hill in the valley to look for the long-neck family from above.",
            fr: "{name} et Lulo grimpent sur la plus haute colline de la vallée pour chercher la famille de longs cous depuis là-haut.",
          },
          next: "c3_egg_a",
        },
        {
          id: "riverbank",
          title: {
            es: "La orilla del río",
            ca: "La riba del riu",
            en: "The riverbank",
            fr: "La rive de la rivière",
          },
          desc: {
            es: "Todas las familias de dinosaurios van allí a beber.",
            ca: "Totes les famílies de dinosaures hi van a beure.",
            en: "Every dinosaur family goes there to drink.",
            fr: "Toutes les familles de dinosaures y vont pour boire.",
          },
          imageSeed: "dinosaurs-c2egg-river",
          icon: "water",
          narrative: {
            es: "{name} y Lulo caminan hasta la orilla del río, donde las familias de dinosaurios dejan sus huellas al ir a beber.",
            ca: "{name} i en Lulo caminen fins a la riba del riu, on les famílies de dinosaures deixen les seves petjades quan van a beure.",
            en: "{name} and Lulo walk to the riverbank, where the dinosaur families leave their footprints when they come to drink.",
            fr: "{name} et Lulo marchent jusqu'à la rive de la rivière, où les familles de dinosaures laissent leurs empreintes en venant boire.",
          },
          next: "c3_egg_b",
        },
        {
          id: "pterodactyl",
          title: {
            es: "El pterodáctilo vigía",
            ca: "El pterodàctil vigia",
            en: "The lookout pterodactyl",
            fr: "Le ptérodactyle vigie",
          },
          desc: {
            es: "Desde el cielo lo ve todo, seguro que sabe dónde están.",
            ca: "Des del cel ho veu tot, segur que sap on són.",
            en: "He sees everything from the sky, he surely knows where they are.",
            fr: "Depuis le ciel, il voit tout, il sait sûrement où ils sont.",
          },
          imageSeed: "dinosaurs-c2egg-ptero",
          icon: "flight",
          narrative: {
            es: "{name} y Lulo van hasta la gran roca donde vive el pterodáctilo vigía, que conoce el valle entero desde el cielo.",
            ca: "{name} i en Lulo van fins a la gran roca on viu el pterodàctil vigia, que coneix la vall sencera des del cel.",
            en: "{name} and Lulo head to the big rock where the lookout pterodactyl lives, who knows the whole valley from the sky.",
            fr: "{name} et Lulo vont jusqu'au grand rocher où vit le ptérodactyle vigie, qui connaît toute la vallée depuis le ciel.",
          },
          next: "c3_egg_c",
        },
      ],
    },
    c2_fossil: {
      id: "c2_fossil",
      chapter: 2,
      question: {
        es: "El fósil canturrea en las manos de {name} y dibuja un caminito de lucecitas hacia la Cueva de Cristal: allí su música despierta las pinturas mágicas de las paredes, que se han quedado dormidas. ¿Por dónde lleva {name} el fósil a casa?",
        ca: "El fòssil cantusseja a les mans de {name} i dibuixa un caminet de llumetes cap a la Cova de Cristall: allà la seva música desperta les pintures màgiques de les parets, que s'han quedat adormides. Per on porta {name} el fòssil a casa?",
        en: "The fossil hums in {name}'s hands and draws a little trail of lights toward the Crystal Cave: there its music wakes the magic paintings on the walls, which have fallen asleep. Which way does {name} carry the fossil home?",
        fr: "Le fossile fredonne dans les mains de {name} et dessine un petit chemin de lumières vers la Grotte de Cristal : là-bas, sa musique réveille les peintures magiques des parois, qui se sont endormies. Par où {name} ramène le fossile chez lui ?",
      },
      options: [
        {
          id: "ferns",
          title: {
            es: "El bosque de helechos gigantes",
            ca: "El bosc de falgueres gegants",
            en: "The giant fern forest",
            fr: "La forêt de fougères géantes",
          },
          desc: {
            es: "Helechos más altos que casas, perfectos para explorar.",
            ca: "Falgueres més altes que cases, perfectes per explorar.",
            en: "Ferns taller than houses, perfect for exploring.",
            fr: "Des fougères plus hautes que des maisons, parfaites à explorer.",
          },
          imageSeed: "dinosaurs-c2fossil-ferns",
          icon: "grass",
          narrative: {
            es: "{name} se adentra en el bosque de helechos gigantes, donde las hojas enormes forman túneles verdes y frescos.",
            ca: "{name} s'endinsa al bosc de falgueres gegants, on les fulles enormes formen túnels verds i frescos.",
            en: "{name} ventures into the giant fern forest, where the enormous leaves form cool green tunnels.",
            fr: "{name} s'enfonce dans la forêt de fougères géantes, où les feuilles énormes forment des tunnels verts et frais.",
          },
          next: "c3_fossil_a",
        },
        {
          id: "volcano-pass",
          title: {
            es: "El paso del volcán dormido",
            ca: "El pas del volcà adormit",
            en: "The sleeping volcano pass",
            fr: "Le col du volcan endormi",
          },
          desc: {
            es: "Un atajo entre vapores calentitos donde el volcán ronca bajito.",
            ca: "Una drecera entre vapors calentons on el volcà ronca fluixet.",
            en: "A shortcut through warm steam where the volcano snores softly.",
            fr: "Un raccourci entre des vapeurs toutes chaudes où le volcan ronfle tout bas.",
          },
          imageSeed: "dinosaurs-c2fossil-volcano",
          icon: "volcano",
          narrative: {
            es: "{name} toma el atajo del volcán dormido, caminando entre nubecitas de vapor calentito mientras el volcán ronca bajito.",
            ca: "{name} agafa la drecera del volcà adormit, caminant entre nuvolets de vapor calentó mentre el volcà ronca fluixet.",
            en: "{name} takes the sleeping volcano shortcut, walking between little clouds of warm steam while the volcano snores softly.",
            fr: "{name} prend le raccourci du volcan endormi, marchant entre de petits nuages de vapeur chaude pendant que le volcan ronfle tout bas.",
          },
          next: "c3_fossil_b",
        },
        {
          id: "lake",
          title: {
            es: "El lago de los nenúfares",
            ca: "El llac dels nenúfars",
            en: "The lily-pad lake",
            fr: "Le lac aux nénuphars",
          },
          desc: {
            es: "La cueva brilla justo al otro lado del agua.",
            ca: "La cova brilla just a l'altra banda de l'aigua.",
            en: "The cave glows just on the other side of the water.",
            fr: "La grotte brille juste de l'autre côté de l'eau.",
          },
          imageSeed: "dinosaurs-c2fossil-lake",
          icon: "waves",
          narrative: {
            es: "{name} llega al lago de los nenúfares gigantes y ve la entrada de la Cueva de Cristal brillando en la otra orilla.",
            ca: "{name} arriba al llac dels nenúfars gegants i veu l'entrada de la Cova de Cristall brillant a l'altra riba.",
            en: "{name} reaches the giant lily-pad lake and sees the entrance to the Crystal Cave glowing on the far shore.",
            fr: "{name} arrive au lac des nénuphars géants et voit l'entrée de la Grotte de Cristal qui brille sur l'autre rive.",
          },
          next: "c3_fossil_c",
        },
      ],
    },
    c2_footprints: {
      id: "c2_footprints",
      chapter: 2,
      question: {
        es: "Las huellas llevan a un claro escondido donde los dinosaurios preparan algo muy especial: ¡esta noche es la Fiesta de la Luna del valle! Todos invitan a {name} a ayudar. ¿Qué prepara primero?",
        ca: "Les petjades porten a una clariana amagada on els dinosaures preparen una cosa molt especial: aquesta nit és la Festa de la Lluna de la vall! Tots conviden {name} a ajudar. Què prepara primer?",
        en: "The footprints lead to a hidden clearing where the dinosaurs are preparing something very special: tonight is the valley's Moon Festival! They all invite {name} to help. What to prepare first?",
        fr: "Les empreintes mènent à une clairière cachée où les dinosaures préparent quelque chose de très spécial : ce soir, c'est la Fête de la Lune de la vallée ! Tous invitent {name} à les aider. Que préparer en premier ?",
      },
      options: [
        {
          id: "music",
          title: {
            es: "La música",
            ca: "La música",
            en: "The music",
            fr: "La musique",
          },
          desc: {
            es: "La banda de los dinosaurios trompeta ensaya sus canciones.",
            ca: "La banda dels dinosaures trompeta assaja les seves cançons.",
            en: "The trumpet dinosaurs' band is rehearsing their songs.",
            fr: "La fanfare des dinosaures trompettes répète ses chansons.",
          },
          imageSeed: "dinosaurs-c2footprints-music",
          icon: "queue_music",
          narrative: {
            es: "{name} se une a la banda de los dinosaurios trompeta, que ensayan sus melodías hinchando las crestas como globos musicales.",
            ca: "{name} s'uneix a la banda dels dinosaures trompeta, que assagen les seves melodies inflant les crestes com globus musicals.",
            en: "{name} joins the trumpet dinosaurs' band, who rehearse their melodies puffing up their crests like musical balloons.",
            fr: "{name} rejoint la fanfare des dinosaures trompettes, qui répètent leurs mélodies en gonflant leurs crêtes comme des ballons musicaux.",
          },
          next: "c3_footprints_a",
        },
        {
          id: "lights",
          title: {
            es: "Las luces",
            ca: "Els llums",
            en: "The lights",
            fr: "Les lumières",
          },
          desc: {
            es: "El claro tiene que brillar cuando salga la luna.",
            ca: "La clariana ha de brillar quan surti la lluna.",
            en: "The clearing has to shine when the moon comes up.",
            fr: "La clairière doit briller quand la lune se lèvera.",
          },
          imageSeed: "dinosaurs-c2footprints-lights",
          icon: "lightbulb",
          narrative: {
            es: "{name} se encarga de las luces de la fiesta para que el claro entero brille cuando salga la luna.",
            ca: "{name} s'encarrega dels llums de la festa perquè la clariana sencera brilli quan surti la lluna.",
            en: "{name} takes charge of the festival lights so the whole clearing shines when the moon comes up.",
            fr: "{name} s'occupe des lumières de la fête pour que toute la clairière brille quand la lune se lèvera.",
          },
          next: "c3_footprints_b",
        },
        {
          id: "feast",
          title: {
            es: "El banquete",
            ca: "El banquet",
            en: "The feast",
            fr: "Le banquet",
          },
          desc: {
            es: "Hay que reunir las frutas más dulces del valle.",
            ca: "Cal reunir les fruites més dolces de la vall.",
            en: "The sweetest fruits in the valley must be gathered.",
            fr: "Il faut réunir les fruits les plus sucrés de la vallée.",
          },
          imageSeed: "dinosaurs-c2footprints-feast",
          icon: "restaurant",
          narrative: {
            es: "{name} ayuda a preparar el gran banquete de la fiesta reuniendo las frutas más dulces de todo el valle.",
            ca: "{name} ajuda a preparar el gran banquet de la festa reunint les fruites més dolces de tota la vall.",
            en: "{name} helps prepare the festival's grand feast by gathering the sweetest fruits in the whole valley.",
            fr: "{name} aide à préparer le grand banquet de la fête en réunissant les fruits les plus sucrés de toute la vallée.",
          },
          next: "c3_footprints_c",
        },
      ],
    },
    c3_egg_a: {
      id: "c3_egg_a",
      chapter: 3,
      question: {
        es: "Desde la colina, {name} y Lulo ven a la familia de cuellos largos al otro lado del valle, ¡pero está lejísimos! ¿Cómo consiguen llamar su atención?",
        ca: "Des del turó, {name} i en Lulo veuen la família de colls llargs a l'altra banda de la vall, però és lluníssim! Com aconsegueixen cridar la seva atenció?",
        en: "From the hill, {name} and Lulo spot the long-neck family on the other side of the valley, but they are so far away! How do they get their attention?",
        fr: "Depuis la colline, {name} et Lulo aperçoivent la famille de longs cous de l'autre côté de la vallée, mais elle est très, très loin ! Comment attirer son attention ?",
      },
      options: [
        {
          id: "call",
          title: {
            es: "Llamar a la vez",
            ca: "Cridar alhora",
            en: "Call out together",
            fr: "Appeler ensemble",
          },
          desc: {
            es: "Un buen ¡uuuh! de cuello largo se oye en todo el valle.",
            ca: "Un bon uuuh! de coll llarg se sent per tota la vall.",
            en: "A good long-neck oooh! can be heard across the whole valley.",
            fr: "Un bon ouuuh ! de long cou s'entend dans toute la vallée.",
          },
          imageSeed: "dinosaurs-c3egga-call",
          icon: "record_voice_over",
          narrative: {
            es: "{name} y Lulo respiran hondo y lanzan juntos una llamada de cuello largo tan grande que cruza todo el valle, y la familia levanta la cabeza.",
            ca: "{name} i en Lulo respiren fons i llancen junts una crida de coll llarg tan gran que creua tota la vall, i la família aixeca el cap.",
            en: "{name} and Lulo take a deep breath and let out a long-neck call so big it crosses the whole valley, and the family lifts their heads.",
            fr: "{name} et Lulo respirent un grand coup et lancent ensemble un appel de long cou si grand qu'il traverse toute la vallée, et la famille lève la tête.",
          },
          next: "ending",
        },
        {
          id: "fern-flag",
          title: {
            es: "La bandera de helecho",
            ca: "La bandera de falguera",
            en: "The fern flag",
            fr: "Le drapeau de fougère",
          },
          desc: {
            es: "Una hoja gigante ondeando se ve desde muy lejos.",
            ca: "Una fulla gegant onejant es veu des de molt lluny.",
            en: "A giant waving leaf can be seen from very far away.",
            fr: "Une feuille géante qui flotte au vent se voit de très loin.",
          },
          imageSeed: "dinosaurs-c3egga-flag",
          icon: "flag",
          narrative: {
            es: "{name} agita una hoja de helecho gigante como una bandera verde brillante hasta que la mamá de Lulo la ve relucir al sol.",
            ca: "{name} agita una fulla de falguera gegant com una bandera verda brillant fins que la mama d'en Lulo la veu lluir al sol.",
            en: "{name} waves a giant fern leaf like a bright green flag until Lulo's mum sees it shining in the sun.",
            fr: "{name} agite une feuille de fougère géante comme un drapeau vert brillant jusqu'à ce que la maman de Lulo la voie luire au soleil.",
          },
          next: "ending",
        },
        {
          id: "shell-horn",
          title: {
            es: "La caracola gigante",
            ca: "La cargola gegant",
            en: "The giant shell horn",
            fr: "La conque géante",
          },
          desc: {
            es: "Soplando dentro suena como un trueno suave y amable.",
            ca: "Bufant a dins sona com un tro suau i amable.",
            en: "Blowing into it sounds like a soft, friendly thunder.",
            fr: "En soufflant dedans, on dirait un tonnerre doux et gentil.",
          },
          imageSeed: "dinosaurs-c3egga-shell",
          icon: "campaign",
          narrative: {
            es: "{name} sopla dentro de una caracola enorme y un sonido profundo como un trueno amable llega rodando hasta la familia de Lulo.",
            ca: "{name} bufa dins d'una cargola enorme i un so profund com un tro amable arriba rodolant fins a la família d'en Lulo.",
            en: "{name} blows into an enormous shell and a deep sound like friendly thunder rolls all the way to Lulo's family.",
            fr: "{name} souffle dans une conque énorme et un son profond comme un tonnerre gentil roule jusqu'à la famille de Lulo.",
          },
          next: "ending",
        },
      ],
    },
    c3_egg_b: {
      id: "c3_egg_b",
      chapter: 3,
      question: {
        es: "En la orilla hay muchísimas huellas de familias distintas, todas mezcladas. ¿Cómo encuentra {name} el rastro de la familia de Lulo?",
        ca: "A la riba hi ha moltíssimes petjades de famílies diferents, totes barrejades. Com troba {name} el rastre de la família d'en Lulo?",
        en: "On the riverbank there are lots of footprints from different families, all mixed up. How does {name} find the trail of Lulo's family?",
        fr: "Sur la rive, il y a plein d'empreintes de familles différentes, toutes mélangées. Comment {name} retrouve la piste de la famille de Lulo ?",
      },
      options: [
        {
          id: "compare",
          title: {
            es: "Comparar las huellas",
            ca: "Comparar les petjades",
            en: "Compare the footprints",
            fr: "Comparer les empreintes",
          },
          desc: {
            es: "Las de su familia son como las de Lulo, ¡pero en gigante!",
            ca: "Les de la seva família són com les d'en Lulo, però en gegant!",
            en: "His family's are just like Lulo's, but giant-sized!",
            fr: "Celles de sa famille sont comme celles de Lulo, mais en géant !",
          },
          imageSeed: "dinosaurs-c3eggb-compare",
          icon: "search",
          narrative: {
            es: "{name} mira la huella de Lulo en el barro y la compara con todas las demás hasta encontrar unas huellas iguales pero gigantes que se alejan río arriba.",
            ca: "{name} mira la petjada d'en Lulo al fang i la compara amb totes les altres fins a trobar unes petjades iguals però gegants que s'allunyen riu amunt.",
            en: "{name} looks at Lulo's footprint in the mud and compares it with all the others until finding matching but giant footprints heading upriver.",
            fr: "{name} regarde l'empreinte de Lulo dans la boue et la compare avec toutes les autres jusqu'à trouver des empreintes identiques mais géantes qui s'éloignent vers l'amont.",
          },
          next: "ending",
        },
        {
          id: "turtle",
          title: {
            es: "Preguntar a la tortuga",
            ca: "Preguntar a la tortuga",
            en: "Ask the turtle",
            fr: "Demander à la tortue",
          },
          desc: {
            es: "La tortuga del río lleva cien años viéndolo todo.",
            ca: "La tortuga del riu fa cent anys que ho veu tot.",
            en: "The river turtle has been watching everything for a hundred years.",
            fr: "La tortue de la rivière voit tout passer depuis cent ans.",
          },
          imageSeed: "dinosaurs-c3eggb-turtle",
          icon: "pets",
          narrative: {
            es: "{name} pregunta a la tortuga gigante del río, que recuerda haber visto pasar a los cuellos largos esta mañana hacia los grandes helechos del norte.",
            ca: "{name} pregunta a la tortuga gegant del riu, que recorda haver vist passar els colls llargs aquest matí cap a les grans falgueres del nord.",
            en: "{name} asks the giant river turtle, who remembers seeing the long-necks pass by this morning toward the great ferns of the north.",
            fr: "{name} demande à la tortue géante de la rivière, qui se souvient d'avoir vu passer les longs cous ce matin vers les grandes fougères du nord.",
          },
          next: "ending",
        },
        {
          id: "nibbled-leaves",
          title: {
            es: "Las hojas mordisqueadas",
            ca: "Les fulles mossegades",
            en: "The nibbled leaves",
            fr: "Les feuilles grignotées",
          },
          desc: {
            es: "Los cuellos largos dejan ramitas mordisqueadas por el camino.",
            ca: "Els colls llargs deixen branquetes mossegades pel camí.",
            en: "Long-necks leave nibbled twigs along their way.",
            fr: "Les longs cous laissent des brindilles grignotées sur leur chemin.",
          },
          imageSeed: "dinosaurs-c3eggb-leaves",
          icon: "eco",
          narrative: {
            es: "{name} y Lulo siguen el caminito de hojas mordisqueadas que la familia ha ido dejando entre los árboles altos.",
            ca: "{name} i en Lulo segueixen el caminet de fulles mossegades que la família ha anat deixant entre els arbres alts.",
            en: "{name} and Lulo follow the little trail of nibbled leaves the family has left behind among the tall trees.",
            fr: "{name} et Lulo suivent le petit chemin de feuilles grignotées que la famille a laissé entre les grands arbres.",
          },
          next: "ending",
        },
      ],
    },
    c3_egg_c: {
      id: "c3_egg_c",
      chapter: 3,
      question: {
        es: "El pterodáctilo vigía acepta ayudar, pero el valle es enorme y hay muchas familias de cuellos largos. ¿Cómo le explica {name} a quién buscar?",
        ca: "El pterodàctil vigia accepta ajudar, però la vall és enorme i hi ha moltes famílies de colls llargs. Com li explica {name} qui ha de buscar?",
        en: "The lookout pterodactyl agrees to help, but the valley is huge and there are many long-neck families. How does {name} explain who to look for?",
        fr: "Le ptérodactyle vigie accepte d'aider, mais la vallée est immense et il y a beaucoup de familles de longs cous. Comment {name} lui explique qui chercher ?",
      },
      options: [
        {
          id: "sand-drawing",
          title: {
            es: "Dibujar a la familia",
            ca: "Dibuixar la família",
            en: "Draw the family",
            fr: "Dessiner la famille",
          },
          desc: {
            es: "Un dibujo en la arena vale más que mil palabras.",
            ca: "Un dibuix a la sorra val més que mil paraules.",
            en: "A drawing in the sand is worth a thousand words.",
            fr: "Un dessin dans le sable vaut mieux que mille mots.",
          },
          imageSeed: "dinosaurs-c3eggc-draw",
          icon: "draw",
          narrative: {
            es: "{name} dibuja en la arena a la mamá de Lulo, con su cuello larguísimo y su mancha en forma de estrella, y el pterodáctilo asiente y despega.",
            ca: "{name} dibuixa a la sorra la mama d'en Lulo, amb el seu coll llarguíssim i la seva taca en forma d'estrella, i el pterodàctil assenteix i s'enlaira.",
            en: "{name} draws Lulo's mum in the sand, with her extra-long neck and her star-shaped spot, and the pterodactyl nods and takes off.",
            fr: "{name} dessine dans le sable la maman de Lulo, avec son très long cou et sa tache en forme d'étoile, et le ptérodactyle hoche la tête et s'envole.",
          },
          next: "ending",
        },
        {
          id: "family-call",
          title: {
            es: "Enseñarle la llamada",
            ca: "Ensenyar-li la crida",
            en: "Teach him the call",
            fr: "Lui apprendre l'appel",
          },
          desc: {
            es: "Cada familia de cuellos largos tiene su propia canción.",
            ca: "Cada família de colls llargs té la seva pròpia cançó.",
            en: "Every long-neck family has its very own song.",
            fr: "Chaque famille de longs cous a sa propre chanson.",
          },
          imageSeed: "dinosaurs-c3eggc-chirp",
          icon: "graphic_eq",
          narrative: {
            es: "{name} y Lulo le enseñan al pterodáctilo la llamada de la familia, y él la repite por el cielo hasta que alguien responde a lo lejos.",
            ca: "{name} i en Lulo ensenyen al pterodàctil la crida de la família, i ell la repeteix pel cel fins que algú respon a la llunyania.",
            en: "{name} and Lulo teach the pterodactyl the family's call, and he repeats it across the sky until someone answers in the distance.",
            fr: "{name} et Lulo apprennent au ptérodactyle l'appel de la famille, et il le répète dans le ciel jusqu'à ce que quelqu'un réponde au loin.",
          },
          next: "ending",
        },
        {
          id: "fly-together",
          title: {
            es: "Volar con él",
            ca: "Volar amb ell",
            en: "Fly with him",
            fr: "Voler avec lui",
          },
          desc: {
            es: "Desde el cielo, {name} reconocerá a la familia enseguida.",
            ca: "Des del cel, {name} reconeixerà la família de seguida.",
            en: "From the sky, {name} will spot the family right away.",
            fr: "Depuis le ciel, {name} reconnaîtra la famille tout de suite.",
          },
          imageSeed: "dinosaurs-c3eggc-fly",
          icon: "flight_takeoff",
          narrative: {
            es: "{name} se sube con cuidado al lomo del pterodáctilo y juntos sobrevuelan el valle hasta ver a la familia de Lulo junto al gran lago.",
            ca: "{name} puja amb cura al llom del pterodàctil i junts sobrevolen la vall fins a veure la família d'en Lulo al costat del gran llac.",
            en: "{name} climbs carefully onto the pterodactyl's back and together they soar over the valley until they spot Lulo's family by the great lake.",
            fr: "{name} monte avec précaution sur le dos du ptérodactyle et ensemble ils survolent la vallée jusqu'à apercevoir la famille de Lulo près du grand lac.",
          },
          next: "ending",
        },
      ],
    },
    c3_fossil_a: {
      id: "c3_fossil_a",
      chapter: 3,
      question: {
        es: "Dentro del bosque, los helechos gigantes forman un laberinto verde y todos los caminos parecen iguales. ¿Cómo encuentra {name} la salida hacia la cueva?",
        ca: "Dins del bosc, les falgueres gegants formen un laberint verd i tots els camins semblen iguals. Com troba {name} la sortida cap a la cova?",
        en: "Inside the forest, the giant ferns form a green maze and every path looks the same. How does {name} find the way out toward the cave?",
        fr: "Dans la forêt, les fougères géantes forment un labyrinthe vert et tous les chemins se ressemblent. Comment {name} trouve la sortie vers la grotte ?",
      },
      options: [
        {
          id: "follow-hum",
          title: {
            es: "Seguir el canturreo",
            ca: "Seguir el cantusseig",
            en: "Follow the humming",
            fr: "Suivre le fredonnement",
          },
          desc: {
            es: "El fósil canta más fuerte cuando va por el buen camino.",
            ca: "El fòssil canta més fort quan va pel bon camí.",
            en: "The fossil sings louder when it's on the right path.",
            fr: "Le fossile chante plus fort quand il est sur le bon chemin.",
          },
          imageSeed: "dinosaurs-c3fossila-hum",
          icon: "hearing",
          narrative: {
            es: "{name} camina despacio escuchando el fósil, que canturrea más fuerte a cada paso bueno, hasta salir del laberinto verde.",
            ca: "{name} camina a poc a poc escoltant el fòssil, que cantusseja més fort a cada pas bo, fins a sortir del laberint verd.",
            en: "{name} walks slowly listening to the fossil, which hums louder with every right step, until stepping out of the green maze.",
            fr: "{name} marche lentement en écoutant le fossile, qui fredonne plus fort à chaque bon pas, jusqu'à sortir du labyrinthe vert.",
          },
          next: "ending",
        },
        {
          id: "tiny-hoppers",
          title: {
            es: "Los pequeños saltarines",
            ca: "Els petits saltarins",
            en: "The tiny hoppers",
            fr: "Les petits sauteurs",
          },
          desc: {
            es: "Una pandilla de dinosaurios chiquititos que conoce cada rincón.",
            ca: "Una colla de dinosaures petitons que coneix cada racó.",
            en: "A gang of teeny dinosaurs who know every corner.",
            fr: "Une bande de tout petits dinosaures qui connaît chaque recoin.",
          },
          imageSeed: "dinosaurs-c3fossila-hoppers",
          icon: "directions_run",
          narrative: {
            es: "{name} sigue a una pandilla de dinosaurios pequeñitos que saltan entre los helechos enseñando el camino secreto hacia la cueva.",
            ca: "{name} segueix una colla de dinosaures petitons que salten entre les falgueres ensenyant el camí secret cap a la cova.",
            en: "{name} follows a gang of teeny dinosaurs hopping between the ferns, showing the secret way to the cave.",
            fr: "{name} suit une bande de tout petits dinosaures qui sautent entre les fougères en montrant le chemin secret vers la grotte.",
          },
          next: "ending",
        },
        {
          id: "climb-fern",
          title: {
            es: "Trepar a un helecho",
            ca: "Enfilar-se a una falguera",
            en: "Climb a fern",
            fr: "Grimper sur une fougère",
          },
          desc: {
            es: "Desde arriba se ve la cueva brillando a lo lejos.",
            ca: "Des de dalt es veu la cova brillant a la llunyania.",
            en: "From up there you can see the cave glowing in the distance.",
            fr: "De là-haut, on voit la grotte briller au loin.",
          },
          imageSeed: "dinosaurs-c3fossila-climb",
          icon: "nature",
          narrative: {
            es: "{name} trepa con cuidado por un helecho gigante, asoma la cabeza por encima del bosque y ve brillar la entrada de la cueva.",
            ca: "{name} s'enfila amb cura per una falguera gegant, treu el cap per sobre del bosc i veu brillar l'entrada de la cova.",
            en: "{name} carefully climbs a giant fern, pokes their head above the forest and sees the cave entrance glowing.",
            fr: "{name} grimpe prudemment sur une fougère géante, passe la tête au-dessus de la forêt et voit briller l'entrée de la grotte.",
          },
          next: "ending",
        },
      ],
    },
    c3_fossil_b: {
      id: "c3_fossil_b",
      chapter: 3,
      question: {
        es: "En el paso del volcán, un anquilosaurio enorme está tumbado en medio del camino y no se mueve: ¡le pica la espalda acorazada y no llega a rascarse! ¿Cómo le ayuda {name}?",
        ca: "Al pas del volcà, un anquilosaure enorme està estirat al mig del camí i no es mou: li pica l'esquena cuirassada i no arriba a rascar-se! Com l'ajuda {name}?",
        en: "At the volcano pass, an enormous ankylosaurus is lying in the middle of the path and won't move: his armoured back is itchy and he can't reach to scratch it! How does {name} help him?",
        fr: "Au col du volcan, un énorme ankylosaure est allongé au milieu du chemin et ne bouge pas : son dos cuirassé le démange et il n'arrive pas à se gratter ! Comment {name} peut l'aider ?",
      },
      options: [
        {
          id: "fern-scratch",
          title: {
            es: "Rascarle con un helecho",
            ca: "Rascar-lo amb una falguera",
            en: "Scratch him with a fern",
            fr: "Le gratter avec une fougère",
          },
          desc: {
            es: "Una hoja grande y suave, perfecta para picores de dinosaurio.",
            ca: "Una fulla gran i suau, perfecta per a picors de dinosaure.",
            en: "A big soft leaf, perfect for dinosaur itches.",
            fr: "Une grande feuille douce, parfaite pour les démangeaisons de dinosaure.",
          },
          imageSeed: "dinosaurs-c3fossilb-scratch",
          icon: "back_hand",
          narrative: {
            es: "{name} rasca la espalda acorazada del anquilosaurio con una hoja de helecho y él suspira feliz, mueve la cola de alegría y deja el camino libre.",
            ca: "{name} rasca l'esquena cuirassada de l'anquilosaure amb una fulla de falguera i ell sospira feliç, mou la cua d'alegria i deixa el camí lliure.",
            en: "{name} scratches the ankylosaurus's armoured back with a fern leaf and he sighs happily, wags his tail with joy and clears the path.",
            fr: "{name} gratte le dos cuirassé de l'ankylosaure avec une feuille de fougère et il soupire de bonheur, remue la queue de joie et libère le chemin.",
          },
          next: "ending",
        },
        {
          id: "sand-bath",
          title: {
            es: "Un baño de arena",
            ca: "Un bany de sorra",
            en: "A sand bath",
            fr: "Un bain de sable",
          },
          desc: {
            es: "Revolcarse en arena suavecita quita todos los picores.",
            ca: "Rebolcar-se en sorra suau treu totes les picors.",
            en: "Rolling in soft sand takes every itch away.",
            fr: "Se rouler dans du sable tout doux fait partir toutes les démangeaisons.",
          },
          imageSeed: "dinosaurs-c3fossilb-sand",
          icon: "grain",
          narrative: {
            es: "{name} prepara para el anquilosaurio un montoncito de arena calentita y él se revuelca contento, dejando el camino libre con una sonrisa.",
            ca: "{name} prepara per a l'anquilosaure un muntet de sorra calentona i ell s'hi rebolca content, deixant el camí lliure amb un somriure.",
            en: "{name} makes the ankylosaurus a little pile of warm sand and he rolls in it happily, clearing the path with a smile.",
            fr: "{name} prépare pour l'ankylosaure un petit tas de sable bien chaud et il s'y roule, tout content, libérant le chemin avec un sourire.",
          },
          next: "ending",
        },
        {
          id: "pinecone",
          title: {
            es: "La piña rasca-rasca",
            ca: "La pinya rasca-rasca",
            en: "The scratchy pinecone",
            fr: "La pomme de pin gratte-gratte",
          },
          desc: {
            es: "Una piña gigante rueda genial por las espaldas con picor.",
            ca: "Una pinya gegant roda genial per les esquenes amb picor.",
            en: "A giant pinecone rolls perfectly over itchy backs.",
            fr: "Une pomme de pin géante roule à merveille sur les dos qui grattent.",
          },
          imageSeed: "dinosaurs-c3fossilb-pinecone",
          icon: "forest",
          narrative: {
            es: "{name} hace rodar una piña gigante por la espalda del anquilosaurio, que ríe con un ronroneo de trueno y se aparta del camino encantado.",
            ca: "{name} fa rodar una pinya gegant per l'esquena de l'anquilosaure, que riu amb un ronc de tro i s'aparta del camí encantat.",
            en: "{name} rolls a giant pinecone over the ankylosaurus's back, and he laughs with a thunder-like purr and happily moves off the path.",
            fr: "{name} fait rouler une pomme de pin géante sur le dos de l'ankylosaure, qui rit avec un ronronnement de tonnerre et s'écarte du chemin, ravi.",
          },
          next: "ending",
        },
      ],
    },
    c3_fossil_c: {
      id: "c3_fossil_c",
      chapter: 3,
      question: {
        es: "La Cueva de Cristal brilla en la otra orilla del lago, pero el agua es ancha y tranquila. ¿Cómo cruza {name} con el fósil?",
        ca: "La Cova de Cristall brilla a l'altra riba del llac, però l'aigua és ampla i tranquil·la. Com creua {name} amb el fòssil?",
        en: "The Crystal Cave glows on the far shore of the lake, but the water is wide and still. How does {name} cross with the fossil?",
        fr: "La Grotte de Cristal brille sur l'autre rive du lac, mais l'eau est large et calme. Comment {name} traverse avec le fossile ?",
      },
      options: [
        {
          id: "swimmer",
          title: {
            es: "El nadador de cuello largo",
            ca: "El nedador de coll llarg",
            en: "The long-necked swimmer",
            fr: "Le nageur au long cou",
          },
          desc: {
            es: "Un dinosaurio acuático muy amable ofrece su lomo de barquito.",
            ca: "Un dinosaure aquàtic molt amable ofereix el seu llom de barqueta.",
            en: "A very friendly water dinosaur offers his back as a little boat.",
            fr: "Un dinosaure aquatique très gentil offre son dos comme petit bateau.",
          },
          imageSeed: "dinosaurs-c3fossilc-swimmer",
          icon: "sailing",
          narrative: {
            es: "{name} sube al lomo de un amable dinosaurio nadador y cruza el lago dejando una estela de onditas brillantes.",
            ca: "{name} puja al llom d'un amable dinosaure nedador i creua el llac deixant una estela d'onetes brillants.",
            en: "{name} climbs onto the back of a friendly swimming dinosaur and crosses the lake leaving a trail of shimmering ripples.",
            fr: "{name} monte sur le dos d'un gentil dinosaure nageur et traverse le lac en laissant un sillage de petites vagues brillantes.",
          },
          next: "ending",
        },
        {
          id: "lily-pads",
          title: {
            es: "Los nenúfares gigantes",
            ca: "Els nenúfars gegants",
            en: "The giant lily pads",
            fr: "Les nénuphars géants",
          },
          desc: {
            es: "Hoja a hoja se puede saltar hasta la otra orilla.",
            ca: "Fulla a fulla es pot saltar fins a l'altra riba.",
            en: "Leaf by leaf you can hop to the other shore.",
            fr: "Feuille après feuille, on peut sauter jusqu'à l'autre rive.",
          },
          imageSeed: "dinosaurs-c3fossilc-lily",
          icon: "spa",
          narrative: {
            es: "{name} cruza el lago saltando de nenúfar en nenúfar, con el fósil bien sujeto entre las manos.",
            ca: "{name} creua el llac saltant de nenúfar en nenúfar, amb el fòssil ben agafat entre les mans.",
            en: "{name} crosses the lake hopping from lily pad to lily pad, holding the fossil tight in both hands.",
            fr: "{name} traverse le lac en sautant de nénuphar en nénuphar, le fossile bien serré entre les mains.",
          },
          next: "ending",
        },
        {
          id: "log-raft",
          title: {
            es: "Una balsa de tronco",
            ca: "Un rai de tronc",
            en: "A log raft",
            fr: "Un radeau de bois",
          },
          desc: {
            es: "Con un tronco y una hoja de vela, ¡a navegar!",
            ca: "Amb un tronc i una fulla de vela, a navegar!",
            en: "With a log and a leaf for a sail, off you sail!",
            fr: "Avec un tronc et une feuille en guise de voile, en avant !",
          },
          imageSeed: "dinosaurs-c3fossilc-raft",
          icon: "construction",
          narrative: {
            es: "{name} empuja un tronco hueco al agua, levanta una hoja gigante como vela y navega despacito hasta la entrada de la cueva.",
            ca: "{name} empeny un tronc buit a l'aigua, aixeca una fulla gegant com a vela i navega a poc a poc fins a l'entrada de la cova.",
            en: "{name} pushes a hollow log into the water, raises a giant leaf as a sail and slowly sails to the cave entrance.",
            fr: "{name} pousse un tronc creux dans l'eau, dresse une feuille géante comme voile et navigue tout doucement jusqu'à l'entrée de la grotte.",
          },
          next: "ending",
        },
      ],
    },
    c3_footprints_a: {
      id: "c3_footprints_a",
      chapter: 3,
      question: {
        es: "A la banda de los dinosaurios trompeta le falta lo más importante: ¡los instrumentos que marcan el ritmo del baile! ¿Qué inventa {name}?",
        ca: "A la banda dels dinosaures trompeta li falta el més important: els instruments que marquen el ritme del ball! Què inventa {name}?",
        en: "The trumpet dinosaurs' band is missing the most important thing: the instruments that keep the dance rhythm! What does {name} invent?",
        fr: "Il manque à la fanfare des dinosaures trompettes le plus important : les instruments qui donnent le rythme de la danse ! Qu'invente {name} ?",
      },
      options: [
        {
          id: "log-drum",
          title: {
            es: "El tronco tambor",
            ca: "El tronc tambor",
            en: "The log drum",
            fr: "Le tronc tambour",
          },
          desc: {
            es: "Un tronco hueco suena como un tambor gigante.",
            ca: "Un tronc buit sona com un tambor gegant.",
            en: "A hollow log sounds like a giant drum.",
            fr: "Un tronc creux sonne comme un tambour géant.",
          },
          imageSeed: "dinosaurs-c3footprintsa-drum",
          icon: "music_note",
          narrative: {
            es: "{name} encuentra un tronco hueco y lo toca con dos ramas: ¡bum, bum!, el ritmo perfecto para la banda de la fiesta.",
            ca: "{name} troba un tronc buit i el toca amb dues branques: bum, bum!, el ritme perfecte per a la banda de la festa.",
            en: "{name} finds a hollow log and plays it with two branches: boom, boom!, the perfect rhythm for the festival band.",
            fr: "{name} trouve un tronc creux et en joue avec deux branches : boum, boum !, le rythme parfait pour la fanfare de la fête.",
          },
          next: "ending",
        },
        {
          id: "stomp-dance",
          title: {
            es: "El baile de pisotones",
            ca: "El ball de trepitjades",
            en: "The stomping dance",
            fr: "La danse des gros pas",
          },
          desc: {
            es: "Los triceratops hacen temblar el suelo al bailar.",
            ca: "Els triceratops fan tremolar el terra quan ballen.",
            en: "The triceratops make the ground rumble when they dance.",
            fr: "Les tricératops font trembler le sol quand ils dansent.",
          },
          imageSeed: "dinosaurs-c3footprintsa-stomp",
          icon: "celebration",
          narrative: {
            es: "{name} dirige a los triceratops en un baile de pisotones suaves que hace tamborilear todo el claro al mismo compás.",
            ca: "{name} dirigeix els triceratops en un ball de trepitjades suaus que fa tamborinar tota la clariana al mateix compàs.",
            en: "{name} leads the triceratops in a gentle stomping dance that makes the whole clearing drum to the same beat.",
            fr: "{name} dirige les tricératops dans une danse de pas tout doux qui fait tambouriner toute la clairière en rythme.",
          },
          next: "ending",
        },
        {
          id: "seed-shakers",
          title: {
            es: "Los sonajeros de semillas",
            ca: "Els sonalls de llavors",
            en: "The seed shakers",
            fr: "Les maracas de graines",
          },
          desc: {
            es: "Las vainas secas hacen chas-chas al agitarlas.",
            ca: "Les beines seques fan xas-xas quan s'agiten.",
            en: "The dry seed pods go shake-shake when you rattle them.",
            fr: "Les gousses sèches font tchac-tchac quand on les agite.",
          },
          imageSeed: "dinosaurs-c3footprintsa-shakers",
          icon: "vibration",
          narrative: {
            es: "{name} reparte vainas llenas de semillas entre los dinosaurios pequeños y todos agitan el ritmo a la vez: ¡chas, chas, chas!",
            ca: "{name} reparteix beines plenes de llavors entre els dinosaures petits i tots agiten el ritme alhora: xas, xas, xas!",
            en: "{name} hands out seed-filled pods to the little dinosaurs and they all shake the rhythm together: shake, shake, shake!",
            fr: "{name} distribue des gousses pleines de graines aux petits dinosaures et tous agitent le rythme en même temps : tchac, tchac, tchac !",
          },
          next: "ending",
        },
      ],
    },
    c3_footprints_b: {
      id: "c3_footprints_b",
      chapter: 3,
      question: {
        es: "Cuando salga la luna, el claro entero tiene que llenarse de lucecitas para el gran baile. ¿Qué luz prepara {name}?",
        ca: "Quan surti la lluna, la clariana sencera s'ha d'omplir de llumetes per al gran ball. Quin llum prepara {name}?",
        en: "When the moon comes up, the whole clearing must fill with little lights for the big dance. What light does {name} prepare?",
        fr: "Quand la lune se lèvera, toute la clairière devra se remplir de petites lumières pour le grand bal. Quelle lumière prépare {name} ?",
      },
      options: [
        {
          id: "moon-mushrooms",
          title: {
            es: "Las setas de luna",
            ca: "Els bolets de lluna",
            en: "The moon mushrooms",
            fr: "Les champignons de lune",
          },
          desc: {
            es: "Se encienden solitas cuando llega la noche.",
            ca: "S'encenen soletes quan arriba la nit.",
            en: "They light up all by themselves when night falls.",
            fr: "Ils s'allument tout seuls quand la nuit tombe.",
          },
          imageSeed: "dinosaurs-c3footprintsb-mushrooms",
          icon: "nightlight",
          narrative: {
            es: "{name} recoge con cuidado setas de luna y las coloca en un circulito brillante alrededor de la pista de baile.",
            ca: "{name} recull amb cura bolets de lluna i els col·loca en un cerclet brillant al voltant de la pista de ball.",
            en: "{name} carefully gathers moon mushrooms and places them in a glowing little circle around the dance floor.",
            fr: "{name} ramasse avec soin des champignons de lune et les dispose en petit cercle brillant autour de la piste de danse.",
          },
          next: "ending",
        },
        {
          id: "lantern-beetles",
          title: {
            es: "Los escarabajos farol",
            ca: "Els escarabats fanalet",
            en: "The lantern beetles",
            fr: "Les scarabées lanternes",
          },
          desc: {
            es: "Les encanta la fruta dulce y brillan como estrellitas.",
            ca: "Els encanta la fruita dolça i brillen com estrelletes.",
            en: "They love sweet fruit and glow like tiny stars.",
            fr: "Ils adorent les fruits sucrés et brillent comme des petites étoiles.",
          },
          imageSeed: "dinosaurs-c3footprintsb-beetles",
          icon: "bug_report",
          narrative: {
            es: "{name} invita a los escarabajos farol con trocitos de fruta dulce y ellos se posan en las ramas como guirnaldas de luz.",
            ca: "{name} convida els escarabats fanalet amb trossets de fruita dolça i ells es posen a les branques com garlandes de llum.",
            en: "{name} invites the lantern beetles with little pieces of sweet fruit and they settle on the branches like garlands of light.",
            fr: "{name} invite les scarabées lanternes avec des petits morceaux de fruits sucrés et ils se posent sur les branches comme des guirlandes de lumière.",
          },
          next: "ending",
        },
        {
          id: "polished-crystals",
          title: {
            es: "Los cristales pulidos",
            ca: "Els cristalls polits",
            en: "The polished crystals",
            fr: "Les cristaux polis",
          },
          desc: {
            es: "Bien limpios, reflejan la luna como espejitos.",
            ca: "Ben nets, reflecteixen la lluna com mirallets.",
            en: "Nice and clean, they reflect the moon like little mirrors.",
            fr: "Bien propres, ils reflètent la lune comme des petits miroirs.",
          },
          imageSeed: "dinosaurs-c3footprintsb-crystals",
          icon: "cleaning_services",
          narrative: {
            es: "{name} pule cristales del río con una hoja suave y los coloca por el claro para que repartan la luz de la luna como espejitos.",
            ca: "{name} poleix cristalls del riu amb una fulla suau i els col·loca per la clariana perquè reparteixin la llum de la lluna com mirallets.",
            en: "{name} polishes river crystals with a soft leaf and places them around the clearing so they spread the moonlight like little mirrors.",
            fr: "{name} polit des cristaux de la rivière avec une feuille douce et les dispose dans la clairière pour qu'ils répandent la lumière de la lune comme des petits miroirs.",
          },
          next: "ending",
        },
      ],
    },
    c3_footprints_c: {
      id: "c3_footprints_c",
      chapter: 3,
      question: {
        es: "Las frutas más dulces del valle crecen en lo alto del árbol más alto, donde nadie llega. ¿Cómo las consigue {name}?",
        ca: "Les fruites més dolces de la vall creixen a dalt de tot de l'arbre més alt, on ningú no arriba. Com les aconsegueix {name}?",
        en: "The sweetest fruits in the valley grow at the top of the tallest tree, where nobody can reach. How does {name} get them?",
        fr: "Les fruits les plus sucrés de la vallée poussent tout en haut de l'arbre le plus haut, où personne n'arrive. Comment {name} va les attraper ?",
      },
      options: [
        {
          id: "neck-elevator",
          title: {
            es: "El ascensor de cuello largo",
            ca: "L'ascensor de coll llarg",
            en: "The long-neck elevator",
            fr: "L'ascenseur au long cou",
          },
          desc: {
            es: "Subir por un cuello largo es como ir en ascensor.",
            ca: "Pujar per un coll llarg és com anar amb ascensor.",
            en: "Riding up a long neck is just like taking an elevator.",
            fr: "Monter sur un long cou, c'est comme prendre l'ascenseur.",
          },
          imageSeed: "dinosaurs-c3footprintsc-elevator",
          icon: "elevator",
          narrative: {
            es: "{name} se sienta en la cabeza de una amable dinosaurio de cuello largo, que le sube despacito hasta las ramas más altas llenas de fruta.",
            ca: "{name} s'asseu al cap d'una amable dinosaure de coll llarg, que el puja a poc a poc fins a les branques més altes plenes de fruita.",
            en: "{name} sits on the head of a friendly long-neck dinosaur, who slowly lifts them up to the highest branches full of fruit.",
            fr: "{name} s'assoit sur la tête d'un gentil dinosaure au long cou, qui le monte tout doucement jusqu'aux plus hautes branches pleines de fruits.",
          },
          next: "ending",
        },
        {
          id: "flying-friend",
          title: {
            es: "El amigo volador",
            ca: "L'amic volador",
            en: "The flying friend",
            fr: "L'ami volant",
          },
          desc: {
            es: "El pterodáctilo recoge las frutas en pleno vuelo.",
            ca: "El pterodàctil recull les fruites en ple vol.",
            en: "The pterodactyl picks the fruits in mid-flight.",
            fr: "Le ptérodactyle cueille les fruits en plein vol.",
          },
          imageSeed: "dinosaurs-c3footprintsc-flyer",
          icon: "paragliding",
          narrative: {
            es: "{name} señala las frutas más maduras y el pterodáctilo las recoge en pleno vuelo, dejándolas caer suavemente en sus brazos.",
            ca: "{name} assenyala les fruites més madures i el pterodàctil les recull en ple vol, deixant-les caure suaument als seus braços.",
            en: "{name} points out the ripest fruits and the pterodactyl picks them in mid-flight, dropping them gently into their arms.",
            fr: "{name} montre les fruits les plus mûrs et le ptérodactyle les cueille en plein vol, les laissant tomber doucement dans ses bras.",
          },
          next: "ending",
        },
        {
          id: "vine-team",
          title: {
            es: "Tirar de la liana",
            ca: "Estirar la liana",
            en: "Pull the vine",
            fr: "Tirer sur la liane",
          },
          desc: {
            es: "Si todos tiran juntos, la rama baja hasta el suelo.",
            ca: "Si tots estiren junts, la branca baixa fins a terra.",
            en: "If everyone pulls together, the branch comes down to the ground.",
            fr: "Si tout le monde tire ensemble, la branche descend jusqu'au sol.",
          },
          imageSeed: "dinosaurs-c3footprintsc-vine",
          icon: "groups",
          narrative: {
            es: "{name} ata una liana a la rama más alta y todos los dinosaurios tiran juntos hasta que la rama baja suavecito y las frutas quedan al alcance de todos.",
            ca: "{name} lliga una liana a la branca més alta i tots els dinosaures estiren junts fins que la branca baixa suaument i les fruites queden a l'abast de tothom.",
            en: "{name} ties a vine to the highest branch and all the dinosaurs pull together until the branch bends down gently and the fruits are within everyone's reach.",
            fr: "{name} attache une liane à la plus haute branche et tous les dinosaures tirent ensemble jusqu'à ce que la branche descende doucement et que les fruits soient à portée de tous.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "", en: "", fr: "" },
      options: [],
    },
  },
};
