import type { StoryTree } from "./types";

// Branching story tree for the "forest" template (El Bosque Mágico).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es source of truth + ca/en/fr). {name} = child's name.

export const forestTree: StoryTree = {
  templateId: "forest",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} se adentra en el Bosque Mágico, donde los árboles más viejos guardan secretos. De pronto, tres descubrimientos asoman entre las hojas. ¿Cuál explora primero?",
        ca: "{name} s'endinsa al Bosc Màgic, on els arbres més vells guarden secrets. De sobte, tres descobriments apareixen entre les fulles. Quin explora primer?",
        en: "{name} steps into the Magic Forest, where the oldest trees keep secrets. Suddenly, three discoveries peek out between the leaves. Which one to explore first?",
        fr: "{name} s'enfonce dans la Forêt Magique, où les arbres les plus anciens gardent des secrets. Soudain, trois découvertes apparaissent entre les feuilles. Laquelle explorer en premier ?",
      },
      options: [
        {
          id: "dragon",
          title: {
            es: "El dragón dormido",
            ca: "El drac adormit",
            en: "The sleeping dragon",
            fr: "Le dragon endormi",
          },
          desc: {
            es: "Un dragoncito ronca suavecito bajo el árbol más viejo del bosque.",
            ca: "Un dragonet ronca fluixet sota l'arbre més vell del bosc.",
            en: "A little dragon snores softly under the oldest tree in the forest.",
            fr: "Un petit dragon ronfle tout doucement sous le plus vieil arbre de la forêt.",
          },
          imageSeed: "forest-c1-dragon",
          icon: "local_fire_department",
          narrative: {
            es: "{name} se acerca de puntillas a un dragoncito verde que duerme acurrucado bajo el árbol más viejo del bosque.",
            ca: "{name} s'acosta de puntetes a un dragonet verd que dorm arraulit sota l'arbre més vell del bosc.",
            en: "{name} tiptoes up to a little green dragon sleeping curled up under the oldest tree in the forest.",
            fr: "{name} s'approche sur la pointe des pieds d'un petit dragon vert qui dort blotti sous le plus vieil arbre de la forêt.",
          },
          next: "c2_dragon",
        },
        {
          id: "chest",
          title: {
            es: "El cofre mágico",
            ca: "El cofre màgic",
            en: "The magic chest",
            fr: "Le coffre magique",
          },
          desc: {
            es: "Un cofre cubierto de musgo y flores brilla entre las raíces.",
            ca: "Un cofre cobert de molsa i flors brilla entre les arrels.",
            en: "A chest covered in moss and flowers glows between the roots.",
            fr: "Un coffre couvert de mousse et de fleurs brille entre les racines.",
          },
          imageSeed: "forest-c1-chest",
          icon: "deployed_code",
          narrative: {
            es: "{name} encuentra entre las raíces un cofre antiguo cubierto de musgo y flores que brilla con luz dorada.",
            ca: "{name} troba entre les arrels un cofre antic cobert de molsa i flors que brilla amb llum daurada.",
            en: "{name} finds an ancient chest covered in moss and flowers glowing with golden light between the roots.",
            fr: "{name} trouve entre les racines un coffre ancien couvert de mousse et de fleurs qui brille d'une lumière dorée.",
          },
          next: "c2_chest",
        },
        {
          id: "door",
          title: {
            es: "La puerta secreta",
            ca: "La porta secreta",
            en: "The secret door",
            fr: "La porte secrète",
          },
          desc: {
            es: "Una puertecita brilla sola entre dos árboles. ¿A dónde llevará?",
            ca: "Una porteta brilla tota sola entre dos arbres. On deu portar?",
            en: "A little door glows all by itself between two trees. Where could it lead?",
            fr: "Une petite porte brille toute seule entre deux arbres. Où peut-elle mener ?",
          },
          imageSeed: "forest-c1-door",
          icon: "door_front",
          narrative: {
            es: "{name} descubre una puerta misteriosa que brilla suavemente entre dos árboles y gira el pomo con cuidado.",
            ca: "{name} descobreix una porta misteriosa que brilla suaument entre dos arbres i gira el pom amb cura.",
            en: "{name} discovers a mysterious door glowing softly between two trees and turns the handle carefully.",
            fr: "{name} découvre une porte mystérieuse qui brille doucement entre deux arbres et tourne la poignée avec précaution.",
          },
          next: "c2_door",
        },
      ],
    },
    c2_dragon: {
      id: "c2_dragon",
      chapter: 2,
      question: {
        es: "El dragoncito se despierta y dice que se llama Brasa. Está triste: su llamita se ha apagado y esta noche debe encender los farolillos del bosque. ¿Dónde buscan {name} y Brasa una chispa nueva?",
        ca: "El dragonet es desperta i diu que es diu Brasa. Està trist: la seva flameta s'ha apagat i aquesta nit ha d'encendre els fanalets del bosc. On busquen {name} i en Brasa una espurna nova?",
        en: "The little dragon wakes up and says his name is Brasa. He is sad: his little flame has gone out and tonight he must light the forest lanterns. Where do {name} and Brasa look for a new spark?",
        fr: "Le petit dragon se réveille et dit qu'il s'appelle Brasa. Il est triste : sa petite flamme s'est éteinte et ce soir il doit allumer les lanternes de la forêt. Où {name} et Brasa cherchent-ils une nouvelle étincelle ?",
      },
      options: [
        {
          id: "fireflies",
          title: {
            es: "El prado de las luciérnagas",
            ca: "El prat de les cuques de llum",
            en: "The firefly meadow",
            fr: "Le pré des lucioles",
          },
          desc: {
            es: "Cientos de lucecitas bailan sobre la hierba al caer la tarde.",
            ca: "Centenars de llumetes ballen sobre l'herba quan cau la tarda.",
            en: "Hundreds of tiny lights dance over the grass at dusk.",
            fr: "Des centaines de petites lumières dansent sur l'herbe à la tombée du jour.",
          },
          imageSeed: "forest-c2dragon-fireflies",
          icon: "emoji_nature",
          narrative: {
            es: "{name} y Brasa caminan hasta un prado donde cientos de luciérnagas bailan como chispitas vivas.",
            ca: "{name} i en Brasa caminen fins a un prat on centenars de cuques de llum ballen com espurnetes vives.",
            en: "{name} and Brasa walk to a meadow where hundreds of fireflies dance like tiny living sparks.",
            fr: "{name} et Brasa marchent jusqu'à un pré où des centaines de lucioles dansent comme de petites étincelles vivantes.",
          },
          next: "c3_dragon_a",
        },
        {
          id: "sunflower",
          title: {
            es: "La Flor del Sol",
            ca: "La Flor del Sol",
            en: "The Sun Flower",
            fr: "La Fleur du Soleil",
          },
          desc: {
            es: "Una flor gigante guarda un rayito de sol entre sus pétalos.",
            ca: "Una flor gegant guarda un raget de sol entre els seus pètals.",
            en: "A giant flower keeps a little sunbeam between its petals.",
            fr: "Une fleur géante garde un petit rayon de soleil entre ses pétales.",
          },
          imageSeed: "forest-c2dragon-sunflower",
          icon: "local_florist",
          narrative: {
            es: "{name} y Brasa buscan la Flor del Sol, una flor gigante que guarda un rayito de sol entre sus pétalos.",
            ca: "{name} i en Brasa busquen la Flor del Sol, una flor gegant que guarda un raget de sol entre els seus pètals.",
            en: "{name} and Brasa search for the Sun Flower, a giant flower that keeps a little sunbeam between its petals.",
            fr: "{name} et Brasa partent chercher la Fleur du Soleil, une fleur géante qui garde un petit rayon de soleil entre ses pétales.",
          },
          next: "c3_dragon_b",
        },
        {
          id: "cave",
          title: {
            es: "La cueva de cristales",
            ca: "La cova de cristalls",
            en: "The crystal cave",
            fr: "La grotte aux cristaux",
          },
          desc: {
            es: "Dentro de la montaña brillan cristales calentitos de colores.",
            ca: "Dins de la muntanya brillen cristalls calentons de colors.",
            en: "Warm, colourful crystals glow inside the mountain.",
            fr: "Des cristaux chauds et colorés brillent à l'intérieur de la montagne.",
          },
          imageSeed: "forest-c2dragon-cave",
          icon: "diamond",
          narrative: {
            es: "{name} y Brasa entran en una cueva escondida donde brillan cristales de colores que dan un calorcito suave.",
            ca: "{name} i en Brasa entren en una cova amagada on brillen cristalls de colors que fan una escalforeta suau.",
            en: "{name} and Brasa enter a hidden cave where colourful crystals glow with a gentle warmth.",
            fr: "{name} et Brasa entrent dans une grotte cachée où brillent des cristaux colorés qui dégagent une douce chaleur.",
          },
          next: "c3_dragon_c",
        },
      ],
    },
    c2_chest: {
      id: "c2_chest",
      chapter: 2,
      question: {
        es: "El cofre susurra: 'Solo me abre la llave de flor, escondida en el bosque'. {name} decide encontrarla. ¿Por dónde empieza a buscar?",
        ca: "El cofre xiuxiueja: 'Només m'obre la clau de flor, amagada al bosc'. {name} decideix trobar-la. Per on comença a buscar?",
        en: "The chest whispers: 'Only the flower key can open me, and it is hidden in the forest.' {name} decides to find it. Where to start looking?",
        fr: "Le coffre chuchote : « Seule la clé-fleur peut m'ouvrir, et elle est cachée dans la forêt. » {name} décide de la trouver. Par où commencer ?",
      },
      options: [
        {
          id: "squirrels",
          title: {
            es: "El nido de las ardillas",
            ca: "El niu dels esquirols",
            en: "The squirrels' nest",
            fr: "Le nid des écureuils",
          },
          desc: {
            es: "Las ardillas coleccionan todos los tesoros brillantes del bosque.",
            ca: "Els esquirols col·leccionen tots els tresors brillants del bosc.",
            en: "The squirrels collect every shiny treasure in the forest.",
            fr: "Les écureuils collectionnent tous les trésors brillants de la forêt.",
          },
          imageSeed: "forest-c2chest-squirrels",
          icon: "pets",
          narrative: {
            es: "{name} trepa hasta el nido de las ardillas, donde guardan montoncitos de tesoros brillantes encontrados por el bosque.",
            ca: "{name} s'enfila fins al niu dels esquirols, on guarden muntets de tresors brillants trobats pel bosc.",
            en: "{name} climbs up to the squirrels' nest, where they keep little piles of shiny treasures found around the forest.",
            fr: "{name} grimpe jusqu'au nid des écureuils, où ils gardent des petits tas de trésors brillants trouvés dans la forêt.",
          },
          next: "c3_chest_a",
        },
        {
          id: "stream",
          title: {
            es: "El arroyo cantarín",
            ca: "El rierol cantaire",
            en: "The singing stream",
            fr: "Le ruisseau chantant",
          },
          desc: {
            es: "Algo dorado brilla en el fondo del agua clara.",
            ca: "Alguna cosa daurada brilla al fons de l'aigua clara.",
            en: "Something golden sparkles at the bottom of the clear water.",
            fr: "Quelque chose de doré brille au fond de l'eau claire.",
          },
          imageSeed: "forest-c2chest-stream",
          icon: "water",
          narrative: {
            es: "{name} sigue el arroyo cantarín y descubre un brillo dorado durmiendo en el fondo del agua clara.",
            ca: "{name} segueix el rierol cantaire i descobreix una lluentor daurada dormint al fons de l'aigua clara.",
            en: "{name} follows the singing stream and spots a golden glimmer resting at the bottom of the clear water.",
            fr: "{name} suit le ruisseau chantant et découvre un éclat doré qui repose au fond de l'eau claire.",
          },
          next: "c3_chest_b",
        },
        {
          id: "hollow-tree",
          title: {
            es: "El árbol hueco",
            ca: "L'arbre buit",
            en: "The hollow tree",
            fr: "L'arbre creux",
          },
          desc: {
            es: "Dentro del tronco más viejo cuelgan cosas misteriosas.",
            ca: "Dins del tronc més vell hi pengen coses misterioses.",
            en: "Mysterious things hang inside the oldest trunk.",
            fr: "Des choses mystérieuses pendent à l'intérieur du plus vieux tronc.",
          },
          imageSeed: "forest-c2chest-hollow",
          icon: "park",
          narrative: {
            es: "{name} se asoma al interior del árbol hueco y ve una llavecita dorada colgando muy, muy arriba.",
            ca: "{name} treu el cap dins de l'arbre buit i veu una claueta daurada penjant molt, molt amunt.",
            en: "{name} peeks inside the hollow tree and sees a little golden key hanging high, high up.",
            fr: "{name} jette un œil à l'intérieur de l'arbre creux et voit une petite clé dorée suspendue tout, tout en haut.",
          },
          next: "c3_chest_c",
        },
      ],
    },
    c2_door: {
      id: "c2_door",
      chapter: 2,
      question: {
        es: "Al otro lado de la puerta, {name} descubre el Jardín de los Susurros... ¡pero sus colores se están apagando! Un cervatillo de luz le pide ayuda. ¿Por dónde empiezan?",
        ca: "A l'altra banda de la porta, {name} descobreix el Jardí dels Xiuxiueigs... però els seus colors s'estan apagant! Un cervatell de llum li demana ajuda. Per on comencen?",
        en: "On the other side of the door, {name} discovers the Whispering Garden... but its colours are fading! A little deer made of light asks for help. Where do they begin?",
        fr: "De l'autre côté de la porte, {name} découvre le Jardin des Murmures... mais ses couleurs s'éteignent ! Un petit faon de lumière lui demande de l'aide. Par où vont-ils commencer ?",
      },
      options: [
        {
          id: "rainbow-tree",
          title: {
            es: "El árbol arcoíris",
            ca: "L'arbre arc de Sant Martí",
            en: "The rainbow tree",
            fr: "L'arbre arc-en-ciel",
          },
          desc: {
            es: "Sus hojas de colores se han vuelto grises y tristes.",
            ca: "Les seves fulles de colors s'han tornat grises i tristes.",
            en: "Its colourful leaves have turned grey and sad.",
            fr: "Ses feuilles colorées sont devenues grises et tristes.",
          },
          imageSeed: "forest-c2door-tree",
          icon: "nature",
          narrative: {
            es: "{name} y el cervatillo de luz caminan hasta el gran árbol arcoíris, que tiene todas sus hojas grises y tristes.",
            ca: "{name} i el cervatell de llum caminen fins al gran arbre arc de Sant Martí, que té totes les fulles grises i tristes.",
            en: "{name} and the little light deer walk to the great rainbow tree, whose leaves have all turned grey and sad.",
            fr: "{name} et le petit faon de lumière marchent jusqu'au grand arbre arc-en-ciel, dont toutes les feuilles sont devenues grises et tristes.",
          },
          next: "c3_door_a",
        },
        {
          id: "fountain",
          title: {
            es: "La fuente de los colores",
            ca: "La font dels colors",
            en: "The fountain of colours",
            fr: "La fontaine des couleurs",
          },
          desc: {
            es: "La fuente que pinta el jardín ha dejado de manar.",
            ca: "La font que pinta el jardí ha deixat de rajar.",
            en: "The fountain that paints the garden has stopped flowing.",
            fr: "La fontaine qui peint le jardin ne coule plus.",
          },
          imageSeed: "forest-c2door-fountain",
          icon: "palette",
          narrative: {
            es: "{name} y el cervatillo de luz llegan a la fuente de los colores, que está seca y en silencio.",
            ca: "{name} i el cervatell de llum arriben a la font dels colors, que està seca i en silenci.",
            en: "{name} and the little light deer reach the fountain of colours, which sits dry and silent.",
            fr: "{name} et le petit faon de lumière arrivent à la fontaine des couleurs, qui est sèche et silencieuse.",
          },
          next: "c3_door_b",
        },
        {
          id: "star-pond",
          title: {
            es: "El estanque de las estrellas",
            ca: "L'estany de les estrelles",
            en: "The pond of stars",
            fr: "L'étang aux étoiles",
          },
          desc: {
            es: "Las estrellitas que iluminan el jardín se han quedado dormidas.",
            ca: "Les estrelletes que il·luminen el jardí s'han quedat adormides.",
            en: "The little stars that light the garden have fallen asleep.",
            fr: "Les petites étoiles qui éclairent le jardin se sont endormies.",
          },
          imageSeed: "forest-c2door-pond",
          icon: "star",
          narrative: {
            es: "{name} y el cervatillo de luz se asoman al estanque donde las estrellitas duermen en el fondo del agua.",
            ca: "{name} i el cervatell de llum s'aboquen a l'estany on les estrelletes dormen al fons de l'aigua.",
            en: "{name} and the little light deer peer into the pond where the tiny stars sleep at the bottom of the water.",
            fr: "{name} et le petit faon de lumière se penchent sur l'étang où les petites étoiles dorment au fond de l'eau.",
          },
          next: "c3_door_c",
        },
      ],
    },
    c3_dragon_a: {
      id: "c3_dragon_a",
      chapter: 3,
      question: {
        es: "Las luciérnagas son tímidas y esconden su luz cuando alguien se acerca. ¿Cómo las convence {name} para que regalen una chispita a Brasa?",
        ca: "Les cuques de llum són tímides i amaguen la seva llum quan algú s'hi acosta. Com les convenç {name} perquè regalin una espurneta a en Brasa?",
        en: "The fireflies are shy and hide their light when someone comes near. How does {name} convince them to gift Brasa a little spark?",
        fr: "Les lucioles sont timides et cachent leur lumière quand on s'approche. Comment {name} va les convaincre d'offrir une petite étincelle à Brasa ?",
      },
      options: [
        {
          id: "dance",
          title: {
            es: "Bailar con ellas",
            ca: "Ballar amb elles",
            en: "Dance with them",
            fr: "Danser avec elles",
          },
          desc: {
            es: "Un baile alegre les hace perder la vergüenza.",
            ca: "Un ball alegre els fa perdre la vergonya.",
            en: "A happy dance helps them forget their shyness.",
            fr: "Une danse joyeuse leur fait oublier leur timidité.",
          },
          imageSeed: "forest-c3dragona-dance",
          icon: "celebration",
          narrative: {
            es: "{name} baila entre las luciérnagas hasta que, encantadas, dejan caer una chispita brillante sobre la nariz de Brasa.",
            ca: "{name} balla entre les cuques de llum fins que, encantades, deixen caure una espurneta brillant sobre el nas d'en Brasa.",
            en: "{name} dances among the fireflies until, delighted, they drop a glowing little spark onto Brasa's nose.",
            fr: "{name} danse parmi les lucioles jusqu'à ce que, ravies, elles laissent tomber une petite étincelle brillante sur le nez de Brasa.",
          },
          next: "ending",
        },
        {
          id: "lullaby",
          title: {
            es: "Cantarles bajito",
            ca: "Cantar-los fluixet",
            en: "Sing to them softly",
            fr: "Leur chanter tout bas",
          },
          desc: {
            es: "Una nana dulce las invita a acercarse sin miedo.",
            ca: "Una cançó de bressol dolça les convida a acostar-se sense por.",
            en: "A sweet lullaby invites them closer without fear.",
            fr: "Une douce berceuse les invite à s'approcher sans peur.",
          },
          imageSeed: "forest-c3dragona-song",
          icon: "music_note",
          narrative: {
            es: "{name} canta una nana tan dulce que las luciérnagas se acercan volando y regalan a Brasa su chispa más brillante.",
            ca: "{name} canta una cançó de bressol tan dolça que les cuques de llum s'acosten volant i regalen a en Brasa la seva espurna més brillant.",
            en: "{name} sings a lullaby so sweet that the fireflies fly closer and gift Brasa their brightest spark.",
            fr: "{name} chante une berceuse si douce que les lucioles s'approchent en volant et offrent à Brasa leur étincelle la plus brillante.",
          },
          next: "ending",
        },
        {
          id: "berries",
          title: {
            es: "Compartir bayas dulces",
            ca: "Compartir baies dolces",
            en: "Share sweet berries",
            fr: "Partager des baies sucrées",
          },
          desc: {
            es: "Una merienda de bayas rojas siempre hace nuevos amigos.",
            ca: "Un berenar de baies vermelles sempre fa nous amics.",
            en: "A snack of red berries always makes new friends.",
            fr: "Un goûter de baies rouges, et voilà de nouveaux amis.",
          },
          imageSeed: "forest-c3dragona-berries",
          icon: "nutrition",
          narrative: {
            es: "{name} reparte bayas dulces entre las luciérnagas y ellas, agradecidas, encienden una chispita para Brasa.",
            ca: "{name} reparteix baies dolces entre les cuques de llum i elles, agraïdes, encenen una espurneta per a en Brasa.",
            en: "{name} shares sweet berries with the fireflies and they gratefully light a little spark for Brasa.",
            fr: "{name} partage des baies sucrées avec les lucioles et celles-ci, reconnaissantes, allument une petite étincelle pour Brasa.",
          },
          next: "ending",
        },
      ],
    },
    c3_dragon_b: {
      id: "c3_dragon_b",
      chapter: 3,
      question: {
        es: "La Flor del Sol está dormida con los pétalos cerrados y el rayito guardado dentro. ¿Cómo la despierta {name} con cuidado?",
        ca: "La Flor del Sol està adormida amb els pètals tancats i el raget guardat a dins. Com la desperta {name} amb cura?",
        en: "The Sun Flower is asleep with its petals closed and the sunbeam tucked inside. How does {name} wake it gently?",
        fr: "La Fleur du Soleil dort, les pétales fermés et le petit rayon caché à l'intérieur. Comment {name} la réveille tout en douceur ?",
      },
      options: [
        {
          id: "dew",
          title: {
            es: "Gotitas de rocío",
            ca: "Gotetes de rosada",
            en: "Drops of dew",
            fr: "Des gouttes de rosée",
          },
          desc: {
            es: "Un poquito de rocío fresco es el mejor despertador de las flores.",
            ca: "Una mica de rosada fresca és el millor despertador de les flors.",
            en: "A little fresh dew is the best alarm clock for flowers.",
            fr: "Un peu de rosée fraîche, le meilleur réveil pour les fleurs.",
          },
          imageSeed: "forest-c3dragonb-dew",
          icon: "water_drop",
          narrative: {
            es: "{name} deja caer gotitas de rocío fresco sobre la Flor del Sol, que despierta bostezando y regala su rayito a Brasa.",
            ca: "{name} deixa caure gotetes de rosada fresca sobre la Flor del Sol, que es desperta badallant i regala el seu raget a en Brasa.",
            en: "{name} sprinkles fresh dewdrops onto the Sun Flower, which wakes with a yawn and gifts its sunbeam to Brasa.",
            fr: "{name} fait tomber des gouttes de rosée fraîche sur la Fleur du Soleil, qui se réveille en bâillant et offre son petit rayon à Brasa.",
          },
          next: "ending",
        },
        {
          id: "sun-song",
          title: {
            es: "La canción del sol",
            ca: "La cançó del sol",
            en: "The song of the sun",
            fr: "La chanson du soleil",
          },
          desc: {
            es: "Dicen que esta flor solo despierta si oye cantar al amanecer.",
            ca: "Diuen que aquesta flor només es desperta si sent cantar a l'alba.",
            en: "They say this flower only wakes if it hears a sunrise song.",
            fr: "On dit que cette fleur ne se réveille que si elle entend la chanson de l'aube.",
          },
          imageSeed: "forest-c3dragonb-song",
          icon: "wb_sunny",
          narrative: {
            es: "{name} canta la canción del amanecer y la Flor del Sol abre sus pétalos como un sol pequeñito, entregando su rayito a Brasa.",
            ca: "{name} canta la cançó de l'alba i la Flor del Sol obre els pètals com un sol petitó, lliurant el seu raget a en Brasa.",
            en: "{name} sings the sunrise song and the Sun Flower opens its petals like a tiny sun, handing its sunbeam to Brasa.",
            fr: "{name} chante la chanson de l'aube et la Fleur du Soleil ouvre ses pétales comme un tout petit soleil, offrant son rayon à Brasa.",
          },
          next: "ending",
        },
        {
          id: "tickle",
          title: {
            es: "Cosquillas con una hoja",
            ca: "Pessigolles amb una fulla",
            en: "Tickles with a leaf",
            fr: "Des chatouilles avec une feuille",
          },
          desc: {
            es: "Una caricia suave en el tallo y... ¡a reír!",
            ca: "Una carícia suau a la tija i... a riure!",
            en: "A soft tickle on the stem and... giggles!",
            fr: "Une douce caresse sur la tige et... fou rire !",
          },
          imageSeed: "forest-c3dragonb-leaf",
          icon: "eco",
          narrative: {
            es: "{name} hace cosquillas en el tallo de la Flor del Sol con una hoja suave y la flor despierta entre risas, regalando su rayito a Brasa.",
            ca: "{name} fa pessigolles a la tija de la Flor del Sol amb una fulla suau i la flor es desperta rient, regalant el seu raget a en Brasa.",
            en: "{name} tickles the Sun Flower's stem with a soft leaf and the flower wakes up giggling, gifting its sunbeam to Brasa.",
            fr: "{name} chatouille la tige de la Fleur du Soleil avec une feuille douce et la fleur se réveille en riant, offrant son petit rayon à Brasa.",
          },
          next: "ending",
        },
      ],
    },
    c3_dragon_c: {
      id: "c3_dragon_c",
      chapter: 3,
      question: {
        es: "En la cueva hay cientos de cristales, pero solo uno guarda la chispa calentita que Brasa necesita. ¿Cómo lo encuentra {name}?",
        ca: "A la cova hi ha centenars de cristalls, però només un guarda l'espurna calentona que en Brasa necessita. Com el troba {name}?",
        en: "There are hundreds of crystals in the cave, but only one holds the warm spark Brasa needs. How does {name} find it?",
        fr: "Dans la grotte, il y a des centaines de cristaux, mais un seul garde l'étincelle chaude dont Brasa a besoin. Comment {name} le trouve ?",
      },
      options: [
        {
          id: "listen",
          title: {
            es: "Escuchar su musiquita",
            ca: "Escoltar la seva musiqueta",
            en: "Listen for its tune",
            fr: "Écouter sa petite musique",
          },
          desc: {
            es: "El cristal de fuego canturrea bajito como una chimenea feliz.",
            ca: "El cristall de foc cantusseja fluixet com una llar de foc feliç.",
            en: "The fire crystal hums softly like a happy fireplace.",
            fr: "Le cristal de feu fredonne tout bas comme une cheminée joyeuse.",
          },
          imageSeed: "forest-c3dragonc-listen",
          icon: "hearing",
          narrative: {
            es: "{name} cierra los ojos, escucha un canturreo calentito y encuentra el cristal de fuego escondido tras una roca.",
            ca: "{name} tanca els ulls, escolta un cantusseig calentó i troba el cristall de foc amagat darrere una roca.",
            en: "{name} closes their eyes, hears a warm little hum and finds the fire crystal hidden behind a rock.",
            fr: "{name} ferme les yeux, entend un petit fredonnement tout chaud et trouve le cristal de feu caché derrière un rocher.",
          },
          next: "ending",
        },
        {
          id: "warmth",
          title: {
            es: "Seguir el calorcito",
            ca: "Seguir l'escalforeta",
            en: "Follow the warmth",
            fr: "Suivre la chaleur",
          },
          desc: {
            es: "Con las manos abiertas se nota qué cristal está más calentito.",
            ca: "Amb les mans obertes es nota quin cristall està més calentó.",
            en: "With open hands you can feel which crystal is warmest.",
            fr: "Mains ouvertes, on sent quel cristal est le plus chaud.",
          },
          imageSeed: "forest-c3dragonc-warmth",
          icon: "volunteer_activism",
          narrative: {
            es: "{name} pasa las manos despacio cerca de los cristales y siente un calorcito dulce que guía sus manos hasta el cristal de fuego.",
            ca: "{name} passa les mans a poc a poc prop dels cristalls i sent una escalforeta dolça que guia les seves mans fins al cristall de foc.",
            en: "{name} moves their hands slowly past the crystals and feels a sweet warmth guiding them to the fire crystal.",
            fr: "{name} passe lentement les mains près des cristaux et sent une douce chaleur qui guide ses mains jusqu'au cristal de feu.",
          },
          next: "ending",
        },
        {
          id: "echo",
          title: {
            es: "Preguntar al eco",
            ca: "Preguntar a l'eco",
            en: "Ask the echo",
            fr: "Demander à l'écho",
          },
          desc: {
            es: "El eco de la cueva conoce cada rincón y cada cristal.",
            ca: "L'eco de la cova coneix cada racó i cada cristall.",
            en: "The cave's echo knows every corner and every crystal.",
            fr: "L'écho de la grotte connaît chaque recoin et chaque cristal.",
          },
          imageSeed: "forest-c3dragonc-echo",
          icon: "graphic_eq",
          narrative: {
            es: "{name} pregunta en voz alta y el eco de la cueva repite '¡aquí, aquí!' hasta señalar el cristal de fuego.",
            ca: "{name} pregunta en veu alta i l'eco de la cova repeteix 'aquí, aquí!' fins a assenyalar el cristall de foc.",
            en: "{name} asks out loud and the cave's echo repeats 'here, here!' until it points to the fire crystal.",
            fr: "{name} demande à voix haute et l'écho de la grotte répète « ici, ici ! » jusqu'à montrer le cristal de feu.",
          },
          next: "ending",
        },
      ],
    },
    c3_chest_a: {
      id: "c3_chest_a",
      chapter: 3,
      question: {
        es: "¡Las ardillas tienen la llave de flor! Pero les encanta y no quieren dársela así como así. ¿Qué hace {name} para conseguirla?",
        ca: "Els esquirols tenen la clau de flor! Però els encanta i no la volen donar així com així. Què fa {name} per aconseguir-la?",
        en: "The squirrels have the flower key! But they love it and won't just hand it over. What does {name} do to get it?",
        fr: "Les écureuils ont la clé-fleur ! Mais ils l'adorent et ne veulent pas la donner comme ça. Que fait {name} pour l'obtenir ?",
      },
      options: [
        {
          id: "trade",
          title: {
            es: "Cambiarla por avellanas",
            ca: "Canviar-la per avellanes",
            en: "Trade it for hazelnuts",
            fr: "L'échanger contre des noisettes",
          },
          desc: {
            es: "Un puñado de avellanas doradas es un trato justo.",
            ca: "Un grapat d'avellanes daurades és un tracte just.",
            en: "A handful of golden hazelnuts is a fair trade.",
            fr: "Une poignée de noisettes dorées, voilà un bon échange.",
          },
          imageSeed: "forest-c3chesta-trade",
          icon: "swap_horiz",
          narrative: {
            es: "{name} recoge un puñado de avellanas doradas y las cambia con las ardillas por la llave de flor.",
            ca: "{name} recull un grapat d'avellanes daurades i les canvia amb els esquirols per la clau de flor.",
            en: "{name} gathers a handful of golden hazelnuts and trades them with the squirrels for the flower key.",
            fr: "{name} ramasse une poignée de noisettes dorées et les échange avec les écureuils contre la clé-fleur.",
          },
          next: "ending",
        },
        {
          id: "hide-and-seek",
          title: {
            es: "Jugar al escondite",
            ca: "Jugar a fet i amagar",
            en: "Play hide-and-seek",
            fr: "Jouer à cache-cache",
          },
          desc: {
            es: "Si {name} gana, la llave será el premio.",
            ca: "Si {name} guanya, la clau serà el premi.",
            en: "If {name} wins, the key is the prize.",
            fr: "Si {name} gagne, la clé sera le prix.",
          },
          imageSeed: "forest-c3chesta-hide",
          icon: "visibility_off",
          narrative: {
            es: "{name} juega al escondite con las ardillas, las encuentra a todas detrás de las setas y gana la llave de flor.",
            ca: "{name} juga a fet i amagar amb els esquirols, els troba tots darrere dels bolets i guanya la clau de flor.",
            en: "{name} plays hide-and-seek with the squirrels, finds them all behind the mushrooms and wins the flower key.",
            fr: "{name} joue à cache-cache avec les écureuils, les trouve tous derrière les champignons et gagne la clé-fleur.",
          },
          next: "ending",
        },
        {
          id: "pantry",
          title: {
            es: "Ordenar su despensa",
            ca: "Endreçar el seu rebost",
            en: "Tidy their pantry",
            fr: "Ranger leur garde-manger",
          },
          desc: {
            es: "Su despensa de otoño está patas arriba y necesitan ayuda.",
            ca: "El seu rebost de tardor està potes enlaire i necessiten ajuda.",
            en: "Their autumn pantry is upside down and they need help.",
            fr: "Leur garde-manger d'automne est sens dessus dessous, ils ont besoin d'aide.",
          },
          imageSeed: "forest-c3chesta-pantry",
          icon: "inventory_2",
          narrative: {
            es: "{name} ayuda a las ardillas a ordenar su despensa de bellotas y, agradecidas, le regalan la llave de flor.",
            ca: "{name} ajuda els esquirols a endreçar el seu rebost de glans i, agraïts, li regalen la clau de flor.",
            en: "{name} helps the squirrels tidy their acorn pantry and, grateful, they gift the flower key.",
            fr: "{name} aide les écureuils à ranger leur garde-manger de glands et, reconnaissants, ils lui offrent la clé-fleur.",
          },
          next: "ending",
        },
      ],
    },
    c3_chest_b: {
      id: "c3_chest_b",
      chapter: 3,
      question: {
        es: "¡Es la llave de flor! Pero está en lo más hondo del arroyo y el agua va deprisa. ¿Cómo la consigue {name}?",
        ca: "És la clau de flor! Però és al fons de tot del rierol i l'aigua baixa de pressa. Com l'aconsegueix {name}?",
        en: "It's the flower key! But it lies at the very bottom of the stream and the water runs fast. How does {name} get it?",
        fr: "C'est la clé-fleur ! Mais elle est tout au fond du ruisseau et l'eau file vite. Comment {name} va la récupérer ?",
      },
      options: [
        {
          id: "stones",
          title: {
            es: "Un caminito de piedras",
            ca: "Un caminet de pedres",
            en: "A little stone path",
            fr: "Un petit chemin de pierres",
          },
          desc: {
            es: "Piedra a piedra se puede llegar hasta el centro del arroyo.",
            ca: "Pedra a pedra es pot arribar fins al centre del rierol.",
            en: "Stone by stone you can reach the middle of the stream.",
            fr: "Pierre après pierre, on peut atteindre le milieu du ruisseau.",
          },
          imageSeed: "forest-c3chestb-stones",
          icon: "construction",
          narrative: {
            es: "{name} coloca piedras planas una a una, llega al centro del arroyo y alcanza la llave de flor con la mano.",
            ca: "{name} col·loca pedres planes una a una, arriba al centre del rierol i agafa la clau de flor amb la mà.",
            en: "{name} places flat stones one by one, reaches the middle of the stream and grabs the flower key.",
            fr: "{name} pose des pierres plates une à une, atteint le milieu du ruisseau et attrape la clé-fleur avec la main.",
          },
          next: "ending",
        },
        {
          id: "frog",
          title: {
            es: "Pedir ayuda a la rana",
            ca: "Demanar ajuda a la granota",
            en: "Ask the frog for help",
            fr: "Demander de l'aide à la grenouille",
          },
          desc: {
            es: "La rana del arroyo es la mejor buceadora del bosque.",
            ca: "La granota del rierol és la millor bussejadora del bosc.",
            en: "The stream frog is the best diver in the forest.",
            fr: "La grenouille du ruisseau est la meilleure plongeuse de la forêt.",
          },
          imageSeed: "forest-c3chestb-frog",
          icon: "mood",
          narrative: {
            es: "{name} pide ayuda a la rana del arroyo, que bucea de un salto y sube la llave de flor entre sus patitas.",
            ca: "{name} demana ajuda a la granota del rierol, que busseja d'un salt i puja la clau de flor entre les seves potetes.",
            en: "{name} asks the stream frog for help, and it dives in one hop and brings up the flower key in its little feet.",
            fr: "{name} demande de l'aide à la grenouille du ruisseau, qui plonge d'un bond et remonte la clé-fleur entre ses petites pattes.",
          },
          next: "ending",
        },
        {
          id: "flower-rod",
          title: {
            es: "Una caña de flor",
            ca: "Una canya de flor",
            en: "A flower fishing rod",
            fr: "Une canne à pêche en fleur",
          },
          desc: {
            es: "Con una ramita y un tallo largo se pesca casi cualquier cosa.",
            ca: "Amb una branqueta i una tija llarga es pesca gairebé qualsevol cosa.",
            en: "With a twig and a long stem you can fish out almost anything.",
            fr: "Avec une brindille et une longue tige, on peut presque tout pêcher.",
          },
          imageSeed: "forest-c3chestb-rod",
          icon: "phishing",
          narrative: {
            es: "{name} fabrica una cañita con una rama y un tallo de flor y pesca la llave dorada con muchísimo cuidado.",
            ca: "{name} fabrica una canyeta amb una branca i una tija de flor i pesca la clau daurada amb moltíssima cura.",
            en: "{name} makes a little rod from a branch and a flower stem and fishes out the golden key very, very carefully.",
            fr: "{name} fabrique une petite canne avec une branche et une tige de fleur et pêche la clé dorée avec beaucoup de précaution.",
          },
          next: "ending",
        },
      ],
    },
    c3_chest_c: {
      id: "c3_chest_c",
      chapter: 3,
      question: {
        es: "La llave de flor cuelga de una ramita en lo alto del árbol hueco. ¿Cómo llega {name} hasta allí arriba?",
        ca: "La clau de flor penja d'una branqueta a dalt de tot de l'arbre buit. Com hi arriba {name}, allà dalt?",
        en: "The flower key hangs from a twig at the very top of the hollow tree. How does {name} get all the way up there?",
        fr: "La clé-fleur pend à une brindille tout en haut de l'arbre creux. Comment {name} va monter jusque là-haut ?",
      },
      options: [
        {
          id: "climb",
          title: {
            es: "Trepar con cuidado",
            ca: "Enfilar-se amb cura",
            en: "Climb up carefully",
            fr: "Grimper prudemment",
          },
          desc: {
            es: "Las cortezas del árbol forman escaloncitos perfectos.",
            ca: "Les escorces de l'arbre formen escalonets perfectes.",
            en: "The tree's bark makes perfect little steps.",
            fr: "L'écorce de l'arbre forme de parfaites petites marches.",
          },
          imageSeed: "forest-c3chestc-climb",
          icon: "hiking",
          narrative: {
            es: "{name} trepa despacito apoyándose en la corteza, llega a la ramita más alta y descuelga la llave de flor.",
            ca: "{name} s'enfila a poc a poc recolzant-se a l'escorça, arriba a la branqueta més alta i despenja la clau de flor.",
            en: "{name} climbs slowly up the bark, reaches the highest twig and unhooks the flower key.",
            fr: "{name} grimpe doucement en s'appuyant sur l'écorce, atteint la plus haute brindille et décroche la clé-fleur.",
          },
          next: "ending",
        },
        {
          id: "woodpecker",
          title: {
            es: "Llamar al pájaro carpintero",
            ca: "Cridar el picot",
            en: "Call the woodpecker",
            fr: "Appeler le pic-vert",
          },
          desc: {
            es: "Nadie conoce este árbol mejor que él.",
            ca: "Ningú coneix aquest arbre millor que ell.",
            en: "Nobody knows this tree better than he does.",
            fr: "Personne ne connaît cet arbre mieux que lui.",
          },
          imageSeed: "forest-c3chestc-woodpecker",
          icon: "raven",
          narrative: {
            es: "{name} llama al pájaro carpintero con tres toques suaves en el tronco y él baja volando la llave de flor en su pico.",
            ca: "{name} crida el picot amb tres tocs suaus al tronc i ell baixa volant la clau de flor al seu bec.",
            en: "{name} calls the woodpecker with three soft knocks on the trunk and he flies down with the flower key in his beak.",
            fr: "{name} appelle le pic-vert avec trois petits coups sur le tronc et il descend en volant avec la clé-fleur dans son bec.",
          },
          next: "ending",
        },
        {
          id: "mushroom-stairs",
          title: {
            es: "Una escalera de setas",
            ca: "Una escala de bolets",
            en: "A mushroom staircase",
            fr: "Un escalier de champignons",
          },
          desc: {
            es: "Las setas del tronco crecen en espiral hasta arriba.",
            ca: "Els bolets del tronc creixen en espiral fins a dalt.",
            en: "The mushrooms on the trunk grow in a spiral to the top.",
            fr: "Les champignons du tronc poussent en spirale jusqu'en haut.",
          },
          imageSeed: "forest-c3chestc-stairs",
          icon: "stairs",
          narrative: {
            es: "{name} sube saltando de seta en seta por la escalera en espiral del tronco hasta alcanzar la llave de flor.",
            ca: "{name} puja saltant de bolet en bolet per l'escala en espiral del tronc fins a agafar la clau de flor.",
            en: "{name} hops from mushroom to mushroom up the spiral staircase of the trunk until reaching the flower key.",
            fr: "{name} monte en sautant de champignon en champignon le long de l'escalier en spirale du tronc jusqu'à attraper la clé-fleur.",
          },
          next: "ending",
        },
      ],
    },
    c3_door_a: {
      id: "c3_door_a",
      chapter: 3,
      question: {
        es: "El árbol arcoíris necesita recordar sus colores para que sus hojas brillen otra vez. ¿Cómo le ayuda {name}?",
        ca: "L'arbre arc de Sant Martí necessita recordar els seus colors perquè les seves fulles brillin una altra vegada. Com l'ajuda {name}?",
        en: "The rainbow tree needs to remember its colours so its leaves can shine again. How does {name} help?",
        fr: "L'arbre arc-en-ciel a besoin de se rappeler ses couleurs pour que ses feuilles brillent à nouveau. Comment {name} peut l'aider ?",
      },
      options: [
        {
          id: "petal-paint",
          title: {
            es: "Pintar con pétalos",
            ca: "Pintar amb pètals",
            en: "Paint with petals",
            fr: "Peindre avec des pétales",
          },
          desc: {
            es: "Los pétalos del jardín guardan todos los colores del mundo.",
            ca: "Els pètals del jardí guarden tots els colors del món.",
            en: "The garden's petals hold every colour in the world.",
            fr: "Les pétales du jardin gardent toutes les couleurs du monde.",
          },
          imageSeed: "forest-c3doora-petals",
          icon: "brush",
          narrative: {
            es: "{name} mezcla pétalos de flores para hacer pintura y colorea las hojas grises hasta que el árbol entero brilla de nuevo.",
            ca: "{name} barreja pètals de flors per fer pintura i acoloreix les fulles grises fins que l'arbre sencer torna a brillar.",
            en: "{name} mixes flower petals into paint and colours the grey leaves until the whole tree shines again.",
            fr: "{name} mélange des pétales de fleurs pour faire de la peinture et colorie les feuilles grises jusqu'à ce que l'arbre tout entier brille à nouveau.",
          },
          next: "ending",
        },
        {
          id: "rainbow-story",
          title: {
            es: "Contarle los colores",
            ca: "Explicar-li els colors",
            en: "Tell it about colours",
            fr: "Lui raconter les couleurs",
          },
          desc: {
            es: "Un abrazo y una historia sobre arcoíris pueden despertar recuerdos.",
            ca: "Una abraçada i una història sobre arcs de Sant Martí poden despertar records.",
            en: "A hug and a story about rainbows can wake old memories.",
            fr: "Un câlin et une histoire d'arc-en-ciel peuvent réveiller les souvenirs.",
          },
          imageSeed: "forest-c3doora-hug",
          icon: "favorite",
          narrative: {
            es: "{name} abraza el tronco y le cuenta cómo brillan los arcoíris, y el árbol recuerda sus colores hoja a hoja.",
            ca: "{name} abraça el tronc i li explica com brillen els arcs de Sant Martí, i l'arbre recorda els seus colors fulla a fulla.",
            en: "{name} hugs the trunk and tells it how rainbows shine, and the tree remembers its colours leaf by leaf.",
            fr: "{name} serre le tronc dans ses bras et lui raconte comme brillent les arcs-en-ciel, et l'arbre retrouve ses couleurs feuille après feuille.",
          },
          next: "ending",
        },
        {
          id: "seven-dew",
          title: {
            es: "El rocío de siete flores",
            ca: "La rosada de set flors",
            en: "The seven-flower dew",
            fr: "La rosée des sept fleurs",
          },
          desc: {
            es: "Una gota de cada flor de color hace una medicina mágica.",
            ca: "Una gota de cada flor de color fa una medecina màgica.",
            en: "One drop from each coloured flower makes a magic potion.",
            fr: "Une goutte de chaque fleur colorée fait une potion magique.",
          },
          imageSeed: "forest-c3doora-dew",
          icon: "filter_vintage",
          narrative: {
            es: "{name} recoge una gota de rocío de siete flores distintas y riega las raíces del árbol, que florece en mil colores.",
            ca: "{name} recull una gota de rosada de set flors diferents i rega les arrels de l'arbre, que floreix en mil colors.",
            en: "{name} collects a dewdrop from seven different flowers and waters the tree's roots, and it blooms in a thousand colours.",
            fr: "{name} recueille une goutte de rosée sur sept fleurs différentes et arrose les racines de l'arbre, qui fleurit de mille couleurs.",
          },
          next: "ending",
        },
      ],
    },
    c3_door_b: {
      id: "c3_door_b",
      chapter: 3,
      question: {
        es: "La fuente de los colores está tapada y ni una gotita puede salir. ¿Cómo la ayuda {name} a manar de nuevo?",
        ca: "La font dels colors està tapada i ni una goteta no pot sortir. Com l'ajuda {name} a rajar de nou?",
        en: "The fountain of colours is blocked and not a single drop can come out. How does {name} help it flow again?",
        fr: "La fontaine des couleurs est bouchée et pas une seule goutte ne peut sortir. Comment {name} l'aide à couler de nouveau ?",
      },
      options: [
        {
          id: "clear-leaves",
          title: {
            es: "Apartar las hojas",
            ca: "Apartar les fulles",
            en: "Clear the leaves",
            fr: "Enlever les feuilles",
          },
          desc: {
            es: "Un montón de hojas de otoño tapa el manantial.",
            ca: "Un munt de fulles de tardor tapa la deu.",
            en: "A pile of autumn leaves is covering the spring.",
            fr: "Un tas de feuilles d'automne recouvre la source.",
          },
          imageSeed: "forest-c3doorb-leaves",
          icon: "cleaning_services",
          narrative: {
            es: "{name} aparta con cuidado las hojas de otoño que tapaban el manantial y la fuente vuelve a manar agua de colores.",
            ca: "{name} aparta amb cura les fulles de tardor que tapaven la deu i la font torna a rajar aigua de colors.",
            en: "{name} carefully clears away the autumn leaves covering the spring and the fountain flows with coloured water again.",
            fr: "{name} enlève avec soin les feuilles d'automne qui recouvraient la source et la fontaine fait à nouveau couler une eau colorée.",
          },
          next: "ending",
        },
        {
          id: "rain-cloud",
          title: {
            es: "Invitar a la nube",
            ca: "Convidar el núvol",
            en: "Invite the cloud",
            fr: "Inviter le nuage",
          },
          desc: {
            es: "Una nubecita amable puede llenar la fuente con su lluvia.",
            ca: "Un nuvolet amable pot omplir la font amb la seva pluja.",
            en: "A friendly little cloud can fill the fountain with its rain.",
            fr: "Un gentil petit nuage peut remplir la fontaine avec sa pluie.",
          },
          imageSeed: "forest-c3doorb-cloud",
          icon: "rainy",
          narrative: {
            es: "{name} invita a una nubecita amable a llover sobre la fuente y el agua de colores empieza a brotar otra vez.",
            ca: "{name} convida un nuvolet amable a ploure sobre la font i l'aigua de colors comença a brollar una altra vegada.",
            en: "{name} invites a friendly little cloud to rain over the fountain and the coloured water starts to flow once more.",
            fr: "{name} invite un gentil petit nuage à pleuvoir sur la fontaine et l'eau colorée se remet à jaillir.",
          },
          next: "ending",
        },
        {
          id: "water-song",
          title: {
            es: "La canción del agua",
            ca: "La cançó de l'aigua",
            en: "The water song",
            fr: "La chanson de l'eau",
          },
          desc: {
            es: "El cervatillo conoce la melodía que el agua adora bailar.",
            ca: "El cervatell coneix la melodia que l'aigua adora ballar.",
            en: "The little deer knows the tune the water loves to dance to.",
            fr: "Le faon connaît la mélodie que l'eau adore danser.",
          },
          imageSeed: "forest-c3doorb-song",
          icon: "queue_music",
          narrative: {
            es: "{name} y el cervatillo cantan la canción del agua y la fuente despierta bailando con chorritos de todos los colores.",
            ca: "{name} i el cervatell canten la cançó de l'aigua i la font es desperta ballant amb rajolins de tots els colors.",
            en: "{name} and the little deer sing the water song and the fountain wakes up dancing with little jets of every colour.",
            fr: "{name} et le faon chantent la chanson de l'eau et la fontaine se réveille en dansant avec des jets de toutes les couleurs.",
          },
          next: "ending",
        },
      ],
    },
    c3_door_c: {
      id: "c3_door_c",
      chapter: 3,
      question: {
        es: "Las estrellitas duermen tan profundamente en el fondo del estanque que no oyen nada. ¿Cómo las despierta {name} sin asustarlas?",
        ca: "Les estrelletes dormen tan profundament al fons de l'estany que no senten res. Com les desperta {name} sense espantar-les?",
        en: "The little stars are sleeping so deeply at the bottom of the pond that they can't hear a thing. How does {name} wake them without startling them?",
        fr: "Les petites étoiles dorment si profondément au fond de l'étang qu'elles n'entendent rien. Comment {name} les réveille sans les effrayer ?",
      },
      options: [
        {
          id: "petal-ripples",
          title: {
            es: "Hacer círculos con pétalos",
            ca: "Fer cercles amb pètals",
            en: "Make ripples with petals",
            fr: "Faire des ronds avec des pétales",
          },
          desc: {
            es: "Los pétalos dibujan ondas suaves que mecen el agua.",
            ca: "Els pètals dibuixen ones suaus que bressolen l'aigua.",
            en: "The petals draw gentle ripples that rock the water.",
            fr: "Les pétales dessinent de douces vagues qui bercent l'eau.",
          },
          imageSeed: "forest-c3doorc-petals",
          icon: "waves",
          narrative: {
            es: "{name} deja caer pétalos sobre el estanque y las ondas suaves hacen cosquillas a las estrellitas, que suben brillando a la superficie.",
            ca: "{name} deixa caure pètals sobre l'estany i les ones suaus fan pessigolles a les estrelletes, que pugen brillant a la superfície.",
            en: "{name} drops petals onto the pond and the gentle ripples tickle the little stars, who float up to the surface shining.",
            fr: "{name} laisse tomber des pétales sur l'étang et les douces vagues chatouillent les petites étoiles, qui remontent à la surface en brillant.",
          },
          next: "ending",
        },
        {
          id: "whistle",
          title: {
            es: "Silbar como un ruiseñor",
            ca: "Xiular com un rossinyol",
            en: "Whistle like a nightingale",
            fr: "Siffler comme un rossignol",
          },
          desc: {
            es: "Es el sonido favorito de las estrellas del jardín.",
            ca: "És el so preferit de les estrelles del jardí.",
            en: "It is the garden stars' favourite sound.",
            fr: "C'est le son préféré des étoiles du jardin.",
          },
          imageSeed: "forest-c3doorc-whistle",
          icon: "music_note",
          narrative: {
            es: "{name} silba bajito como un ruiseñor y las estrellitas abren los ojos y suben bailando hasta la superficie.",
            ca: "{name} xiula fluixet com un rossinyol i les estrelletes obren els ulls i pugen ballant fins a la superfície.",
            en: "{name} whistles softly like a nightingale and the little stars open their eyes and dance up to the surface.",
            fr: "{name} siffle doucement comme un rossignol et les petites étoiles ouvrent les yeux et remontent à la surface en dansant.",
          },
          next: "ending",
        },
        {
          id: "moonbeam",
          title: {
            es: "Atrapar un rayo de luna",
            ca: "Atrapar un raig de lluna",
            en: "Catch a moonbeam",
            fr: "Attraper un rayon de lune",
          },
          desc: {
            es: "Su luz plateada llega hasta el fondo del estanque.",
            ca: "La seva llum platejada arriba fins al fons de l'estany.",
            en: "Its silver light reaches all the way to the bottom of the pond.",
            fr: "Sa lumière argentée descend jusqu'au fond de l'étang.",
          },
          imageSeed: "forest-c3doorc-moonbeam",
          icon: "nightlight",
          narrative: {
            es: "{name} atrapa un rayo de luna con las manos y lo sumerge despacito en el estanque, y las estrellitas despiertan llenando el jardín de luz.",
            ca: "{name} atrapa un raig de lluna amb les mans i el submergeix a poc a poc a l'estany, i les estrelletes es desperten omplint el jardí de llum.",
            en: "{name} catches a moonbeam with both hands and dips it gently into the pond, and the little stars wake up filling the garden with light.",
            fr: "{name} attrape un rayon de lune avec les mains et le plonge doucement dans l'étang, et les petites étoiles se réveillent en remplissant le jardin de lumière.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "", en: "", fr: "" },
      options: [],
    },
  },
};
