import type { StoryTree } from "./types";

// Branching story tree for the "inventor" template (La Fábrica de Inventos).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es source of truth + ca/en/fr). {name} = child's name.

export const inventorTree: StoryTree = {
  templateId: "inventor",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} empuja la gran puerta de la Fábrica de Inventos, donde las máquinas más asombrosas esperan a que alguien las termine. Entre engranajes y planos asoman tres descubrimientos. ¿Cuál explora primero?",
        ca: "{name} empeny la gran porta de la Fàbrica d'Invents, on les màquines més sorprenents esperen que algú les acabi. Entre engranatges i plànols apareixen tres descobriments. Quin explora primer?",
        en: "{name} pushes open the big door of the Invention Factory, where the most amazing machines wait for someone to finish them. Between gears and blueprints, three discoveries peek out. Which one to explore first?",
        fr: "{name} pousse la grande porte de la Fabrique d'Inventions, où les machines les plus étonnantes attendent que quelqu'un les termine. Entre les engrenages et les plans, trois découvertes apparaissent. Laquelle explorer en premier ?",
      },
      options: [
        {
          id: "robot",
          title: {
            es: "El robot pequeñito",
            ca: "El robot petitó",
            en: "The little robot",
            fr: "Le petit robot",
          },
          desc: {
            es: "Un robotito de hojalata parpadea solito sobre la mesa de trabajo.",
            ca: "Un robotet de llauna parpelleja tot sol sobre la taula de treball.",
            en: "A little tin robot blinks all alone on the workbench.",
            fr: "Un petit robot en fer-blanc clignote tout seul sur l'établi.",
          },
          imageSeed: "inventor-c1-robot",
          icon: "smart_toy",
          narrative: {
            es: "{name} se acerca despacito a un robotito de hojalata que parpadea sobre la mesa de trabajo, con una bombillita en el pecho que apenas brilla.",
            ca: "{name} s'acosta a poc a poc a un robotet de llauna que parpelleja sobre la taula de treball, amb una bombeteta al pit que gairebé no brilla.",
            en: "{name} tiptoes up to a little tin robot blinking on the workbench, with a tiny bulb on its chest that barely glows.",
            fr: "{name} s'approche tout doucement d'un petit robot en fer-blanc qui clignote sur l'établi, avec une petite ampoule sur la poitrine qui brille à peine.",
          },
          next: "c2_robot",
        },
        {
          id: "machine",
          title: {
            es: "La máquina voladora",
            ca: "La màquina voladora",
            en: "The flying machine",
            fr: "La machine volante",
          },
          desc: {
            es: "Una máquina hecha de paraguas y engranajes cuelga del techo, casi terminada.",
            ca: "Una màquina feta de paraigües i engranatges penja del sostre, gairebé acabada.",
            en: "A machine made of umbrellas and gears hangs from the ceiling, almost finished.",
            fr: "Une machine faite de parapluies et d'engrenages pend du plafond, presque terminée.",
          },
          imageSeed: "inventor-c1-machine",
          icon: "flight",
          narrative: {
            es: "{name} descubre una máquina voladora hecha de paraguas y engranajes que cuelga del techo y a la que solo le falta una pieza.",
            ca: "{name} descobreix una màquina voladora feta de paraigües i engranatges que penja del sostre i a la qual només li falta una peça.",
            en: "{name} discovers a flying machine made of umbrellas and gears hanging from the ceiling, missing just one piece.",
            fr: "{name} découvre une machine volante faite de parapluies et d'engrenages suspendue au plafond, à laquelle il ne manque qu'une seule pièce.",
          },
          next: "c2_machine",
        },
        {
          id: "attic",
          title: {
            es: "El desván de los inventos",
            ca: "Les golfes dels invents",
            en: "The invention attic",
            fr: "Le grenier aux inventions",
          },
          desc: {
            es: "Tras una puertecita con pestillo dorado duermen máquinas cubiertas de polvo.",
            ca: "Darrere una porteta amb baldó daurat dormen màquines cobertes de pols.",
            en: "Behind a little door with a golden latch, dusty machines lie asleep.",
            fr: "Derrière une petite porte au loquet doré dorment des machines couvertes de poussière.",
          },
          imageSeed: "inventor-c1-attic",
          icon: "door_open",
          narrative: {
            es: "{name} abre una puertecita con pestillo dorado y encuentra un desván donde duermen inventos olvidados cubiertos de polvo.",
            ca: "{name} obre una porteta amb baldó daurat i troba unes golfes on dormen invents oblidats coberts de pols.",
            en: "{name} opens a little door with a golden latch and finds an attic where forgotten inventions sleep under a blanket of dust.",
            fr: "{name} ouvre une petite porte au loquet doré et découvre un grenier où dorment des inventions oubliées couvertes de poussière.",
          },
          next: "c2_attic",
        },
      ],
    },
    c2_robot: {
      id: "c2_robot",
      chapter: 2,
      question: {
        es: "El robotito se enciende un poquito y dice que se llama Tuerca. Está triste: una pieza de su corazón de maquinita se ha gastado y esta noche es la Gran Feria de Inventos. ¿Dónde buscan {name} y Tuerca una pieza nueva?",
        ca: "El robotet s'encén una miqueta i diu que es diu Tuerca. Està trist: una peça del seu cor de maquineta s'ha gastat i aquesta nit és la Gran Fira d'Invents. On busquen {name} i en Tuerca una peça nova?",
        en: "The little robot flickers on and says his name is Tuerca. He is sad: a piece of his clockwork heart has worn out and tonight is the Great Invention Fair. Where do {name} and Tuerca look for a new piece?",
        fr: "Le petit robot s'allume faiblement et dit qu'il s'appelle Tuerca. Il est triste : une pièce de son cœur mécanique s'est usée et ce soir, c'est la Grande Foire aux Inventions. Où {name} et Tuerca cherchent-ils une pièce neuve ?",
      },
      options: [
        {
          id: "gear-wall",
          title: {
            es: "La pared de los mil engranajes",
            ca: "La paret dels mil engranatges",
            en: "The wall of a thousand gears",
            fr: "Le mur aux mille engrenages",
          },
          desc: {
            es: "Una pared entera de ruedas dentadas que giran todas a la vez.",
            ca: "Una paret sencera de rodes dentades que giren totes alhora.",
            en: "A whole wall of cogwheels all turning at once.",
            fr: "Un mur entier de roues dentées qui tournent toutes en même temps.",
          },
          imageSeed: "inventor-c2robot-gears",
          icon: "settings",
          narrative: {
            es: "{name} y Tuerca caminan hasta la pared de los mil engranajes, donde ruedas dentadas de todos los tamaños giran sin parar.",
            ca: "{name} i en Tuerca caminen fins a la paret dels mil engranatges, on rodes dentades de totes les mides giren sense parar.",
            en: "{name} and Tuerca walk to the wall of a thousand gears, where cogwheels of every size spin without stopping.",
            fr: "{name} et Tuerca marchent jusqu'au mur aux mille engrenages, où des roues dentées de toutes les tailles tournent sans s'arrêter.",
          },
          next: "c3_robot_a",
        },
        {
          id: "spring-drawer",
          title: {
            es: "El cajón de los muelles saltarines",
            ca: "El calaix de les molles saltadores",
            en: "The drawer of bouncy springs",
            fr: "Le tiroir aux ressorts bondissants",
          },
          desc: {
            es: "Un cajón gigante donde los muelles botan solos como saltamontes.",
            ca: "Un calaix gegant on les molles boten soles amunt i avall.",
            en: "A giant drawer where springs bounce about all by themselves.",
            fr: "Un tiroir géant où les ressorts bondissent tout seuls.",
          },
          imageSeed: "inventor-c2robot-springs",
          icon: "unfold_more",
          narrative: {
            es: "{name} y Tuerca abren un cajón gigante lleno de muelles saltarines que botan alegres de un lado a otro.",
            ca: "{name} i en Tuerca obren un calaix gegant ple de molles saltadores que boten contentes d'una banda a l'altra.",
            en: "{name} and Tuerca open a giant drawer full of bouncy springs hopping merrily from side to side.",
            fr: "{name} et Tuerca ouvrent un tiroir géant rempli de ressorts bondissants qui sautent joyeusement d'un côté à l'autre.",
          },
          next: "c3_robot_b",
        },
        {
          id: "bulb-shelf",
          title: {
            es: "La estantería de las bombillas",
            ca: "La prestatgeria de les bombetes",
            en: "The shelf of glowing bulbs",
            fr: "L'étagère aux ampoules",
          },
          desc: {
            es: "Cientos de bombillas de colores descansan en una estantería altísima.",
            ca: "Centenars de bombetes de colors descansen en una prestatgeria altíssima.",
            en: "Hundreds of colourful bulbs rest on a very tall shelf.",
            fr: "Des centaines d'ampoules colorées reposent sur une étagère très haute.",
          },
          imageSeed: "inventor-c2robot-bulbs",
          icon: "lightbulb",
          narrative: {
            es: "{name} y Tuerca llegan a una estantería altísima donde cientos de bombillas de colores descansan en filas ordenadas.",
            ca: "{name} i en Tuerca arriben a una prestatgeria altíssima on centenars de bombetes de colors descansen en fileres ordenades.",
            en: "{name} and Tuerca reach a very tall shelf where hundreds of colourful bulbs rest in tidy rows.",
            fr: "{name} et Tuerca arrivent devant une très haute étagère où des centaines d'ampoules colorées reposent en rangées bien ordonnées.",
          },
          next: "c3_robot_c",
        },
      ],
    },
    c2_machine: {
      id: "c2_machine",
      chapter: 2,
      question: {
        es: "La máquina voladora baja despacito del techo, lista para su primer vuelo... ¡pero le falta la última pieza! Sobre el banco de trabajo hay tres ideas dibujadas. ¿Cuál construye {name}?",
        ca: "La màquina voladora baixa a poc a poc del sostre, a punt per al seu primer vol... però li falta l'última peça! Sobre el banc de treball hi ha tres idees dibuixades. Quina construeix {name}?",
        en: "The flying machine floats gently down from the ceiling, ready for its first flight... but the last piece is missing! On the workbench there are three ideas sketched out. Which one does {name} build?",
        fr: "La machine volante descend doucement du plafond, prête pour son premier vol... mais il lui manque la dernière pièce ! Sur l'établi, trois idées sont dessinées. Laquelle {name} va construire ?",
      },
      options: [
        {
          id: "propeller",
          title: {
            es: "Una hélice de molinillos",
            ca: "Una hèlix de molinets",
            en: "A pinwheel propeller",
            fr: "Une hélice de moulinets",
          },
          desc: {
            es: "Cuatro molinillos de papel de colores girando juntos.",
            ca: "Quatre molinets de paper de colors girant junts.",
            en: "Four colourful paper pinwheels spinning together.",
            fr: "Quatre moulinets en papier coloré qui tournent ensemble.",
          },
          imageSeed: "inventor-c2machine-propeller",
          icon: "toys",
          narrative: {
            es: "{name} une cuatro molinillos de papel de colores y fabrica una hélice que gira con solo un soplido suave.",
            ca: "{name} uneix quatre molinets de paper de colors i fabrica una hèlix que gira només amb una bufada suau.",
            en: "{name} joins four colourful paper pinwheels into a propeller that spins with just one gentle puff.",
            fr: "{name} assemble quatre moulinets en papier coloré et fabrique une hélice qui tourne d'un seul petit souffle.",
          },
          next: "c3_machine_a",
        },
        {
          id: "rudder",
          title: {
            es: "Un timón de bicicleta",
            ca: "Un timó de bicicleta",
            en: "A bicycle rudder",
            fr: "Un gouvernail de bicyclette",
          },
          desc: {
            es: "Un manillar brillante para decidir hacia dónde volar.",
            ca: "Un manillar brillant per decidir cap a on volar.",
            en: "A shiny handlebar to choose where to fly.",
            fr: "Un guidon brillant pour choisir où voler.",
          },
          imageSeed: "inventor-c2machine-rudder",
          icon: "directions_bike",
          narrative: {
            es: "{name} atornilla un manillar de bicicleta en la parte delantera de la máquina para poder girar a un lado y a otro.",
            ca: "{name} cargola un manillar de bicicleta a la part del davant de la màquina per poder girar a una banda i a l'altra.",
            en: "{name} bolts a bicycle handlebar onto the front of the machine so it can turn this way and that.",
            fr: "{name} visse un guidon de bicyclette à l'avant de la machine pour pouvoir tourner d'un côté et de l'autre.",
          },
          next: "c3_machine_b",
        },
        {
          id: "windup",
          title: {
            es: "Un motor de cuerda",
            ca: "Un motor de corda",
            en: "A wind-up motor",
            fr: "Un moteur à remontoir",
          },
          desc: {
            es: "Un motor con una llave gigante que se carga dando vueltas.",
            ca: "Un motor amb una clau gegant que es carrega fent voltes.",
            en: "A motor with a giant key that winds up turn by turn.",
            fr: "Un moteur avec une clé géante qu'on remonte tour après tour.",
          },
          imageSeed: "inventor-c2machine-windup",
          icon: "key",
          narrative: {
            es: "{name} monta un motor de cuerda con una llave gigante dorada que sobresale por un lado de la máquina.",
            ca: "{name} munta un motor de corda amb una clau gegant daurada que sobresurt per un costat de la màquina.",
            en: "{name} fits a wind-up motor with a giant golden key sticking out of the machine's side.",
            fr: "{name} installe un moteur à remontoir avec une clé géante dorée qui dépasse sur le côté de la machine.",
          },
          next: "c3_machine_c",
        },
      ],
    },
    c2_attic: {
      id: "c2_attic",
      chapter: 2,
      question: {
        es: "En el desván, los inventos olvidados despiertan al oír pasos. Una vocecita oxidada susurra: 'Hace años que nadie nos arregla'. {name} decide reparar uno primero. ¿Cuál elige?",
        ca: "A les golfes, els invents oblidats es desperten en sentir passos. Una veueta rovellada xiuxiueja: 'Fa anys que ningú no ens arregla'. {name} decideix reparar-ne un primer. Quin tria?",
        en: "In the attic, the forgotten inventions wake at the sound of footsteps. A rusty little voice whispers: 'Nobody has fixed us for years.' {name} decides to repair one first. Which one?",
        fr: "Dans le grenier, les inventions oubliées se réveillent au bruit des pas. Une petite voix rouillée chuchote : « Personne ne nous répare depuis des années. » {name} décide d'en réparer une d'abord. Laquelle ?",
      },
      options: [
        {
          id: "carousel",
          title: {
            es: "El carrusel musical",
            ca: "El carrusel musical",
            en: "The musical carousel",
            fr: "Le carrousel musical",
          },
          desc: {
            es: "Un carrusel de hojalata con caballitos que ya no giran ni suenan.",
            ca: "Un carrusel de llauna amb cavallets que ja no giren ni sonen.",
            en: "A tin carousel with little horses that no longer turn or play.",
            fr: "Un carrousel en fer-blanc avec des petits chevaux qui ne tournent plus.",
          },
          imageSeed: "inventor-c2attic-carousel",
          icon: "attractions",
          narrative: {
            es: "{name} se acerca a un carrusel de hojalata donde unos caballitos diminutos esperan quietos a que vuelva la música.",
            ca: "{name} s'acosta a un carrusel de llauna on uns cavallets diminuts esperen quiets que torni la música.",
            en: "{name} walks up to a tin carousel where tiny horses wait silently for the music to come back.",
            fr: "{name} s'approche d'un carrousel en fer-blanc où de minuscules chevaux attendent, immobiles, que la musique revienne.",
          },
          next: "c3_attic_a",
        },
        {
          id: "bubbles",
          title: {
            es: "La máquina de pompas",
            ca: "La màquina de bombolles",
            en: "The bubble machine",
            fr: "La machine à bulles",
          },
          desc: {
            es: "Una máquina redondita que antes llenaba el taller de pompas de jabón.",
            ca: "Una màquina rodoneta que abans omplia el taller de bombolles de sabó.",
            en: "A round little machine that once filled the workshop with soap bubbles.",
            fr: "Une petite machine toute ronde qui remplissait autrefois l'atelier de bulles de savon.",
          },
          imageSeed: "inventor-c2attic-bubbles",
          icon: "bubble_chart",
          narrative: {
            es: "{name} examina una máquina redondita y polvorienta que hace años llenaba el taller de pompas de jabón brillantes.",
            ca: "{name} examina una màquina rodoneta i polsosa que fa anys omplia el taller de bombolles de sabó brillants.",
            en: "{name} looks over a dusty round machine that years ago filled the workshop with shiny soap bubbles.",
            fr: "{name} examine une petite machine ronde et poussiéreuse qui, il y a des années, remplissait l'atelier de bulles de savon brillantes.",
          },
          next: "c3_attic_b",
        },
        {
          id: "painter",
          title: {
            es: "El pintor automático",
            ca: "El pintor automàtic",
            en: "The automatic painter",
            fr: "Le peintre automatique",
          },
          desc: {
            es: "Un brazo de madera con tres pinceles que pintaba cuadros él solito.",
            ca: "Un braç de fusta amb tres pinzells que pintava quadres tot sol.",
            en: "A wooden arm with three brushes that used to paint pictures all by itself.",
            fr: "Un bras en bois avec trois pinceaux qui peignait des tableaux tout seul.",
          },
          imageSeed: "inventor-c2attic-painter",
          icon: "brush",
          narrative: {
            es: "{name} descubre un brazo de madera con tres pinceles que, hace mucho tiempo, pintaba cuadros él solito.",
            ca: "{name} descobreix un braç de fusta amb tres pinzells que, fa molt de temps, pintava quadres tot sol.",
            en: "{name} discovers a wooden arm with three brushes that, long ago, painted pictures all by itself.",
            fr: "{name} découvre un bras en bois avec trois pinceaux qui, il y a très longtemps, peignait des tableaux tout seul.",
          },
          next: "c3_attic_c",
        },
      ],
    },
    c3_robot_a: {
      id: "c3_robot_a",
      chapter: 3,
      question: {
        es: "Entre los mil engranajes hay uno dorado y pequeñito que encaja justo en el corazón de Tuerca. ¡Pero gira muy arriba, en lo más alto de la pared! ¿Cómo lo alcanza {name}?",
        ca: "Entre els mil engranatges n'hi ha un de daurat i petitó que encaixa just al cor d'en Tuerca. Però gira molt amunt, a dalt de tot de la paret! Com l'agafa {name}?",
        en: "Among the thousand gears there is a tiny golden one that fits Tuerca's heart just right. But it spins way up at the very top of the wall! How does {name} reach it?",
        fr: "Parmi les mille engrenages, il y en a un tout petit, doré, qui s'emboîte parfaitement dans le cœur de Tuerca. Mais il tourne tout en haut du mur ! Comment {name} va l'attraper ?",
      },
      options: [
        {
          id: "crane",
          title: {
            es: "Construir una grúa",
            ca: "Construir una grua",
            en: "Build a little crane",
            fr: "Construire une petite grue",
          },
          desc: {
            es: "Con cajas, una cuerda y una polea se levanta casi cualquier cosa.",
            ca: "Amb caixes, una corda i una politja s'aixeca gairebé qualsevol cosa.",
            en: "With boxes, a rope and a pulley you can lift almost anything.",
            fr: "Avec des caisses, une corde et une poulie, on peut presque tout soulever.",
          },
          imageSeed: "inventor-c3robota-crane",
          icon: "construction",
          narrative: {
            es: "{name} construye una grúa pequeña con cajas, una cuerda y una polea, y baja con muchísimo cuidado el engranaje dorado.",
            ca: "{name} construeix una grua petita amb caixes, una corda i una politja, i baixa amb moltíssima cura l'engranatge daurat.",
            en: "{name} builds a little crane from boxes, a rope and a pulley, and lowers the golden gear very, very carefully.",
            fr: "{name} construit une petite grue avec des caisses, une corde et une poulie, et descend l'engrenage doré avec beaucoup de précaution.",
          },
          next: "ending",
        },
        {
          id: "magnet",
          title: {
            es: "Una caña con imán",
            ca: "Una canya amb imant",
            en: "A magnet on a stick",
            fr: "Une canne aimantée",
          },
          desc: {
            es: "Un imán atado a un palo largo atrapa las piezas brillantes.",
            ca: "Un imant lligat a un pal llarg atrapa les peces brillants.",
            en: "A magnet tied to a long stick catches shiny metal pieces.",
            fr: "Un aimant attaché à un long bâton attrape les pièces brillantes.",
          },
          imageSeed: "inventor-c3robota-magnet",
          icon: "phishing",
          narrative: {
            es: "{name} ata un imán a un palo largo, lo acerca despacito y, ¡clic!, el engranaje dorado salta hasta el imán.",
            ca: "{name} lliga un imant a un pal llarg, l'acosta a poc a poc i, clic!, l'engranatge daurat salta fins a l'imant.",
            en: "{name} ties a magnet to a long stick, lifts it up slowly and, click!, the golden gear jumps onto the magnet.",
            fr: "{name} attache un aimant à un long bâton, l'approche tout doucement et, clic !, l'engrenage doré saute sur l'aimant.",
          },
          next: "ending",
        },
        {
          id: "please",
          title: {
            es: "Pedirlo por favor",
            ca: "Demanar-ho si us plau",
            en: "Ask very politely",
            fr: "Le demander poliment",
          },
          desc: {
            es: "Si alguien lo pide amablemente, los engranajes se lo pasan de rueda en rueda.",
            ca: "Si algú ho demana amablement, els engranatges s'ho passen de roda en roda.",
            en: "If someone asks kindly, the gears pass it along wheel to wheel.",
            fr: "Si on le demande gentiment, les engrenages se le passent de roue en roue.",
          },
          imageSeed: "inventor-c3robota-please",
          icon: "volunteer_activism",
          narrative: {
            es: "{name} lo pide por favor en voz alta y los engranajes se pasan la piecita dorada de rueda en rueda hasta sus manos.",
            ca: "{name} ho demana si us plau en veu alta i els engranatges es passen la peceta daurada de roda en roda fins a les seves mans.",
            en: "{name} asks out loud, very politely, and the gears pass the little golden piece wheel to wheel right into waiting hands.",
            fr: "{name} le demande poliment à voix haute et les engrenages se passent la petite pièce dorée de roue en roue jusqu'à ses mains.",
          },
          next: "ending",
        },
      ],
    },
    c3_robot_b: {
      id: "c3_robot_b",
      chapter: 3,
      question: {
        es: "En el cajón, los muelles botan tan alto que el muelle plateado que necesita Tuerca no se deja atrapar. ¿Cómo lo consigue {name}?",
        ca: "Al calaix, les molles boten tan amunt que la molla platejada que necessita en Tuerca no es deixa atrapar. Com l'aconsegueix {name}?",
        en: "Inside the drawer, the springs bounce so high that the silver spring Tuerca needs won't let itself be caught. How does {name} get it?",
        fr: "Dans le tiroir, les ressorts bondissent si haut que le ressort argenté dont Tuerca a besoin ne se laisse pas attraper. Comment {name} va l'obtenir ?",
      },
      options: [
        {
          id: "cushion",
          title: {
            es: "Un colchón de esponjas",
            ca: "Un matalàs d'esponges",
            en: "A sponge mattress",
            fr: "Un matelas d'éponges",
          },
          desc: {
            es: "Sobre algo blandito, los muelles se calman y dejan de botar.",
            ca: "Sobre una cosa toveta, les molles es calmen i deixen de botar.",
            en: "On something soft, the springs calm down and stop bouncing.",
            fr: "Sur quelque chose de tout doux, les ressorts se calment et arrêtent de bondir.",
          },
          imageSeed: "inventor-c3robotb-cushion",
          icon: "bed",
          narrative: {
            es: "{name} cubre el fondo del cajón con esponjas blanditas y los muelles se calman, dejando el muelle plateado quietecito.",
            ca: "{name} cobreix el fons del calaix amb esponges tovetes i les molles es calmen, deixant la molla platejada ben quieta.",
            en: "{name} lines the drawer with soft sponges and the springs settle down, leaving the silver spring sitting nice and still.",
            fr: "{name} tapisse le fond du tiroir d'éponges toutes douces et les ressorts se calment, laissant le ressort argenté bien tranquille.",
          },
          next: "ending",
        },
        {
          id: "bounce-game",
          title: {
            es: "Saltar a su ritmo",
            ca: "Saltar al seu ritme",
            en: "Bounce along with them",
            fr: "Sauter à leur rythme",
          },
          desc: {
            es: "A los muelles les encanta que alguien salte a su ritmo.",
            ca: "A les molles els encanta que algú salti al seu ritme.",
            en: "Springs love it when someone bounces along to their rhythm.",
            fr: "Les ressorts adorent qu'on saute à leur rythme.",
          },
          imageSeed: "inventor-c3robotb-game",
          icon: "celebration",
          narrative: {
            es: "{name} salta al ritmo de los muelles hasta que, encantado de la fiesta, el muelle plateado bota directo a sus manos.",
            ca: "{name} salta al ritme de les molles fins que, encantada de la festa, la molla platejada bota directa a les seves mans.",
            en: "{name} bounces along with the springs until, delighted with the game, the silver spring hops straight into open hands.",
            fr: "{name} saute au rythme des ressorts jusqu'à ce que, ravi de la fête, le ressort argenté bondisse droit dans ses mains.",
          },
          next: "ending",
        },
        {
          id: "funnel",
          title: {
            es: "Un embudo gigante",
            ca: "Un embut gegant",
            en: "A giant funnel",
            fr: "Un entonnoir géant",
          },
          desc: {
            es: "Un embudo de cartón guía las piezas saltarinas hasta un tarro de cristal.",
            ca: "Un embut de cartró guia les peces saltadores fins a un pot de vidre.",
            en: "A cardboard funnel guides the bouncy pieces into a glass jar.",
            fr: "Un entonnoir en carton guide les pièces bondissantes jusqu'à un bocal en verre.",
          },
          imageSeed: "inventor-c3robotb-funnel",
          icon: "filter_alt",
          narrative: {
            es: "{name} fabrica un embudo gigante de cartón y el muelle plateado cae rodando despacito hasta un tarro de cristal.",
            ca: "{name} fabrica un embut gegant de cartró i la molla platejada cau rodolant a poc a poc fins a un pot de vidre.",
            en: "{name} builds a giant cardboard funnel and the silver spring rolls gently down into a glass jar.",
            fr: "{name} fabrique un entonnoir géant en carton et le ressort argenté roule tout doucement jusque dans un bocal en verre.",
          },
          next: "ending",
        },
      ],
    },
    c3_robot_c: {
      id: "c3_robot_c",
      chapter: 3,
      question: {
        es: "En la estantería hay cientos de bombillas, pero solo una guarda la lucecita calentita que encaja en el corazón de Tuerca. ¿Cómo la encuentra {name}?",
        ca: "A la prestatgeria hi ha centenars de bombetes, però només una guarda la llumeta calentona que encaixa al cor d'en Tuerca. Com la troba {name}?",
        en: "There are hundreds of bulbs on the shelf, but only one holds the warm little light that fits Tuerca's heart. How does {name} find it?",
        fr: "Sur l'étagère, il y a des centaines d'ampoules, mais une seule garde la petite lumière toute chaude qui va dans le cœur de Tuerca. Comment {name} la trouve ?",
      },
      options: [
        {
          id: "lights-off",
          title: {
            es: "Apagar todas las luces",
            ca: "Apagar tots els llums",
            en: "Turn off all the lights",
            fr: "Éteindre toutes les lumières",
          },
          desc: {
            es: "En la oscuridad, la bombilla especial brilla ella solita.",
            ca: "A la foscor, la bombeta especial brilla tota sola.",
            en: "In the dark, the special bulb glows all by itself.",
            fr: "Dans le noir, l'ampoule spéciale brille toute seule.",
          },
          imageSeed: "inventor-c3robotc-dark",
          icon: "dark_mode",
          narrative: {
            es: "{name} apaga las luces del taller y, en la oscuridad, una bombillita brilla solita con una luz dorada y calentita.",
            ca: "{name} apaga els llums del taller i, a la foscor, una bombeteta brilla tota sola amb una llum daurada i calentona.",
            en: "{name} switches off the workshop lights and, in the dark, one little bulb glows all alone with a warm golden light.",
            fr: "{name} éteint les lumières de l'atelier et, dans le noir, une petite ampoule brille toute seule d'une lumière dorée et chaude.",
          },
          next: "ending",
        },
        {
          id: "new-idea",
          title: {
            es: "Contarle una idea",
            ca: "Explicar-li una idea",
            en: "Tell it a brand-new idea",
            fr: "Lui raconter une idée",
          },
          desc: {
            es: "La bombilla de las ideas se enciende cuando escucha una idea nueva.",
            ca: "La bombeta de les idees s'encén quan escolta una idea nova.",
            en: "The idea bulb lights up when it hears a brand-new idea.",
            fr: "L'ampoule à idées s'allume quand elle entend une idée toute neuve.",
          },
          imageSeed: "inventor-c3robotc-idea",
          icon: "emoji_objects",
          narrative: {
            es: "{name} cuenta en voz alta su idea más loca y una bombilla se enciende de golpe, parpadeando de pura emoción.",
            ca: "{name} explica en veu alta la seva idea més boja i una bombeta s'encén de cop, parpellejant de pura emoció.",
            en: "{name} says their wildest idea out loud and one bulb flashes on at once, blinking with pure excitement.",
            fr: "{name} raconte à voix haute son idée la plus folle et une ampoule s'allume d'un coup, clignotant d'émotion.",
          },
          next: "ending",
        },
        {
          id: "hum",
          title: {
            es: "Escuchar su zumbido",
            ca: "Escoltar el seu brunzit",
            en: "Listen for its hum",
            fr: "Écouter son bourdonnement",
          },
          desc: {
            es: "La bombilla especial zumba bajito como una abeja contenta.",
            ca: "La bombeta especial brunzeix fluixet com una abella contenta.",
            en: "The special bulb hums softly like a happy bee.",
            fr: "L'ampoule spéciale bourdonne tout bas comme une abeille joyeuse.",
          },
          imageSeed: "inventor-c3robotc-hum",
          icon: "hearing",
          narrative: {
            es: "{name} pega la oreja a la estantería, sigue un zumbido suave como de abeja y encuentra la bombilla de las ideas.",
            ca: "{name} arrima l'orella a la prestatgeria, segueix un brunzit suau com d'abella i troba la bombeta de les idees.",
            en: "{name} presses an ear to the shelf, follows a soft bee-like hum and finds the idea bulb.",
            fr: "{name} colle son oreille à l'étagère, suit un doux bourdonnement d'abeille et trouve l'ampoule à idées.",
          },
          next: "ending",
        },
      ],
    },
    c3_machine_a: {
      id: "c3_machine_a",
      chapter: 3,
      question: {
        es: "Con la hélice de molinillos girando, la máquina despega... ¡pero vuela dando tumbos y vueltas por todo el taller! ¿Cómo la equilibra {name}?",
        ca: "Amb l'hèlix de molinets girant, la màquina s'enlaira... però vola fent tombs i voltes per tot el taller! Com l'equilibra {name}?",
        en: "With the pinwheel propeller spinning, the machine takes off... but it wobbles and loops all around the workshop! How does {name} balance it?",
        fr: "Avec l'hélice de moulinets qui tourne, la machine décolle... mais elle vole en zigzag et fait des loopings dans tout l'atelier ! Comment {name} va l'équilibrer ?",
      },
      options: [
        {
          id: "kite-tail",
          title: {
            es: "Una cola de cometa",
            ca: "Una cua d'estel",
            en: "A kite tail",
            fr: "Une queue de cerf-volant",
          },
          desc: {
            es: "Una cinta larga con lacitos que baila detrás de las cosas que vuelan.",
            ca: "Una cinta llarga amb llacets que balla darrere de les coses que volen.",
            en: "A long ribbon with little bows that dances behind flying things.",
            fr: "Un long ruban avec des petits nœuds qui danse derrière ce qui vole.",
          },
          imageSeed: "inventor-c3machinea-tail",
          icon: "air",
          narrative: {
            es: "{name} ata una cola de cometa con lacitos de colores y la máquina vuela recta y suave como un pájaro tranquilo.",
            ca: "{name} lliga una cua d'estel amb llacets de colors i la màquina vola recta i suau com un ocell tranquil.",
            en: "{name} ties on a kite tail with colourful bows and the machine flies straight and smooth like a calm bird.",
            fr: "{name} attache une queue de cerf-volant avec des nœuds colorés et la machine vole droit, douce comme un oiseau tranquille.",
          },
          next: "ending",
        },
        {
          id: "marbles",
          title: {
            es: "Un saquito de canicas",
            ca: "Un saquet de bales",
            en: "A little bag of marbles",
            fr: "Un petit sac de billes",
          },
          desc: {
            es: "Un pesito en el lado justo lo endereza todo.",
            ca: "Un peset al costat just ho redreça tot.",
            en: "A tiny weight in just the right spot sets everything straight.",
            fr: "Un petit poids au bon endroit remet tout droit.",
          },
          imageSeed: "inventor-c3machinea-marbles",
          icon: "fitness_center",
          narrative: {
            es: "{name} cuelga un saquito de canicas en el lado que se inclina y la máquina se endereza poquito a poco.",
            ca: "{name} penja un saquet de bales al costat que s'inclina i la màquina es redreça a poc a poc.",
            en: "{name} hangs a little bag of marbles on the tilting side and the machine straightens up bit by bit.",
            fr: "{name} accroche un petit sac de billes du côté qui penche et la machine se redresse petit à petit.",
          },
          next: "ending",
        },
        {
          id: "flaps",
          title: {
            es: "Alerones de cartón",
            ca: "Alerons de cartró",
            en: "Cardboard wing flaps",
            fr: "Des ailerons en carton",
          },
          desc: {
            es: "Dos aletas pequeñas como las de los aviones de verdad.",
            ca: "Dues aletes petites com les dels avions de debò.",
            en: "Two small flaps just like real aeroplanes have.",
            fr: "Deux petits volets comme sur les vrais avions.",
          },
          imageSeed: "inventor-c3machinea-flaps",
          icon: "flight_takeoff",
          narrative: {
            es: "{name} recorta dos alerones de cartón, los pega a los lados y la máquina planea suave hasta posarse en su mano.",
            ca: "{name} retalla dos alerons de cartró, els enganxa als costats i la màquina planeja suau fins a posar-se a la seva mà.",
            en: "{name} cuts out two cardboard flaps, sticks them on the sides and the machine glides gently down to land on an open hand.",
            fr: "{name} découpe deux ailerons en carton, les colle sur les côtés et la machine plane doucement jusqu'à se poser sur sa main.",
          },
          next: "ending",
        },
      ],
    },
    c3_machine_b: {
      id: "c3_machine_b",
      chapter: 3,
      question: {
        es: "El timón ya está montado, pero la máquina todavía no sabe hacia dónde ir y casi choca con las estanterías. ¿Qué inventa {name} para guiarla hasta el cielo?",
        ca: "El timó ja està muntat, però la màquina encara no sap cap a on anar i gairebé xoca amb les prestatgeries. Què inventa {name} per guiar-la fins al cel?",
        en: "The rudder is in place, but the machine still doesn't know where to go and nearly bumps into the shelves. What does {name} invent to guide it to the sky?",
        fr: "Le gouvernail est installé, mais la machine ne sait pas encore où aller et manque de heurter les étagères. Qu'est-ce que {name} invente pour la guider jusqu'au ciel ?",
      },
      options: [
        {
          id: "map",
          title: {
            es: "Un mapa del taller",
            ca: "Un mapa del taller",
            en: "A workshop map",
            fr: "Une carte de l'atelier",
          },
          desc: {
            es: "Un plano con caminitos y flechas que esquivan cada estantería.",
            ca: "Un plànol amb caminets i fletxes que esquiven cada prestatgeria.",
            en: "A map with little paths and arrows that dodge every shelf.",
            fr: "Un plan avec des petits chemins et des flèches qui évitent chaque étagère.",
          },
          imageSeed: "inventor-c3machineb-map",
          icon: "map",
          narrative: {
            es: "{name} dibuja un mapa del taller con flechas de colores y la máquina aprende el caminito hasta la gran ventana.",
            ca: "{name} dibuixa un mapa del taller amb fletxes de colors i la màquina aprèn el caminet fins a la gran finestra.",
            en: "{name} draws a map of the workshop with colourful arrows and the machine learns the little path to the big window.",
            fr: "{name} dessine une carte de l'atelier avec des flèches colorées et la machine apprend le petit chemin jusqu'à la grande fenêtre.",
          },
          next: "ending",
        },
        {
          id: "bell",
          title: {
            es: "Una campanilla guía",
            ca: "Una campaneta guia",
            en: "A guiding bell",
            fr: "Une clochette guide",
          },
          desc: {
            es: "Un tin-tin alegre que se puede seguir con los ojos cerrados.",
            ca: "Un dring-dring alegre que es pot seguir amb els ulls tancats.",
            en: "A cheerful ring-ring you can follow with your eyes closed.",
            fr: "Un ding-ding joyeux qu'on peut suivre les yeux fermés.",
          },
          imageSeed: "inventor-c3machineb-bell",
          icon: "notifications",
          narrative: {
            es: "{name} camina delante haciendo sonar una campanilla y la máquina sigue el tin-tin, esquivando todas las estanterías.",
            ca: "{name} camina al davant fent sonar una campaneta i la màquina segueix el dring-dring, esquivant totes les prestatgeries.",
            en: "{name} walks ahead ringing a little bell and the machine follows the ring-ring, dodging every shelf.",
            fr: "{name} marche devant en faisant sonner une clochette et la machine suit le ding-ding, évitant toutes les étagères.",
          },
          next: "ending",
        },
        {
          id: "headlamp",
          title: {
            es: "Un farito delantero",
            ca: "Un fanalet davanter",
            en: "A little headlamp",
            fr: "Un petit phare avant",
          },
          desc: {
            es: "Una lucecita que dibuja el camino libre entre las máquinas.",
            ca: "Una llumeta que dibuixa el camí lliure entre les màquines.",
            en: "A little light that draws the clear path between the machines.",
            fr: "Une petite lumière qui dessine le chemin libre entre les machines.",
          },
          imageSeed: "inventor-c3machineb-light",
          icon: "flashlight_on",
          narrative: {
            es: "{name} monta un farito en la punta de la máquina y la luz dibuja un caminito brillante hasta el cielo abierto.",
            ca: "{name} munta un fanalet a la punta de la màquina i la llum dibuixa un caminet brillant fins al cel obert.",
            en: "{name} fits a little headlamp on the machine's nose and the light draws a shining path to the open sky.",
            fr: "{name} installe un petit phare au bout de la machine et la lumière dessine un chemin brillant jusqu'au ciel ouvert.",
          },
          next: "ending",
        },
      ],
    },
    c3_machine_c: {
      id: "c3_machine_c",
      chapter: 3,
      question: {
        es: "El motor de cuerda ya tiene su llave gigante, pero hay que darle el número justo de vueltas: ni una más, ni una menos. ¿Cómo lo descubre {name}?",
        ca: "El motor de corda ja té la seva clau gegant, però cal donar-li el nombre just de voltes: ni una més, ni una menys. Com ho descobreix {name}?",
        en: "The wind-up motor has its giant key, but it needs exactly the right number of turns: not one more, not one less. How does {name} figure it out?",
        fr: "Le moteur à remontoir a sa clé géante, mais il faut lui donner juste le bon nombre de tours : pas un de plus, pas un de moins. Comment {name} va le découvrir ?",
      },
      options: [
        {
          id: "blueprint",
          title: {
            es: "Mirar los planos",
            ca: "Mirar els plànols",
            en: "Check the blueprints",
            fr: "Regarder les plans",
          },
          desc: {
            es: "En un plano antiguo lleno de números está apuntado el secreto.",
            ca: "En un plànol antic ple de números hi ha apuntat el secret.",
            en: "The secret is written on an old blueprint full of numbers.",
            fr: "Le secret est noté sur un vieux plan rempli de chiffres.",
          },
          imageSeed: "inventor-c3machinec-plan",
          icon: "draw",
          narrative: {
            es: "{name} desenrolla un plano antiguo y encuentra el número secreto escrito en una esquina: ¡siete vueltas y media!",
            ca: "{name} desenrotlla un plànol antic i troba el número secret escrit en un racó: set voltes i mitja!",
            en: "{name} unrolls an old blueprint and finds the secret number written in one corner: seven and a half turns!",
            fr: "{name} déroule un vieux plan et trouve le nombre secret écrit dans un coin : sept tours et demi !",
          },
          next: "ending",
        },
        {
          id: "purr",
          title: {
            es: "Escuchar el motor",
            ca: "Escoltar el motor",
            en: "Listen to the motor",
            fr: "Écouter le moteur",
          },
          desc: {
            es: "Cuando el motor está contento, ronronea como un gatito.",
            ca: "Quan el motor està content, ronroneja com un gatet.",
            en: "When the motor is happy, it purrs like a kitten.",
            fr: "Quand le moteur est content, il ronronne comme un chaton.",
          },
          imageSeed: "inventor-c3machinec-purr",
          icon: "graphic_eq",
          narrative: {
            es: "{name} gira la llave despacito, cuenta cada vuelta y para justo cuando el motor ronronea como un gatito feliz.",
            ca: "{name} gira la clau a poc a poc, compta cada volta i s'atura just quan el motor ronroneja com un gatet feliç.",
            en: "{name} turns the key slowly, counting every turn, and stops just as the motor purrs like a happy kitten.",
            fr: "{name} tourne la clé tout doucement, compte chaque tour et s'arrête juste quand le moteur ronronne comme un chaton heureux.",
          },
          next: "ending",
        },
        {
          id: "counting-song",
          title: {
            es: "Una canción para contar",
            ca: "Una cançó per comptar",
            en: "A counting song",
            fr: "Une chanson pour compter",
          },
          desc: {
            es: "Una cancioncita donde cada verso vale una vuelta de llave.",
            ca: "Una cançoneta on cada vers val una volta de clau.",
            en: "A little song where every verse counts for one turn of the key.",
            fr: "Une petite chanson où chaque couplet vaut un tour de clé.",
          },
          imageSeed: "inventor-c3machinec-song",
          icon: "music_note",
          narrative: {
            es: "{name} inventa una cancioncita de siete versos y da una vuelta de llave con cada uno, sin saltarse ni uno solo.",
            ca: "{name} inventa una cançoneta de set versos i fa una volta de clau amb cadascun, sense saltar-se'n ni un.",
            en: "{name} makes up a little song with seven verses and gives the key one turn for each, never skipping a single one.",
            fr: "{name} invente une petite chanson de sept couplets et donne un tour de clé à chacun, sans en sauter un seul.",
          },
          next: "ending",
        },
      ],
    },
    c3_attic_a: {
      id: "c3_attic_a",
      chapter: 3,
      question: {
        es: "Al carrusel le falta la manivela que lo hace girar, y sin música los caballitos no pueden bailar. ¿Qué hace {name}?",
        ca: "Al carrusel li falta la maneta que el fa girar, i sense música els cavallets no poden ballar. Què fa {name}?",
        en: "The carousel is missing the crank that makes it turn, and without music the little horses cannot dance. What does {name} do?",
        fr: "Il manque au carrousel la manivelle qui le fait tourner, et sans musique les petits chevaux ne peuvent pas danser. Que fait {name} ?",
      },
      options: [
        {
          id: "spoon-crank",
          title: {
            es: "Una manivela de cuchara",
            ca: "Una maneta de cullera",
            en: "A spoon crank",
            fr: "Une manivelle-cuillère",
          },
          desc: {
            es: "Una cuchara grande y un corcho hacen una manivela perfecta.",
            ca: "Una cullera grossa i un suro fan una maneta perfecta.",
            en: "A big spoon and a cork make a perfect crank.",
            fr: "Une grande cuillère et un bouchon de liège font une manivelle parfaite.",
          },
          imageSeed: "inventor-c3attica-spoon",
          icon: "flatware",
          narrative: {
            es: "{name} fabrica una manivela con una cuchara grande y un corcho, la encaja y los caballitos empiezan a girar despacito.",
            ca: "{name} fabrica una maneta amb una cullera grossa i un suro, l'encaixa i els cavallets comencen a girar a poc a poc.",
            en: "{name} makes a crank from a big spoon and a cork, slots it in, and the little horses slowly begin to turn.",
            fr: "{name} fabrique une manivelle avec une grande cuillère et un bouchon de liège, l'emboîte, et les petits chevaux se mettent à tourner doucement.",
          },
          next: "ending",
        },
        {
          id: "hum-tune",
          title: {
            es: "Tararear su melodía",
            ca: "Taral·lejar la seva melodia",
            en: "Hum its tune",
            fr: "Fredonner sa mélodie",
          },
          desc: {
            es: "Si alguien tararea su canción, el carrusel la recuerda solito.",
            ca: "Si algú taral·leja la seva cançó, el carrusel la recorda tot sol.",
            en: "If someone hums its song, the carousel remembers it on its own.",
            fr: "Si quelqu'un fredonne sa chanson, le carrousel s'en souvient tout seul.",
          },
          imageSeed: "inventor-c3attica-hum",
          icon: "queue_music",
          narrative: {
            es: "{name} tararea una melodía dulce muy cerca del carrusel y sus campanitas la repiten, girando poquito a poco.",
            ca: "{name} taral·leja una melodia dolça molt a prop del carrusel i les seves campanetes la repeteixen, girant a poc a poc.",
            en: "{name} hums a sweet tune right next to the carousel and its little bells repeat it, turning round bit by bit.",
            fr: "{name} fredonne une douce mélodie tout près du carrousel et ses clochettes la répètent, en tournant petit à petit.",
          },
          next: "ending",
        },
        {
          id: "parts-box",
          title: {
            es: "La caja de piezas antiguas",
            ca: "La caixa de peces antigues",
            en: "The box of old parts",
            fr: "La boîte aux vieilles pièces",
          },
          desc: {
            es: "Una caja llena de manivelas, ruedas y botones de otros tiempos.",
            ca: "Una caixa plena de manetes, rodes i botons d'altres temps.",
            en: "A box full of cranks, wheels and buttons from long ago.",
            fr: "Une boîte pleine de manivelles, de roues et de boutons d'autrefois.",
          },
          imageSeed: "inventor-c3attica-box",
          icon: "inventory_2",
          narrative: {
            es: "{name} rebusca en la caja de piezas antiguas y encuentra la manivela dorada del carrusel debajo de tres botones.",
            ca: "{name} remena la caixa de peces antigues i troba la maneta daurada del carrusel sota tres botons.",
            en: "{name} rummages through the box of old parts and finds the carousel's golden crank underneath three buttons.",
            fr: "{name} fouille dans la boîte aux vieilles pièces et trouve la manivelle dorée du carrousel sous trois boutons.",
          },
          next: "ending",
        },
      ],
    },
    c3_attic_b: {
      id: "c3_attic_b",
      chapter: 3,
      question: {
        es: "La máquina de pompas tose un poquito de polvo: su jabón se secó hace años y necesita una mezcla nueva y especial. ¿Cómo la prepara {name}?",
        ca: "La màquina de bombolles tus una miqueta de pols: el seu sabó es va assecar fa anys i necessita una barreja nova i especial. Com la prepara {name}?",
        en: "The bubble machine coughs out a puff of dust: its soap dried up years ago and it needs a special new mixture. How does {name} make it?",
        fr: "La machine à bulles tousse un petit nuage de poussière : son savon a séché il y a des années et il lui faut un mélange tout neuf. Comment {name} va le préparer ?",
      },
      options: [
        {
          id: "recipe",
          title: {
            es: "Seguir la receta secreta",
            ca: "Seguir la recepta secreta",
            en: "Follow the secret recipe",
            fr: "Suivre la recette secrète",
          },
          desc: {
            es: "Una receta escrita a mano asoma pegada debajo de la máquina.",
            ca: "Una recepta escrita a mà treu el nas enganxada sota la màquina.",
            en: "A handwritten recipe peeks out from under the machine.",
            fr: "Une recette écrite à la main dépasse sous la machine.",
          },
          imageSeed: "inventor-c3atticb-recipe",
          icon: "menu_book",
          narrative: {
            es: "{name} encuentra una receta escrita a mano debajo de la máquina y mezcla jabón, agua y una cucharadita de miel.",
            ca: "{name} troba una recepta escrita a mà sota la màquina i barreja sabó, aigua i una cullaradeta de mel.",
            en: "{name} finds a handwritten recipe under the machine and mixes soap, water and a little spoonful of honey.",
            fr: "{name} trouve une recette écrite à la main sous la machine et mélange du savon, de l'eau et une petite cuillerée de miel.",
          },
          next: "ending",
        },
        {
          id: "rainbow-soaps",
          title: {
            es: "Jabones de colores",
            ca: "Sabons de colors",
            en: "Rainbow soaps",
            fr: "Des savons colorés",
          },
          desc: {
            es: "Tres jabones de colores distintos hacen pompas de arcoíris.",
            ca: "Tres sabons de colors diferents fan bombolles d'arc de Sant Martí.",
            en: "Three different coloured soaps make rainbow bubbles.",
            fr: "Trois savons de couleurs différentes font des bulles arc-en-ciel.",
          },
          imageSeed: "inventor-c3atticb-colors",
          icon: "palette",
          narrative: {
            es: "{name} ralla tres jabones de colores, los mezcla con agua tibia y la máquina sopla pompas de arcoíris por todo el desván.",
            ca: "{name} ratlla tres sabons de colors, els barreja amb aigua tèbia i la màquina bufa bombolles d'arc de Sant Martí per totes les golfes.",
            en: "{name} grates three coloured soaps, mixes them with warm water, and the machine blows rainbow bubbles all over the attic.",
            fr: "{name} râpe trois savons colorés, les mélange à de l'eau tiède, et la machine souffle des bulles arc-en-ciel dans tout le grenier.",
          },
          next: "ending",
        },
        {
          id: "drop-by-drop",
          title: {
            es: "Probar gota a gota",
            ca: "Provar gota a gota",
            en: "Test it drop by drop",
            fr: "Essayer goutte à goutte",
          },
          desc: {
            es: "Con una libretita y mucha paciencia se encuentra la mezcla perfecta.",
            ca: "Amb una llibreteta i molta paciència es troba la barreja perfecta.",
            en: "With a little notebook and lots of patience you find the perfect mix.",
            fr: "Avec un petit carnet et beaucoup de patience, on trouve le mélange parfait.",
          },
          imageSeed: "inventor-c3atticb-drops",
          icon: "science",
          narrative: {
            es: "{name} prueba la mezcla gota a gota, apuntando cada intento en una libretita, hasta que sale una pompa gigante y perfecta.",
            ca: "{name} prova la barreja gota a gota, apuntant cada intent en una llibreteta, fins que surt una bombolla gegant i perfecta.",
            en: "{name} tests the mixture drop by drop, noting every try in a little notebook, until one giant, perfect bubble floats out.",
            fr: "{name} essaie le mélange goutte à goutte, en notant chaque essai dans un petit carnet, jusqu'à ce qu'une bulle géante et parfaite s'envole.",
          },
          next: "ending",
        },
      ],
    },
    c3_attic_c: {
      id: "c3_attic_c",
      chapter: 3,
      question: {
        es: "El pintor automático ya mueve sus tres pinceles, ¡pero no recuerda qué le gustaba pintar! ¿Cómo le devuelve {name} la inspiración?",
        ca: "El pintor automàtic ja mou els seus tres pinzells, però no recorda què li agradava pintar! Com li torna {name} la inspiració?",
        en: "The automatic painter can move its three brushes again, but it can't remember what it loved to paint! How does {name} bring back its inspiration?",
        fr: "Le peintre automatique bouge à nouveau ses trois pinceaux, mais il ne se souvient plus de ce qu'il aimait peindre ! Comment {name} va lui rendre l'inspiration ?",
      },
      options: [
        {
          id: "window",
          title: {
            es: "Abrir la ventana",
            ca: "Obrir la finestra",
            en: "Open the window",
            fr: "Ouvrir la fenêtre",
          },
          desc: {
            es: "Desde el desván se ve el atardecer más bonito de la ciudad.",
            ca: "Des de les golfes es veu el capvespre més bonic de la ciutat.",
            en: "From the attic you can see the prettiest sunset in town.",
            fr: "Du grenier, on voit le plus beau coucher de soleil de la ville.",
          },
          imageSeed: "inventor-c3atticc-window",
          icon: "wb_twilight",
          narrative: {
            es: "{name} abre la ventana del desván y el pintor automático pinta el atardecer naranja con sus tres pinceles a la vez.",
            ca: "{name} obre la finestra de les golfes i el pintor automàtic pinta el capvespre taronja amb els seus tres pinzells alhora.",
            en: "{name} opens the attic window and the automatic painter paints the orange sunset with all three brushes at once.",
            fr: "{name} ouvre la fenêtre du grenier et le peintre automatique peint le coucher de soleil orange avec ses trois pinceaux à la fois.",
          },
          next: "ending",
        },
        {
          id: "show-drawing",
          title: {
            es: "Enseñarle un dibujo",
            ca: "Ensenyar-li un dibuix",
            en: "Show it a drawing",
            fr: "Lui montrer un dessin",
          },
          desc: {
            es: "Un dibujo nuevo y lleno de colores puede despertar muchas ideas.",
            ca: "Un dibuix nou i ple de colors pot despertar moltes idees.",
            en: "A brand-new drawing full of colours can wake up lots of ideas.",
            fr: "Un dessin tout neuf et plein de couleurs peut réveiller plein d'idées.",
          },
          imageSeed: "inventor-c3atticc-drawing",
          icon: "image",
          narrative: {
            es: "{name} dibuja una fábrica voladora con ceras de colores y se la enseña al pintor, que empieza a pintar emocionado.",
            ca: "{name} dibuixa una fàbrica voladora amb ceres de colors i l'ensenya al pintor, que comença a pintar emocionat.",
            en: "{name} draws a flying factory with colourful crayons and shows it to the painter, who starts painting with excitement.",
            fr: "{name} dessine une fabrique volante avec des craies de couleur et la montre au peintre, qui se met à peindre tout excité.",
          },
          next: "ending",
        },
        {
          id: "new-colour",
          title: {
            es: "Inventar un color nuevo",
            ca: "Inventar un color nou",
            en: "Invent a new colour",
            fr: "Inventer une nouvelle couleur",
          },
          desc: {
            es: "Mezclando pinturas puede nacer un color que nadie ha visto jamás.",
            ca: "Barrejant pintures pot néixer un color que ningú no ha vist mai.",
            en: "Mixing paints can create a colour nobody has ever seen.",
            fr: "En mélangeant les peintures peut naître une couleur que personne n'a jamais vue.",
          },
          imageSeed: "inventor-c3atticc-color",
          icon: "colorize",
          narrative: {
            es: "{name} mezcla pinturas hasta inventar un color nuevo, dorado y azul como una mañana de ideas, y el pintor lo adora.",
            ca: "{name} barreja pintures fins a inventar un color nou, daurat i blau com un matí d'idees, i el pintor l'adora.",
            en: "{name} mixes paints until inventing a brand-new colour, golden and blue like a morning full of ideas, and the painter loves it.",
            fr: "{name} mélange les peintures jusqu'à inventer une couleur toute neuve, dorée et bleue comme un matin plein d'idées, et le peintre l'adore.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "", en: "", fr: "" },
      options: [],
    },
  },
};
