import type { StoryTree } from "./types";

// Branching story tree for the "pirates" template (Piratas del Mar).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es source of truth + ca/en/fr). {name} = child's name.
// Friendly pirate world: no violence, no weapons — treasure hunts, sea friends and teamwork.

export const piratesTree: StoryTree = {
  templateId: "pirates",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} navega en su barco pirata por aguas turquesas, con la brisa hinchando las velas. De pronto, tres sorpresas asoman entre las olas. ¿Cuál descubre primero?",
        ca: "{name} navega amb el seu vaixell pirata per aigües turqueses, amb la brisa inflant les veles. De sobte, tres sorpreses apareixen entre les onades. Quina descobreix primer?",
        en: "{name} sails a pirate ship across turquoise waters, the breeze filling the sails. Suddenly, three surprises peek out between the waves. Which one to discover first?",
        fr: "{name} navigue sur son bateau pirate dans des eaux turquoise, la brise gonflant les voiles. Soudain, trois surprises apparaissent entre les vagues. Laquelle découvrir en premier ?",
      },
      options: [
        {
          id: "dolphin",
          title: {
            es: "El delfín plateado",
            ca: "El dofí platejat",
            en: "The silver dolphin",
            fr: "Le dauphin argenté",
          },
          desc: {
            es: "Un delfín juguetón salta junto al barco como si quisiera decir algo.",
            ca: "Un dofí juganer salta al costat del vaixell com si volgués dir alguna cosa.",
            en: "A playful dolphin leaps beside the ship as if it wants to say something.",
            fr: "Un dauphin joueur saute à côté du bateau comme s'il voulait dire quelque chose.",
          },
          imageSeed: "pirates-c1-dolphin",
          icon: "waves",
          narrative: {
            es: "{name} se asoma por la borda y saluda a Coral, un delfín plateado que salta entre las olas junto al barco.",
            ca: "{name} treu el cap per la borda i saluda en Coral, un dofí platejat que salta entre les onades al costat del vaixell.",
            en: "{name} leans over the rail and waves at Coral, a silver dolphin leaping through the waves beside the ship.",
            fr: "{name} se penche par-dessus le bastingage et salue Coral, un dauphin argenté qui saute entre les vagues à côté du bateau.",
          },
          next: "c2_dolphin",
        },
        {
          id: "bottle-map",
          title: {
            es: "La botella con mapa",
            ca: "L'ampolla amb mapa",
            en: "The bottle with a map",
            fr: "La bouteille à la carte",
          },
          desc: {
            es: "Una botella de cristal flota en el agua con un mapa enrollado dentro.",
            ca: "Una ampolla de vidre sura a l'aigua amb un mapa enrotllat a dins.",
            en: "A glass bottle floats on the water with a rolled-up map inside.",
            fr: "Une bouteille en verre flotte sur l'eau avec une carte enroulée à l'intérieur.",
          },
          imageSeed: "pirates-c1-bottle",
          icon: "map",
          narrative: {
            es: "{name} pesca del agua una botella de cristal y desenrolla con cuidado un mapa del tesoro muy antiguo.",
            ca: "{name} pesca de l'aigua una ampolla de vidre i desenrotlla amb cura un mapa del tresor molt antic.",
            en: "{name} fishes a glass bottle out of the water and carefully unrolls a very old treasure map.",
            fr: "{name} repêche une bouteille en verre et déroule avec précaution une très vieille carte au trésor.",
          },
          next: "c2_map",
        },
        {
          id: "lighthouse-island",
          title: {
            es: "La isla del faro dormido",
            ca: "L'illa del far adormit",
            en: "The sleeping lighthouse island",
            fr: "L'île du phare endormi",
          },
          desc: {
            es: "En una islita cercana, un viejo faro espera apagado y en silencio.",
            ca: "En una illeta propera, un far vell espera apagat i en silenci.",
            en: "On a nearby little island, an old lighthouse waits, dark and silent.",
            fr: "Sur une petite île toute proche, un vieux phare attend, éteint et silencieux.",
          },
          imageSeed: "pirates-c1-lighthouse",
          icon: "landscape",
          narrative: {
            es: "{name} gira el timón hacia una islita donde un viejo faro de rayas rojas y blancas duerme apagado sobre las rocas.",
            ca: "{name} gira el timó cap a una illeta on un far vell de ratlles vermelles i blanques dorm apagat sobre les roques.",
            en: "{name} turns the helm toward a little island where an old red-and-white striped lighthouse sleeps unlit on the rocks.",
            fr: "{name} tourne la barre vers une petite île où un vieux phare à rayures rouges et blanches dort éteint sur les rochers.",
          },
          next: "c2_island",
        },
      ],
    },
    c2_dolphin: {
      id: "c2_dolphin",
      chapter: 2,
      question: {
        es: "Coral cuenta que la Perla Cantarina, la perla que canta nanas a los peces pequeños, ha rodado y se ha perdido. Sin su canción, nadie duerme bien bajo las olas. ¿Dónde la buscan {name} y Coral?",
        ca: "En Coral explica que la Perla Cantaire, la perla que canta cançons de bressol als peixos petits, ha rodolat i s'ha perdut. Sense la seva cançó, ningú no dorm bé sota les onades. On la busquen {name} i en Coral?",
        en: "Coral explains that the Singing Pearl, the pearl that sings lullabies to the little fish, has rolled away and is lost. Without its song, nobody sleeps well beneath the waves. Where do {name} and Coral look for it?",
        fr: "Coral raconte que la Perle Chantante, la perle qui chante des berceuses aux petits poissons, a roulé et s'est perdue. Sans sa chanson, personne ne dort bien sous les vagues. Où {name} et Coral vont-ils la chercher ?",
      },
      options: [
        {
          id: "coral-reef",
          title: {
            es: "El jardín de coral",
            ca: "El jardí de corall",
            en: "The coral garden",
            fr: "Le jardin de corail",
          },
          desc: {
            es: "Un arrecife de mil colores donde se esconden conchas brillantes.",
            ca: "Un escull de mil colors on s'amaguen petxines brillants.",
            en: "A reef of a thousand colours where shiny shells hide.",
            fr: "Un récif aux mille couleurs où se cachent des coquillages brillants.",
          },
          imageSeed: "pirates-c2dolphin-reef",
          icon: "scuba_diving",
          narrative: {
            es: "{name} y Coral bucean hasta un jardín de coral de mil colores, lleno de conchas brillantes y caballitos de mar curiosos.",
            ca: "{name} i en Coral bussegen fins a un jardí de corall de mil colors, ple de petxines brillants i cavallets de mar curiosos.",
            en: "{name} and Coral dive down to a coral garden of a thousand colours, full of shiny shells and curious seahorses.",
            fr: "{name} et Coral plongent jusqu'à un jardin de corail aux mille couleurs, plein de coquillages brillants et d'hippocampes curieux.",
          },
          next: "c3_dolphin_a",
        },
        {
          id: "whale-bay",
          title: {
            es: "La bahía de la ballena",
            ca: "La badia de la balena",
            en: "The whale's bay",
            fr: "La baie de la baleine",
          },
          desc: {
            es: "Dicen que la vieja ballena Bruma recoge todo lo que brilla en el mar.",
            ca: "Diuen que la vella balena Bruma recull tot el que brilla al mar.",
            en: "They say old Bruma the whale collects everything that shines in the sea.",
            fr: "On dit que la vieille baleine Bruma ramasse tout ce qui brille dans la mer.",
          },
          imageSeed: "pirates-c2dolphin-whale",
          icon: "water",
          narrative: {
            es: "{name} y Coral nadan hasta una bahía tranquila donde la vieja ballena Bruma descansa flotando como una isla suave.",
            ca: "{name} i en Coral neden fins a una badia tranquil·la on la vella balena Bruma descansa surant com una illa suau.",
            en: "{name} and Coral swim to a quiet bay where old Bruma the whale rests, floating like a soft island.",
            fr: "{name} et Coral nagent jusqu'à une baie tranquille où la vieille baleine Bruma se repose en flottant comme une île douce.",
          },
          next: "c3_dolphin_b",
        },
        {
          id: "seaweed-forest",
          title: {
            es: "El bosque de algas",
            ca: "El bosc d'algues",
            en: "The seaweed forest",
            fr: "La forêt d'algues",
          },
          desc: {
            es: "Entre las algas altas viven unos cangrejos muy coleccionistas.",
            ca: "Entre les algues altes hi viuen uns crancs molt col·leccionistes.",
            en: "Among the tall seaweed live some very collector-y crabs.",
            fr: "Parmi les hautes algues vivent des crabes très collectionneurs.",
          },
          imageSeed: "pirates-c2dolphin-seaweed",
          icon: "grass",
          narrative: {
            es: "{name} y Coral se adentran en un bosque de algas verdes y doradas que se mecen despacio con la corriente.",
            ca: "{name} i en Coral s'endinsen en un bosc d'algues verdes i daurades que es gronxen a poc a poc amb el corrent.",
            en: "{name} and Coral swim into a forest of green and golden seaweed swaying slowly with the current.",
            fr: "{name} et Coral s'enfoncent dans une forêt d'algues vertes et dorées qui se balancent lentement avec le courant.",
          },
          next: "c3_dolphin_c",
        },
      ],
    },
    c2_map: {
      id: "c2_map",
      chapter: 2,
      question: {
        es: "El mapa muestra la Isla Tortuga y una X roja donde duerme un tesoro escondido. Pero hay tres caminos para llegar hasta la X. ¿Cuál elige {name}?",
        ca: "El mapa mostra l'Illa Tortuga i una X vermella on dorm un tresor amagat. Però hi ha tres camins per arribar fins a la X. Quin tria {name}?",
        en: "The map shows Turtle Island and a red X where a hidden treasure sleeps. But there are three paths to reach the X. Which one does {name} choose?",
        fr: "La carte montre l'Île Tortue et un X rouge où dort un trésor caché. Mais il y a trois chemins pour atteindre le X. Lequel {name} va choisir ?",
      },
      options: [
        {
          id: "singing-cave",
          title: {
            es: "La cueva que canta",
            ca: "La cova que canta",
            en: "The singing cave",
            fr: "La grotte qui chante",
          },
          desc: {
            es: "Un túnel secreto cruza la isla, pero su puerta solo se abre con música.",
            ca: "Un túnel secret travessa l'illa, però la seva porta només s'obre amb música.",
            en: "A secret tunnel crosses the island, but its door only opens with music.",
            fr: "Un tunnel secret traverse l'île, mais sa porte ne s'ouvre qu'en musique.",
          },
          imageSeed: "pirates-c2map-cave",
          icon: "graphic_eq",
          narrative: {
            es: "{name} llega a la entrada de una cueva donde el viento hace silbar las rocas como una flauta gigante.",
            ca: "{name} arriba a l'entrada d'una cova on el vent fa xiular les roques com una flauta gegant.",
            en: "{name} reaches the mouth of a cave where the wind makes the rocks whistle like a giant flute.",
            fr: "{name} arrive à l'entrée d'une grotte où le vent fait siffler les rochers comme une flûte géante.",
          },
          next: "c3_map_a",
        },
        {
          id: "palm-forest",
          title: {
            es: "El bosque de palmeras",
            ca: "El bosc de palmeres",
            en: "The palm tree forest",
            fr: "La forêt de palmiers",
          },
          desc: {
            es: "Un sendero de flechas de madera se adentra entre los cocoteros.",
            ca: "Un corriol de fletxes de fusta s'endinsa entre els cocoters.",
            en: "A trail of wooden arrows winds in among the coconut trees.",
            fr: "Un sentier de flèches en bois s'enfonce entre les cocotiers.",
          },
          imageSeed: "pirates-c2map-palms",
          icon: "forest",
          narrative: {
            es: "{name} sigue un sendero que se adentra en un bosque de palmeras llenas de cocos y de monitos juguetones.",
            ca: "{name} segueix un corriol que s'endinsa en un bosc de palmeres plenes de cocos i de miquets juganers.",
            en: "{name} follows a trail into a forest of palm trees full of coconuts and playful little monkeys.",
            fr: "{name} suit un sentier qui s'enfonce dans une forêt de palmiers remplis de noix de coco et de petits singes joueurs.",
          },
          next: "c3_map_b",
        },
        {
          id: "tide-pools",
          title: {
            es: "Las pozas de la marea",
            ca: "Les basses de la marea",
            en: "The tide pools",
            fr: "Les bassins de marée",
          },
          desc: {
            es: "Un caminito de rocas cruza las pozas llenas de estrellas de mar.",
            ca: "Un caminet de roques travessa les basses plenes d'estrelles de mar.",
            en: "A little rock path crosses the pools full of starfish.",
            fr: "Un petit chemin de rochers traverse les bassins remplis d'étoiles de mer.",
          },
          imageSeed: "pirates-c2map-tidepools",
          icon: "water_drop",
          narrative: {
            es: "{name} bordea la playa hasta unas pozas de agua clarita donde brillan estrellas de mar de colores.",
            ca: "{name} voreja la platja fins a unes basses d'aigua clara on brillen estrelles de mar de colors.",
            en: "{name} follows the beach to some pools of clear water where colourful starfish shine.",
            fr: "{name} longe la plage jusqu'à des bassins d'eau claire où brillent des étoiles de mer colorées.",
          },
          next: "c3_map_c",
        },
      ],
    },
    c2_island: {
      id: "c2_island",
      chapter: 2,
      question: {
        es: "En la playa, una gaviota cuenta que el viejo faro se apagó y ahora los barquitos pesqueros se pierden por la noche. {name} decide encenderlo de nuevo. ¿Dónde busca una luz nueva?",
        ca: "A la platja, una gavina explica que el far vell es va apagar i ara els vaixellets de pesca es perden a la nit. {name} decideix encendre'l de nou. On busca una llum nova?",
        en: "On the beach, a seagull explains that the old lighthouse went out and now the little fishing boats get lost at night. {name} decides to light it again. Where to look for a new light?",
        fr: "Sur la plage, une mouette raconte que le vieux phare s'est éteint et que les petits bateaux de pêche se perdent la nuit. {name} décide de le rallumer. Où chercher une nouvelle lumière ?",
      },
      options: [
        {
          id: "jellyfish-cove",
          title: {
            es: "La cala de las medusas",
            ca: "La cala de les meduses",
            en: "The jellyfish cove",
            fr: "La crique aux méduses",
          },
          desc: {
            es: "Unas medusas brillantes iluminan el agua como farolillos.",
            ca: "Unes meduses brillants il·luminen l'aigua com fanalets.",
            en: "Glowing jellyfish light up the water like little lanterns.",
            fr: "Des méduses lumineuses éclairent l'eau comme des lampions.",
          },
          imageSeed: "pirates-c2island-jellyfish",
          icon: "blur_on",
          narrative: {
            es: "{name} llega a una cala escondida donde unas medusas brillantes flotan iluminando el agua como farolillos de colores.",
            ca: "{name} arriba a una cala amagada on unes meduses brillants suren il·luminant l'aigua com fanalets de colors.",
            en: "{name} reaches a hidden cove where glowing jellyfish float, lighting the water like colourful little lanterns.",
            fr: "{name} arrive dans une crique cachée où des méduses lumineuses flottent en éclairant l'eau comme des lampions colorés.",
          },
          next: "c3_island_a",
        },
        {
          id: "moon-shell",
          title: {
            es: "La concha de luna",
            ca: "La petxina de lluna",
            en: "The moon shell",
            fr: "Le coquillage de lune",
          },
          desc: {
            es: "Cuentan que en la playa hay una concha que brilla como la luna llena.",
            ca: "Diuen que a la platja hi ha una petxina que brilla com la lluna plena.",
            en: "They say there is a shell on the beach that shines like the full moon.",
            fr: "On dit qu'il y a sur la plage un coquillage qui brille comme la pleine lune.",
          },
          imageSeed: "pirates-c2island-moonshell",
          icon: "nightlight",
          narrative: {
            es: "{name} camina por la playa al atardecer buscando la concha de luna, escondida entre miles de conchas.",
            ca: "{name} camina per la platja al capvespre buscant la petxina de lluna, amagada entre milers de petxines.",
            en: "{name} walks along the beach at sunset looking for the moon shell, hidden among thousands of shells.",
            fr: "{name} marche sur la plage au coucher du soleil à la recherche du coquillage de lune, caché parmi des milliers de coquillages.",
          },
          next: "c3_island_b",
        },
        {
          id: "octopus-workshop",
          title: {
            es: "El taller del pulpo Octavio",
            ca: "El taller del pop Octavio",
            en: "Octavio the octopus's workshop",
            fr: "L'atelier du poulpe Octavio",
          },
          desc: {
            es: "El antiguo farero guarda una lámpara de repuesto... en alguna parte.",
            ca: "L'antic farer guarda una làmpada de recanvi... en algun lloc.",
            en: "The old lighthouse keeper has a spare lamp... somewhere.",
            fr: "L'ancien gardien du phare garde une lampe de rechange... quelque part.",
          },
          imageSeed: "pirates-c2island-workshop",
          icon: "construction",
          narrative: {
            es: "{name} visita el taller del pulpo Octavio, el antiguo farero, lleno de cuerdas, catalejos y cachivaches por todas partes.",
            ca: "{name} visita el taller del pop Octavio, l'antic farer, ple de cordes, ulleres de llarga vista i andròmines per tot arreu.",
            en: "{name} visits the workshop of Octavio the octopus, the old lighthouse keeper, full of ropes, spyglasses and bits and bobs everywhere.",
            fr: "{name} visite l'atelier du poulpe Octavio, l'ancien gardien du phare, rempli de cordes, de longues-vues et de bric-à-brac partout.",
          },
          next: "c3_island_c",
        },
      ],
    },
    c3_dolphin_a: {
      id: "c3_dolphin_a",
      chapter: 3,
      question: {
        es: "¡La perla está en el jardín de coral! Pero se esconde dentro de una de las cientos de conchas cerradas. ¿Cómo encuentra {name} la concha correcta?",
        ca: "La perla és al jardí de corall! Però s'amaga dins d'una de les centenars de petxines tancades. Com troba {name} la petxina correcta?",
        en: "The pearl is in the coral garden! But it hides inside one of the hundreds of closed shells. How does {name} find the right shell?",
        fr: "La perle est dans le jardin de corail ! Mais elle se cache dans l'un des centaines de coquillages fermés. Comment {name} trouve le bon coquillage ?",
      },
      options: [
        {
          id: "listen-song",
          title: {
            es: "Escuchar su nana",
            ca: "Escoltar la seva cançó de bressol",
            en: "Listen for its lullaby",
            fr: "Écouter sa berceuse",
          },
          desc: {
            es: "La Perla Cantarina canturrea bajito incluso dormida.",
            ca: "La Perla Cantaire cantusseja fluixet fins i tot adormida.",
            en: "The Singing Pearl hums softly even in its sleep.",
            fr: "La Perle Chantante fredonne tout bas même endormie.",
          },
          imageSeed: "pirates-c3dolphina-listen",
          icon: "hearing",
          narrative: {
            es: "{name} contiene la respiración, escucha con atención y oye una nana dulce que sale de una concha rosada.",
            ca: "{name} aguanta la respiració, escolta amb atenció i sent una cançó de bressol dolça que surt d'una petxina rosada.",
            en: "{name} holds their breath, listens carefully and hears a sweet lullaby coming from a pink shell.",
            fr: "{name} retient son souffle, écoute attentivement et entend une douce berceuse qui sort d'un coquillage rose.",
          },
          next: "ending",
        },
        {
          id: "follow-glow",
          title: {
            es: "Seguir su brillo rosado",
            ca: "Seguir la seva lluentor rosada",
            en: "Follow its pink glow",
            fr: "Suivre sa lueur rose",
          },
          desc: {
            es: "Un resplandor suave se cuela entre las conchas.",
            ca: "Una resplendor suau s'escola entre les petxines.",
            en: "A soft glow slips out between the shells.",
            fr: "Une douce lueur se faufile entre les coquillages.",
          },
          imageSeed: "pirates-c3dolphina-glow",
          icon: "flare",
          narrative: {
            es: "{name} sigue un resplandor rosado que se cuela entre los corales y abre despacio la concha donde duerme la perla.",
            ca: "{name} segueix una resplendor rosada que s'escola entre els coralls i obre a poc a poc la petxina on dorm la perla.",
            en: "{name} follows a pink glow slipping between the corals and slowly opens the shell where the pearl sleeps.",
            fr: "{name} suit une lueur rose qui se faufile entre les coraux et ouvre doucement le coquillage où dort la perle.",
          },
          next: "ending",
        },
        {
          id: "ask-starfish",
          title: {
            es: "Preguntar a la estrella de mar",
            ca: "Preguntar a l'estrella de mar",
            en: "Ask the starfish",
            fr: "Demander à l'étoile de mer",
          },
          desc: {
            es: "La estrella de mar sabia conoce cada rincón del arrecife.",
            ca: "L'estrella de mar sàvia coneix cada racó de l'escull.",
            en: "The wise starfish knows every corner of the reef.",
            fr: "L'étoile de mer sage connaît chaque recoin du récif.",
          },
          imageSeed: "pirates-c3dolphina-starfish",
          icon: "star",
          narrative: {
            es: "{name} pregunta a la estrella de mar sabia, que señala con uno de sus brazos la concha donde duerme la perla.",
            ca: "{name} pregunta a l'estrella de mar sàvia, que assenyala amb un dels seus braços la petxina on dorm la perla.",
            en: "{name} asks the wise starfish, who points with one of its arms to the shell where the pearl sleeps.",
            fr: "{name} demande à l'étoile de mer sage, qui montre avec l'un de ses bras le coquillage où dort la perle.",
          },
          next: "ending",
        },
      ],
    },
    c3_dolphin_b: {
      id: "c3_dolphin_b",
      chapter: 3,
      question: {
        es: "La Perla Cantarina descansa sobre el lomo de la ballena Bruma... ¡pero Bruma está profundamente dormida! ¿Cómo la despierta {name} sin asustarla?",
        ca: "La Perla Cantaire descansa sobre el llom de la balena Bruma... però la Bruma està profundament adormida! Com la desperta {name} sense espantar-la?",
        en: "The Singing Pearl rests on Bruma the whale's back... but Bruma is fast asleep! How does {name} wake her without startling her?",
        fr: "La Perle Chantante repose sur le dos de la baleine Bruma... mais Bruma dort profondément ! Comment {name} la réveille sans l'effrayer ?",
      },
      options: [
        {
          id: "sailor-song",
          title: {
            es: "Cantarle una canción marinera",
            ca: "Cantar-li una cançó marinera",
            en: "Sing her a sailor's song",
            fr: "Lui chanter une chanson de marin",
          },
          desc: {
            es: "Una canción alegre y suave que las ballenas adoran.",
            ca: "Una cançó alegre i suau que les balenes adoren.",
            en: "A happy, gentle song that whales adore.",
            fr: "Une chanson joyeuse et douce que les baleines adorent.",
          },
          imageSeed: "pirates-c3dolphinb-song",
          icon: "music_note",
          narrative: {
            es: "{name} canta bajito una canción marinera y Bruma abre un ojo enorme, sonríe y acerca la perla con su aleta.",
            ca: "{name} canta fluixet una cançó marinera i la Bruma obre un ull enorme, somriu i acosta la perla amb la seva aleta.",
            en: "{name} softly sings a sailor's song and Bruma opens one huge eye, smiles and nudges the pearl over with her fin.",
            fr: "{name} chante tout bas une chanson de marin et Bruma ouvre un œil énorme, sourit et approche la perle avec sa nageoire.",
          },
          next: "ending",
        },
        {
          id: "gentle-bubbles",
          title: {
            es: "Soplar burbujas suaves",
            ca: "Bufar bombolles suaus",
            en: "Blow gentle bubbles",
            fr: "Souffler de douces bulles",
          },
          desc: {
            es: "Unas burbujitas de cosquillas son el despertador más amable del mar.",
            ca: "Unes bombolletes de pessigolles són el despertador més amable del mar.",
            en: "Ticklish little bubbles are the kindest alarm clock in the sea.",
            fr: "De petites bulles qui chatouillent, le réveil le plus gentil de la mer.",
          },
          imageSeed: "pirates-c3dolphinb-bubbles",
          icon: "bubble_chart",
          narrative: {
            es: "{name} sopla burbujitas que suben haciendo cosquillas en la barriga de Bruma, y la ballena despierta entre risas y entrega la perla.",
            ca: "{name} bufa bombolletes que pugen fent pessigolles a la panxa de la Bruma, i la balena es desperta rient i dona la perla.",
            en: "{name} blows little bubbles that float up and tickle Bruma's tummy, and the whale wakes up giggling and hands over the pearl.",
            fr: "{name} souffle de petites bulles qui montent en chatouillant le ventre de Bruma, et la baleine se réveille en riant et donne la perle.",
          },
          next: "ending",
        },
        {
          id: "soft-whisper",
          title: {
            es: "Susurrarle buenos días",
            ca: "Xiuxiuejar-li bon dia",
            en: "Whisper good morning",
            fr: "Lui chuchoter bonjour",
          },
          desc: {
            es: "Un saludo amable dicho muy bajito llega hasta los sueños.",
            ca: "Una salutació amable dita molt fluixet arriba fins als somnis.",
            en: "A kind hello said very softly reaches all the way into dreams.",
            fr: "Un gentil bonjour dit tout bas arrive jusque dans les rêves.",
          },
          imageSeed: "pirates-c3dolphinb-whisper",
          icon: "record_voice_over",
          narrative: {
            es: "{name} se acerca despacio y susurra 'buenos días, Bruma' tan dulcemente que la ballena despierta contenta y regala la perla.",
            ca: "{name} s'acosta a poc a poc i xiuxiueja 'bon dia, Bruma' tan dolçament que la balena es desperta contenta i regala la perla.",
            en: "{name} swims up slowly and whispers 'good morning, Bruma' so sweetly that the whale wakes up happy and gifts the pearl.",
            fr: "{name} s'approche lentement et chuchote « bonjour, Bruma » si doucement que la baleine se réveille contente et offre la perle.",
          },
          next: "ending",
        },
      ],
    },
    c3_dolphin_c: {
      id: "c3_dolphin_c",
      chapter: 3,
      question: {
        es: "¡Los cangrejos coleccionistas han encontrado la perla y la han puesto en su jardín de tesoros! La cuidan mucho y no quieren darla así como así. ¿Qué hace {name}?",
        ca: "Els crancs col·leccionistes han trobat la perla i l'han posada al seu jardí de tresors! La cuiden molt i no la volen donar així com així. Què fa {name}?",
        en: "The collector crabs have found the pearl and put it in their treasure garden! They take great care of it and won't just hand it over. What does {name} do?",
        fr: "Les crabes collectionneurs ont trouvé la perle et l'ont mise dans leur jardin aux trésors ! Ils en prennent grand soin et ne veulent pas la donner comme ça. Que fait {name} ?",
      },
      options: [
        {
          id: "tidy-garden",
          title: {
            es: "Ordenar su jardín de tesoros",
            ca: "Endreçar el seu jardí de tresors",
            en: "Tidy their treasure garden",
            fr: "Ranger leur jardin aux trésors",
          },
          desc: {
            es: "Las corrientes lo han dejado todo patas arriba.",
            ca: "Els corrents ho han deixat tot potes enlaire.",
            en: "The currents have turned everything upside down.",
            fr: "Les courants ont tout mis sens dessus dessous.",
          },
          imageSeed: "pirates-c3dolphinc-tidy",
          icon: "cleaning_services",
          narrative: {
            es: "{name} ayuda a los cangrejos a ordenar su jardín de conchas y piedras brillantes y, agradecidos, le regalan la perla.",
            ca: "{name} ajuda els crancs a endreçar el seu jardí de petxines i pedres brillants i, agraïts, li regalen la perla.",
            en: "{name} helps the crabs tidy their garden of shells and shiny pebbles and, grateful, they gift the pearl.",
            fr: "{name} aide les crabes à ranger leur jardin de coquillages et de pierres brillantes et, reconnaissants, ils offrent la perle.",
          },
          next: "ending",
        },
        {
          id: "shiny-button",
          title: {
            es: "Cambiarla por un botón dorado",
            ca: "Canviar-la per un botó daurat",
            en: "Trade it for a golden button",
            fr: "L'échanger contre un bouton doré",
          },
          desc: {
            es: "Un botón dorado de chaqueta pirata es un tesoro magnífico.",
            ca: "Un botó daurat de jaqueta pirata és un tresor magnífic.",
            en: "A golden button from a pirate jacket is a magnificent treasure.",
            fr: "Un bouton doré de veste de pirate, voilà un trésor magnifique.",
          },
          imageSeed: "pirates-c3dolphinc-button",
          icon: "swap_horiz",
          narrative: {
            es: "{name} ofrece a los cangrejos un botón dorado de su chaqueta pirata y ellos, encantados, lo cambian por la perla.",
            ca: "{name} ofereix als crancs un botó daurat de la seva jaqueta pirata i ells, encantats, el canvien per la perla.",
            en: "{name} offers the crabs a golden button from their pirate jacket and they happily trade it for the pearl.",
            fr: "{name} offre aux crabes un bouton doré de sa veste de pirate et ceux-ci, ravis, l'échangent contre la perle.",
          },
          next: "ending",
        },
        {
          id: "beach-race",
          title: {
            es: "Una carrera por la arena",
            ca: "Una cursa per la sorra",
            en: "A race along the sand",
            fr: "Une course sur le sable",
          },
          desc: {
            es: "Si {name} gana, la perla será el premio.",
            ca: "Si {name} guanya, la perla serà el premi.",
            en: "If {name} wins, the pearl is the prize.",
            fr: "Si {name} gagne, la perle sera le prix.",
          },
          imageSeed: "pirates-c3dolphinc-race",
          icon: "directions_run",
          narrative: {
            es: "{name} corre de lado por la arena como un cangrejo más, gana la carrera entre risas y recibe la perla de premio.",
            ca: "{name} corre de costat per la sorra com un cranc més, guanya la cursa entre riures i rep la perla de premi.",
            en: "{name} runs sideways along the sand just like a crab, wins the race amid laughter and receives the pearl as a prize.",
            fr: "{name} court de côté sur le sable comme un vrai crabe, gagne la course dans les rires et reçoit la perle en récompense.",
          },
          next: "ending",
        },
      ],
    },
    c3_map_a: {
      id: "c3_map_a",
      chapter: 3,
      question: {
        es: "La puerta de piedra de la cueva solo se abre si oye la melodía del mar. ¿Cómo hace música {name}?",
        ca: "La porta de pedra de la cova només s'obre si sent la melodia del mar. Com fa música {name}?",
        en: "The cave's stone door only opens if it hears the melody of the sea. How does {name} make music?",
        fr: "La porte de pierre de la grotte ne s'ouvre que si elle entend la mélodie de la mer. Comment {name} fait de la musique ?",
      },
      options: [
        {
          id: "wind-whistle",
          title: {
            es: "Silbar como el viento",
            ca: "Xiular com el vent",
            en: "Whistle like the wind",
            fr: "Siffler comme le vent",
          },
          desc: {
            es: "Un silbido suave que sube y baja como las olas.",
            ca: "Un xiulet suau que puja i baixa com les onades.",
            en: "A soft whistle that rises and falls like the waves.",
            fr: "Un sifflement doux qui monte et descend comme les vagues.",
          },
          imageSeed: "pirates-c3mapa-whistle",
          icon: "air",
          narrative: {
            es: "{name} silba una melodía que sube y baja como las olas y la puerta de piedra se abre despacito, mostrando el camino hacia la X.",
            ca: "{name} xiula una melodia que puja i baixa com les onades i la porta de pedra s'obre a poc a poc, mostrant el camí cap a la X.",
            en: "{name} whistles a melody that rises and falls like the waves and the stone door slowly opens, revealing the path to the X.",
            fr: "{name} siffle une mélodie qui monte et descend comme les vagues et la porte de pierre s'ouvre lentement, révélant le chemin vers le X.",
          },
          next: "ending",
        },
        {
          id: "shell-trumpet",
          title: {
            es: "Tocar una caracola",
            ca: "Tocar un corn marí",
            en: "Play a conch shell",
            fr: "Jouer de la conque",
          },
          desc: {
            es: "Una caracola grande suena como una trompeta del mar.",
            ca: "Un corn marí gros sona com una trompeta del mar.",
            en: "A big conch shell sounds like a trumpet of the sea.",
            fr: "Une grande conque sonne comme une trompette de la mer.",
          },
          imageSeed: "pirates-c3mapa-trumpet",
          icon: "campaign",
          narrative: {
            es: "{name} sopla una caracola gigante que suena como una trompeta y la cueva entera responde abriendo su puerta de piedra.",
            ca: "{name} bufa un corn marí gegant que sona com una trompeta i la cova sencera respon obrint la seva porta de pedra.",
            en: "{name} blows a giant conch shell that sounds like a trumpet and the whole cave answers by opening its stone door.",
            fr: "{name} souffle dans une conque géante qui sonne comme une trompette et toute la grotte répond en ouvrant sa porte de pierre.",
          },
          next: "ending",
        },
        {
          id: "clap-rhythm",
          title: {
            es: "Marcar el ritmo con palmas",
            ca: "Marcar el ritme amb palmes",
            en: "Clap out a rhythm",
            fr: "Taper le rythme dans ses mains",
          },
          desc: {
            es: "El eco de la cueva adora los juegos de ritmo.",
            ca: "L'eco de la cova adora els jocs de ritme.",
            en: "The cave's echo loves rhythm games.",
            fr: "L'écho de la grotte adore les jeux de rythme.",
          },
          imageSeed: "pirates-c3mapa-clap",
          icon: "back_hand",
          narrative: {
            es: "{name} da palmas siguiendo el ritmo de las olas y el eco repite la música hasta que la puerta de piedra se abre.",
            ca: "{name} pica de mans seguint el ritme de les onades i l'eco repeteix la música fins que la porta de pedra s'obre.",
            en: "{name} claps along to the rhythm of the waves and the echo repeats the music until the stone door swings open.",
            fr: "{name} tape dans ses mains au rythme des vagues et l'écho répète la musique jusqu'à ce que la porte de pierre s'ouvre.",
          },
          next: "ending",
        },
      ],
    },
    c3_map_b: {
      id: "c3_map_b",
      chapter: 3,
      question: {
        es: "¡Los monitos juguetones han escondido las flechas de madera que marcan el camino hacia la X! ¿Cómo recupera {name} el sendero?",
        ca: "Els miquets juganers han amagat les fletxes de fusta que marquen el camí cap a la X! Com recupera {name} el corriol?",
        en: "The playful little monkeys have hidden the wooden arrows that mark the way to the X! How does {name} get the trail back?",
        fr: "Les petits singes joueurs ont caché les flèches en bois qui marquent le chemin vers le X ! Comment {name} retrouve le sentier ?",
      },
      options: [
        {
          id: "banana-trade",
          title: {
            es: "Cambiarlas por plátanos",
            ca: "Canviar-les per plàtans",
            en: "Trade them for bananas",
            fr: "Les échanger contre des bananes",
          },
          desc: {
            es: "Un buen racimo de plátanos es el mejor trato de la isla.",
            ca: "Un bon ram de plàtans és el millor tracte de l'illa.",
            en: "A good bunch of bananas is the best deal on the island.",
            fr: "Un beau régime de bananes, le meilleur marché de l'île.",
          },
          imageSeed: "pirates-c3mapb-bananas",
          icon: "nutrition",
          narrative: {
            es: "{name} ofrece a los monitos un racimo de plátanos maduros y ellos devuelven las flechas de madera entre saltos de alegría.",
            ca: "{name} ofereix als miquets un ram de plàtans madurs i ells tornen les fletxes de fusta entre salts d'alegria.",
            en: "{name} offers the little monkeys a bunch of ripe bananas and they return the wooden arrows with joyful leaps.",
            fr: "{name} offre aux petits singes un régime de bananes mûres et ceux-ci rendent les flèches en bois en sautant de joie.",
          },
          next: "ending",
        },
        {
          id: "follow-footprints",
          title: {
            es: "Seguir sus huellas",
            ca: "Seguir les seves petjades",
            en: "Follow their footprints",
            fr: "Suivre leurs empreintes",
          },
          desc: {
            es: "Las patitas de los monitos dejan huellas en la arena.",
            ca: "Les potetes dels miquets deixen petjades a la sorra.",
            en: "The monkeys' little feet leave tracks in the sand.",
            fr: "Les petites pattes des singes laissent des traces dans le sable.",
          },
          imageSeed: "pirates-c3mapb-footprints",
          icon: "footprint",
          narrative: {
            es: "{name} sigue las huellas pequeñitas en la arena hasta el escondite de los monitos y recupera las flechas de madera.",
            ca: "{name} segueix les petjades petitones a la sorra fins a l'amagatall dels miquets i recupera les fletxes de fusta.",
            en: "{name} follows the tiny footprints in the sand to the monkeys' hiding place and gets the wooden arrows back.",
            fr: "{name} suit les toutes petites empreintes dans le sable jusqu'à la cachette des singes et récupère les flèches en bois.",
          },
          next: "ending",
        },
        {
          id: "coconut-juggle",
          title: {
            es: "Hacer malabares con cocos",
            ca: "Fer malabars amb cocos",
            en: "Juggle coconuts",
            fr: "Jongler avec des noix de coco",
          },
          desc: {
            es: "A los monitos les encantan los espectáculos divertidos.",
            ca: "Als miquets els encanten els espectacles divertits.",
            en: "The little monkeys love a funny show.",
            fr: "Les petits singes adorent les spectacles amusants.",
          },
          imageSeed: "pirates-c3mapb-juggle",
          icon: "mood",
          narrative: {
            es: "{name} hace malabares con tres cocos pequeños y los monitos aplauden tan contentos que devuelven todas las flechas.",
            ca: "{name} fa malabars amb tres cocos petits i els miquets aplaudeixen tan contents que tornen totes les fletxes.",
            en: "{name} juggles three small coconuts and the little monkeys clap so happily that they give back all the arrows.",
            fr: "{name} jongle avec trois petites noix de coco et les singes applaudissent si fort qu'ils rendent toutes les flèches.",
          },
          next: "ending",
        },
      ],
    },
    c3_map_c: {
      id: "c3_map_c",
      chapter: 3,
      question: {
        es: "Para llegar a la X hay que cruzar las pozas, pero la marea ha subido y el caminito de rocas ha desaparecido bajo el agua. ¿Cómo cruza {name}?",
        ca: "Per arribar a la X cal travessar les basses, però la marea ha pujat i el caminet de roques ha desaparegut sota l'aigua. Com travessa {name}?",
        en: "To reach the X you have to cross the pools, but the tide has come in and the little rock path has disappeared underwater. How does {name} cross?",
        fr: "Pour atteindre le X, il faut traverser les bassins, mais la marée est montée et le petit chemin de rochers a disparu sous l'eau. Comment {name} va traverser ?",
      },
      options: [
        {
          id: "driftwood-raft",
          title: {
            es: "Construir una balsita",
            ca: "Construir un raiet",
            en: "Build a little raft",
            fr: "Construire un petit radeau",
          },
          desc: {
            es: "Con maderitas de la playa y un nudo marinero bien hecho.",
            ca: "Amb fustetes de la platja i un nus mariner ben fet.",
            en: "With driftwood from the beach and a well-tied sailor's knot.",
            fr: "Avec du bois flotté de la plage et un nœud marin bien fait.",
          },
          imageSeed: "pirates-c3mapc-raft",
          icon: "handyman",
          narrative: {
            es: "{name} ata maderitas de la playa con un nudo marinero, construye una balsita y cruza remando las pozas hasta la X.",
            ca: "{name} lliga fustetes de la platja amb un nus mariner, construeix un raiet i travessa les basses remant fins a la X.",
            en: "{name} ties driftwood together with a sailor's knot, builds a little raft and paddles across the pools to the X.",
            fr: "{name} attache du bois flotté avec un nœud marin, construit un petit radeau et traverse les bassins en ramant jusqu'au X.",
          },
          next: "ending",
        },
        {
          id: "turtle-ride",
          title: {
            es: "Pedir ayuda a las tortugas",
            ca: "Demanar ajuda a les tortugues",
            en: "Ask the turtles for help",
            fr: "Demander de l'aide aux tortues",
          },
          desc: {
            es: "Las tortugas marinas conocen el camino entre las pozas.",
            ca: "Les tortugues marines coneixen el camí entre les basses.",
            en: "The sea turtles know the way between the pools.",
            fr: "Les tortues de mer connaissent le chemin entre les bassins.",
          },
          imageSeed: "pirates-c3mapc-turtle",
          icon: "pets",
          narrative: {
            es: "{name} sube al caparazón de una tortuga marina amable, que nada despacito entre las pozas hasta la orilla de la X.",
            ca: "{name} puja a la closca d'una tortuga marina amable, que neda a poc a poc entre les basses fins a la vora de la X.",
            en: "{name} climbs onto the shell of a kind sea turtle, who swims slowly between the pools to the shore of the X.",
            fr: "{name} monte sur la carapace d'une gentille tortue de mer, qui nage doucement entre les bassins jusqu'au rivage du X.",
          },
          next: "ending",
        },
        {
          id: "rope-bridge",
          title: {
            es: "Un puente de cuerda",
            ca: "Un pont de corda",
            en: "A rope bridge",
            fr: "Un pont de corde",
          },
          desc: {
            es: "Con la cuerda del barco y dos palmeras se hace un puente pirata.",
            ca: "Amb la corda del vaixell i dues palmeres es fa un pont pirata.",
            en: "With the ship's rope and two palm trees you can make a pirate bridge.",
            fr: "Avec la corde du bateau et deux palmiers, on fait un pont de pirate.",
          },
          imageSeed: "pirates-c3mapc-bridge",
          icon: "cable",
          narrative: {
            es: "{name} ata la cuerda del barco entre dos palmeras y cruza despacito por encima del agua como en la cuerda floja.",
            ca: "{name} lliga la corda del vaixell entre dues palmeres i travessa a poc a poc per sobre de l'aigua com a la corda fluixa.",
            en: "{name} ties the ship's rope between two palm trees and crosses slowly above the water like a tightrope walker.",
            fr: "{name} attache la corde du bateau entre deux palmiers et traverse doucement au-dessus de l'eau comme sur un fil de funambule.",
          },
          next: "ending",
        },
      ],
    },
    c3_island_a: {
      id: "c3_island_a",
      chapter: 3,
      question: {
        es: "Las medusas brillan precioso, pero son tímidas y nunca han salido de su cala. ¿Cómo invita {name} a una medusa a vivir en lo alto del faro?",
        ca: "Les meduses brillen precioses, però són tímides i mai no han sortit de la seva cala. Com convida {name} una medusa a viure a dalt del far?",
        en: "The jellyfish glow beautifully, but they are shy and have never left their cove. How does {name} invite a jellyfish to live at the top of the lighthouse?",
        fr: "Les méduses brillent magnifiquement, mais elles sont timides et n'ont jamais quitté leur crique. Comment {name} invite une méduse à vivre en haut du phare ?",
      },
      options: [
        {
          id: "jar-lantern",
          title: {
            es: "Un farolillo viajero",
            ca: "Un fanalet viatger",
            en: "A travelling lantern",
            fr: "Un lampion voyageur",
          },
          desc: {
            es: "Un tarro de cristal con agua de mar es una casita perfecta para el viaje.",
            ca: "Un pot de vidre amb aigua de mar és una caseta perfecta per al viatge.",
            en: "A glass jar with seawater makes a perfect little home for the trip.",
            fr: "Un bocal en verre avec de l'eau de mer, une parfaite petite maison pour le voyage.",
          },
          imageSeed: "pirates-c3islanda-lantern",
          icon: "lightbulb",
          narrative: {
            es: "{name} prepara un tarro de cristal con agua de mar y la medusa más valiente se acomoda dentro para viajar hasta el faro.",
            ca: "{name} prepara un pot de vidre amb aigua de mar i la medusa més valenta s'hi acomoda per viatjar fins al far.",
            en: "{name} prepares a glass jar with seawater and the bravest jellyfish settles inside to travel up to the lighthouse.",
            fr: "{name} prépare un bocal en verre avec de l'eau de mer et la méduse la plus courageuse s'y installe pour voyager jusqu'au phare.",
          },
          next: "ending",
        },
        {
          id: "tide-song",
          title: {
            es: "La canción de la marea",
            ca: "La cançó de la marea",
            en: "The song of the tide",
            fr: "La chanson de la marée",
          },
          desc: {
            es: "Las medusas bailan cuando oyen la melodía de las olas.",
            ca: "Les meduses ballen quan senten la melodia de les onades.",
            en: "Jellyfish dance when they hear the melody of the waves.",
            fr: "Les méduses dansent quand elles entendent la mélodie des vagues.",
          },
          imageSeed: "pirates-c3islanda-song",
          icon: "queue_music",
          narrative: {
            es: "{name} canta la canción de la marea y la medusa más curiosa baila siguiendo la música hasta la lámpara del faro.",
            ca: "{name} canta la cançó de la marea i la medusa més curiosa balla seguint la música fins a la llanterna del far.",
            en: "{name} sings the song of the tide and the most curious jellyfish dances along to the music all the way up to the lighthouse lamp.",
            fr: "{name} chante la chanson de la marée et la méduse la plus curieuse danse en suivant la musique jusqu'à la lampe du phare.",
          },
          next: "ending",
        },
        {
          id: "sea-window",
          title: {
            es: "Prometerle vistas al mar",
            ca: "Prometre-li vistes al mar",
            en: "Promise it a sea view",
            fr: "Lui promettre une vue sur la mer",
          },
          desc: {
            es: "Desde lo alto del faro se ve el mar entero.",
            ca: "Des de dalt del far es veu tot el mar sencer.",
            en: "From the top of the lighthouse you can see the whole sea.",
            fr: "Du haut du phare, on voit la mer tout entière.",
          },
          imageSeed: "pirates-c3islanda-window",
          icon: "window",
          narrative: {
            es: "{name} cuenta a las medusas que desde la lámpara del faro se ve el mar entero, y la más soñadora decide mudarse allí encantada.",
            ca: "{name} explica a les meduses que des de la llanterna del far es veu tot el mar, i la més somiadora decideix mudar-s'hi encantada.",
            en: "{name} tells the jellyfish that from the lighthouse lamp you can see the whole sea, and the dreamiest one happily decides to move in.",
            fr: "{name} raconte aux méduses que depuis la lampe du phare on voit la mer tout entière, et la plus rêveuse décide ravie de s'y installer.",
          },
          next: "ending",
        },
      ],
    },
    c3_island_b: {
      id: "c3_island_b",
      chapter: 3,
      question: {
        es: "¡Hay miles de conchas en la playa y todas parecen iguales! Solo una es la concha de luna. ¿Cómo la encuentra {name}?",
        ca: "Hi ha milers de petxines a la platja i totes semblen iguals! Només una és la petxina de lluna. Com la troba {name}?",
        en: "There are thousands of shells on the beach and they all look the same! Only one is the moon shell. How does {name} find it?",
        fr: "Il y a des milliers de coquillages sur la plage et ils se ressemblent tous ! Un seul est le coquillage de lune. Comment {name} le trouve ?",
      },
      options: [
        {
          id: "moonrise",
          title: {
            es: "Esperar a que salga la luna",
            ca: "Esperar que surti la lluna",
            en: "Wait for the moon to rise",
            fr: "Attendre le lever de la lune",
          },
          desc: {
            es: "Cuando la luna asoma, su concha le contesta brillando.",
            ca: "Quan la lluna apareix, la seva petxina li contesta brillant.",
            en: "When the moon appears, its shell answers back with a glow.",
            fr: "Quand la lune apparaît, son coquillage lui répond en brillant.",
          },
          imageSeed: "pirates-c3islandb-moonrise",
          icon: "dark_mode",
          narrative: {
            es: "{name} espera a que la luna asome sobre el mar y, de pronto, una conchita responde brillando con luz de plata.",
            ca: "{name} espera que la lluna aparegui sobre el mar i, de sobte, una petxineta respon brillant amb llum de plata.",
            en: "{name} waits for the moon to peek over the sea and, suddenly, one little shell answers, glowing with silver light.",
            fr: "{name} attend que la lune apparaisse au-dessus de la mer et, soudain, un petit coquillage répond en brillant d'une lumière argentée.",
          },
          next: "ending",
        },
        {
          id: "hermit-crabs",
          title: {
            es: "Preguntar a los cangrejos ermitaños",
            ca: "Preguntar als crancs ermitans",
            en: "Ask the hermit crabs",
            fr: "Demander aux bernard-l'ermite",
          },
          desc: {
            es: "Ellos conocen todas las conchas de la playa: ¡viven dentro!",
            ca: "Ells coneixen totes les petxines de la platja: hi viuen a dins!",
            en: "They know every shell on the beach — they live inside them!",
            fr: "Ils connaissent tous les coquillages de la plage : ils vivent dedans !",
          },
          imageSeed: "pirates-c3islandb-crabs",
          icon: "home",
          narrative: {
            es: "{name} pregunta a los cangrejos ermitaños y el más viejito guía un desfile de conchitas andantes hasta la concha de luna.",
            ca: "{name} pregunta als crancs ermitans i el més velleta guia una desfilada de petxinetes caminadores fins a la petxina de lluna.",
            en: "{name} asks the hermit crabs and the oldest one leads a parade of walking little shells straight to the moon shell.",
            fr: "{name} demande aux bernard-l'ermite et le plus vieux guide un défilé de petits coquillages marcheurs jusqu'au coquillage de lune.",
          },
          next: "ending",
        },
        {
          id: "sand-moon",
          title: {
            es: "Dibujar una luna en la arena",
            ca: "Dibuixar una lluna a la sorra",
            en: "Draw a moon in the sand",
            fr: "Dessiner une lune dans le sable",
          },
          desc: {
            es: "Quizá la concha quiera acercarse a su dibujo favorito.",
            ca: "Potser la petxina voldrà acostar-se al seu dibuix preferit.",
            en: "Maybe the shell will want to come close to its favourite drawing.",
            fr: "Peut-être que le coquillage voudra s'approcher de son dessin préféré.",
          },
          imageSeed: "pirates-c3islandb-sandmoon",
          icon: "draw",
          narrative: {
            es: "{name} dibuja una luna enorme en la arena con un palito y la concha de luna rueda solita hasta el centro del dibujo.",
            ca: "{name} dibuixa una lluna enorme a la sorra amb un bastonet i la petxina de lluna rodola tota sola fins al centre del dibuix.",
            en: "{name} draws a huge moon in the sand with a little stick and the moon shell rolls all by itself to the centre of the drawing.",
            fr: "{name} dessine une lune énorme dans le sable avec un petit bâton et le coquillage de lune roule tout seul jusqu'au centre du dessin.",
          },
          next: "ending",
        },
      ],
    },
    c3_island_c: {
      id: "c3_island_c",
      chapter: 3,
      question: {
        es: "Octavio tiene una lámpara mágica de repuesto, ¡pero su taller está tan desordenado que no recuerda dónde la dejó! ¿Cómo la encuentra {name}?",
        ca: "L'Octavio té una làmpada màgica de recanvi, però el seu taller està tan desendreçat que no recorda on la va deixar! Com la troba {name}?",
        en: "Octavio has a spare magic lamp, but his workshop is so messy that he can't remember where he left it! How does {name} find it?",
        fr: "Octavio a une lampe magique de rechange, mais son atelier est si en désordre qu'il ne se souvient plus où il l'a laissée ! Comment {name} la trouve ?",
      },
      options: [
        {
          id: "tidy-tools",
          title: {
            es: "Ordenar el taller juntos",
            ca: "Endreçar el taller plegats",
            en: "Tidy the workshop together",
            fr: "Ranger l'atelier ensemble",
          },
          desc: {
            es: "Cada cosa en su sitio, hasta que aparezca la lámpara.",
            ca: "Cada cosa al seu lloc, fins que aparegui la làmpada.",
            en: "Everything in its place, until the lamp turns up.",
            fr: "Chaque chose à sa place, jusqu'à ce que la lampe apparaisse.",
          },
          imageSeed: "pirates-c3islandc-boxes",
          icon: "inventory_2",
          narrative: {
            es: "{name} y Octavio ordenan juntos el taller, caja por caja, hasta que la lámpara mágica aparece dentro de una bota vieja.",
            ca: "{name} i l'Octavio endrecen plegats el taller, caixa per caixa, fins que la làmpada màgica apareix dins d'una bota vella.",
            en: "{name} and Octavio tidy the workshop together, box by box, until the magic lamp turns up inside an old boot.",
            fr: "{name} et Octavio rangent l'atelier ensemble, caisse par caisse, jusqu'à ce que la lampe magique apparaisse dans une vieille botte.",
          },
          next: "ending",
        },
        {
          id: "hot-cold",
          title: {
            es: "Jugar a frío o caliente",
            ca: "Jugar a fred o calent",
            en: "Play hot or cold",
            fr: "Jouer à chaud ou froid",
          },
          desc: {
            es: "Octavio dirá 'caliente' cuando {name} se acerque a la lámpara.",
            ca: "L'Octavio dirà 'calent' quan {name} s'acosti a la làmpada.",
            en: "Octavio will say 'hot' when {name} gets close to the lamp.",
            fr: "Octavio dira « chaud » quand {name} s'approchera de la lampe.",
          },
          imageSeed: "pirates-c3islandc-game",
          icon: "search",
          narrative: {
            es: "{name} busca por el taller mientras Octavio dice 'frío' y 'caliente', hasta encontrar la lámpara mágica bajo un sombrero pirata.",
            ca: "{name} busca pel taller mentre l'Octavio diu 'fred' i 'calent', fins a trobar la làmpada màgica sota un barret pirata.",
            en: "{name} searches the workshop while Octavio calls out 'cold' and 'hot', until finding the magic lamp under a pirate hat.",
            fr: "{name} cherche dans l'atelier pendant qu'Octavio dit « froid » et « chaud », jusqu'à trouver la lampe magique sous un chapeau de pirate.",
          },
          next: "ending",
        },
        {
          id: "eight-arms",
          title: {
            es: "Buscar con ocho brazos",
            ca: "Buscar amb vuit braços",
            en: "Search with eight arms",
            fr: "Chercher avec huit bras",
          },
          desc: {
            es: "Ocho brazos de pulpo y dos manos buscan mejor que nada en el mundo.",
            ca: "Vuit braços de pop i dues mans busquen millor que res al món.",
            en: "Eight octopus arms and two hands search better than anything in the world.",
            fr: "Huit bras de poulpe et deux mains, rien ne cherche mieux au monde.",
          },
          imageSeed: "pirates-c3islandc-teamwork",
          icon: "diversity_3",
          narrative: {
            es: "{name} y Octavio buscan a la vez por todos los rincones, ocho brazos y dos manos, y la lámpara aparece tras una pila de mapas.",
            ca: "{name} i l'Octavio busquen alhora per tots els racons, vuit braços i dues mans, i la làmpada apareix darrere una pila de mapes.",
            en: "{name} and Octavio search every corner at once, eight arms and two hands, and the lamp turns up behind a pile of maps.",
            fr: "{name} et Octavio cherchent dans tous les recoins à la fois, huit bras et deux mains, et la lampe apparaît derrière une pile de cartes.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "", en: "", fr: "" },
      options: [],
    },
  },
};
