import type { StoryTree } from "./types";

// Branching story tree for the "safari" template (Safari en la Sabana).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es source of truth + ca/en/fr). {name} = child's name.

export const safariTree: StoryTree = {
  templateId: "safari",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} llega a la sabana africana justo cuando el sol pinta de naranja las acacias. Tres maravillas esperan entre la hierba dorada. ¿Cuál descubre primero?",
        ca: "{name} arriba a la sabana africana just quan el sol pinta de taronja les acàcies. Tres meravelles esperen entre l'herba daurada. Quina descobreix primer?",
        en: "{name} arrives in the African savanna just as the sun paints the acacia trees orange. Three wonders are waiting in the golden grass. Which one to discover first?",
        fr: "{name} arrive dans la savane africaine juste quand le soleil peint les acacias en orange. Trois merveilles attendent dans l'herbe dorée. Laquelle découvrir en premier ?",
      },
      options: [
        {
          id: "cub",
          title: {
            es: "El cachorro de león",
            ca: "El cadell de lleó",
            en: "The lion cub",
            fr: "Le lionceau",
          },
          desc: {
            es: "Un cachorrito de león bosteza solito bajo una acacia, lejos de su manada.",
            ca: "Un cadellet de lleó badalla tot solet sota una acàcia, lluny de la seva manada.",
            en: "A little lion cub yawns all alone under an acacia tree, far from its pride.",
            fr: "Un petit lionceau bâille tout seul sous un acacia, loin de sa troupe.",
          },
          imageSeed: "safari-c1-cub",
          icon: "pets",
          narrative: {
            es: "{name} se acerca despacito a un cachorrito de león que bosteza bajo una acacia, lejos de su manada.",
            ca: "{name} s'acosta a poc a poc a un cadellet de lleó que badalla sota una acàcia, lluny de la seva manada.",
            en: "{name} walks up slowly to a little lion cub yawning under an acacia tree, far from its pride.",
            fr: "{name} s'approche tout doucement d'un petit lionceau qui bâille sous un acacia, loin de sa troupe.",
          },
          next: "c2_cub",
        },
        {
          id: "baobab",
          title: {
            es: "El baobab que habla",
            ca: "El baobab que parla",
            en: "The talking baobab",
            fr: "Le baobab qui parle",
          },
          desc: {
            es: "El árbol más viejo de la sabana susurra historias con voz profunda y cálida.",
            ca: "L'arbre més vell de la sabana xiuxiueja històries amb veu profunda i càlida.",
            en: "The oldest tree in the savanna whispers stories in a deep, warm voice.",
            fr: "Le plus vieil arbre de la savane chuchote des histoires d'une voix profonde et chaleureuse.",
          },
          imageSeed: "safari-c1-baobab",
          icon: "park",
          narrative: {
            es: "{name} apoya la mano en el tronco enorme del viejo baobab y el árbol le saluda con una voz profunda y cálida.",
            ca: "{name} posa la mà al tronc enorme del vell baobab i l'arbre el saluda amb una veu profunda i càlida.",
            en: "{name} rests a hand on the huge trunk of the old baobab and the tree says hello in a deep, warm voice.",
            fr: "{name} pose la main sur l'énorme tronc du vieux baobab et l'arbre lui dit bonjour d'une voix profonde et chaleureuse.",
          },
          next: "c2_baobab",
        },
        {
          id: "oasis",
          title: {
            es: "El oasis mágico",
            ca: "L'oasi màgic",
            en: "The magic oasis",
            fr: "L'oasis magique",
          },
          desc: {
            es: "Un remanso de agua brillante donde todos los animales beben juntos en paz.",
            ca: "Un racó d'aigua brillant on tots els animals beuen junts en pau.",
            en: "A pool of sparkling water where all the animals drink together in peace.",
            fr: "Un point d'eau scintillante où tous les animaux boivent ensemble en paix.",
          },
          imageSeed: "safari-c1-oasis",
          icon: "water_drop",
          narrative: {
            es: "{name} descubre un oasis de agua brillante donde cebras, elefantes y gacelas beben juntos en paz.",
            ca: "{name} descobreix un oasi d'aigua brillant on zebres, elefants i gaseles beuen junts en pau.",
            en: "{name} discovers an oasis of sparkling water where zebras, elephants and gazelles drink together in peace.",
            fr: "{name} découvre une oasis d'eau scintillante où zèbres, éléphants et gazelles boivent ensemble en paix.",
          },
          next: "c2_oasis",
        },
      ],
    },
    c2_cub: {
      id: "c2_cub",
      chapter: 2,
      question: {
        es: "El cachorrito se llama Kibo y se quedó dormido mientras su manada caminaba hacia la hierba fresca. ¡Ahora no sabe dónde están! ¿Dónde buscan {name} y Kibo la primera pista?",
        ca: "El cadellet es diu Kibo i es va quedar adormit mentre la seva manada caminava cap a l'herba fresca. Ara no sap on són! On busquen {name} i en Kibo la primera pista?",
        en: "The little cub's name is Kibo, and he fell asleep while his pride walked on towards the fresh grass. Now he doesn't know where they are! Where do {name} and Kibo look for the first clue?",
        fr: "Le petit lionceau s'appelle Kibo : il s'est endormi pendant que sa troupe marchait vers l'herbe fraîche. Maintenant il ne sait plus où elle est ! Où {name} et Kibo cherchent-ils le premier indice ?",
      },
      options: [
        {
          id: "tracks",
          title: {
            es: "Las huellas del barro",
            ca: "Les petjades del fang",
            en: "The muddy paw prints",
            fr: "Les empreintes dans la boue",
          },
          desc: {
            es: "Junto a la charca, el barro fresco guarda las huellas de todos los animales.",
            ca: "Vora la bassa, el fang fresc guarda les petjades de tots els animals.",
            en: "By the waterhole, the fresh mud keeps the footprints of every animal.",
            fr: "Près de la mare, la boue fraîche garde les empreintes de tous les animaux.",
          },
          imageSeed: "safari-c2cub-tracks",
          icon: "footprint",
          narrative: {
            es: "{name} y Kibo se agachan junto a la charca, donde el barro fresco guarda huellas de patas grandes y pequeñas.",
            ca: "{name} i en Kibo s'ajupen vora la bassa, on el fang fresc guarda petjades de potes grans i petites.",
            en: "{name} and Kibo crouch down by the waterhole, where the fresh mud keeps prints of paws big and small.",
            fr: "{name} et Kibo s'accroupissent près de la mare, où la boue fraîche garde des empreintes de pattes grandes et petites.",
          },
          next: "c3_cub_a",
        },
        {
          id: "weavers",
          title: {
            es: "Los pájaros tejedores",
            ca: "Els ocells teixidors",
            en: "The weaver birds",
            fr: "Les oiseaux tisserins",
          },
          desc: {
            es: "Desde sus nidos colgantes ven todo lo que pasa en la sabana.",
            ca: "Des dels seus nius penjants veuen tot el que passa a la sabana.",
            en: "From their hanging nests they see everything that happens in the savanna.",
            fr: "Depuis leurs nids suspendus, ils voient tout ce qui se passe dans la savane.",
          },
          imageSeed: "safari-c2cub-weavers",
          icon: "raven",
          narrative: {
            es: "{name} y Kibo caminan hasta la gran acacia donde los pájaros tejedores cuelgan sus nidos como farolillos de paja.",
            ca: "{name} i en Kibo caminen fins a la gran acàcia on els ocells teixidors pengen els seus nius com fanalets de palla.",
            en: "{name} and Kibo walk to the great acacia where the weaver birds hang their nests like little straw lanterns.",
            fr: "{name} et Kibo marchent jusqu'au grand acacia où les oiseaux tisserins suspendent leurs nids comme des petites lanternes de paille.",
          },
          next: "c3_cub_b",
        },
        {
          id: "kopje",
          title: {
            es: "Las rocas del kopje",
            ca: "Les roques del kopje",
            en: "The kopje rocks",
            fr: "Les rochers du kopje",
          },
          desc: {
            es: "Desde lo alto de las rocas se ve la sabana entera hasta el horizonte.",
            ca: "Des de dalt de les roques es veu la sabana sencera fins a l'horitzó.",
            en: "From the top of the rocks you can see the whole savanna to the horizon.",
            fr: "Du haut des rochers, on voit toute la savane jusqu'à l'horizon.",
          },
          imageSeed: "safari-c2cub-kopje",
          icon: "landscape",
          narrative: {
            es: "{name} y Kibo suben a las rocas del kopje, desde donde la sabana se extiende dorada hasta el horizonte.",
            ca: "{name} i en Kibo pugen a les roques del kopje, des d'on la sabana s'estén daurada fins a l'horitzó.",
            en: "{name} and Kibo climb the kopje rocks, where the savanna stretches out golden all the way to the horizon.",
            fr: "{name} et Kibo grimpent sur les rochers du kopje, d'où la savane s'étend, dorée, jusqu'à l'horizon.",
          },
          next: "c3_cub_c",
        },
      ],
    },
    c2_baobab: {
      id: "c2_baobab",
      chapter: 2,
      question: {
        es: "El viejo baobab guarda todas las historias de la sabana, pero ha olvidado el final de su preferida: la historia de la primera lluvia. {name} promete ayudarle a recordarla. ¿A quién pregunta primero?",
        ca: "El vell baobab guarda totes les històries de la sabana, però ha oblidat el final de la seva preferida: la història de la primera pluja. {name} promet ajudar-lo a recordar-la. A qui pregunta primer?",
        en: "The old baobab keeps all the stories of the savanna, but it has forgotten the ending of its favourite one: the story of the first rain. {name} promises to help it remember. Who to ask first?",
        fr: "Le vieux baobab garde toutes les histoires de la savane, mais il a oublié la fin de sa préférée : l'histoire de la première pluie. {name} promet de l'aider à s'en souvenir. À qui demander en premier ?",
      },
      options: [
        {
          id: "elephant",
          title: {
            es: "La elefanta de gran memoria",
            ca: "L'elefanta de gran memòria",
            en: "The elephant with the great memory",
            fr: "L'éléphante à la grande mémoire",
          },
          desc: {
            es: "La abuela elefanta recuerda cada lluvia que ha caído sobre la sabana.",
            ca: "L'àvia elefanta recorda cada pluja que ha caigut sobre la sabana.",
            en: "Grandma elephant remembers every rain that has ever fallen on the savanna.",
            fr: "Grand-mère éléphante se souvient de chaque pluie tombée sur la savane.",
          },
          imageSeed: "safari-c2baobab-elephant",
          icon: "cruelty_free",
          narrative: {
            es: "{name} cruza la llanura hasta la abuela elefanta, que recuerda cada lluvia que ha caído sobre la sabana.",
            ca: "{name} travessa la plana fins a l'àvia elefanta, que recorda cada pluja que ha caigut sobre la sabana.",
            en: "{name} crosses the plain to grandma elephant, who remembers every rain that has ever fallen on the savanna.",
            fr: "{name} traverse la plaine jusqu'à grand-mère éléphante, qui se souvient de chaque pluie tombée sur la savane.",
          },
          next: "c3_baobab_a",
        },
        {
          id: "river",
          title: {
            es: "El río que canta",
            ca: "El riu que canta",
            en: "The singing river",
            fr: "La rivière qui chante",
          },
          desc: {
            es: "Dicen que el río nació de la primera lluvia y aún canta su historia.",
            ca: "Diuen que el riu va néixer de la primera pluja i encara canta la seva història.",
            en: "They say the river was born from the first rain and still sings its story.",
            fr: "On dit que la rivière est née de la première pluie et chante encore son histoire.",
          },
          imageSeed: "safari-c2baobab-river",
          icon: "water",
          narrative: {
            es: "{name} sigue el brillo del río que canta, el mismo que nació de la primera lluvia hace muchísimo tiempo.",
            ca: "{name} segueix la lluentor del riu que canta, el mateix que va néixer de la primera pluja fa moltíssim temps.",
            en: "{name} follows the sparkle of the singing river, the very one born from the first rain long, long ago.",
            fr: "{name} suit l'éclat de la rivière qui chante, celle-là même qui est née de la première pluie il y a très, très longtemps.",
          },
          next: "c3_baobab_b",
        },
        {
          id: "wind",
          title: {
            es: "El viento de la hierba",
            ca: "El vent de l'herba",
            en: "The wind in the grass",
            fr: "Le vent dans l'herbe",
          },
          desc: {
            es: "El viento lleva siglos susurrando la historia entre la hierba alta.",
            ca: "El vent fa segles que xiuxiueja la història entre l'herba alta.",
            en: "The wind has been whispering the story through the tall grass for ages.",
            fr: "Le vent murmure l'histoire dans les hautes herbes depuis des siècles.",
          },
          imageSeed: "safari-c2baobab-wind",
          icon: "air",
          narrative: {
            es: "{name} camina hacia la hierba alta, donde el viento susurra trocitos de historias muy antiguas.",
            ca: "{name} camina cap a l'herba alta, on el vent xiuxiueja trossets d'històries molt antigues.",
            en: "{name} walks into the tall grass, where the wind whispers little pieces of very old stories.",
            fr: "{name} marche vers les hautes herbes, où le vent murmure des petits bouts d'histoires très anciennes.",
          },
          next: "c3_baobab_c",
        },
      ],
    },
    c2_oasis: {
      id: "c2_oasis",
      chapter: 2,
      question: {
        es: "El agua del oasis brilla y le enseña a {name} tres reflejos: animales tímidos que nunca se han atrevido a venir a beber con los demás. ¿A quién va a invitar primero?",
        ca: "L'aigua de l'oasi brilla i li ensenya a {name} tres reflexos: animals tímids que mai no s'han atrevit a venir a beure amb els altres. A qui anirà a convidar primer?",
        en: "The oasis water sparkles and shows {name} three reflections: shy animals who have never dared to come and drink with the others. Who to invite first?",
        fr: "L'eau de l'oasis scintille et montre à {name} trois reflets : des animaux timides qui n'ont jamais osé venir boire avec les autres. Qui inviter en premier ?",
      },
      options: [
        {
          id: "pangolin",
          title: {
            es: "El pangolín tímido",
            ca: "El pangolí tímid",
            en: "The shy pangolin",
            fr: "Le pangolin timide",
          },
          desc: {
            es: "Un animalito con escamas que se enrosca como una piña cuando algo le da vergüenza.",
            ca: "Un animaló amb escates que s'enrosca com una pinya quan alguna cosa li fa vergonya.",
            en: "A little scaly animal that rolls up like a pinecone whenever it feels shy.",
            fr: "Un petit animal à écailles qui se roule en boule comme une pomme de pin dès qu'il est intimidé.",
          },
          imageSeed: "safari-c2oasis-pangolin",
          icon: "shield",
          narrative: {
            es: "{name} encuentra al pangolín enroscado como una piña entre las raíces de un arbusto.",
            ca: "{name} troba el pangolí enroscat com una pinya entre les arrels d'un arbust.",
            en: "{name} finds the pangolin rolled up like a pinecone between the roots of a bush.",
            fr: "{name} trouve le pangolin roulé en boule comme une pomme de pin entre les racines d'un buisson.",
          },
          next: "c3_oasis_a",
        },
        {
          id: "tortoise",
          title: {
            es: "La tortuga centenaria",
            ca: "La tortuga centenària",
            en: "The hundred-year-old tortoise",
            fr: "La tortue centenaire",
          },
          desc: {
            es: "Camina tan despacito que siempre llega cuando los demás ya se han ido.",
            ca: "Camina tan a poc a poc que sempre arriba quan els altres ja se n'han anat.",
            en: "She walks so slowly that she always arrives after everyone else has gone.",
            fr: "Elle marche si lentement qu'elle arrive toujours quand les autres sont déjà partis.",
          },
          imageSeed: "safari-c2oasis-tortoise",
          icon: "schedule",
          narrative: {
            es: "{name} encuentra a la tortuga centenaria avanzando pasito a pasito por la llanura, todavía muy lejos del oasis.",
            ca: "{name} troba la tortuga centenària avançant passet a passet per la plana, encara molt lluny de l'oasi.",
            en: "{name} finds the hundred-year-old tortoise inching step by tiny step across the plain, still far from the oasis.",
            fr: "{name} trouve la tortue centenaire qui avance tout petit pas par tout petit pas dans la plaine, encore très loin de l'oasis.",
          },
          next: "c3_oasis_b",
        },
        {
          id: "zebra",
          title: {
            es: "El potrillo de cebra",
            ca: "El pollí de zebra",
            en: "The zebra foal",
            fr: "Le bébé zèbre",
          },
          desc: {
            es: "Le da miedo su propio reflejo rayado y nunca se atreve a acercarse al agua.",
            ca: "Li fa por el seu propi reflex ratllat i mai no s'atreveix a acostar-se a l'aigua.",
            en: "He is scared of his own stripy reflection and never dares to go near the water.",
            fr: "Il a peur de son propre reflet rayé et n'ose jamais s'approcher de l'eau.",
          },
          imageSeed: "safari-c2oasis-zebra",
          icon: "flip",
          narrative: {
            es: "{name} ve al potrillo de cebra mirando el oasis desde lejos, sin atreverse a acercarse al agua.",
            ca: "{name} veu el pollí de zebra mirant l'oasi des de lluny, sense atrevir-se a acostar-se a l'aigua.",
            en: "{name} spots the zebra foal watching the oasis from far away, not daring to come near the water.",
            fr: "{name} aperçoit le bébé zèbre qui regarde l'oasis de loin, sans oser s'approcher de l'eau.",
          },
          next: "c3_oasis_c",
        },
      ],
    },
    c3_cub_a: {
      id: "c3_cub_a",
      chapter: 3,
      question: {
        es: "En el barro hay huellas de cebra, de jirafa, de avestruz... ¡y muchas más! ¿Cómo encuentra {name} las huellas de la manada de Kibo?",
        ca: "Al fang hi ha petjades de zebra, de girafa, d'estruç... i moltes més! Com troba {name} les petjades de la manada d'en Kibo?",
        en: "In the mud there are zebra prints, giraffe prints, ostrich prints... and many more! How does {name} find the prints of Kibo's pride?",
        fr: "Dans la boue, il y a des empreintes de zèbre, de girafe, d'autruche... et bien d'autres ! Comment {name} trouve les empreintes de la troupe de Kibo ?",
      },
      options: [
        {
          id: "compare-paw",
          title: {
            es: "Comparar con la pata de Kibo",
            ca: "Comparar amb la pota d'en Kibo",
            en: "Compare with Kibo's paw",
            fr: "Comparer avec la patte de Kibo",
          },
          desc: {
            es: "Una patita junto a cada huella dice enseguida cuál es de león.",
            ca: "Una poteta al costat de cada petjada diu de seguida quina és de lleó.",
            en: "A little paw next to each print quickly shows which one belongs to a lion.",
            fr: "Une petite patte posée à côté de chaque empreinte montre vite laquelle est celle d'un lion.",
          },
          imageSeed: "safari-c3cuba-paw",
          icon: "fingerprint",
          narrative: {
            es: "{name} apoya con cuidado la patita de Kibo junto a cada huella hasta dar con las de león, que les guían hasta la manada descansando bajo una acacia.",
            ca: "{name} posa amb cura la poteta d'en Kibo al costat de cada petjada fins a trobar les de lleó, que els guien fins a la manada que descansa sota una acàcia.",
            en: "{name} gently places Kibo's little paw next to each print until finding the lion ones, which lead them to the pride resting under an acacia.",
            fr: "{name} pose délicatement la petite patte de Kibo à côté de chaque empreinte jusqu'à trouver celles des lions, qui les guident vers la troupe qui se repose sous un acacia.",
          },
          next: "ending",
        },
        {
          id: "flat-grass",
          title: {
            es: "El caminito de hierba aplastada",
            ca: "El caminet d'herba aixafada",
            en: "The flattened-grass trail",
            fr: "Le sentier d'herbe aplatie",
          },
          desc: {
            es: "Cuando pasa una manada, la hierba alta se peina hacia un lado.",
            ca: "Quan passa una manada, l'herba alta es pentina cap a un costat.",
            en: "When a pride walks past, the tall grass gets combed to one side.",
            fr: "Quand une troupe passe, les hautes herbes se couchent du même côté.",
          },
          imageSeed: "safari-c3cuba-grass",
          icon: "grass",
          narrative: {
            es: "{name} descubre un caminito de hierba aplastada que serpentea por la llanura y lo sigue con Kibo hasta ver a la manada a lo lejos.",
            ca: "{name} descobreix un caminet d'herba aixafada que serpenteja per la plana i el segueix amb en Kibo fins a veure la manada al lluny.",
            en: "{name} spots a winding trail of flattened grass across the plain and follows it with Kibo until the pride appears in the distance.",
            fr: "{name} découvre un sentier d'herbe aplatie qui serpente dans la plaine et le suit avec Kibo jusqu'à apercevoir la troupe au loin.",
          },
          next: "ending",
        },
        {
          id: "ask-hippo",
          title: {
            es: "Preguntar al hipopótamo",
            ca: "Preguntar a l'hipopòtam",
            en: "Ask the hippo",
            fr: "Demander à l'hippopotame",
          },
          desc: {
            es: "El hipopótamo de la charca ve pasar a todos los animales que vienen a beber.",
            ca: "L'hipopòtam de la bassa veu passar tots els animals que vénen a beure.",
            en: "The waterhole hippo watches every animal that comes to drink.",
            fr: "L'hippopotame de la mare voit passer tous les animaux qui viennent boire.",
          },
          imageSeed: "safari-c3cuba-hippo",
          icon: "mood",
          narrative: {
            es: "{name} pregunta al hipopótamo de la charca, que señala con su gran hocico el camino por donde se fue la manada de Kibo.",
            ca: "{name} pregunta a l'hipopòtam de la bassa, que assenyala amb el seu gran morro el camí per on se'n va anar la manada d'en Kibo.",
            en: "{name} asks the waterhole hippo, who points with his big snout down the path Kibo's pride took.",
            fr: "{name} demande à l'hippopotame de la mare, qui montre avec son grand museau le chemin qu'a pris la troupe de Kibo.",
          },
          next: "ending",
        },
      ],
    },
    c3_cub_b: {
      id: "c3_cub_b",
      chapter: 3,
      question: {
        es: "Los pájaros tejedores lo ven todo desde arriba, pero están atareadísimos terminando sus nidos antes de la noche. ¿Cómo consigue {name} su ayuda?",
        ca: "Els ocells teixidors ho veuen tot des de dalt, però estan atrafegadíssims acabant els seus nius abans de la nit. Com aconsegueix {name} la seva ajuda?",
        en: "The weaver birds see everything from up high, but they are ever so busy finishing their nests before nightfall. How does {name} get their help?",
        fr: "Les oiseaux tisserins voient tout d'en haut, mais ils sont très occupés à finir leurs nids avant la nuit. Comment {name} obtient leur aide ?",
      },
      options: [
        {
          id: "help-nests",
          title: {
            es: "Ayudar con los nidos",
            ca: "Ajudar amb els nius",
            en: "Help with the nests",
            fr: "Aider à faire les nids",
          },
          desc: {
            es: "Unas briznas de hierba más y los nidos estarán terminados.",
            ca: "Uns brins d'herba més i els nius estaran acabats.",
            en: "A few more blades of grass and the nests will be finished.",
            fr: "Encore quelques brins d'herbe et les nids seront terminés.",
          },
          imageSeed: "safari-c3cubb-nests",
          icon: "home",
          narrative: {
            es: "{name} recoge briznas de hierba dorada y se las pasa a los tejedores hasta terminar los nidos, y ellos, agradecidos, le señalan volando el camino de la manada.",
            ca: "{name} recull brins d'herba daurada i els passa als teixidors fins a acabar els nius, i ells, agraïts, li assenyalen volant el camí de la manada.",
            en: "{name} gathers blades of golden grass and passes them up to the weavers until the nests are done, and they gratefully fly ahead to show the way to the pride.",
            fr: "{name} ramasse des brins d'herbe dorée et les passe aux tisserins jusqu'à finir les nids, et eux, reconnaissants, volent devant pour montrer le chemin de la troupe.",
          },
          next: "ending",
        },
        {
          id: "whistle-song",
          title: {
            es: "Silbar su canción",
            ca: "Xiular la seva cançó",
            en: "Whistle their song",
            fr: "Siffler leur chanson",
          },
          desc: {
            es: "A los tejedores les encanta que alguien cante con ellos mientras trabajan.",
            ca: "Als teixidors els encanta que algú canti amb ells mentre treballen.",
            en: "The weavers love it when someone sings along while they work.",
            fr: "Les tisserins adorent que quelqu'un chante avec eux pendant qu'ils travaillent.",
          },
          imageSeed: "safari-c3cubb-song",
          icon: "music_note",
          narrative: {
            es: "{name} silba la canción alegre de los tejedores y los pájaros bajan en espiral para contarle dónde han visto a la manada de Kibo.",
            ca: "{name} xiula la cançó alegre dels teixidors i els ocells baixen en espiral per explicar-li on han vist la manada d'en Kibo.",
            en: "{name} whistles the weavers' cheerful song and the birds spiral down to tell where they have seen Kibo's pride.",
            fr: "{name} siffle la chanson joyeuse des tisserins et les oiseaux descendent en spirale pour raconter où ils ont vu la troupe de Kibo.",
          },
          next: "ending",
        },
        {
          id: "share-seeds",
          title: {
            es: "Compartir semillas",
            ca: "Compartir llavors",
            en: "Share some seeds",
            fr: "Partager des graines",
          },
          desc: {
            es: "Un puñadito de semillas es la merienda favorita de los tejedores.",
            ca: "Un grapadet de llavors és el berenar preferit dels teixidors.",
            en: "A little handful of seeds is the weavers' favourite snack.",
            fr: "Une petite poignée de graines, c'est le goûter préféré des tisserins.",
          },
          imageSeed: "safari-c3cubb-seeds",
          icon: "nutrition",
          narrative: {
            es: "{name} reparte un puñadito de semillas entre los tejedores y ellos, contentos, vuelan en flecha hacia la acacia donde descansa la manada.",
            ca: "{name} reparteix un grapadet de llavors entre els teixidors i ells, contents, volen en fletxa cap a l'acàcia on descansa la manada.",
            en: "{name} shares a little handful of seeds with the weavers and they happily fly arrow-straight to the acacia where the pride is resting.",
            fr: "{name} partage une petite poignée de graines avec les tisserins et ceux-ci, tout contents, filent comme des flèches vers l'acacia où se repose la troupe.",
          },
          next: "ending",
        },
      ],
    },
    c3_cub_c: {
      id: "c3_cub_c",
      chapter: 3,
      question: {
        es: "Desde lo alto del kopje la sabana parece no terminar nunca. ¿Cómo encuentra {name} a la manada entre tanta hierba dorada?",
        ca: "Des de dalt del kopje la sabana sembla que no s'acabi mai. Com troba {name} la manada entre tanta herba daurada?",
        en: "From the top of the kopje the savanna seems to go on forever. How does {name} find the pride in all that golden grass?",
        fr: "Du haut du kopje, la savane semble ne jamais finir. Comment {name} trouve la troupe dans toute cette herbe dorée ?",
      },
      options: [
        {
          id: "sunset-roar",
          title: {
            es: "Escuchar el rugido del atardecer",
            ca: "Escoltar el rugit del capvespre",
            en: "Listen for the sunset roar",
            fr: "Écouter le rugissement du soir",
          },
          desc: {
            es: "Cada tarde, las leonas rugen suavecito para llamar a los suyos.",
            ca: "Cada tarda, les lleones rugeixen fluixet per cridar els seus.",
            en: "Every evening, the lionesses roar softly to call their family home.",
            fr: "Chaque soir, les lionnes rugissent doucement pour appeler les leurs.",
          },
          imageSeed: "safari-c3cubc-roar",
          icon: "hearing",
          narrative: {
            es: "{name} cierra los ojos, escucha el rugido suave que trae el viento y guía a Kibo hacia el lugar donde su manada lo llama.",
            ca: "{name} tanca els ulls, escolta el rugit suau que porta el vent i guia en Kibo cap al lloc on la seva manada el crida.",
            en: "{name} closes their eyes, hears the soft roar carried on the wind and guides Kibo towards the place where his pride is calling.",
            fr: "{name} ferme les yeux, entend le doux rugissement porté par le vent et guide Kibo vers l'endroit où sa troupe l'appelle.",
          },
          next: "ending",
        },
        {
          id: "golden-dots",
          title: {
            es: "Buscar las siluetas doradas",
            ca: "Buscar les siluetes daurades",
            en: "Look for the golden shapes",
            fr: "Chercher les silhouettes dorées",
          },
          desc: {
            es: "Desde tan alto, los leones se ven como motitas doradas entre la hierba.",
            ca: "Des de tan amunt, els lleons es veuen com puntets daurats entre l'herba.",
            en: "From so high up, the lions look like little golden dots in the grass.",
            fr: "De si haut, les lions ressemblent à des petits points dorés dans l'herbe.",
          },
          imageSeed: "safari-c3cubc-watch",
          icon: "visibility",
          narrative: {
            es: "{name} mira despacio la llanura hasta descubrir unas motitas doradas moviéndose junto al río: ¡la manada de Kibo!",
            ca: "{name} mira a poc a poc la plana fins a descobrir uns puntets daurats movent-se vora el riu: la manada d'en Kibo!",
            en: "{name} scans the plain slowly until spotting little golden dots moving by the river: Kibo's pride!",
            fr: "{name} observe lentement la plaine jusqu'à repérer des petits points dorés qui bougent près de la rivière : la troupe de Kibo !",
          },
          next: "ending",
        },
        {
          id: "ask-hyrax",
          title: {
            es: "Preguntar a los damanes",
            ca: "Preguntar als damans",
            en: "Ask the rock hyraxes",
            fr: "Demander aux damans",
          },
          desc: {
            es: "La familia de damanes vive entre las rocas y conoce todos los caminos.",
            ca: "La família de damans viu entre les roques i coneix tots els camins.",
            en: "The hyrax family lives among the rocks and knows every path.",
            fr: "La famille de damans vit entre les rochers et connaît tous les chemins.",
          },
          imageSeed: "safari-c3cubc-hyrax",
          icon: "cruelty_free",
          narrative: {
            es: "{name} pregunta a la familia de damanes del kopje y el abuelo damán señala con su naricita el sendero que tomó la manada.",
            ca: "{name} pregunta a la família de damans del kopje i l'avi damà assenyala amb el seu nasset el corriol que va agafar la manada.",
            en: "{name} asks the kopje's hyrax family and the grandpa hyrax points with his little nose to the trail the pride took.",
            fr: "{name} demande à la famille de damans du kopje et le grand-père daman montre avec son petit nez le sentier qu'a pris la troupe.",
          },
          next: "ending",
        },
      ],
    },
    c3_baobab_a: {
      id: "c3_baobab_a",
      chapter: 3,
      question: {
        es: "La abuela elefanta conoce el final de la historia, pero sus recuerdos solo despiertan cuando está contenta y tranquila. ¿Cómo hace {name} que el recuerdo vuelva?",
        ca: "L'àvia elefanta coneix el final de la història, però els seus records només es desperten quan està contenta i tranquil·la. Com fa {name} que el record torni?",
        en: "Grandma elephant knows the ending of the story, but her memories only wake up when she is happy and calm. How does {name} bring the memory back?",
        fr: "Grand-mère éléphante connaît la fin de l'histoire, mais ses souvenirs ne se réveillent que quand elle est contente et tranquille. Comment {name} fait revenir le souvenir ?",
      },
      options: [
        {
          id: "river-walk",
          title: {
            es: "Pasear juntos al río",
            ca: "Passejar junts cap al riu",
            en: "Stroll to the river together",
            fr: "Se promener ensemble à la rivière",
          },
          desc: {
            es: "Caminar despacito junto al agua es lo que más le gusta a la abuela elefanta.",
            ca: "Caminar a poc a poc vora l'aigua és el que més li agrada a l'àvia elefanta.",
            en: "Walking slowly by the water is what grandma elephant loves most.",
            fr: "Marcher lentement au bord de l'eau, c'est ce que grand-mère éléphante préfère.",
          },
          imageSeed: "safari-c3baobaba-walk",
          icon: "hiking",
          narrative: {
            es: "{name} pasea despacito junto a la abuela elefanta hasta el río y, paso a paso, el final de la historia vuelve a su memoria.",
            ca: "{name} passeja a poc a poc al costat de l'àvia elefanta fins al riu i, pas a pas, el final de la història torna a la seva memòria.",
            en: "{name} strolls slowly beside grandma elephant down to the river and, step by step, the ending of the story comes back to her.",
            fr: "{name} se promène lentement aux côtés de grand-mère éléphante jusqu'à la rivière et, pas à pas, la fin de l'histoire lui revient en mémoire.",
          },
          next: "ending",
        },
        {
          id: "acacia-pods",
          title: {
            es: "Llevarle vainas de acacia",
            ca: "Portar-li tavelles d'acàcia",
            en: "Bring her acacia pods",
            fr: "Lui apporter des gousses d'acacia",
          },
          desc: {
            es: "Las vainas dulces de acacia son su merienda preferida desde pequeña.",
            ca: "Les tavelles dolces d'acàcia són el seu berenar preferit des de petita.",
            en: "Sweet acacia pods have been her favourite snack since she was little.",
            fr: "Les gousses sucrées d'acacia sont son goûter préféré depuis toute petite.",
          },
          imageSeed: "safari-c3baobaba-pods",
          icon: "eco",
          narrative: {
            es: "{name} recoge vainas dulces de acacia para la abuela elefanta y, mientras ella merienda feliz, el final de la historia vuelve a su memoria.",
            ca: "{name} recull tavelles dolces d'acàcia per a l'àvia elefanta i, mentre ella berena feliç, el final de la història torna a la seva memòria.",
            en: "{name} gathers sweet acacia pods for grandma elephant and, as she happily munches, the ending of the story comes back to her.",
            fr: "{name} ramasse des gousses sucrées d'acacia pour grand-mère éléphante et, pendant qu'elle goûte joyeusement, la fin de l'histoire lui revient.",
          },
          next: "ending",
        },
        {
          id: "rumble-song",
          title: {
            es: "Tararear la canción elefanta",
            ca: "Taral·lejar la cançó elefanta",
            en: "Hum the elephant song",
            fr: "Fredonner la chanson des éléphants",
          },
          desc: {
            es: "Los elefantes se cantan canciones bajitas que hacen vibrar la tierra.",
            ca: "Els elefants es canten cançons fluixetes que fan vibrar la terra.",
            en: "Elephants sing each other low songs that make the ground hum.",
            fr: "Les éléphants se chantent des chansons graves qui font vibrer la terre.",
          },
          imageSeed: "safari-c3baobaba-hum",
          icon: "queue_music",
          narrative: {
            es: "{name} tararea bajito la canción de los elefantes y la abuela elefanta, emocionada, recuerda el final palabra por palabra.",
            ca: "{name} taral·leja fluixet la cançó dels elefants i l'àvia elefanta, emocionada, recorda el final paraula per paraula.",
            en: "{name} softly hums the elephants' song and grandma elephant, touched, remembers the ending word for word.",
            fr: "{name} fredonne tout bas la chanson des éléphants et grand-mère éléphante, émue, se rappelle la fin mot pour mot.",
          },
          next: "ending",
        },
      ],
    },
    c3_baobab_b: {
      id: "c3_baobab_b",
      chapter: 3,
      question: {
        es: "El río canta la historia, pero la canta entre salpicaduras y borboteos, ¡y no se entiende nada! ¿Cómo escucha {name} el final de la historia?",
        ca: "El riu canta la història, però la canta entre esquitxos i borbolls, i no s'entén res! Com escolta {name} el final de la història?",
        en: "The river sings the story, but it sings between splashes and gurgles, and you can't make out a word! How does {name} hear the ending of the story?",
        fr: "La rivière chante l'histoire, mais elle la chante entre éclaboussures et gargouillis, et on ne comprend rien ! Comment {name} écoute la fin de l'histoire ?",
      },
      options: [
        {
          id: "smooth-stone",
          title: {
            es: "Sentarse en la piedra lisa",
            ca: "Seure a la pedra llisa",
            en: "Sit on the smooth stone",
            fr: "S'asseoir sur la pierre lisse",
          },
          desc: {
            es: "Al amanecer el río canta despacito, casi en susurros.",
            ca: "A l'alba el riu canta a poc a poc, gairebé en xiuxiueigs.",
            en: "At dawn the river sings slowly, almost in whispers.",
            fr: "À l'aube, la rivière chante doucement, presque en chuchotant.",
          },
          imageSeed: "safari-c3baobabb-stone",
          icon: "self_improvement",
          narrative: {
            es: "{name} se sienta sin moverse en la piedra lisa de la orilla al amanecer y escucha el final de la historia en los susurros del agua.",
            ca: "{name} seu sense moure's a la pedra llisa de la riba a l'alba i escolta el final de la història en els xiuxiueigs de l'aigua.",
            en: "{name} sits perfectly still on the smooth stone by the bank at dawn and hears the ending of the story in the water's whispers.",
            fr: "{name} s'assoit sans bouger sur la pierre lisse de la rive à l'aube et entend la fin de l'histoire dans les chuchotements de l'eau.",
          },
          next: "ending",
        },
        {
          id: "ask-heron",
          title: {
            es: "Preguntar a la garza",
            ca: "Preguntar al bernat pescaire",
            en: "Ask the heron",
            fr: "Demander au héron",
          },
          desc: {
            es: "La garza pescadora escucha las canciones del río todos los días.",
            ca: "El bernat pescaire escolta les cançons del riu cada dia.",
            en: "The fishing heron listens to the river's songs every single day.",
            fr: "Le héron pêcheur écoute les chansons de la rivière tous les jours.",
          },
          imageSeed: "safari-c3baobabb-heron",
          icon: "raven",
          narrative: {
            es: "{name} pregunta a la garza pescadora, que conoce de memoria las canciones del río y le recita el final de la historia.",
            ca: "{name} pregunta al bernat pescaire, que coneix de memòria les cançons del riu i li recita el final de la història.",
            en: "{name} asks the fishing heron, who knows the river's songs by heart and recites the ending of the story.",
            fr: "{name} demande au héron pêcheur, qui connaît par cœur les chansons de la rivière et lui récite la fin de l'histoire.",
          },
          next: "ending",
        },
        {
          id: "calm-pool",
          title: {
            es: "Seguir el río al remanso",
            ca: "Seguir el riu fins al toll tranquil",
            en: "Follow the river to the calm pool",
            fr: "Suivre la rivière jusqu'au bassin calme",
          },
          desc: {
            es: "Hay un rincón de aguas tranquilas donde el río canta lento y clarito.",
            ca: "Hi ha un racó d'aigües tranquil·les on el riu canta lent i clar.",
            en: "There is a corner of calm water where the river sings slowly and clearly.",
            fr: "Il existe un coin d'eaux calmes où la rivière chante lentement et clairement.",
          },
          imageSeed: "safari-c3baobabb-pool",
          icon: "explore",
          narrative: {
            es: "{name} sigue la orilla hasta un remanso de aguas tranquilas, donde el río canta tan clarito que el final se entiende entero.",
            ca: "{name} segueix la riba fins a un toll d'aigües tranquil·les, on el riu canta tan clar que el final s'entén sencer.",
            en: "{name} follows the bank to a pool of calm water, where the river sings so clearly that the whole ending can be heard.",
            fr: "{name} suit la rive jusqu'à un bassin d'eaux calmes, où la rivière chante si clairement que la fin s'entend en entier.",
          },
          next: "ending",
        },
      ],
    },
    c3_baobab_c: {
      id: "c3_baobab_c",
      chapter: 3,
      question: {
        es: "El viento conoce la historia, pero nunca se está quieto: pasa corriendo y sus palabras se escapan. ¿Cómo atrapa {name} su susurro?",
        ca: "El vent coneix la història, però mai no s'està quiet: passa corrent i les seves paraules s'escapen. Com atrapa {name} el seu xiuxiueig?",
        en: "The wind knows the story, but it never stays still: it rushes past and its words slip away. How does {name} catch its whisper?",
        fr: "Le vent connaît l'histoire, mais il ne tient jamais en place : il passe en courant et ses mots s'échappent. Comment {name} attrape son murmure ?",
      },
      options: [
        {
          id: "tall-grass",
          title: {
            es: "Esconderse en la hierba alta",
            ca: "Amagar-se a l'herba alta",
            en: "Hide in the tall grass",
            fr: "Se cacher dans les hautes herbes",
          },
          desc: {
            es: "Cuando el viento peina la hierba, cada brizna repite un trocito de la historia.",
            ca: "Quan el vent pentina l'herba, cada bri repeteix un trosset de la història.",
            en: "When the wind combs the grass, each blade repeats a little piece of the story.",
            fr: "Quand le vent peigne l'herbe, chaque brin répète un petit bout de l'histoire.",
          },
          imageSeed: "safari-c3baobabc-grass",
          icon: "grass",
          narrative: {
            es: "{name} se esconde entre la hierba alta sin hacer ruido y cada brizna le susurra un trocito del final de la historia.",
            ca: "{name} s'amaga entre l'herba alta sense fer soroll i cada bri li xiuxiueja un trosset del final de la història.",
            en: "{name} hides in the tall grass without a sound and each blade whispers a little piece of the story's ending.",
            fr: "{name} se cache dans les hautes herbes sans faire de bruit et chaque brin lui murmure un petit bout de la fin de l'histoire.",
          },
          next: "ending",
        },
        {
          id: "leaf-shell",
          title: {
            es: "Una hoja como caracola",
            ca: "Una fulla com un cargol de mar",
            en: "A leaf like a seashell",
            fr: "Une feuille comme un coquillage",
          },
          desc: {
            es: "Una hoja grande y curvada recoge los susurros igual que una caracola.",
            ca: "Una fulla gran i corbada recull els xiuxiueigs igual que un cargol de mar.",
            en: "A big curved leaf gathers whispers just like a seashell.",
            fr: "Une grande feuille courbée recueille les murmures comme un coquillage.",
          },
          imageSeed: "safari-c3baobabc-leaf",
          icon: "spa",
          narrative: {
            es: "{name} acerca al oído una hoja grande y curvada como una caracola y dentro suena, clarito, el susurro del viento con el final de la historia.",
            ca: "{name} acosta a l'orella una fulla gran i corbada com un cargol de mar i a dins hi sona, ben clar, el xiuxiueig del vent amb el final de la història.",
            en: "{name} holds a big leaf curved like a seashell up to one ear and inside, clear as anything, sounds the wind's whisper with the ending of the story.",
            fr: "{name} approche de son oreille une grande feuille courbée comme un coquillage et dedans résonne, tout clair, le murmure du vent avec la fin de l'histoire.",
          },
          next: "ending",
        },
        {
          id: "acacia-wait",
          title: {
            es: "Esperar en la acacia",
            ca: "Esperar a l'acàcia",
            en: "Wait by the acacia",
            fr: "Attendre près de l'acacia",
          },
          desc: {
            es: "Al atardecer, el viento siempre se detiene a descansar en la copa de la acacia.",
            ca: "Al capvespre, el vent sempre s'atura a descansar a la copa de l'acàcia.",
            en: "At sunset, the wind always stops to rest in the acacia's crown.",
            fr: "Au coucher du soleil, le vent s'arrête toujours pour se reposer dans la cime de l'acacia.",
          },
          imageSeed: "safari-c3baobabc-acacia",
          icon: "wb_twilight",
          narrative: {
            es: "{name} espera bajo la acacia al atardecer y, cuando el viento se detiene a descansar entre las ramas, le cuenta el final de la historia.",
            ca: "{name} espera sota l'acàcia al capvespre i, quan el vent s'atura a descansar entre les branques, li explica el final de la història.",
            en: "{name} waits under the acacia at sunset and, when the wind stops to rest among the branches, it tells the ending of the story.",
            fr: "{name} attend sous l'acacia au coucher du soleil et, quand le vent s'arrête pour se reposer dans les branches, il lui raconte la fin de l'histoire.",
          },
          next: "ending",
        },
      ],
    },
    c3_oasis_a: {
      id: "c3_oasis_a",
      chapter: 3,
      question: {
        es: "El pangolín está enroscado como una piña y no quiere asomar ni la naricita. ¿Cómo le enseña {name} que el oasis es un lugar seguro?",
        ca: "El pangolí està enroscat com una pinya i no vol treure ni el nasset. Com li ensenya {name} que l'oasi és un lloc segur?",
        en: "The pangolin is rolled up like a pinecone and won't even poke out his little nose. How does {name} show him the oasis is a safe place?",
        fr: "Le pangolin est roulé en boule comme une pomme de pin et ne veut même pas sortir son petit nez. Comment {name} lui montre que l'oasis est un endroit sûr ?",
      },
      options: [
        {
          id: "patient-wait",
          title: {
            es: "Esperar a su lado",
            ca: "Esperar al seu costat",
            en: "Wait by his side",
            fr: "Attendre à ses côtés",
          },
          desc: {
            es: "Sentarse cerquita, sin prisas, es la mejor manera de dar confianza.",
            ca: "Seure a prop, sense presses, és la millor manera de donar confiança.",
            en: "Sitting close by, with no hurry at all, is the best way to build trust.",
            fr: "S'installer tout près, sans se presser, c'est la meilleure façon de mettre en confiance.",
          },
          imageSeed: "safari-c3oasisa-wait",
          icon: "hourglass_empty",
          narrative: {
            es: "{name} se sienta cerquita del pangolín sin hacer ruido y espera con paciencia hasta que él se desenrosca y camina a su lado hacia el oasis.",
            ca: "{name} seu a prop del pangolí sense fer soroll i espera amb paciència fins que ell es desenrosca i camina al seu costat cap a l'oasi.",
            en: "{name} sits quietly close to the pangolin and waits patiently until he unrolls and walks alongside towards the oasis.",
            fr: "{name} s'installe tout près du pangolin sans faire de bruit et attend patiemment jusqu'à ce qu'il se déroule et marche à ses côtés vers l'oasis.",
          },
          next: "ending",
        },
        {
          id: "snack-trail",
          title: {
            es: "Un caminito de termitas",
            ca: "Un caminet de tèrmits",
            en: "A little termite trail",
            fr: "Un petit chemin de termites",
          },
          desc: {
            es: "Sus bocaditos favoritos, colocados en filita hasta la orilla del agua.",
            ca: "Els seus mossets preferits, col·locats en filera fins a la vora de l'aigua.",
            en: "His favourite nibbles, laid out in a neat little line down to the water's edge.",
            fr: "Ses petites bouchées préférées, alignées en file jusqu'au bord de l'eau.",
          },
          imageSeed: "safari-c3oasisa-trail",
          icon: "route",
          narrative: {
            es: "{name} coloca una filita de sabrosas termitas hasta la orilla y el pangolín la sigue pasito a pasito hasta el oasis.",
            ca: "{name} col·loca una filera de tèrmits saborosos fins a la vora i el pangolí la segueix passet a passet fins a l'oasi.",
            en: "{name} lays out a little line of tasty termites down to the bank and the pangolin follows it step by tiny step to the oasis.",
            fr: "{name} dispose une petite file de termites savoureuses jusqu'à la rive et le pangolin la suit tout petit pas par tout petit pas jusqu'à l'oasis.",
          },
          next: "ending",
        },
        {
          id: "soft-whisper",
          title: {
            es: "Contarle el oasis bajito",
            ca: "Explicar-li l'oasi fluixet",
            en: "Whisper about the oasis",
            fr: "Lui raconter l'oasis tout bas",
          },
          desc: {
            es: "Una voz suave que describe el agua brillante quita todos los miedos.",
            ca: "Una veu suau que descriu l'aigua brillant treu totes les pors.",
            en: "A soft voice describing the sparkling water melts every fear away.",
            fr: "Une voix douce qui décrit l'eau scintillante fait fondre toutes les peurs.",
          },
          imageSeed: "safari-c3oasisa-whisper",
          icon: "record_voice_over",
          narrative: {
            es: "{name} le cuenta bajito al pangolín cómo brilla el agua y qué amables son los animales, hasta que él se desenrosca con una sonrisa.",
            ca: "{name} explica fluixet al pangolí com brilla l'aigua i que amables que són els animals, fins que ell es desenrosca amb un somriure.",
            en: "{name} whispers to the pangolin about the sparkling water and the friendly animals, until he unrolls with a smile.",
            fr: "{name} raconte tout bas au pangolin comme l'eau scintille et comme les animaux sont gentils, jusqu'à ce qu'il se déroule avec un sourire.",
          },
          next: "ending",
        },
      ],
    },
    c3_oasis_b: {
      id: "c3_oasis_b",
      chapter: 3,
      question: {
        es: "La tortuga centenaria quiere llegar al oasis antes de que el sol se ponga, pero sus patitas van muy despacio. ¿Cómo la ayuda {name}?",
        ca: "La tortuga centenària vol arribar a l'oasi abans que el sol es pongui, però les seves potetes van molt a poc a poc. Com l'ajuda {name}?",
        en: "The hundred-year-old tortoise wants to reach the oasis before the sun sets, but her little legs are very slow. How does {name} help her?",
        fr: "La tortue centenaire veut arriver à l'oasis avant le coucher du soleil, mais ses petites pattes vont très lentement. Comment {name} l'aide ?",
      },
      options: [
        {
          id: "elephant-ride",
          title: {
            es: "Pedir ayuda al elefante",
            ca: "Demanar ajuda a l'elefant",
            en: "Ask the elephant for help",
            fr: "Demander de l'aide à l'éléphant",
          },
          desc: {
            es: "Un viaje en el lomo del elefante es el autobús más cómodo de la sabana.",
            ca: "Un viatge al llom de l'elefant és l'autobús més còmode de la sabana.",
            en: "A ride on the elephant's back is the comfiest bus in the savanna.",
            fr: "Un voyage sur le dos de l'éléphant, c'est le bus le plus confortable de la savane.",
          },
          imageSeed: "safari-c3oasisb-ride",
          icon: "cruelty_free",
          narrative: {
            es: "{name} pide ayuda a un elefante amable, que sube a la tortuga a su lomo con la trompa y los lleva a los dos hasta el oasis.",
            ca: "{name} demana ajuda a un elefant amable, que puja la tortuga al seu llom amb la trompa i els porta tots dos fins a l'oasi.",
            en: "{name} asks a kind elephant for help, and it lifts the tortoise onto its back with its trunk and carries them both to the oasis.",
            fr: "{name} demande de l'aide à un gentil éléphant, qui hisse la tortue sur son dos avec sa trompe et les porte tous les deux jusqu'à l'oasis.",
          },
          next: "ending",
        },
        {
          id: "meerkat-shortcut",
          title: {
            es: "El atajo de las suricatas",
            ca: "La drecera de les suricates",
            en: "The meerkats' shortcut",
            fr: "Le raccourci des suricates",
          },
          desc: {
            es: "Las suricatas conocen un caminito secreto entre la hierba alta.",
            ca: "Les suricates coneixen un caminet secret entre l'herba alta.",
            en: "The meerkats know a secret little path through the tall grass.",
            fr: "Les suricates connaissent un petit chemin secret dans les hautes herbes.",
          },
          imageSeed: "safari-c3oasisb-shortcut",
          icon: "alt_route",
          narrative: {
            es: "{name} sigue a una suricata exploradora por un atajo secreto entre la hierba y la tortuga llega al oasis antes de la puesta de sol.",
            ca: "{name} segueix una suricata exploradora per una drecera secreta entre l'herba i la tortuga arriba a l'oasi abans de la posta de sol.",
            en: "{name} follows a scout meerkat down a secret shortcut through the grass and the tortoise reaches the oasis before sunset.",
            fr: "{name} suit une suricate exploratrice par un raccourci secret dans l'herbe et la tortue atteint l'oasis avant le coucher du soleil.",
          },
          next: "ending",
        },
        {
          id: "her-pace",
          title: {
            es: "Caminar a su ritmo",
            ca: "Caminar al seu ritme",
            en: "Walk at her pace",
            fr: "Marcher à son rythme",
          },
          desc: {
            es: "Con buenas historias, hasta el camino más largo se hace cortito.",
            ca: "Amb bones històries, fins i tot el camí més llarg es fa curtet.",
            en: "With good stories, even the longest road feels short.",
            fr: "Avec de bonnes histoires, même le plus long chemin paraît court.",
          },
          imageSeed: "safari-c3oasisb-stories",
          icon: "auto_stories",
          narrative: {
            es: "{name} camina pasito a pasito junto a la tortuga contándole historias, y los dos llegan al oasis justo cuando el cielo se vuelve dorado.",
            ca: "{name} camina passet a passet al costat de la tortuga explicant-li històries, i tots dos arriben a l'oasi just quan el cel es torna daurat.",
            en: "{name} walks step by tiny step beside the tortoise telling her stories, and the two of them reach the oasis just as the sky turns golden.",
            fr: "{name} marche tout petit pas par tout petit pas à côté de la tortue en lui racontant des histoires, et tous deux arrivent à l'oasis juste quand le ciel devient doré.",
          },
          next: "ending",
        },
      ],
    },
    c3_oasis_c: {
      id: "c3_oasis_c",
      chapter: 3,
      question: {
        es: "El potrillo de cebra tiene miedo del reflejo rayado que le mira desde el agua. ¿Cómo le ayuda {name} a perder el miedo?",
        ca: "El pollí de zebra té por del reflex ratllat que el mira des de l'aigua. Com l'ajuda {name} a perdre la por?",
        en: "The zebra foal is scared of the stripy reflection staring back at him from the water. How does {name} help him lose his fear?",
        fr: "Le bébé zèbre a peur du reflet rayé qui le regarde depuis l'eau. Comment {name} l'aide à ne plus avoir peur ?",
      },
      options: [
        {
          id: "funny-faces",
          title: {
            es: "Hacer muecas divertidas",
            ca: "Fer ganyotes divertides",
            en: "Make funny faces",
            fr: "Faire des grimaces rigolotes",
          },
          desc: {
            es: "Si el reflejo hace muecas graciosas, el miedo se convierte en risa.",
            ca: "Si el reflex fa ganyotes gracioses, la por es converteix en riure.",
            en: "If the reflection pulls silly faces, fear turns into giggles.",
            fr: "Si le reflet fait des grimaces rigolotes, la peur se transforme en rire.",
          },
          imageSeed: "safari-c3oasisc-faces",
          icon: "sentiment_very_satisfied",
          narrative: {
            es: "{name} hace muecas divertidas al agua junto al potrillo hasta que los dos reflejos se ríen y el miedo desaparece.",
            ca: "{name} fa ganyotes divertides a l'aigua al costat del pollí fins que els dos reflexos riuen i la por desapareix.",
            en: "{name} pulls funny faces at the water next to the foal until both reflections are laughing and the fear is gone.",
            fr: "{name} fait des grimaces rigolotes à l'eau à côté du bébé zèbre jusqu'à ce que les deux reflets rient et que la peur disparaisse.",
          },
          next: "ending",
        },
        {
          id: "dancing-water",
          title: {
            es: "Hacer bailar el agua",
            ca: "Fer ballar l'aigua",
            en: "Make the water dance",
            fr: "Faire danser l'eau",
          },
          desc: {
            es: "Al tocar el agua con un dedo, el reflejo se ondula y baila.",
            ca: "En tocar l'aigua amb un dit, el reflex s'ondula i balla.",
            en: "One touch of a finger and the reflection ripples and dances.",
            fr: "Un doigt qui touche l'eau, et le reflet ondule et danse.",
          },
          imageSeed: "safari-c3oasisc-ripples",
          icon: "waves",
          narrative: {
            es: "{name} toca el agua con la punta del dedo y el reflejo del potrillo se ondula bailando, y él descubre riendo que solo es agua juguetona.",
            ca: "{name} toca l'aigua amb la punta del dit i el reflex del pollí s'ondula ballant, i ell descobreix rient que només és aigua juganera.",
            en: "{name} touches the water with a fingertip and the foal's reflection ripples into a dance, and he discovers with a laugh that it is only playful water.",
            fr: "{name} touche l'eau du bout du doigt et le reflet du bébé zèbre ondule en dansant, et il découvre en riant que ce n'est que de l'eau joueuse.",
          },
          next: "ending",
        },
        {
          id: "starry-drink",
          title: {
            es: "Beber bajo las estrellas",
            ca: "Beure sota les estrelles",
            en: "Drink under the stars",
            fr: "Boire sous les étoiles",
          },
          desc: {
            es: "De noche, el agua del oasis se llena de estrellitas brillantes.",
            ca: "De nit, l'aigua de l'oasi s'omple d'estrelletes brillants.",
            en: "At night, the oasis water fills up with shining little stars.",
            fr: "La nuit, l'eau de l'oasis se remplit de petites étoiles brillantes.",
          },
          imageSeed: "safari-c3oasisc-stars",
          icon: "star",
          narrative: {
            es: "{name} vuelve con el potrillo al caer la noche y los dos beben rodeados de estrellitas reflejadas, sin ningún miedo.",
            ca: "{name} torna amb el pollí quan cau la nit i tots dos beuen envoltats d'estrelletes reflectides, sense gens de por.",
            en: "{name} comes back with the foal at nightfall and the two of them drink surrounded by reflected little stars, with no fear at all.",
            fr: "{name} revient avec le bébé zèbre à la tombée de la nuit et tous deux boivent entourés de petites étoiles reflétées, sans aucune peur.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "", en: "", fr: "" },
      options: [],
    },
  },
};
