import type { StoryTree } from "./types";

// Branching story tree for the "space" template (Fase B).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es, ca, en, fr). {name} = child's name.

export const spaceTree: StoryTree = {
  templateId: "space",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} despega en su cohete y, al asomarse por la ventanilla, ve tres cosas brillando en la oscuridad. ¿Hacia cuál quiere ir primero?",
        ca: "{name} enlaira el seu coet i, en treure el cap per la finestreta, veu tres coses brillant a la foscor. Cap a quina vol anar primer?",
        en: "{name} blasts off in the rocket and, peeking out of the little window, sees three things shining in the darkness. Which one do they want to visit first?",
        fr: "{name} décolle à bord de sa fusée et, en regardant par le hublot, aperçoit trois choses qui brillent dans le noir. Vers laquelle aller en premier ?",
      },
      options: [
        {
          id: "robot",
          title: { es: "El robot perdido", ca: "El robot perdut", en: "The lost robot", fr: "Le robot perdu" },
          desc: {
            es: "Un robot pequeño parpadea pidiendo ayuda entre las estrellas.",
            ca: "Un robot petit parpelleja demanant ajuda entre les estrelles.",
            en: "A little robot blinks for help among the stars.",
            fr: "Un petit robot clignote pour demander de l'aide parmi les étoiles.",
          },
          imageSeed: "space-c1-robot",
          icon: "smart_toy",
          narrative: {
            es: "{name} dirige el cohete hacia un robot plateado que flota solo y parpadea pidiendo ayuda.",
            ca: "{name} dirigeix el coet cap a un robot platejat que sura tot sol i parpelleja demanant ajuda.",
            en: "{name} steers the rocket toward a silver robot floating all alone, blinking for help.",
            fr: "{name} dirige la fusée vers un robot argenté qui flotte tout seul et clignote pour demander de l'aide.",
          },
          next: "c2_robot",
        },
        {
          id: "crystal",
          title: { es: "El cristal mágico", ca: "El cristall màgic", en: "The magic crystal", fr: "Le cristal magique" },
          desc: {
            es: "Un cristal de colores late suavemente sobre un asteroide.",
            ca: "Un cristall de colors batega suaument sobre un asteroide.",
            en: "A colorful crystal pulses softly on an asteroid.",
            fr: "Un cristal de toutes les couleurs palpite doucement sur un astéroïde.",
          },
          imageSeed: "space-c1-crystal",
          icon: "diamond",
          narrative: {
            es: "{name} guía el cohete hacia un asteroide donde late un cristal de mil colores.",
            ca: "{name} guia el coet cap a un asteroide on batega un cristall de mil colors.",
            en: "{name} guides the rocket to an asteroid where a crystal of a thousand colors pulses with light.",
            fr: "{name} guide la fusée vers un astéroïde où palpite un cristal aux mille couleurs.",
          },
          next: "c2_crystal",
        },
        {
          id: "ship",
          title: { es: "La nave dormida", ca: "La nau adormida", en: "The sleeping ship", fr: "Le vaisseau endormi" },
          desc: {
            es: "Una nave enorme flota en silencio con las luces apagadas.",
            ca: "Una nau enorme sura en silenci amb els llums apagats.",
            en: "A huge ship floats silently with all its lights off.",
            fr: "Un immense vaisseau flotte en silence, toutes lumières éteintes.",
          },
          imageSeed: "space-c1-ship",
          icon: "rocket_launch",
          narrative: {
            es: "{name} se acerca a una nave gigante y silenciosa que parece dormida en el vacío.",
            ca: "{name} s'acosta a una nau gegant i silenciosa que sembla adormida al buit.",
            en: "{name} drifts closer to a giant, silent ship that seems to be sleeping in space.",
            fr: "{name} s'approche d'un vaisseau géant et silencieux qui semble endormi dans le vide.",
          },
          next: "c2_ship",
        },
      ],
    },
    c2_robot: {
      id: "c2_robot",
      chapter: 2,
      question: {
        es: "El robot se llama Tin y ha perdido su tornillo de energía. {name} quiere ayudarle. ¿Por dónde empiezan a buscar?",
        ca: "El robot es diu Tin i ha perdut el seu cargol d'energia. {name} vol ajudar-lo. Per on comencen a buscar?",
        en: "The robot's name is Tin, and he has lost his energy screw. {name} wants to help him. Where do they start looking?",
        fr: "Le robot s'appelle Tin et il a perdu sa vis d'énergie. {name} veut l'aider. Par où commencent-ils à chercher ?",
      },
      options: [
        {
          id: "factory",
          title: { es: "La fábrica flotante", ca: "La fàbrica flotant", en: "The floating factory", fr: "L'usine flottante" },
          desc: {
            es: "Una fábrica vieja gira llena de piezas y tornillos brillantes.",
            ca: "Una fàbrica vella gira plena de peces i cargols brillants.",
            en: "An old factory spins, full of shiny parts and screws.",
            fr: "Une vieille usine tourne, remplie de pièces et de vis brillantes.",
          },
          imageSeed: "space-c2robot-factory",
          icon: "factory",
          narrative: {
            es: "{name} y Tin entran en una fábrica flotante repleta de engranajes y tornillos relucientes.",
            ca: "{name} i en Tin entren en una fàbrica flotant plena d'engranatges i cargols lluents.",
            en: "{name} and Tin step into a floating factory packed with gears and gleaming screws.",
            fr: "{name} et Tin entrent dans une usine flottante remplie d'engrenages et de vis étincelantes.",
          },
          next: "c3_robot_a",
        },
        {
          id: "comet",
          title: { es: "La cola del cometa", ca: "La cua del cometa", en: "The comet's tail", fr: "La queue de la comète" },
          desc: {
            es: "Un cometa veloz deja chispas que parecen piezas perdidas.",
            ca: "Un cometa veloç deixa espurnes que semblen peces perdudes.",
            en: "A speedy comet leaves sparks that look like lost parts.",
            fr: "Une comète rapide laisse des étincelles qui ressemblent à des pièces perdues.",
          },
          imageSeed: "space-c2robot-comet",
          icon: "flare",
          narrative: {
            es: "{name} y Tin persiguen un cometa que va dejando chispas brillantes por todo el cielo.",
            ca: "{name} i en Tin persegueixen un cometa que va deixant espurnes brillants per tot el cel.",
            en: "{name} and Tin chase a comet that scatters bright sparks all across the sky.",
            fr: "{name} et Tin poursuivent une comète qui sème des étincelles brillantes dans tout le ciel.",
          },
          next: "c3_robot_b",
        },
        {
          id: "moon",
          title: { es: "La luna de chatarra", ca: "La lluna de ferralla", en: "The scrap-metal moon", fr: "La lune de ferraille" },
          desc: {
            es: "Una luna gris guarda montañas de piezas antiguas.",
            ca: "Una lluna grisa guarda muntanyes de peces antigues.",
            en: "A gray moon keeps mountains of old parts.",
            fr: "Une lune grise garde des montagnes de vieilles pièces.",
          },
          imageSeed: "space-c2robot-moon",
          icon: "recycling",
          narrative: {
            es: "{name} y Tin aterrizan en una luna gris cubierta de montañas de chatarra espacial.",
            ca: "{name} i en Tin aterren en una lluna grisa coberta de muntanyes de ferralla espacial.",
            en: "{name} and Tin land on a gray moon covered in mountains of space scrap.",
            fr: "{name} et Tin atterrissent sur une lune grise couverte de montagnes de ferraille spatiale.",
          },
          next: "c3_robot_c",
        },
      ],
    },
    c2_crystal: {
      id: "c2_crystal",
      chapter: 2,
      question: {
        es: "Al tocar el cristal, este susurra que está triste porque perdió su brillo. {name} quiere devolvérselo. ¿Cómo lo hacen?",
        ca: "En tocar el cristall, aquest xiuxiueja que està trist perquè ha perdut la seva lluentor. {name} vol tornar-l'hi. Com ho fan?",
        en: "When {name} touches the crystal, it whispers that it is sad because it lost its sparkle. {name} wants to give it back. How do they do it?",
        fr: "Quand {name} touche le cristal, celui-ci murmure qu'il est triste parce qu'il a perdu son éclat. {name} veut le lui rendre. Comment faire ?",
      },
      options: [
        {
          id: "star",
          title: { es: "Pedir luz a una estrella", ca: "Demanar llum a una estrella", en: "Ask a star for light", fr: "Demander de la lumière à une étoile" },
          desc: {
            es: "Una estrella amable podría regalar un poco de su luz.",
            ca: "Una estrella amable podria regalar una mica de la seva llum.",
            en: "A kind star might share a little of its light.",
            fr: "Une étoile gentille pourrait offrir un peu de sa lumière.",
          },
          imageSeed: "space-c2crystal-star",
          icon: "star",
          narrative: {
            es: "{name} vuela hasta una estrella sonriente y le pide con dulzura un poquito de su luz.",
            ca: "{name} vola fins a una estrella somrient i li demana amb dolçor una miqueta de la seva llum.",
            en: "{name} flies up to a smiling star and sweetly asks for a tiny bit of its light.",
            fr: "{name} vole jusqu'à une étoile souriante et lui demande tout doucement un petit peu de sa lumière.",
          },
          next: "c3_crystal_a",
        },
        {
          id: "rainbow",
          title: { es: "Cruzar el arcoíris cósmico", ca: "Travessar l'arc de Sant Martí còsmic", en: "Cross the cosmic rainbow", fr: "Traverser l'arc-en-ciel cosmique" },
          desc: {
            es: "Un puente de colores podría pintar el cristal de nuevo.",
            ca: "Un pont de colors podria pintar el cristall de nou.",
            en: "A bridge of colors could paint the crystal again.",
            fr: "Un pont de couleurs pourrait repeindre le cristal.",
          },
          imageSeed: "space-c2crystal-rainbow",
          icon: "looks",
          narrative: {
            es: "{name} cruza un arcoíris cósmico esperando que sus colores tiñan el cristal otra vez.",
            ca: "{name} travessa un arc de Sant Martí còsmic esperant que els seus colors tornin a tenyir el cristall.",
            en: "{name} crosses a cosmic rainbow, hoping its colors will paint the crystal once more.",
            fr: "{name} traverse un arc-en-ciel cosmique en espérant que ses couleurs colorent à nouveau le cristal.",
          },
          next: "c3_crystal_b",
        },
        {
          id: "song",
          title: { es: "Cantarle una canción", ca: "Cantar-li una cançó", en: "Sing it a song", fr: "Lui chanter une chanson" },
          desc: {
            es: "Quizás una canción tierna despierte su brillo dormido.",
            ca: "Potser una cançó tendra desperti la seva lluentor adormida.",
            en: "Maybe a tender song will wake its sleeping sparkle.",
            fr: "Peut-être qu'une douce chanson réveillera son éclat endormi.",
          },
          imageSeed: "space-c2crystal-song",
          icon: "music_note",
          narrative: {
            es: "{name} respira hondo y le canta al cristal una canción tan tierna que empieza a vibrar.",
            ca: "{name} respira fons i canta al cristall una cançó tan tendra que comença a vibrar.",
            en: "{name} takes a deep breath and sings the crystal a song so tender that it begins to hum and tremble.",
            fr: "{name} respire un grand coup et chante au cristal une chanson si douce qu'il se met à vibrer.",
          },
          next: "c3_crystal_c",
        },
      ],
    },
    c2_ship: {
      id: "c2_ship",
      chapter: 2,
      question: {
        es: "{name} entra en la nave dormida y todo está oscuro y en silencio. ¿Qué hace para despertarla?",
        ca: "{name} entra a la nau adormida i tot està fosc i en silenci. Què fa per despertar-la?",
        en: "{name} steps inside the sleeping ship, where everything is dark and silent. What do they do to wake it up?",
        fr: "{name} entre dans le vaisseau endormi : tout est sombre et silencieux. Que faire pour le réveiller ?",
      },
      options: [
        {
          id: "bridge",
          title: { es: "Buscar el puente de mando", ca: "Buscar el pont de comandament", en: "Find the command bridge", fr: "Chercher le poste de pilotage" },
          desc: {
            es: "Allí debe estar el gran botón que enciende todo.",
            ca: "Allà hi deu haver el gran botó que ho encén tot.",
            en: "The big button that turns everything on must be there.",
            fr: "Le grand bouton qui allume tout doit se trouver là-bas.",
          },
          imageSeed: "space-c2ship-bridge",
          icon: "power_settings_new",
          narrative: {
            es: "{name} recorre pasillos oscuros buscando el puente de mando y su gran botón de encendido.",
            ca: "{name} recorre passadissos foscos buscant el pont de comandament i el seu gran botó d'engegada.",
            en: "{name} walks down dark corridors, searching for the command bridge and its big power button.",
            fr: "{name} parcourt des couloirs sombres à la recherche du poste de pilotage et de son grand bouton de démarrage.",
          },
          next: "c3_ship_a",
        },
        {
          id: "engine",
          title: { es: "Bajar a los motores", ca: "Baixar als motors", en: "Go down to the engines", fr: "Descendre aux moteurs" },
          desc: {
            es: "Tal vez el corazón de la nave solo necesita calor.",
            ca: "Potser el cor de la nau només necessita escalfor.",
            en: "Maybe the heart of the ship just needs some warmth.",
            fr: "Peut-être que le cœur du vaisseau a juste besoin de chaleur.",
          },
          imageSeed: "space-c2ship-engine",
          icon: "settings",
          narrative: {
            es: "{name} baja por una escalera hasta la sala de motores, el corazón dormido de la nave.",
            ca: "{name} baixa per una escala fins a la sala de motors, el cor adormit de la nau.",
            en: "{name} climbs down a ladder to the engine room, the sleeping heart of the ship.",
            fr: "{name} descend par une échelle jusqu'à la salle des moteurs, le cœur endormi du vaisseau.",
          },
          next: "c3_ship_b",
        },
        {
          id: "garden",
          title: { es: "Explorar el jardín interior", ca: "Explorar el jardí interior", en: "Explore the indoor garden", fr: "Explorer le jardin intérieur" },
          desc: {
            es: "Una puerta deja ver plantas que brillan en la penumbra.",
            ca: "Una porta deixa veure plantes que brillen a la penombra.",
            en: "A door reveals plants glowing in the half-light.",
            fr: "Une porte laisse voir des plantes qui brillent dans la pénombre.",
          },
          imageSeed: "space-c2ship-garden",
          icon: "potted_plant",
          narrative: {
            es: "{name} abre una puerta y descubre un jardín interior con plantas que brillan en la penumbra.",
            ca: "{name} obre una porta i descobreix un jardí interior amb plantes que brillen a la penombra.",
            en: "{name} opens a door and discovers an indoor garden full of plants glowing in the half-light.",
            fr: "{name} ouvre une porte et découvre un jardin intérieur aux plantes qui brillent dans la pénombre.",
          },
          next: "c3_ship_c",
        },
      ],
    },
    c3_robot_a: {
      id: "c3_robot_a",
      chapter: 3,
      question: {
        es: "Dentro de la fábrica flotante hay tornillos por todas partes. ¿Cómo encuentra {name} el tornillo de energía correcto para Tin?",
        ca: "Dins de la fàbrica flotant hi ha cargols per tot arreu. Com troba {name} el cargol d'energia correcte per a en Tin?",
        en: "Inside the floating factory there are screws everywhere. How does {name} find the right energy screw for Tin?",
        fr: "Dans l'usine flottante, il y a des vis partout. Comment est-ce que {name} trouve la bonne vis d'énergie pour Tin ?",
      },
      options: [
        {
          id: "magnet",
          title: { es: "Usar un imán", ca: "Fer servir un imant", en: "Use a magnet", fr: "Utiliser un aimant" },
          desc: {
            es: "Un imán gigante atrae justo la pieza que brilla más.",
            ca: "Un imant gegant atrau just la peça que brilla més.",
            en: "A giant magnet attracts just the part that shines the brightest.",
            fr: "Un aimant géant attire juste la pièce qui brille le plus.",
          },
          imageSeed: "space-c3robota-magnet",
          icon: "hardware",
          narrative: {
            es: "{name} agarra un imán gigante y la pieza correcta vuela directa a la mano de Tin.",
            ca: "{name} agafa un imant gegant i la peça correcta vola directa a la mà d'en Tin.",
            en: "{name} grabs a giant magnet, and the right part flies straight into Tin's hand.",
            fr: "{name} attrape un aimant géant et la bonne pièce vole droit dans la main de Tin.",
          },
          next: "ending",
        },
        {
          id: "listen",
          title: { es: "Escuchar su zumbido", ca: "Escoltar el seu brunzit", en: "Listen for its buzz", fr: "Écouter son bourdonnement" },
          desc: {
            es: "El tornillo correcto zumba bajito como una abejita.",
            ca: "El cargol correcte brunz fluixet com una abelleta.",
            en: "The right screw buzzes softly, like a little bee.",
            fr: "La bonne vis bourdonne tout bas, comme une petite abeille.",
          },
          imageSeed: "space-c3robota-listen",
          icon: "hearing",
          narrative: {
            es: "{name} cierra los ojos, escucha el zumbido más dulce y encuentra el tornillo escondido.",
            ca: "{name} tanca els ulls, escolta el brunzit més dolç i troba el cargol amagat.",
            en: "{name} closes their eyes, listens for the sweetest buzz, and finds the hidden screw.",
            fr: "{name} ferme les yeux, écoute le bourdonnement le plus doux et trouve la vis cachée.",
          },
          next: "ending",
        },
        {
          id: "robot-helper",
          title: { es: "Pedir ayuda a las máquinas", ca: "Demanar ajuda a les màquines", en: "Ask the machines for help", fr: "Demander de l'aide aux machines" },
          desc: {
            es: "Las máquinas amables de la fábrica quieren colaborar.",
            ca: "Les màquines amables de la fàbrica volen col·laborar.",
            en: "The friendly factory machines are happy to help.",
            fr: "Les gentilles machines de l'usine veulent bien aider.",
          },
          imageSeed: "space-c3robota-helper",
          icon: "precision_manufacturing",
          narrative: {
            es: "{name} pide ayuda a las máquinas de la fábrica, que con cariño le entregan el tornillo justo.",
            ca: "{name} demana ajuda a les màquines de la fàbrica, que amb afecte li lliuren el cargol just.",
            en: "{name} asks the factory machines for help, and they lovingly hand over just the right screw.",
            fr: "{name} demande de l'aide aux machines de l'usine, qui lui donnent avec tendresse la vis parfaite.",
          },
          next: "ending",
        },
      ],
    },
    c3_robot_b: {
      id: "c3_robot_b",
      chapter: 3,
      question: {
        es: "El cometa va muy rápido y las chispas se escapan. ¿Cómo atrapa {name} la chispa que esconde el tornillo de Tin?",
        ca: "El cometa va molt ràpid i les espurnes s'escapen. Com atrapa {name} l'espurna que amaga el cargol d'en Tin?",
        en: "The comet moves so fast that the sparks keep slipping away. How does {name} catch the spark that hides Tin's screw?",
        fr: "La comète file très vite et les étincelles s'échappent. Comment est-ce que {name} attrape l'étincelle qui cache la vis de Tin ?",
      },
      options: [
        {
          id: "net",
          title: { es: "Lanzar una red de estrellas", ca: "Llançar una xarxa d'estrelles", en: "Throw a net of stars", fr: "Lancer un filet d'étoiles" },
          desc: {
            es: "Una red tejida con luz puede atrapar la chispa.",
            ca: "Una xarxa teixida amb llum pot atrapar l'espurna.",
            en: "A net woven from light can catch the spark.",
            fr: "Un filet tissé de lumière peut attraper l'étincelle.",
          },
          imageSeed: "space-c3robotb-net",
          icon: "phishing",
          narrative: {
            es: "{name} lanza una red tejida con luz de estrellas y atrapa la chispa al vuelo.",
            ca: "{name} llança una xarxa teixida amb llum d'estrelles i atrapa l'espurna al vol.",
            en: "{name} throws a net woven from starlight and catches the spark in mid-flight.",
            fr: "{name} lance un filet tissé de lumière d'étoiles et attrape l'étincelle en plein vol.",
          },
          next: "ending",
        },
        {
          id: "race",
          title: { es: "Echar una carrera", ca: "Fer una cursa", en: "Have a race", fr: "Faire la course" },
          desc: {
            es: "El cohete acelera para alcanzar al cometa veloz.",
            ca: "El coet accelera per atrapar el cometa veloç.",
            en: "The rocket speeds up to catch the swift comet.",
            fr: "La fusée accélère pour rattraper la comète rapide.",
          },
          imageSeed: "space-c3robotb-race",
          icon: "rocket",
          narrative: {
            es: "{name} acelera el cohete y, en una carrera emocionante, alcanza al cometa y su chispa.",
            ca: "{name} accelera el coet i, en una cursa emocionant, atrapa el cometa i la seva espurna.",
            en: "{name} speeds up the rocket and, in a thrilling race, catches up with the comet and its spark.",
            fr: "{name} accélère la fusée et, dans une course palpitante, rattrape la comète et son étincelle.",
          },
          next: "ending",
        },
        {
          id: "wish",
          title: { es: "Pedir un deseo", ca: "Demanar un desig", en: "Make a wish", fr: "Faire un vœu" },
          desc: {
            es: "A veces un deseo sincero hace que la chispa venga sola.",
            ca: "De vegades un desig sincer fa que l'espurna vingui sola.",
            en: "Sometimes a heartfelt wish makes the spark come all by itself.",
            fr: "Parfois, un vœu sincère fait venir l'étincelle toute seule.",
          },
          imageSeed: "space-c3robotb-wish",
          icon: "star",
          narrative: {
            es: "{name} cierra los ojos, pide un deseo sincero y la chispa baja despacito hasta su mano.",
            ca: "{name} tanca els ulls, demana un desig sincer i l'espurna baixa a poc a poc fins a la seva mà.",
            en: "{name} closes their eyes, makes a heartfelt wish, and the spark floats gently down into their hand.",
            fr: "{name} ferme les yeux, fait un vœu sincère et l'étincelle descend tout doucement jusqu'à sa main.",
          },
          next: "ending",
        },
      ],
    },
    c3_robot_c: {
      id: "c3_robot_c",
      chapter: 3,
      question: {
        es: "En la luna de chatarra hay montañas enormes de piezas. ¿Cómo busca {name} entre tanto desorden el tornillo de Tin?",
        ca: "A la lluna de ferralla hi ha muntanyes enormes de peces. Com busca {name} entre tant desordre el cargol d'en Tin?",
        en: "On the scrap-metal moon there are huge mountains of parts. How does {name} search through all that mess for Tin's screw?",
        fr: "Sur la lune de ferraille, il y a d'énormes montagnes de pièces. Comment est-ce que {name} cherche la vis de Tin dans tout ce désordre ?",
      },
      options: [
        {
          id: "dig",
          title: { es: "Cavar con cuidado", ca: "Cavar amb cura", en: "Dig carefully", fr: "Creuser avec précaution" },
          desc: {
            es: "Apartando piezas poco a poco aparece un brillo dorado.",
            ca: "Apartant peces de mica en mica apareix una lluentor daurada.",
            en: "Moving parts aside little by little, a golden glow appears.",
            fr: "En écartant les pièces petit à petit, une lueur dorée apparaît.",
          },
          imageSeed: "space-c3robotc-dig",
          icon: "construction",
          narrative: {
            es: "{name} aparta piezas con cuidado hasta que un brillo dorado asoma entre la chatarra.",
            ca: "{name} aparta peces amb cura fins que una lluentor daurada apareix entre la ferralla.",
            en: "{name} carefully moves parts aside until a golden glow peeks out from the scrap.",
            fr: "{name} écarte les pièces avec précaution jusqu'à ce qu'une lueur dorée apparaisse au milieu de la ferraille.",
          },
          next: "ending",
        },
        {
          id: "friend",
          title: { es: "Conocer a un alienígena", ca: "Conèixer un alienígena", en: "Meet an alien", fr: "Rencontrer un extraterrestre" },
          desc: {
            es: "Un ser pequeñito vive aquí y conoce cada pieza.",
            ca: "Un ésser petitó viu aquí i coneix cada peça.",
            en: "A tiny creature lives here and knows every single part.",
            fr: "Un tout petit être vit ici et connaît chaque pièce.",
          },
          imageSeed: "space-c3robotc-friend",
          icon: "mood",
          narrative: {
            es: "{name} conoce a un alienígena risueño que vive en la luna y le señala el tornillo perfecto.",
            ca: "{name} coneix un alienígena rialler que viu a la lluna i li assenyala el cargol perfecte.",
            en: "{name} meets a cheerful alien who lives on the moon and points out the perfect screw.",
            fr: "{name} rencontre un extraterrestre rieur qui vit sur la lune et lui montre la vis parfaite.",
          },
          next: "ending",
        },
        {
          id: "build",
          title: { es: "Fabricar uno nuevo", ca: "Fabricar-ne un de nou", en: "Build a new one", fr: "En fabriquer une neuve" },
          desc: {
            es: "Con piezas sueltas {name} construye un tornillo flamante.",
            ca: "Amb peces soltes {name} construeix un cargol flamant.",
            en: "With loose parts, {name} builds a brand-new screw.",
            fr: "Avec des pièces détachées, {name} fabrique une vis toute neuve.",
          },
          imageSeed: "space-c3robotc-build",
          icon: "build",
          narrative: {
            es: "{name} junta varias piezas sueltas y construye un tornillo flamante para Tin.",
            ca: "{name} ajunta diverses peces soltes i construeix un cargol flamant per a en Tin.",
            en: "{name} gathers some loose parts and builds a shiny brand-new screw for Tin.",
            fr: "{name} assemble plusieurs pièces détachées et fabrique une vis toute neuve pour Tin.",
          },
          next: "ending",
        },
      ],
    },
    c3_crystal_a: {
      id: "c3_crystal_a",
      chapter: 3,
      question: {
        es: "La estrella sonríe y quiere ayudar, pero su luz es muy fuerte. ¿Cómo lleva {name} esa luz hasta el cristal sin que se apague?",
        ca: "L'estrella somriu i vol ajudar, però la seva llum és molt forta. Com porta {name} aquesta llum fins al cristall sense que s'apagui?",
        en: "The star smiles and wants to help, but its light is very strong. How does {name} carry that light to the crystal without letting it go out?",
        fr: "L'étoile sourit et veut aider, mais sa lumière est très forte. Comment est-ce que {name} porte cette lumière jusqu'au cristal sans qu'elle s'éteigne ?",
      },
      options: [
        {
          id: "jar",
          title: { es: "Guardarla en un frasco", ca: "Guardar-la en un pot", en: "Keep it in a jar", fr: "La garder dans un bocal" },
          desc: {
            es: "Un frasco mágico atrapa la luz como una luciérnaga.",
            ca: "Un pot màgic atrapa la llum com una cuca de llum.",
            en: "A magic jar catches the light like a firefly.",
            fr: "Un bocal magique attrape la lumière comme une luciole.",
          },
          imageSeed: "space-c3crystala-jar",
          icon: "science",
          narrative: {
            es: "{name} guarda un trocito de luz en un frasco mágico y lo lleva hasta el cristal.",
            ca: "{name} guarda un trosset de llum en un pot màgic i el porta fins al cristall.",
            en: "{name} keeps a little piece of light in a magic jar and carries it to the crystal.",
            fr: "{name} garde un petit bout de lumière dans un bocal magique et le porte jusqu'au cristal.",
          },
          next: "ending",
        },
        {
          id: "ray",
          title: { es: "Hacer un rayo suave", ca: "Fer un raig suau", en: "Make a gentle ray", fr: "Faire un rayon tout doux" },
          desc: {
            es: "La estrella sopla un rayito justo hacia el cristal.",
            ca: "L'estrella bufa un raget just cap al cristall.",
            en: "The star blows a little ray straight toward the crystal.",
            fr: "L'étoile souffle un petit rayon droit vers le cristal.",
          },
          imageSeed: "space-c3crystala-ray",
          icon: "light_mode",
          narrative: {
            es: "La estrella sopla un rayito suave y {name} lo guía con las manos hasta el cristal.",
            ca: "L'estrella bufa un raget suau i {name} el guia amb les mans fins al cristall.",
            en: "The star blows a gentle little ray, and {name} guides it with their hands to the crystal.",
            fr: "L'étoile souffle un petit rayon tout doux et {name} le guide avec les mains jusqu'au cristal.",
          },
          next: "ending",
        },
        {
          id: "carry",
          title: { es: "Llevarla en las manos", ca: "Portar-la a les mans", en: "Carry it in their hands", fr: "La porter dans ses mains" },
          desc: {
            es: "Con mucho cuidado {name} sostiene la luz tibia.",
            ca: "Amb molta cura {name} sosté la llum tèbia.",
            en: "Very carefully, {name} holds the warm light.",
            fr: "Avec beaucoup de précaution, {name} tient la lumière tiède.",
          },
          imageSeed: "space-c3crystala-carry",
          icon: "volunteer_activism",
          narrative: {
            es: "{name} ahueca las manos, sostiene la luz tibia con mucho cuidado y la acerca al cristal.",
            ca: "{name} fa un bressol amb les mans, sosté la llum tèbia amb molta cura i l'acosta al cristall.",
            en: "{name} cups their hands, holds the warm light very carefully, and brings it close to the crystal.",
            fr: "{name} fait un creux avec ses mains, tient la lumière tiède avec grand soin et l'approche du cristal.",
          },
          next: "ending",
        },
      ],
    },
    c3_crystal_b: {
      id: "c3_crystal_b",
      chapter: 3,
      question: {
        es: "El arcoíris cósmico tiene siete colores y el cristal los necesita todos. ¿Cómo recoge {name} cada color para el cristal?",
        ca: "L'arc de Sant Martí còsmic té set colors i el cristall els necessita tots. Com recull {name} cada color per al cristall?",
        en: "The cosmic rainbow has seven colors, and the crystal needs them all. How does {name} gather each color for the crystal?",
        fr: "L'arc-en-ciel cosmique a sept couleurs et le cristal a besoin des sept. Comment est-ce que {name} recueille chaque couleur pour le cristal ?",
      },
      options: [
        {
          id: "brush",
          title: { es: "Pintar con un pincel", ca: "Pintar amb un pinzell", en: "Paint with a brush", fr: "Peindre avec un pinceau" },
          desc: {
            es: "Un pincel mojado en arcoíris pinta el cristal entero.",
            ca: "Un pinzell mullat en arc de Sant Martí pinta el cristall sencer.",
            en: "A brush dipped in rainbow paints the whole crystal.",
            fr: "Un pinceau trempé dans l'arc-en-ciel peint le cristal tout entier.",
          },
          imageSeed: "space-c3crystalb-brush",
          icon: "brush",
          narrative: {
            es: "{name} moja un pincel en cada franja del arcoíris y pinta el cristal de mil colores.",
            ca: "{name} mulla un pinzell en cada franja de l'arc de Sant Martí i pinta el cristall de mil colors.",
            en: "{name} dips a brush into each stripe of the rainbow and paints the crystal a thousand colors.",
            fr: "{name} trempe un pinceau dans chaque bande de l'arc-en-ciel et peint le cristal de mille couleurs.",
          },
          next: "ending",
        },
        {
          id: "slide",
          title: { es: "Deslizarse por él", ca: "Lliscar per ell", en: "Slide down it", fr: "Glisser dessus" },
          desc: {
            es: "Como un tobogán, {name} resbala recogiendo colores.",
            ca: "Com un tobogan, {name} llisca recollint colors.",
            en: "Like a slide, {name} whooshes down, collecting colors.",
            fr: "Comme sur un toboggan, {name} glisse en ramassant les couleurs.",
          },
          imageSeed: "space-c3crystalb-slide",
          icon: "sledding",
          narrative: {
            es: "{name} se desliza por el arcoíris como un tobogán y los colores se le pegan a la ropa.",
            ca: "{name} llisca per l'arc de Sant Martí com un tobogan i els colors se li enganxen a la roba.",
            en: "{name} slides down the rainbow like a slide, and the colors stick to their clothes.",
            fr: "{name} glisse sur l'arc-en-ciel comme sur un toboggan et les couleurs s'accrochent à ses vêtements.",
          },
          next: "ending",
        },
        {
          id: "bottles",
          title: { es: "Llenar siete botellas", ca: "Omplir set ampolles", en: "Fill seven bottles", fr: "Remplir sept bouteilles" },
          desc: {
            es: "Una botella para cada color, listas para el cristal.",
            ca: "Una ampolla per a cada color, a punt per al cristall.",
            en: "One bottle for each color, ready for the crystal.",
            fr: "Une bouteille pour chaque couleur, prêtes pour le cristal.",
          },
          imageSeed: "space-c3crystalb-bottles",
          icon: "colorize",
          narrative: {
            es: "{name} llena siete botellitas, una por color, y las vierte despacio sobre el cristal.",
            ca: "{name} omple set ampolletes, una per color, i les aboca a poc a poc sobre el cristall.",
            en: "{name} fills seven little bottles, one for each color, and pours them slowly over the crystal.",
            fr: "{name} remplit sept petites bouteilles, une par couleur, et les verse doucement sur le cristal.",
          },
          next: "ending",
        },
      ],
    },
    c3_crystal_c: {
      id: "c3_crystal_c",
      chapter: 3,
      question: {
        es: "El cristal vibra con la canción de {name} pero todavía le falta un poquito de magia. ¿Qué añade {name} a su canción?",
        ca: "El cristall vibra amb la cançó de {name} però encara li falta una miqueta de màgia. Què afegeix {name} a la seva cançó?",
        en: "The crystal hums along with {name}'s song, but it still needs a tiny bit more magic. What does {name} add to the song?",
        fr: "Le cristal vibre avec la chanson de {name}, mais il lui manque encore un petit peu de magie. Qu'est-ce que {name} ajoute à sa chanson ?",
      },
      options: [
        {
          id: "clap",
          title: { es: "Marcar el ritmo", ca: "Marcar el ritme", en: "Keep the beat", fr: "Marquer le rythme" },
          desc: {
            es: "Unas palmadas alegres hacen latir más fuerte el cristal.",
            ca: "Unes palmades alegres fan bategar més fort el cristall.",
            en: "Happy claps make the crystal beat even stronger.",
            fr: "Des applaudissements joyeux font battre le cristal plus fort.",
          },
          imageSeed: "space-c3crystalc-clap",
          icon: "graphic_eq",
          narrative: {
            es: "{name} acompaña la canción con palmadas alegres y el cristal late con más fuerza.",
            ca: "{name} acompanya la cançó amb palmades alegres i el cristall batega amb més força.",
            en: "{name} joins the song with cheerful claps, and the crystal beats stronger and stronger.",
            fr: "{name} accompagne la chanson en frappant joyeusement dans ses mains et le cristal bat plus fort.",
          },
          next: "ending",
        },
        {
          id: "friends",
          title: { es: "Cantar con amigos", ca: "Cantar amb amics", en: "Sing with friends", fr: "Chanter avec des amis" },
          desc: {
            es: "Unas lunas pequeñas se unen al coro estelar.",
            ca: "Unes llunes petites s'uneixen al cor estel·lar.",
            en: "Some little moons join the starry choir.",
            fr: "De petites lunes rejoignent le chœur des étoiles.",
          },
          imageSeed: "space-c3crystalc-friends",
          icon: "group",
          narrative: {
            es: "{name} invita a unas lunas pequeñas a cantar y juntos llenan el cristal de música.",
            ca: "{name} convida unes llunes petites a cantar i junts omplen el cristall de música.",
            en: "{name} invites some little moons to sing, and together they fill the crystal with music.",
            fr: "{name} invite de petites lunes à chanter et, tous ensemble, ils remplissent le cristal de musique.",
          },
          next: "ending",
        },
        {
          id: "dance",
          title: { es: "Bailar entre estrellas", ca: "Ballar entre estrelles", en: "Dance among the stars", fr: "Danser parmi les étoiles" },
          desc: {
            es: "Un baile flotante hace girar la luz alrededor del cristal.",
            ca: "Un ball flotant fa girar la llum al voltant del cristall.",
            en: "A floating dance makes the light spin around the crystal.",
            fr: "Une danse flottante fait tourner la lumière autour du cristal.",
          },
          imageSeed: "space-c3crystalc-dance",
          icon: "celebration",
          narrative: {
            es: "{name} baila flotando entre las estrellas y la luz gira feliz alrededor del cristal.",
            ca: "{name} balla surant entre les estrelles i la llum gira feliç al voltant del cristall.",
            en: "{name} dances, floating among the stars, and the light spins happily around the crystal.",
            fr: "{name} danse en flottant parmi les étoiles et la lumière tourne joyeusement autour du cristal.",
          },
          next: "ending",
        },
      ],
    },
    c3_ship_a: {
      id: "c3_ship_a",
      chapter: 3,
      question: {
        es: "{name} llega al puente de mando y ve muchos botones de colores. ¿Cuál se atreve a pulsar para despertar la nave?",
        ca: "{name} arriba al pont de comandament i veu molts botons de colors. Quin s'atreveix a prémer per despertar la nau?",
        en: "{name} reaches the command bridge and sees lots of colorful buttons. Which one do they dare to press to wake the ship?",
        fr: "{name} arrive au poste de pilotage et voit plein de boutons de toutes les couleurs. Sur lequel est-ce que {name} ose appuyer pour réveiller le vaisseau ?",
      },
      options: [
        {
          id: "blue-button",
          title: { es: "El botón azul brillante", ca: "El botó blau brillant", en: "The shiny blue button", fr: "Le bouton bleu brillant" },
          desc: {
            es: "Late despacito, como si quisiera que lo tocaran.",
            ca: "Batega a poc a poc, com si volgués que el toquessin.",
            en: "It pulses slowly, as if it wanted to be touched.",
            fr: "Il palpite tout doucement, comme s'il voulait qu'on le touche.",
          },
          imageSeed: "space-c3shipa-blue",
          icon: "radio_button_checked",
          narrative: {
            es: "{name} pulsa el botón azul que late suave y la nave abre sus ojos de luz poco a poco.",
            ca: "{name} prem el botó blau que batega suau i la nau obre els seus ulls de llum a poc a poc.",
            en: "{name} presses the softly pulsing blue button, and the ship slowly opens its eyes of light.",
            fr: "{name} appuie sur le bouton bleu qui palpite doucement et le vaisseau ouvre peu à peu ses yeux de lumière.",
          },
          next: "ending",
        },
        {
          id: "big-lever",
          title: { es: "La gran palanca", ca: "La gran palanca", en: "The big lever", fr: "Le grand levier" },
          desc: {
            es: "Una palanca enorme promete encenderlo todo de golpe.",
            ca: "Una palanca enorme promet encendre-ho tot de cop.",
            en: "A huge lever promises to switch everything on at once.",
            fr: "Un énorme levier promet de tout allumer d'un coup.",
          },
          imageSeed: "space-c3shipa-lever",
          icon: "toggle_on",
          narrative: {
            es: "{name} tira con fuerza de la gran palanca y todas las luces de la nave se encienden a la vez.",
            ca: "{name} estira amb força la gran palanca i tots els llums de la nau s'encenen alhora.",
            en: "{name} pulls the big lever hard, and all the ship's lights come on at once.",
            fr: "{name} tire de toutes ses forces sur le grand levier et toutes les lumières du vaisseau s'allument en même temps.",
          },
          next: "ending",
        },
        {
          id: "map-screen",
          title: { es: "La pantalla con un mapa", ca: "La pantalla amb un mapa", en: "The screen with a map", fr: "L'écran avec une carte" },
          desc: {
            es: "Un mapa de estrellas espera que alguien lo despierte.",
            ca: "Un mapa d'estrelles espera que algú el desperti.",
            en: "A map of stars is waiting for someone to wake it.",
            fr: "Une carte des étoiles attend que quelqu'un la réveille.",
          },
          imageSeed: "space-c3shipa-map",
          icon: "map",
          narrative: {
            es: "{name} toca la pantalla del mapa y la nave despierta mostrando un camino de estrellas.",
            ca: "{name} toca la pantalla del mapa i la nau es desperta mostrant un camí d'estrelles.",
            en: "{name} touches the map screen, and the ship wakes up, showing a path of stars.",
            fr: "{name} touche l'écran de la carte et le vaisseau se réveille en montrant un chemin d'étoiles.",
          },
          next: "ending",
        },
      ],
    },
    c3_ship_b: {
      id: "c3_ship_b",
      chapter: 3,
      question: {
        es: "En la sala de motores el corazón de la nave está frío. ¿Cómo lo calienta {name} para que vuelva a latir?",
        ca: "A la sala de motors el cor de la nau està fred. Com l'escalfa {name} perquè torni a bategar?",
        en: "In the engine room, the heart of the ship is cold. How does {name} warm it up so it beats again?",
        fr: "Dans la salle des moteurs, le cœur du vaisseau est tout froid. Comment est-ce que {name} le réchauffe pour qu'il batte à nouveau ?",
      },
      options: [
        {
          id: "star-coal",
          title: { es: "Echar polvo de estrellas", ca: "Tirar pols d'estrelles", en: "Sprinkle stardust", fr: "Verser de la poussière d'étoiles" },
          desc: {
            es: "Un puñado de polvo estelar enciende el motor.",
            ca: "Un grapat de pols estel·lar encén el motor.",
            en: "A handful of stardust lights up the engine.",
            fr: "Une poignée de poussière d'étoiles allume le moteur.",
          },
          imageSeed: "space-c3shipb-stardust",
          icon: "grain",
          narrative: {
            es: "{name} echa un puñado de polvo de estrellas y el corazón del motor empieza a latir caliente.",
            ca: "{name} tira un grapat de pols d'estrelles i el cor del motor comença a bategar calent.",
            en: "{name} sprinkles in a handful of stardust, and the engine's heart starts beating warmly.",
            fr: "{name} verse une poignée de poussière d'étoiles et le cœur du moteur se met à battre tout chaud.",
          },
          next: "ending",
        },
        {
          id: "hug",
          title: { es: "Darle un abrazo", ca: "Fer-li una abraçada", en: "Give it a hug", fr: "Lui faire un câlin" },
          desc: {
            es: "A veces un abrazo es el mejor calorcito.",
            ca: "De vegades una abraçada és la millor escalforeta.",
            en: "Sometimes a hug is the best kind of warmth.",
            fr: "Parfois, un câlin est la plus douce des chaleurs.",
          },
          imageSeed: "space-c3shipb-hug",
          icon: "favorite",
          narrative: {
            es: "{name} abraza el motor frío con todo su cariño y poco a poco vuelve a calentarse.",
            ca: "{name} abraça el motor fred amb tot el seu afecte i de mica en mica torna a escalfar-se.",
            en: "{name} hugs the cold engine with all their love, and little by little it warms up again.",
            fr: "{name} serre le moteur froid dans ses bras avec tout son amour et, petit à petit, il se réchauffe.",
          },
          next: "ending",
        },
        {
          id: "sun-ray",
          title: { es: "Traer un rayo de sol", ca: "Portar un raig de sol", en: "Bring a ray of sunshine", fr: "Apporter un rayon de soleil" },
          desc: {
            es: "Un rayito de un sol cercano puede encender el motor.",
            ca: "Un raget d'un sol proper pot encendre el motor.",
            en: "A little ray from a nearby sun could light the engine.",
            fr: "Un petit rayon d'un soleil voisin peut allumer le moteur.",
          },
          imageSeed: "space-c3shipb-sunray",
          icon: "wb_sunny",
          narrative: {
            es: "{name} sale a buscar un rayito de un sol cercano y lo lleva hasta el motor para encenderlo.",
            ca: "{name} surt a buscar un raget d'un sol proper i el porta fins al motor per encendre'l.",
            en: "{name} flies out to fetch a little ray from a nearby sun and carries it to the engine to light it up.",
            fr: "{name} part chercher un petit rayon d'un soleil voisin et le porte jusqu'au moteur pour l'allumer.",
          },
          next: "ending",
        },
      ],
    },
    c3_ship_c: {
      id: "c3_ship_c",
      chapter: 3,
      question: {
        es: "El jardín interior está lleno de plantas brillantes y una parece dormida del todo. ¿Cómo ayuda {name} a que reviva y despierte la nave?",
        ca: "El jardí interior és ple de plantes brillants i una sembla adormida del tot. Com ajuda {name} a fer-la reviure i despertar la nau?",
        en: "The indoor garden is full of glowing plants, and one seems fast asleep. How does {name} help it come back to life and wake the ship?",
        fr: "Le jardin intérieur est plein de plantes brillantes et l'une d'elles semble profondément endormie. Comment est-ce que {name} l'aide à revivre et à réveiller le vaisseau ?",
      },
      options: [
        {
          id: "water",
          title: { es: "Regarla con agua de cometa", ca: "Regar-la amb aigua de cometa", en: "Water it with comet water", fr: "L'arroser avec de l'eau de comète" },
          desc: {
            es: "Unas gotas brillantes hacen abrir sus hojas.",
            ca: "Unes gotes brillants fan obrir les seves fulles.",
            en: "A few sparkling drops make its leaves open up.",
            fr: "Quelques gouttes brillantes font ouvrir ses feuilles.",
          },
          imageSeed: "space-c3shipc-water",
          icon: "water_drop",
          narrative: {
            es: "{name} riega la planta con gotas brillantes de agua de cometa y sus hojas se abren felices.",
            ca: "{name} rega la planta amb gotes brillants d'aigua de cometa i les seves fulles s'obren felices.",
            en: "{name} waters the plant with sparkling drops of comet water, and its leaves open up happily.",
            fr: "{name} arrose la plante avec des gouttes brillantes d'eau de comète et ses feuilles s'ouvrent toutes contentes.",
          },
          next: "ending",
        },
        {
          id: "sing-plant",
          title: { es: "Susurrarle palabras dulces", ca: "Xiuxiuejar-li paraules dolces", en: "Whisper sweet words to it", fr: "Lui murmurer des mots doux" },
          desc: {
            es: "Las plantas también escuchan cuando les hablamos con amor.",
            ca: "Les plantes també escolten quan els parlem amb amor.",
            en: "Plants listen too, when we speak to them with love.",
            fr: "Les plantes aussi écoutent quand on leur parle avec amour.",
          },
          imageSeed: "space-c3shipc-whisper",
          icon: "record_voice_over",
          narrative: {
            es: "{name} se acerca y le susurra palabras dulces hasta que la planta despierta brillando.",
            ca: "{name} s'acosta i li xiuxiueja paraules dolces fins que la planta es desperta brillant.",
            en: "{name} leans in close and whispers sweet words until the plant wakes up glowing.",
            fr: "{name} s'approche et lui murmure des mots doux jusqu'à ce que la plante se réveille en brillant.",
          },
          next: "ending",
        },
        {
          id: "light-plant",
          title: { es: "Darle un poco de luz", ca: "Donar-li una mica de llum", en: "Give it a little light", fr: "Lui donner un peu de lumière" },
          desc: {
            es: "Una linterna estelar la baña en luz tibia.",
            ca: "Una llanterna estel·lar la banya en llum tèbia.",
            en: "A star lantern bathes it in warm light.",
            fr: "Une lanterne étoilée la baigne d'une lumière tiède.",
          },
          imageSeed: "space-c3shipc-light",
          icon: "flashlight_on",
          narrative: {
            es: "{name} enciende una linterna estelar y baña la planta en luz tibia hasta que revive.",
            ca: "{name} encén una llanterna estel·lar i banya la planta en llum tèbia fins que reviu.",
            en: "{name} turns on a star lantern and bathes the plant in warm light until it comes back to life.",
            fr: "{name} allume une lanterne étoilée et baigne la plante d'une lumière tiède jusqu'à ce qu'elle revive.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "" },
      options: [],
    },
  },
};
