import type { StoryTree } from "./types";

// Branching story tree for the "superhero" template (Superhéroe por un Día).
// Depth 3 (c1 → c2 → c3) then converges to a shared ending.
// Real branching: each c2 question references the c1 choice; each c3 references its c2 choice.
// Text inline per-locale (es source of truth + ca/en/fr). {name} = child's name.
// Tone: heroic-kind — every mission is about helping people and animals, never fighting.

export const superheroTree: StoryTree = {
  templateId: "superhero",
  root: "c1",
  ending: "ending",
  nodes: {
    c1: {
      id: "c1",
      chapter: 1,
      question: {
        es: "{name} estrena capa nueva y vigila la ciudad desde el tejado más alto. Desde allí arriba, tres misterios llaman su atención. ¿Cuál investiga primero?",
        ca: "{name} estrena capa nova i vigila la ciutat des del terrat més alt. Des d'allà dalt, tres misteris criden la seva atenció. Quin investiga primer?",
        en: "{name} puts on a brand-new cape and watches over the city from the tallest rooftop. From up there, three mysteries catch their eye. Which one to investigate first?",
        fr: "{name} étrenne une cape toute neuve et veille sur la ville depuis le toit le plus haut. De là-haut, trois mystères attirent son attention. Lequel explorer en premier ?",
      },
      options: [
        {
          id: "gargoyle",
          title: {
            es: "La gárgola de piedra",
            ca: "La gàrgola de pedra",
            en: "The stone gargoyle",
            fr: "La gargouille de pierre",
          },
          desc: {
            es: "Una gárgola pequeñita con alas de piedra bosteza en lo alto de la torre del reloj.",
            ca: "Una gàrgola petitona amb ales de pedra badalla a dalt de la torre del rellotge.",
            en: "A tiny gargoyle with little stone wings yawns at the top of the clock tower.",
            fr: "Une toute petite gargouille aux ailes de pierre bâille en haut de la tour de l'horloge.",
          },
          imageSeed: "superhero-c1-gargoyle",
          icon: "castle",
          narrative: {
            es: "{name} se acerca con cuidado a una gárgola pequeñita de piedra gris que bosteza y se despereza en lo alto de la torre del reloj.",
            ca: "{name} s'acosta amb compte a una gàrgola petitona de pedra grisa que badalla i s'estira a dalt de la torre del rellotge.",
            en: "{name} carefully approaches a tiny grey stone gargoyle yawning and stretching at the top of the clock tower.",
            fr: "{name} s'approche prudemment d'une toute petite gargouille de pierre grise qui bâille et s'étire en haut de la tour de l'horloge.",
          },
          next: "c2_gargoyle",
        },
        {
          id: "badge",
          title: {
            es: "El comunicador dorado",
            ca: "El comunicador daurat",
            en: "The golden communicator",
            fr: "Le communicateur doré",
          },
          desc: {
            es: "Una insignia antigua en forma de estrella parpadea dentro de una cajita de terciopelo.",
            ca: "Una insígnia antiga en forma d'estrella parpelleja dins d'una capseta de vellut.",
            en: "An old star-shaped badge blinks inside a little velvet box.",
            fr: "Un vieil insigne en forme d'étoile clignote dans un petit écrin de velours.",
          },
          imageSeed: "superhero-c1-badge",
          icon: "radar",
          narrative: {
            es: "{name} abre una cajita de terciopelo y descubre un comunicador dorado en forma de estrella que parpadea con tres lucecitas.",
            ca: "{name} obre una capseta de vellut i descobreix un comunicador daurat en forma d'estrella que parpelleja amb tres llumetes.",
            en: "{name} opens a little velvet box and discovers a golden star-shaped communicator blinking with three tiny lights.",
            fr: "{name} ouvre un petit écrin de velours et découvre un communicateur doré en forme d'étoile qui clignote avec trois petites lumières.",
          },
          next: "c2_badge",
        },
        {
          id: "cloud-stairs",
          title: {
            es: "La escalera de las nubes",
            ca: "L'escala dels núvols",
            en: "The cloud staircase",
            fr: "L'escalier des nuages",
          },
          desc: {
            es: "Una escalera de caracol plateada sube desde el tejado y desaparece entre las nubes.",
            ca: "Una escala de cargol platejada puja des del terrat i desapareix entre els núvols.",
            en: "A silver spiral staircase climbs from the rooftop and disappears into the clouds.",
            fr: "Un escalier en colimaçon argenté monte depuis le toit et disparaît dans les nuages.",
          },
          imageSeed: "superhero-c1-skystairs",
          icon: "filter_drama",
          narrative: {
            es: "{name} descubre una escalera de caracol plateada que nace en el tejado y sube hasta perderse entre las nubes.",
            ca: "{name} descobreix una escala de cargol platejada que neix al terrat i puja fins a perdre's entre els núvols.",
            en: "{name} discovers a silver spiral staircase rising from the rooftop and climbing until it vanishes into the clouds.",
            fr: "{name} découvre un escalier en colimaçon argenté qui part du toit et monte jusqu'à se perdre dans les nuages.",
          },
          next: "c2_sky",
        },
      ],
    },
    c2_gargoyle: {
      id: "c2_gargoyle",
      chapter: 2,
      question: {
        es: "La gárgola se despierta del todo y dice que se llama Roca. Está preocupada: el gran reloj de la ciudad se ha parado y, sin sus campanadas, mañana nadie se despertará a tiempo. ¿Cómo ayudan {name} y Roca al reloj?",
        ca: "La gàrgola es desperta del tot i diu que es diu Roca. Està preocupada: el gran rellotge de la ciutat s'ha aturat i, sense les seves campanades, demà ningú no es despertarà a temps. Com ajuden {name} i la Roca el rellotge?",
        en: "The gargoyle wakes up fully and says her name is Roca. She is worried: the city's great clock has stopped, and without its chimes nobody will wake up on time tomorrow. How do {name} and Roca help the clock?",
        fr: "La gargouille se réveille tout à fait et dit qu'elle s'appelle Roca. Elle est inquiète : la grande horloge de la ville s'est arrêtée et, sans ses carillons, personne ne se réveillera à l'heure demain. Comment {name} et Roca vont-ils aider l'horloge ?",
      },
      options: [
        {
          id: "golden-gear",
          title: {
            es: "La rueda dorada",
            ca: "La roda daurada",
            en: "The golden gear",
            fr: "La roue dorée",
          },
          desc: {
            es: "La pieza más brillante del mecanismo rodó calle abajo hasta la fuente de la plaza.",
            ca: "La peça més brillant del mecanisme va rodar carrer avall fins a la font de la plaça.",
            en: "The shiniest piece of the clockwork rolled down the street to the fountain in the square.",
            fr: "La pièce la plus brillante du mécanisme a roulé dans la rue jusqu'à la fontaine de la place.",
          },
          imageSeed: "superhero-c2gargoyle-gear",
          icon: "settings",
          narrative: {
            es: "{name} y Roca siguen un caminito de arañazos brillantes que baja desde la torre hasta la fuente de la plaza.",
            ca: "{name} i la Roca segueixen un caminet de rascades brillants que baixa des de la torre fins a la font de la plaça.",
            en: "{name} and Roca follow a trail of shiny little scratches leading down from the tower to the fountain in the square.",
            fr: "{name} et Roca suivent un petit chemin de traces brillantes qui descend de la tour jusqu'à la fontaine de la place.",
          },
          next: "c3_gargoyle_a",
        },
        {
          id: "clockmaker",
          title: {
            es: "El relojero jubilado",
            ca: "El rellotger jubilat",
            en: "The retired clockmaker",
            fr: "L'horloger à la retraite",
          },
          desc: {
            es: "En una casita azul vive el relojero que cuidó el gran reloj durante cincuenta años.",
            ca: "En una caseta blava hi viu el rellotger que va cuidar el gran rellotge durant cinquanta anys.",
            en: "In a little blue house lives the clockmaker who cared for the great clock for fifty years.",
            fr: "Dans une petite maison bleue vit l'horloger qui a pris soin de la grande horloge pendant cinquante ans.",
          },
          imageSeed: "superhero-c2gargoyle-clockmaker",
          icon: "handyman",
          narrative: {
            es: "{name} y Roca llaman a la puerta de una casita azul donde vive el relojero que conoce cada pieza del gran reloj.",
            ca: "{name} i la Roca truquen a la porta d'una caseta blava on viu el rellotger que coneix cada peça del gran rellotge.",
            en: "{name} and Roca knock on the door of a little blue house where the clockmaker who knows every piece of the great clock lives.",
            fr: "{name} et Roca frappent à la porte d'une petite maison bleue où vit l'horloger qui connaît chaque pièce de la grande horloge.",
          },
          next: "c3_gargoyle_b",
        },
        {
          id: "wind-up-key",
          title: {
            es: "La llave de cuerda gigante",
            ca: "La clau de corda gegant",
            en: "The giant wind-up key",
            fr: "La clé à remonter géante",
          },
          desc: {
            es: "En lo más alto de la torre espera una llave enorme que da cuerda al gran reloj.",
            ca: "A dalt de tot de la torre espera una clau enorme que dona corda al gran rellotge.",
            en: "At the very top of the tower waits an enormous key that winds up the great clock.",
            fr: "Tout en haut de la tour attend une clé énorme qui remonte la grande horloge.",
          },
          imageSeed: "superhero-c2gargoyle-windkey",
          icon: "key",
          narrative: {
            es: "{name} y Roca suben hasta lo más alto de la torre, donde una llave enorme espera para dar cuerda al gran reloj.",
            ca: "{name} i la Roca pugen fins a dalt de tot de la torre, on una clau enorme espera per donar corda al gran rellotge.",
            en: "{name} and Roca climb to the very top of the tower, where an enormous key waits to wind up the great clock.",
            fr: "{name} et Roca montent tout en haut de la tour, où une clé énorme attend pour remonter la grande horloge.",
          },
          next: "c3_gargoyle_c",
        },
      ],
    },
    c2_badge: {
      id: "c2_badge",
      chapter: 2,
      question: {
        es: "El comunicador perteneció a la primera heroína de la ciudad ¡y todavía funciona! En su pantallita brillan tres avisos de vecinos que necesitan una mano. ¿A quién ayuda {name} primero?",
        ca: "El comunicador va pertànyer a la primera heroïna de la ciutat i encara funciona! A la seva pantalleta hi brillen tres avisos de veïns que necessiten un cop de mà. A qui ajuda {name} primer?",
        en: "The communicator belonged to the city's very first hero — and it still works! Three alerts glow on its little screen, from neighbours who need a hand. Who does {name} help first?",
        fr: "Le communicateur appartenait à la toute première héroïne de la ville... et il fonctionne encore ! Sur son petit écran brillent trois appels de voisins qui ont besoin d'un coup de main. Qui {name} va aider en premier ?",
      },
      options: [
        {
          id: "bakery-order",
          title: {
            es: "La panadería en apuros",
            ca: "El forn de pa en un embolic",
            en: "The bakery in a pickle",
            fr: "La boulangerie en détresse",
          },
          desc: {
            es: "En la pantallita parpadea un cruasán: cien pastelitos esperan y la bicicleta de reparto está pinchada.",
            ca: "A la pantalleta hi parpelleja un croissant: cent pastissets esperen i la bicicleta de repartiment està punxada.",
            en: "A croissant blinks on the little screen: a hundred pastries are waiting and the delivery bike has a flat tyre.",
            fr: "Un croissant clignote sur le petit écran : cent petits gâteaux attendent et le vélo de livraison est crevé.",
          },
          imageSeed: "superhero-c2badge-bakery",
          icon: "bakery_dining",
          narrative: {
            es: "{name} llega a la panadería, donde la panadera Lola rodea cien cajitas de pastelitos junto a una bicicleta con la rueda pinchada.",
            ca: "{name} arriba al forn de pa, on la fornera Lola està envoltada de cent capsetes de pastissets al costat d'una bicicleta amb la roda punxada.",
            en: "{name} arrives at the bakery, where Lola the baker stands among a hundred little boxes of pastries next to a bike with a flat tyre.",
            fr: "{name} arrive à la boulangerie, où Lola la boulangère est entourée de cent petites boîtes de gâteaux à côté d'un vélo à la roue crevée.",
          },
          next: "c3_badge_a",
        },
        {
          id: "scared-kitten",
          title: {
            es: "El gatito del andamio",
            ca: "El gatet de la bastida",
            en: "The kitten on the scaffolding",
            fr: "Le chaton de l'échafaudage",
          },
          desc: {
            es: "En la pantallita maúlla un aviso: un gatito está atrapado en lo alto de un andamio.",
            ca: "A la pantalleta hi miola un avís: un gatet està atrapat a dalt d'una bastida.",
            en: "An alert mews on the little screen: a kitten is stuck high up on some scaffolding.",
            fr: "Sur le petit écran, un message miaule : un chaton est coincé tout en haut d'un échafaudage.",
          },
          imageSeed: "superhero-c2badge-kitten",
          icon: "pets",
          narrative: {
            es: "{name} corre hasta la obra de la esquina, donde un gatito gris tiembla en la tabla más alta del andamio.",
            ca: "{name} corre fins a l'obra de la cantonada, on un gatet gris tremola a la fusta més alta de la bastida.",
            en: "{name} runs to the building site on the corner, where a little grey kitten trembles on the highest plank of the scaffolding.",
            fr: "{name} court jusqu'au chantier du coin de la rue, où un petit chaton gris tremble sur la planche la plus haute de l'échafaudage.",
          },
          next: "c3_badge_b",
        },
        {
          id: "lost-glasses",
          title: {
            es: "Las gafas del abuelo Justo",
            ca: "Les ulleres de l'avi Just",
            en: "Grandpa Justo's glasses",
            fr: "Les lunettes de papi Justo",
          },
          desc: {
            es: "El abuelo que cuenta cuentos en el parque ha perdido sus gafas esta mañana.",
            ca: "L'avi que explica contes al parc ha perdut les ulleres aquest matí.",
            en: "The grandpa who tells stories in the park has lost his glasses this morning.",
            fr: "Le papi qui raconte des histoires dans le parc a perdu ses lunettes ce matin.",
          },
          imageSeed: "superhero-c2badge-glasses",
          icon: "eyeglasses",
          narrative: {
            es: "{name} encuentra al abuelo Justo en su banco del parque, buscando a tientas las gafas que perdió esta mañana.",
            ca: "{name} troba l'avi Just al seu banc del parc, buscant a les palpentes les ulleres que ha perdut aquest matí.",
            en: "{name} finds Grandpa Justo on his park bench, feeling around for the glasses he lost this morning.",
            fr: "{name} trouve papi Justo sur son banc du parc, cherchant à tâtons les lunettes qu'il a perdues ce matin.",
          },
          next: "c3_badge_c",
        },
      ],
    },
    c2_sky: {
      id: "c2_sky",
      chapter: 2,
      question: {
        es: "Arriba del todo, {name} descubre la Estación de las Nubes, donde la guardiana Nimba prepara el cielo de cada día. ¡Pero hoy todo está patas arriba y podría formarse una supertormenta! ¿Qué arreglan primero?",
        ca: "A dalt de tot, {name} descobreix l'Estació dels Núvols, on la guardiana Nimba prepara el cel de cada dia. Però avui tot està potes enlaire i es podria formar una supertempesta! Què arreglen primer?",
        en: "At the very top, {name} discovers the Cloud Station, where Nimba the keeper prepares the sky for each new day. But today everything is upside down and a superstorm could form! What do they fix first?",
        fr: "Tout en haut, {name} découvre la Station des Nuages, où Nimba la gardienne prépare le ciel de chaque jour. Mais aujourd'hui tout est sens dessus dessous et une supertempête pourrait se former ! Que vont-ils réparer en premier ?",
      },
      options: [
        {
          id: "tangled-clouds",
          title: {
            es: "Las nubes enredadas",
            ca: "Els núvols embolicats",
            en: "The tangled clouds",
            fr: "Les nuages emmêlés",
          },
          desc: {
            es: "Las nubes se han enredado entre ellas como un ovillo gigante de algodón.",
            ca: "Els núvols s'han embolicat entre ells com un cabdell gegant de cotó.",
            en: "The clouds have tangled together like a giant ball of cotton wool.",
            fr: "Les nuages se sont emmêlés comme une pelote géante de coton.",
          },
          imageSeed: "superhero-c2sky-clouds",
          icon: "cloud",
          narrative: {
            es: "{name} y Nimba se acercan a un montón de nubes enredadas entre sí como un ovillo gigante de algodón.",
            ca: "{name} i la Nimba s'acosten a un munt de núvols embolicats entre ells com un cabdell gegant de cotó.",
            en: "{name} and Nimba walk up to a heap of clouds tangled together like a giant ball of cotton wool.",
            fr: "{name} et Nimba s'approchent d'un tas de nuages emmêlés comme une pelote géante de coton.",
          },
          next: "c3_sky_a",
        },
        {
          id: "stuck-rainbow",
          title: {
            es: "El arcoíris atascado",
            ca: "L'arc de Sant Martí encallat",
            en: "The stuck rainbow",
            fr: "L'arc-en-ciel coincé",
          },
          desc: {
            es: "El arcoíris se ha quedado enrollado en su cajón y no quiere salir.",
            ca: "L'arc de Sant Martí s'ha quedat enrotllat al seu calaix i no vol sortir.",
            en: "The rainbow has stayed rolled up in its drawer and won't come out.",
            fr: "L'arc-en-ciel est resté enroulé dans son tiroir et ne veut pas sortir.",
          },
          imageSeed: "superhero-c2sky-rainbow",
          icon: "looks",
          narrative: {
            es: "{name} y Nimba abren un cajón enorme donde el arcoíris duerme enrollado como una alfombra de colores.",
            ca: "{name} i la Nimba obren un calaix enorme on l'arc de Sant Martí dorm enrotllat com una catifa de colors.",
            en: "{name} and Nimba open an enormous drawer where the rainbow sleeps rolled up like a carpet of colours.",
            fr: "{name} et Nimba ouvrent un tiroir énorme où l'arc-en-ciel dort enroulé comme un tapis de couleurs.",
          },
          next: "c3_sky_b",
        },
        {
          id: "sleepy-wind",
          title: {
            es: "El viento dormilón",
            ca: "El vent dormilega",
            en: "The sleepy wind",
            fr: "Le vent endormi",
          },
          desc: {
            es: "El viento se ha quedado dormido y abajo las cometas y los molinos están parados.",
            ca: "El vent s'ha quedat adormit i a baix els estels i els molins estan aturats.",
            en: "The wind has fallen asleep, and down below the kites and windmills have all stopped.",
            fr: "Le vent s'est endormi et, en bas, les cerfs-volants et les moulins sont à l'arrêt.",
          },
          imageSeed: "superhero-c2sky-wind",
          icon: "air",
          narrative: {
            es: "{name} y Nimba encuentran al viento profundamente dormido, abrazado a una nube blandita que sube y baja con sus ronquidos.",
            ca: "{name} i la Nimba troben el vent profundament adormit, abraçat a un núvol tou que puja i baixa amb els seus roncs.",
            en: "{name} and Nimba find the wind fast asleep, hugging a squishy cloud that rises and falls with his snores.",
            fr: "{name} et Nimba trouvent le vent profondément endormi, serrant un nuage tout doux qui monte et descend au rythme de ses ronflements.",
          },
          next: "c3_sky_c",
        },
      ],
    },
    c3_gargoyle_a: {
      id: "c3_gargoyle_a",
      chapter: 3,
      question: {
        es: "¡Allí está! La rueda dorada brilla en el fondo de la fuente de la plaza. ¿Cómo la recupera {name} con cuidado?",
        ca: "Allà és! La roda daurada brilla al fons de la font de la plaça. Com la recupera {name} amb compte?",
        en: "There it is! The golden gear shines at the bottom of the fountain in the square. How does {name} get it back carefully?",
        fr: "La voilà ! La roue dorée brille au fond de la fontaine de la place. Comment {name} va la récupérer avec précaution ?",
      },
      options: [
        {
          id: "fountain-ducks",
          title: {
            es: "Los patos buceadores",
            ca: "Els ànecs bussejadors",
            en: "The diving ducks",
            fr: "Les canards plongeurs",
          },
          desc: {
            es: "Los patos de la fuente son los mejores buceadores de toda la plaza.",
            ca: "Els ànecs de la font són els millors bussejadors de tota la plaça.",
            en: "The fountain ducks are the best divers in the whole square.",
            fr: "Les canards de la fontaine sont les meilleurs plongeurs de toute la place.",
          },
          imageSeed: "superhero-c3gargoylea-ducks",
          icon: "waves",
          narrative: {
            es: "{name} pide ayuda con amabilidad a los patos de la fuente, que bucean en fila y empujan la rueda dorada hasta la orilla.",
            ca: "{name} demana ajuda amb amabilitat als ànecs de la font, que bussegen en fila i empenyen la roda daurada fins a la vora.",
            en: "{name} kindly asks the fountain ducks for help, and they dive in a line and push the golden gear to the edge.",
            fr: "{name} demande gentiment de l'aide aux canards de la fontaine, qui plongent à la file et poussent la roue dorée jusqu'au bord.",
          },
          next: "ending",
        },
        {
          id: "toy-crane",
          title: {
            es: "La grúa de juguete",
            ca: "La grua de joguina",
            en: "The toy crane",
            fr: "La grue en jouet",
          },
          desc: {
            es: "En la plaza hay una grúa de juguete con un gancho pequeñito, perfecta para pescar tesoros.",
            ca: "A la plaça hi ha una grua de joguina amb un ganxo petitó, perfecta per pescar tresors.",
            en: "In the square there is a toy crane with a tiny hook, perfect for fishing out treasures.",
            fr: "Sur la place, il y a une grue en jouet avec un tout petit crochet, parfaite pour repêcher des trésors.",
          },
          imageSeed: "superhero-c3gargoylea-crane",
          icon: "precision_manufacturing",
          narrative: {
            es: "{name} pide prestada la grúa de juguete a los niños de la plaza y, entre todos, pescan la rueda dorada con el ganchito.",
            ca: "{name} demana en préstec la grua de joguina als nens de la plaça i, entre tots, pesquen la roda daurada amb el ganxet.",
            en: "{name} borrows the toy crane from the kids in the square and, all together, they fish out the golden gear with the little hook.",
            fr: "{name} emprunte la grue en jouet aux enfants de la place et, tous ensemble, ils repêchent la roue dorée avec le petit crochet.",
          },
          next: "ending",
        },
        {
          id: "hero-dive",
          title: {
            es: "Misión de buceo",
            ca: "Missió de busseig",
            en: "A diving mission",
            fr: "Mission plongée",
          },
          desc: {
            es: "El agua de la fuente es bajita y clara: perfecta para bucear un momentito.",
            ca: "L'aigua de la font és baixeta i clara: perfecta per bussejar un momentet.",
            en: "The fountain water is shallow and clear: perfect for a quick little dive.",
            fr: "L'eau de la fontaine est peu profonde et claire : parfaite pour un petit plongeon.",
          },
          imageSeed: "superhero-c3gargoylea-dive",
          icon: "pool",
          narrative: {
            es: "{name} se descalza, respira hondo y bucea hasta el fondo de la fuente para recoger la rueda dorada con las dos manos.",
            ca: "{name} es descalça, respira fondo i busseja fins al fons de la font per recollir la roda daurada amb les dues mans.",
            en: "{name} takes off their shoes, takes a deep breath and dives to the bottom of the fountain to scoop up the golden gear with both hands.",
            fr: "{name} se déchausse, respire un grand coup et plonge jusqu'au fond de la fontaine pour ramasser la roue dorée à deux mains.",
          },
          next: "ending",
        },
      ],
    },
    c3_gargoyle_b: {
      id: "c3_gargoyle_b",
      chapter: 3,
      question: {
        es: "El relojero sonríe y saca su caja de herramientas, pero sus rodillas ya no pueden subir los doscientos escalones de la torre. ¿Qué se le ocurre a {name}?",
        ca: "El rellotger somriu i treu la seva caixa d'eines, però els seus genolls ja no poden pujar els dos-cents esglaons de la torre. Què se li acut a {name}?",
        en: "The clockmaker smiles and gets out his toolbox, but his knees can no longer climb the two hundred steps of the tower. What does {name} come up with?",
        fr: "L'horloger sourit et sort sa boîte à outils, mais ses genoux ne peuvent plus monter les deux cents marches de la tour. Quelle idée vient à {name} ?",
      },
      options: [
        {
          id: "megaphone",
          title: {
            es: "El megáfono del parque",
            ca: "El megàfon del parc",
            en: "The park megaphone",
            fr: "Le mégaphone du parc",
          },
          desc: {
            es: "Con un megáfono, las instrucciones llegan clarísimas hasta lo más alto de la torre.",
            ca: "Amb un megàfon, les instruccions arriben claríssimes fins a dalt de tot de la torre.",
            en: "With a megaphone, instructions reach the very top of the tower loud and clear.",
            fr: "Avec un mégaphone, les instructions arrivent très clairement jusqu'en haut de la tour.",
          },
          imageSeed: "superhero-c3gargoyleb-megaphone",
          icon: "campaign",
          narrative: {
            es: "{name} sube las herramientas a la torre y arregla el reloj paso a paso, siguiendo las instrucciones que el relojero grita por el megáfono desde la plaza.",
            ca: "{name} puja les eines a la torre i arregla el rellotge pas a pas, seguint les instruccions que el rellotger crida pel megàfon des de la plaça.",
            en: "{name} carries the tools up the tower and fixes the clock step by step, following the instructions the clockmaker calls out through the megaphone from the square.",
            fr: "{name} monte les outils dans la tour et répare l'horloge pas à pas, en suivant les instructions que l'horloger crie au mégaphone depuis la place.",
          },
          next: "ending",
        },
        {
          id: "rope-pulley",
          title: {
            es: "Una polea de cuerda",
            ca: "Una politja de corda",
            en: "A rope pulley",
            fr: "Une poulie à corde",
          },
          desc: {
            es: "Con una cuerda y una cesta se puede subir y bajar de todo: herramientas, notas y hasta meriendas.",
            ca: "Amb una corda i un cistell es pot pujar i baixar de tot: eines, notes i fins i tot berenars.",
            en: "With a rope and a basket you can send anything up and down: tools, notes and even snacks.",
            fr: "Avec une corde et un panier, on peut faire monter et descendre de tout : des outils, des notes et même des goûters.",
          },
          imageSeed: "superhero-c3gargoyleb-pulley",
          icon: "construction",
          narrative: {
            es: "{name} monta una polea con una cuerda y una cesta, y el relojero va enviando arriba sus herramientas y una notita con cada paso a seguir.",
            ca: "{name} munta una politja amb una corda i un cistell, i el rellotger va enviant amunt les seves eines i una noteta amb cada pas a seguir.",
            en: "{name} rigs up a pulley with a rope and a basket, and the clockmaker sends up his tools and a little note with each step to follow.",
            fr: "{name} installe une poulie avec une corde et un panier, et l'horloger fait monter ses outils et un petit mot avec chaque étape à suivre.",
          },
          next: "ending",
        },
        {
          id: "clock-drawing",
          title: {
            es: "El dibujo del mecanismo",
            ca: "El dibuix del mecanisme",
            en: "The clockwork drawing",
            fr: "Le dessin du mécanisme",
          },
          desc: {
            es: "Un buen mapa de ruedas y muelles vale tanto como mil palabras.",
            ca: "Un bon mapa de rodes i molles val tant com mil paraules.",
            en: "A good map of gears and springs is worth a thousand words.",
            fr: "Une bonne carte des roues et des ressorts vaut mille mots.",
          },
          imageSeed: "superhero-c3gargoyleb-drawing",
          icon: "draw",
          narrative: {
            es: "El relojero dibuja un mapa del mecanismo con todos sus secretos y {name} sube a la torre y coloca cada pieza siguiendo el dibujo con muchísima atención.",
            ca: "El rellotger dibuixa un mapa del mecanisme amb tots els seus secrets i {name} puja a la torre i col·loca cada peça seguint el dibuix amb moltíssima atenció.",
            en: "The clockmaker draws a map of the clockwork with all its secrets, and {name} climbs the tower and sets each piece in place following the drawing very, very carefully.",
            fr: "L'horloger dessine une carte du mécanisme avec tous ses secrets, et {name} monte dans la tour et place chaque pièce en suivant le dessin avec beaucoup d'attention.",
          },
          next: "ending",
        },
      ],
    },
    c3_gargoyle_c: {
      id: "c3_gargoyle_c",
      chapter: 3,
      question: {
        es: "¡El gran reloj solo necesita cuerda! Pero la llave gigante está durísima y no gira ni un poquito. ¿Cómo lo consigue {name}?",
        ca: "El gran rellotge només necessita corda! Però la clau gegant està duríssima i no gira ni una miqueta. Com ho aconsegueix {name}?",
        en: "The great clock just needs winding! But the giant key is ever so stiff and won't turn even a tiny bit. How does {name} manage it?",
        fr: "La grande horloge a juste besoin d'être remontée ! Mais la clé géante est très dure et ne tourne pas d'un poil. Comment {name} va y arriver ?",
      },
      options: [
        {
          id: "oil-drop",
          title: {
            es: "Una gotita de aceite",
            ca: "Una goteta d'oli",
            en: "A little drop of oil",
            fr: "Une petite goutte d'huile",
          },
          desc: {
            es: "Con una gota de aceite, hasta la llave más dura gira contenta.",
            ca: "Amb una gota d'oli, fins i tot la clau més dura gira contenta.",
            en: "With a drop of oil, even the stiffest key turns happily.",
            fr: "Avec une goutte d'huile, même la clé la plus dure tourne joyeusement.",
          },
          imageSeed: "superhero-c3gargoylec-oil",
          icon: "water_drop",
          narrative: {
            es: "{name} deja caer una gotita de aceite en la cerradura gigante y la llave empieza a girar suave como un tiovivo.",
            ca: "{name} deixa caure una goteta d'oli al pany gegant i la clau comença a girar suau com uns cavallets.",
            en: "{name} lets a little drop of oil fall into the giant lock and the key starts turning as smoothly as a merry-go-round.",
            fr: "{name} laisse tomber une petite goutte d'huile dans la serrure géante et la clé se met à tourner aussi doucement qu'un manège.",
          },
          next: "ending",
        },
        {
          id: "team-push",
          title: {
            es: "Fuerza de equipo",
            ca: "Força d'equip",
            en: "Team power",
            fr: "La force de l'équipe",
          },
          desc: {
            es: "Roca, las palomas de la torre y muchas alas amigas empujando todas a la vez.",
            ca: "La Roca, els coloms de la torre i moltes ales amigues empenyent totes alhora.",
            en: "Roca, the tower pigeons and lots of friendly wings all pushing at once.",
            fr: "Roca, les pigeons de la tour et plein d'ailes amies qui poussent toutes en même temps.",
          },
          imageSeed: "superhero-c3gargoylec-team",
          icon: "groups",
          narrative: {
            es: "{name} cuenta hasta tres y empuja la llave gigante junto a Roca y las palomas de la torre, y entre todos la hacen girar.",
            ca: "{name} compta fins a tres i empeny la clau gegant amb la Roca i els coloms de la torre, i entre tots la fan girar.",
            en: "{name} counts to three and pushes the giant key together with Roca and the tower pigeons, and together they make it turn.",
            fr: "{name} compte jusqu'à trois et pousse la clé géante avec Roca et les pigeons de la tour, et tous ensemble ils la font tourner.",
          },
          next: "ending",
        },
        {
          id: "hero-warmup",
          title: {
            es: "Estirar, respirar y girar",
            ca: "Estirar, respirar i girar",
            en: "Stretch, breathe and turn",
            fr: "S'étirer, respirer et tourner",
          },
          desc: {
            es: "Primero se estiran los brazos, después una respiración profunda y... ¡ahora!",
            ca: "Primer s'estiren els braços, després una respiració profunda i... ara!",
            en: "First stretch your arms, then one deep breath and... now!",
            fr: "D'abord on étire les bras, puis une grande respiration et... maintenant !",
          },
          imageSeed: "superhero-c3gargoylec-warmup",
          icon: "fitness_center",
          narrative: {
            es: "{name} estira bien los brazos, respira hondo tres veces y gira la llave gigante con toda su fuerza tranquila.",
            ca: "{name} estira bé els braços, respira fondo tres vegades i gira la clau gegant amb tota la seva força tranquil·la.",
            en: "{name} stretches both arms, takes three deep breaths and turns the giant key with all their calm strength.",
            fr: "{name} étire bien les bras, respire profondément trois fois et tourne la clé géante avec toute sa force tranquille.",
          },
          next: "ending",
        },
      ],
    },
    c3_badge_a: {
      id: "c3_badge_a",
      chapter: 3,
      question: {
        es: "La fiesta del barrio empieza enseguida y los cien pastelitos tienen que llegar a la otra punta de la ciudad. ¿Cómo entrega {name} el pedido a tiempo?",
        ca: "La festa del barri comença de seguida i els cent pastissets han d'arribar a l'altra punta de la ciutat. Com lliura {name} la comanda a temps?",
        en: "The neighbourhood party starts very soon and the hundred pastries must reach the other side of the city. How does {name} deliver the order on time?",
        fr: "La fête du quartier commence très bientôt et les cent petits gâteaux doivent arriver à l'autre bout de la ville. Comment {name} va livrer la commande à temps ?",
      },
      options: [
        {
          id: "scooter-train",
          title: {
            es: "El tren de patinetes",
            ca: "El tren de patinets",
            en: "The scooter train",
            fr: "Le train de trottinettes",
          },
          desc: {
            es: "Los patinetes del barrio, en fila india, pueden repartir cajas a toda velocidad.",
            ca: "Els patinets del barri, en fila índia, poden repartir capses a tota velocitat.",
            en: "The neighbourhood scooters, in single file, can deliver boxes at top speed.",
            fr: "Les trottinettes du quartier, à la queue leu leu, peuvent livrer des boîtes à toute vitesse.",
          },
          imageSeed: "superhero-c3badgea-scooters",
          icon: "skateboarding",
          narrative: {
            es: "{name} reúne a los amigos del barrio con sus patinetes y forman un tren de reparto que cruza la ciudad timbre a timbre.",
            ca: "{name} reuneix els amics del barri amb els seus patinets i formen un tren de repartiment que travessa la ciutat timbre a timbre.",
            en: "{name} gathers the neighbourhood friends with their scooters and they form a delivery train that crosses the city, doorbell by doorbell.",
            fr: "{name} réunit les amis du quartier avec leurs trottinettes et ils forment un train de livraison qui traverse la ville, sonnette après sonnette.",
          },
          next: "ending",
        },
        {
          id: "fix-bike",
          title: {
            es: "Arreglar la bicicleta",
            ca: "Arreglar la bicicleta",
            en: "Fix the bike",
            fr: "Réparer le vélo",
          },
          desc: {
            es: "Con parches y un hinchador, la rueda pinchada queda como nueva.",
            ca: "Amb pedaços i una bomba d'aire, la roda punxada queda com nova.",
            en: "With patches and a pump, the flat tyre is as good as new.",
            fr: "Avec des rustines et une pompe, la roue crevée redevient comme neuve.",
          },
          imageSeed: "superhero-c3badgea-bike",
          icon: "pedal_bike",
          narrative: {
            es: "{name} busca los parches y el hinchador, arregla la rueda pinchada y la panadera Lola sale pedaleando feliz con sus pastelitos.",
            ca: "{name} busca els pedaços i la bomba d'aire, arregla la roda punxada i la fornera Lola surt pedalant feliç amb els seus pastissets.",
            en: "{name} finds the patches and the pump, fixes the flat tyre, and Lola the baker pedals off happily with her pastries.",
            fr: "{name} trouve les rustines et la pompe, répare la roue crevée, et Lola la boulangère repart à vélo toute contente avec ses gâteaux.",
          },
          next: "ending",
        },
        {
          id: "market-cart",
          title: {
            es: "El carrito del mercado",
            ca: "El carretó del mercat",
            en: "The market cart",
            fr: "Le chariot du marché",
          },
          desc: {
            es: "El frutero presta su carrito grande, perfecto para cien cajitas de pastelitos.",
            ca: "El fruiter deixa el seu carretó gran, perfecte per a cent capsetes de pastissets.",
            en: "The fruit seller lends his big cart, perfect for a hundred little pastry boxes.",
            fr: "Le marchand de fruits prête son grand chariot, parfait pour cent petites boîtes de gâteaux.",
          },
          imageSeed: "superhero-c3badgea-cart",
          icon: "shopping_cart",
          narrative: {
            es: "{name} pide prestado el carrito del frutero, lo carga con las cien cajitas y lo empuja con cuidado hasta la fiesta del barrio.",
            ca: "{name} demana en préstec el carretó del fruiter, el carrega amb les cent capsetes i l'empeny amb compte fins a la festa del barri.",
            en: "{name} borrows the fruit seller's cart, loads it with the hundred little boxes and pushes it carefully all the way to the neighbourhood party.",
            fr: "{name} emprunte le chariot du marchand de fruits, le charge avec les cent petites boîtes et le pousse prudemment jusqu'à la fête du quartier.",
          },
          next: "ending",
        },
      ],
    },
    c3_badge_b: {
      id: "c3_badge_b",
      chapter: 3,
      question: {
        es: "El gatito tiembla en la tabla más alta del andamio y los ruidos fuertes lo asustan todavía más. ¿Cómo lo rescata {name} sin asustarlo?",
        ca: "El gatet tremola a la fusta més alta de la bastida i els sorolls forts l'espanten encara més. Com el rescata {name} sense espantar-lo?",
        en: "The kitten trembles on the highest plank of the scaffolding, and loud noises scare it even more. How does {name} rescue it without frightening it?",
        fr: "Le chaton tremble sur la planche la plus haute de l'échafaudage, et les bruits forts l'effraient encore plus. Comment {name} va le sauver sans lui faire peur ?",
      },
      options: [
        {
          id: "soft-climb",
          title: {
            es: "Subir despacito",
            ca: "Pujar a poc a poc",
            en: "Climb up slowly",
            fr: "Monter tout doucement",
          },
          desc: {
            es: "Peldaño a peldaño, sin prisa y hablando muy bajito.",
            ca: "Esglaó a esglaó, sense pressa i parlant molt fluixet.",
            en: "Rung by rung, taking it slow and talking very softly.",
            fr: "Barreau après barreau, sans se presser et en parlant tout bas.",
          },
          imageSeed: "superhero-c3badgeb-climb",
          icon: "hiking",
          narrative: {
            es: "{name} sube por el andamio peldaño a peldaño, hablando bajito, y el gatito se deja abrazar ronroneando.",
            ca: "{name} puja per la bastida esglaó a esglaó, parlant fluixet, i el gatet es deixa abraçar roncant de gust.",
            en: "{name} climbs the scaffolding rung by rung, talking softly, and the kitten lets itself be scooped up, purring.",
            fr: "{name} grimpe sur l'échafaudage barreau après barreau, en parlant tout bas, et le chaton se laisse prendre dans les bras en ronronnant.",
          },
          next: "ending",
        },
        {
          id: "fish-snack",
          title: {
            es: "Una merienda de sardinas",
            ca: "Un berenar de sardines",
            en: "A sardine snack",
            fr: "Un goûter de sardines",
          },
          desc: {
            es: "Un platito de sardinas convence hasta al gatito más asustado.",
            ca: "Un platet de sardines convenç fins i tot el gatet més espantat.",
            en: "A little plate of sardines wins over even the most frightened kitten.",
            fr: "Une petite assiette de sardines convainc même le chaton le plus effrayé.",
          },
          imageSeed: "superhero-c3badgeb-snack",
          icon: "set_meal",
          narrative: {
            es: "{name} coloca un platito de sardinas en la tabla de abajo y el gatito baja pasito a pasito, olisqueando el aire.",
            ca: "{name} col·loca un platet de sardines a la fusta de sota i el gatet baixa passet a passet, ensumant l'aire.",
            en: "{name} sets a little plate of sardines on the plank below and the kitten comes down step by tiny step, sniffing the air.",
            fr: "{name} pose une petite assiette de sardines sur la planche du dessous et le chaton descend pas à pas, en reniflant l'air.",
          },
          next: "ending",
        },
        {
          id: "purr-lullaby",
          title: {
            es: "La nana ronroneada",
            ca: "La cançó de bressol roncadora",
            en: "The purring lullaby",
            fr: "La berceuse ronronnée",
          },
          desc: {
            es: "Una canción suave como un ronroneo calma a cualquier gatito.",
            ca: "Una cançó suau com un ronc de gat calma qualsevol gatet.",
            en: "A song as soft as a purr calms any kitten.",
            fr: "Une chanson douce comme un ronron calme n'importe quel chaton.",
          },
          imageSeed: "superhero-c3badgeb-lullaby",
          icon: "music_note",
          narrative: {
            es: "{name} canta una nana suave como un ronroneo y el gatito, ya tranquilo, salta directo a sus brazos.",
            ca: "{name} canta una cançó de bressol suau com un ronc de gat i el gatet, ja tranquil, salta directe als seus braços.",
            en: "{name} sings a lullaby as soft as a purr and the kitten, calm at last, jumps straight into their arms.",
            fr: "{name} chante une berceuse douce comme un ronron et le chaton, enfin rassuré, saute droit dans ses bras.",
          },
          next: "ending",
        },
      ],
    },
    c3_badge_c: {
      id: "c3_badge_c",
      chapter: 3,
      question: {
        es: "Sin sus gafas, el abuelo Justo no podrá leer el cuento de hoy a los niños del parque. ¿Cómo las encuentra {name}?",
        ca: "Sense les ulleres, l'avi Just no podrà llegir el conte d'avui als nens del parc. Com les troba {name}?",
        en: "Without his glasses, Grandpa Justo won't be able to read today's story to the children in the park. How does {name} find them?",
        fr: "Sans ses lunettes, papi Justo ne pourra pas lire l'histoire du jour aux enfants du parc. Comment {name} va les retrouver ?",
      },
      options: [
        {
          id: "follow-steps",
          title: {
            es: "Seguir sus pasos",
            ca: "Seguir les seves passes",
            en: "Follow his steps",
            fr: "Suivre ses pas",
          },
          desc: {
            es: "Repetir el paseo de la mañana, pista a pista, como un buen detective.",
            ca: "Repetir el passeig del matí, pista a pista, com un bon detectiu.",
            en: "Retrace the morning walk, clue by clue, like a good detective.",
            fr: "Refaire la promenade du matin, indice après indice, comme un bon détective.",
          },
          imageSeed: "superhero-c3badgec-footsteps",
          icon: "footprint",
          narrative: {
            es: "{name} repite el paseo del abuelo pista a pista, desde el quiosco hasta el estanque, y encuentra las gafas junto al banco de las flores.",
            ca: "{name} repeteix el passeig de l'avi pista a pista, des del quiosc fins a l'estany, i troba les ulleres al costat del banc de les flors.",
            en: "{name} retraces the grandpa's walk clue by clue, from the kiosk to the pond, and finds the glasses beside the flower bench.",
            fr: "{name} refait la promenade du papi indice après indice, du kiosque jusqu'à l'étang, et trouve les lunettes près du banc aux fleurs.",
          },
          next: "ending",
        },
        {
          id: "sun-sparkle",
          title: {
            es: "El brillo al sol",
            ca: "La lluentor al sol",
            en: "The sparkle in the sun",
            fr: "L'éclat au soleil",
          },
          desc: {
            es: "Los cristales de unas gafas brillan como estrellitas cuando les da el sol.",
            ca: "Els vidres d'unes ulleres brillen com estrelletes quan els toca el sol.",
            en: "Glasses lenses sparkle like little stars when the sun hits them.",
            fr: "Les verres de lunettes brillent comme des petites étoiles quand le soleil les touche.",
          },
          imageSeed: "superhero-c3badgec-sparkle",
          icon: "search",
          narrative: {
            es: "{name} se sube a lo alto del tobogán, mira despacio todo el parque y descubre un brillito de cristal escondido entre los tréboles.",
            ca: "{name} s'enfila a dalt del tobogan, mira a poc a poc tot el parc i descobreix una lluentor de vidre amagada entre els trèvols.",
            en: "{name} climbs to the top of the slide, scans the whole park slowly and spots a glassy glint hidden among the clovers.",
            fr: "{name} grimpe en haut du toboggan, observe lentement tout le parc et repère un petit éclat de verre caché parmi les trèfles.",
          },
          next: "ending",
        },
        {
          id: "ask-pigeons",
          title: {
            es: "Preguntar a las palomas",
            ca: "Preguntar als coloms",
            en: "Ask the pigeons",
            fr: "Demander aux pigeons",
          },
          desc: {
            es: "Las palomas del parque lo ven todo desde el aire.",
            ca: "Els coloms del parc ho veuen tot des de l'aire.",
            en: "The park pigeons see everything from the air.",
            fr: "Les pigeons du parc voient tout depuis le ciel.",
          },
          imageSeed: "superhero-c3badgec-pigeons",
          icon: "raven",
          narrative: {
            es: "{name} comparte miguitas con las palomas del parque y ellas vuelan bajito en círculos para señalar el seto donde duermen las gafas.",
            ca: "{name} comparteix molletes amb els coloms del parc i ells volen baixet fent cercles per assenyalar la tanca on dormen les ulleres.",
            en: "{name} shares breadcrumbs with the park pigeons and they fly low in circles to point out the hedge where the glasses are resting.",
            fr: "{name} partage des miettes avec les pigeons du parc et ils volent bas en cercles pour montrer la haie où dorment les lunettes.",
          },
          next: "ending",
        },
      ],
    },
    c3_sky_a: {
      id: "c3_sky_a",
      chapter: 3,
      question: {
        es: "Si las nubes siguen enredadas, toda la lluvia caerá en un solo barrio de la ciudad. ¿Cómo las desenreda {name} con delicadeza?",
        ca: "Si els núvols continuen embolicats, tota la pluja caurà en un sol barri de la ciutat. Com els desembolica {name} amb delicadesa?",
        en: "If the clouds stay tangled, all the rain will fall on just one neighbourhood of the city. How does {name} untangle them gently?",
        fr: "Si les nuages restent emmêlés, toute la pluie tombera sur un seul quartier de la ville. Comment {name} va les démêler en douceur ?",
      },
      options: [
        {
          id: "silver-comb",
          title: {
            es: "El peine plateado",
            ca: "La pinta platejada",
            en: "The silver comb",
            fr: "Le peigne argenté",
          },
          desc: {
            es: "El peine gigante de la estación deja las nubes suaves y esponjosas.",
            ca: "La pinta gegant de l'estació deixa els núvols suaus i esponjosos.",
            en: "The station's giant comb leaves the clouds soft and fluffy.",
            fr: "Le peigne géant de la station rend les nuages doux et moelleux.",
          },
          imageSeed: "superhero-c3skya-comb",
          icon: "brush",
          narrative: {
            es: "{name} peina las nubes con el peine plateado gigante hasta dejarlas sueltas, suaves y esponjosas.",
            ca: "{name} pentina els núvols amb la pinta platejada gegant fins a deixar-los solts, suaus i esponjosos.",
            en: "{name} combs the clouds with the giant silver comb until they come loose, soft and fluffy.",
            fr: "{name} peigne les nuages avec le peigne argenté géant jusqu'à les rendre libres, doux et moelleux.",
          },
          next: "ending",
        },
        {
          id: "feather-tickles",
          title: {
            es: "Cosquillas de pluma",
            ca: "Pessigolles de ploma",
            en: "Feather tickles",
            fr: "Chatouilles à la plume",
          },
          desc: {
            es: "Con unas buenas cosquillas, las nubes ríen y se sueltan solas.",
            ca: "Amb unes bones pessigolles, els núvols riuen i es deixen anar sols.",
            en: "With a good tickle, the clouds laugh and let go of each other all by themselves.",
            fr: "Avec de bonnes chatouilles, les nuages rient et se détachent tout seuls.",
          },
          imageSeed: "superhero-c3skya-tickle",
          icon: "waving_hand",
          narrative: {
            es: "{name} hace cosquillas a las nubes con una pluma blanca y ellas, entre risas, se van soltando una a una.",
            ca: "{name} fa pessigolles als núvols amb una ploma blanca i ells, entre rialles, es van deixant anar un a un.",
            en: "{name} tickles the clouds with a white feather and, giggling, they let go of each other one by one.",
            fr: "{name} chatouille les nuages avec une plume blanche et, entre deux fous rires, ils se détachent un à un.",
          },
          next: "ending",
        },
        {
          id: "sky-song",
          title: {
            es: "La canción del cielo",
            ca: "La cançó del cel",
            en: "The sky song",
            fr: "La chanson du ciel",
          },
          desc: {
            es: "Una melodía lenta que invita a las nubes a bailar separadas.",
            ca: "Una melodia lenta que convida els núvols a ballar separats.",
            en: "A slow melody that invites the clouds to dance apart.",
            fr: "Une mélodie lente qui invite les nuages à danser chacun de son côté.",
          },
          imageSeed: "superhero-c3skya-song",
          icon: "queue_music",
          narrative: {
            es: "{name} y Nimba cantan la canción del cielo y las nubes se separan bailando un vals muy despacito.",
            ca: "{name} i la Nimba canten la cançó del cel i els núvols se separen ballant un vals molt a poc a poc.",
            en: "{name} and Nimba sing the sky song and the clouds drift apart, dancing a very slow waltz.",
            fr: "{name} et Nimba chantent la chanson du ciel et les nuages se séparent en dansant une valse tout doucement.",
          },
          next: "ending",
        },
      ],
    },
    c3_sky_b: {
      id: "c3_sky_b",
      chapter: 3,
      question: {
        es: "El arcoíris lleva tantos días enrollado que se ha quedado dormido y un poco pálido. ¿Cómo lo despierta {name} para que vuelva a cruzar el cielo?",
        ca: "L'arc de Sant Martí fa tants dies que està enrotllat que s'ha quedat adormit i una mica pàl·lid. Com el desperta {name} perquè torni a creuar el cel?",
        en: "The rainbow has been rolled up for so many days that it has fallen asleep and gone a little pale. How does {name} wake it so it can stretch across the sky again?",
        fr: "L'arc-en-ciel est resté enroulé tant de jours qu'il s'est endormi et a un peu pâli. Comment {name} va le réveiller pour qu'il traverse à nouveau le ciel ?",
      },
      options: [
        {
          id: "gentle-stretch",
          title: {
            es: "Estirarlo entre dos",
            ca: "Estirar-lo entre dos",
            en: "Stretch it out together",
            fr: "L'étirer à deux",
          },
          desc: {
            es: "Cada punta en una mano, despacito, como una cinta gigante.",
            ca: "Cada punta en una mà, a poc a poc, com una cinta gegant.",
            en: "One end in each pair of hands, nice and slow, like a giant ribbon.",
            fr: "Chaque bout dans une main, tout doucement, comme un ruban géant.",
          },
          imageSeed: "superhero-c3skyb-stretch",
          icon: "open_in_full",
          narrative: {
            es: "{name} y Nimba cogen el arcoíris por las puntas y lo estiran despacito hasta que cruza el cielo entero.",
            ca: "{name} i la Nimba agafen l'arc de Sant Martí per les puntes i l'estiren a poc a poc fins que creua el cel sencer.",
            en: "{name} and Nimba take the rainbow by its ends and stretch it slowly until it arcs across the whole sky.",
            fr: "{name} et Nimba prennent l'arc-en-ciel par les bouts et l'étirent tout doucement jusqu'à ce qu'il traverse le ciel entier.",
          },
          next: "ending",
        },
        {
          id: "colour-joke",
          title: {
            es: "Un chiste de colores",
            ca: "Un acudit de colors",
            en: "A colour joke",
            fr: "Une blague en couleurs",
          },
          desc: {
            es: "Dicen que los arcoíris se desenrollan de risa con un buen chiste.",
            ca: "Diuen que els arcs de Sant Martí es desenrotllen de riure amb un bon acudit.",
            en: "They say rainbows unroll with laughter at a good joke.",
            fr: "On dit que les arcs-en-ciel se déroulent de rire avec une bonne blague.",
          },
          imageSeed: "superhero-c3skyb-joke",
          icon: "sentiment_satisfied",
          narrative: {
            es: "{name} le cuenta al arcoíris el chiste del tomate que se puso rojo y él se desenrolla de golpe, riendo con sus siete colores.",
            ca: "{name} explica a l'arc de Sant Martí l'acudit del tomàquet que es va posar vermell i ell es desenrotlla de cop, rient amb els seus set colors.",
            en: "{name} tells the rainbow the joke about the tomato that turned red, and it unrolls all at once, laughing with all seven colours.",
            fr: "{name} raconte à l'arc-en-ciel la blague de la tomate devenue toute rouge, et il se déroule d'un coup, riant de ses sept couleurs.",
          },
          next: "ending",
        },
        {
          id: "sunbeam-window",
          title: {
            es: "La ventana del sol",
            ca: "La finestra del sol",
            en: "The sun window",
            fr: "La fenêtre du soleil",
          },
          desc: {
            es: "Un chorrito de sol calentito despierta cualquier color dormido.",
            ca: "Un rajolí de sol calentó desperta qualsevol color adormit.",
            en: "A little stream of warm sunlight wakes any sleeping colour.",
            fr: "Un petit filet de soleil bien chaud réveille n'importe quelle couleur endormie.",
          },
          imageSeed: "superhero-c3skyb-sunbeam",
          icon: "wb_sunny",
          narrative: {
            es: "{name} abre la gran ventana del sol y un rayo calentito acaricia el arcoíris, que se despierta brillando con todos sus colores.",
            ca: "{name} obre la gran finestra del sol i un raig calentó acarona l'arc de Sant Martí, que es desperta brillant amb tots els seus colors.",
            en: "{name} opens the great sun window and a warm beam strokes the rainbow, which wakes up glowing with all its colours.",
            fr: "{name} ouvre la grande fenêtre du soleil et un rayon tout chaud caresse l'arc-en-ciel, qui se réveille en brillant de toutes ses couleurs.",
          },
          next: "ending",
        },
      ],
    },
    c3_sky_c: {
      id: "c3_sky_c",
      chapter: 3,
      question: {
        es: "El viento ronca tan fuerte que tiemblan las nubes, y sin él nada vuela en la ciudad. ¿Cómo lo despierta {name} sin enfadarlo?",
        ca: "El vent ronca tan fort que tremolen els núvols, i sense ell res no vola a la ciutat. Com el desperta {name} sense fer-lo enfadar?",
        en: "The wind snores so loudly that the clouds tremble, and without him nothing flies in the city. How does {name} wake him without making him grumpy?",
        fr: "Le vent ronfle si fort que les nuages tremblent, et sans lui rien ne vole dans la ville. Comment {name} va le réveiller sans le fâcher ?",
      },
      options: [
        {
          id: "breeze-whistle",
          title: {
            es: "El silbato de brisa",
            ca: "El xiulet de brisa",
            en: "The breeze whistle",
            fr: "Le sifflet de brise",
          },
          desc: {
            es: "Su nota suave despierta al viento de buen humor.",
            ca: "La seva nota suau desperta el vent de bon humor.",
            en: "Its soft note wakes the wind up in a good mood.",
            fr: "Sa note douce réveille le vent de bonne humeur.",
          },
          imageSeed: "superhero-c3skyc-whistle",
          icon: "sports",
          narrative: {
            es: "{name} sopla el silbato de brisa de Nimba y el viento abre un ojo, sonríe y se despereza soplando suavecito.",
            ca: "{name} bufa el xiulet de brisa de la Nimba i el vent obre un ull, somriu i s'estira bufant fluixet.",
            en: "{name} blows Nimba's breeze whistle and the wind opens one eye, smiles and stretches with a gentle puff.",
            fr: "{name} souffle dans le sifflet de brise de Nimba et le vent ouvre un œil, sourit et s'étire en soufflant tout doucement.",
          },
          next: "ending",
        },
        {
          id: "hot-chocolate",
          title: {
            es: "Olor a chocolate",
            ca: "Olor de xocolata",
            en: "The smell of chocolate",
            fr: "Une odeur de chocolat",
          },
          desc: {
            es: "El olorcito de una taza calentita despierta hasta al viento más dormilón.",
            ca: "L'oloreta d'una tassa calentona desperta fins i tot el vent més dormilega.",
            en: "The smell of a warm cup wakes even the sleepiest wind.",
            fr: "Le parfum d'une tasse bien chaude réveille même le vent le plus endormi.",
          },
          imageSeed: "superhero-c3skyc-chocolate",
          icon: "local_cafe",
          narrative: {
            es: "{name} prepara una taza de chocolate calentito y el viento se despierta olisqueando, con la nariz por delante.",
            ca: "{name} prepara una tassa de xocolata calentona i el vent es desperta ensumant, amb el nas per davant.",
            en: "{name} makes a cup of warm chocolate and the wind wakes up sniffing, nose first.",
            fr: "{name} prépare une tasse de chocolat bien chaud et le vent se réveille en reniflant, le nez en avant.",
          },
          next: "ending",
        },
        {
          id: "paper-pinwheel",
          title: {
            es: "El molinillo de papel",
            ca: "El molinet de paper",
            en: "The paper pinwheel",
            fr: "Le moulinet en papier",
          },
          desc: {
            es: "Un molinillo girando es una invitación a jugar que ningún viento rechaza.",
            ca: "Un molinet girant és una invitació a jugar que cap vent no rebutja.",
            en: "A spinning pinwheel is an invitation to play that no wind can refuse.",
            fr: "Un moulinet qui tourne est une invitation à jouer qu'aucun vent ne refuse.",
          },
          imageSeed: "superhero-c3skyc-pinwheel",
          icon: "toys",
          narrative: {
            es: "{name} dobla un molinillo de papel y lo hace girar delante del viento, que se despierta soplando con ganas de jugar.",
            ca: "{name} doblega un molinet de paper i el fa girar davant del vent, que es desperta bufant amb ganes de jugar.",
            en: "{name} folds a paper pinwheel and spins it in front of the wind, who wakes up puffing, eager to play.",
            fr: "{name} plie un moulinet en papier et le fait tourner devant le vent, qui se réveille en soufflant, tout prêt à jouer.",
          },
          next: "ending",
        },
      ],
    },
    ending: {
      id: "ending",
      chapter: 4,
      question: { es: "", ca: "", en: "", fr: "" },
      options: [],
    },
  },
};
