/**
 * The one example child the landing's "how / proof / print" sections follow:
 * Noa, 4, a real showcase book (forest world) that exists in every locale, generated by the
 * current production pipeline (showcase v2, 2026-09-30). Its art is copied from the book's final
 * renders to /public/images/landing/noa as right-sized webp (≤ ~95 KB each; the originals are 2–4 MB).
 * If that story ever stops being a showcase, swap the id + art here; `gender` drives the Catalan
 * personal article in the landing strings ("de la Noa" / "d'en Hugo").
 */
export const LANDING_EXAMPLE = {
  childName: "Noa",
  age: 4,
  gender: "girl",
  templateId: "forest",
  /** Noa's own pre-rendered portrait of the "Créalo tú" builder (girl · 3–6 · light skin · red curly hair). */
  avatarSrc: "/images/avatar/girl/small/light/red-curly.webp",
  skinTone: "light",
  /** Square crop of the print cover art (640²). */
  coverSrc: "/images/landing/noa/cover.webp",
  /** Panorama spread (1200×600) used as "the preview before paying". */
  previewScene: "/images/landing/noa/scene-3.webp",
  /** Panorama spread (1200×600) shown in the open printed book. */
  printSpread: "/images/landing/noa/scene-8.webp",
  /** Scenes shown as proof that each page is painted for the story (640² each). */
  scenes: [
    { src: "/images/landing/noa/scene-4.webp", width: 640, height: 640 },
    { src: "/images/landing/noa/scene-7.webp", width: 640, height: 640 },
    { src: "/images/landing/noa/scene-9.webp", width: 640, height: 640 },
    { src: "/images/landing/noa/scene-10.webp", width: 640, height: 640 },
  ],
} as const;

/** The same book in each locale: its showcase story (for /examples/{id}) and printed title. */
const EXAMPLE_BOOK: Record<string, { storyId: string; title: string }> = {
  es: { storyId: "bc6e2dbd-fd14-4c5d-a9d0-07b10cffdbf2", title: "Noa y la llave de flor" },
  ca: { storyId: "5dfc4f5e-9a42-4ae5-a42b-a821d36c2f01", title: "La Noa i la clau de flor" },
  en: { storyId: "602106d0-7b6d-4f6b-a862-bedb0eb6debc", title: "Noa and the Flower Key" },
  fr: { storyId: "7294b4d0-ecd1-4dcb-a744-faead62d58ba", title: "Noa et la clé-fleur" },
};

export function landingExampleBook(locale: string) {
  return EXAMPLE_BOOK[locale] ?? EXAMPLE_BOOK.es;
}
