// What the posts are teaching us, as numbers: joins every post in docs/social/posts/<date>/ (its strategy, voice,
// length, people) with its Zernio analytics and writes docs/social/scoreboard.md. Read it before creating a post:
//   node scripts/social/learn.mjs
// One post a day, so a post is matched by its Madrid publication day. A pattern is only reported as a lead when
// it has at least MIN_POSTS posts on each side: with ~250 views a video, one post proves nothing.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { api, meapicaAccounts } from "./zernio.mjs";

const POSTS = "docs/social/posts";
const MIN_POSTS = 3;
const day = (iso) => new Intl.DateTimeFormat("sv-SE", { timeZone: "Europe/Madrid" }).format(new Date(iso));
const avg = (xs) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null);
const f = (x, d = 1) => (x == null || Number.isNaN(x) ? "–" : x.toFixed(d));
console.assert(day("2026-10-08T22:30:00Z") === "2026-10-09", "Madrid day"); // ponytail: the one check that matters, late-night posts

const posts = readdirSync(POSTS).filter((d) => /^\d{4}-\d{2}-\d{2}$/.test(d) && existsSync(`${POSTS}/${d}/post.json`)).sort().map((date) => {
  const p = JSON.parse(readFileSync(`${POSTS}/${date}/post.json`, "utf8"));
  const vj = existsSync(`${POSTS}/${date}/video.json`) ? JSON.parse(readFileSync(`${POSTS}/${date}/video.json`, "utf8")) : null;
  const video = p.media?.[0]?.type === "video" ? `${POSTS}/${date}/${p.media[0].file}` : null;
  const seconds = video && existsSync(video) ? Number(execFileSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", video])) : null;
  return { date, title: p.title, lang: p.lang, strategy: p.strategy ?? "?", people: !!p.people, voice: !!vj?.beats?.some((b) => b.say), format: video ? "video" : "carousel", seconds, m: {} };
});

const from = posts[0]?.date, byDate = Object.fromEntries(posts.map((p) => [p.date, p]));
for (const [platform, a] of Object.entries(await meapicaAccounts())) {
  if (!a) continue;
  const r = await api("GET", `/analytics?accountId=${a._id}&fromDate=${from}&limit=100&sortBy=date&order=desc`);
  for (const z of r.json.posts ?? []) {
    const p = byDate[day(z.publishedAt ?? z.scheduledFor)];
    // Two uploads on one day (4 Oct): keep the one with more views.
    if (p && z.analytics && (p.m[platform]?.views ?? -1) < (z.analytics.views ?? 0)) p.m[platform] = z.analytics;
  }
}
for (const p of posts) {
  const { tiktok: t = {}, facebook: fb = {}, instagram: ig = {} } = p.m;
  const all = Object.values(p.m);
  p.views = all.reduce((s, x) => s + (x.views ?? 0), 0);
  p.ttWatch = t.views ? t.igReelsAvgWatchTime / 1000 : null;
  p.ttDone = t.views ? t.completionRate * 100 : null;
  p.fbRet3 = fb.views >= 50 && fb.retentionCurve?.["3"] != null ? fb.retentionCurve["3"] * 100 : null;
  p.acts = all.reduce((s, x) => s + (x.saves ?? 0) + (x.shares ?? 0), 0);
  p.actsPerK = p.views ? (p.acts / p.views) * 1000 : null;
  p.igViews = ig.views ?? 0;
}
const measured = posts.filter((p) => p.views > 0);

const row = (p) => `| ${p.date.slice(5)} | ${p.title.slice(0, 44)} | ${p.strategy} | ${p.lang} | ${p.voice ? "voz" : "muda"} | ${p.people ? "sí" : "no"} | ${p.seconds ? Math.round(p.seconds) : "–"} | ${p.views} | ${f(p.ttWatch)} | ${f(p.ttDone)} | ${f(p.fbRet3, 0)} | ${p.acts} |`;
const cut = (label, key, name = (v) => String(v)) => {
  const groups = Object.entries(Object.groupBy(measured.filter((p) => p.format === "video"), (p) => name(p[key])));
  const lines = groups.map(([g, ps]) => `| ${label}: ${g} | ${ps.length} | ${f(avg(ps.map((p) => p.views)), 0)} | ${f(avg(ps.filter((p) => p.ttWatch != null).map((p) => p.ttWatch)))} | ${f(avg(ps.filter((p) => p.ttDone != null).map((p) => p.ttDone)))} | ${f(avg(ps.filter((p) => p.fbRet3 != null).map((p) => p.fbRet3)), 0)} | ${f(avg(ps.map((p) => p.actsPerK)))} | ${groups.every(([, x]) => x.length >= MIN_POSTS) && groups.length > 1 ? "comparable" : "too few posts"} |`);
  return lines.join("\n");
};
const out = `# Scoreboard (generated by scripts/social/learn.mjs, ${day(new Date().toISOString())}; do not edit)

Read this before creating a post. Numbers lag up to 48 h. Posts with no views yet are listed but not averaged.
A cut marked "too few posts" (fewer than ${MIN_POSTS} on a side) is not evidence: keep testing it, do not act on it.

## Every post

| Day | Post | Strategy | Lang | Voice | People | s | Views | TikTok avg watch s | TikTok finished % | Facebook still watching at 3 s % | Saves + sends |
|---|---|---|---|---|---|---|---|---|---|---|---|
${posts.map(row).join("\n")}

## Averages by what we chose (videos only)

| Cut | Posts | Views | TikTok avg watch s | TikTok finished % | Facebook at 3 s % | Saves + sends per 1,000 views | Evidence |
|---|---|---|---|---|---|---|---|
${[cut("strategy", "strategy"), cut("voice", "voice", (v) => (v ? "yes" : "no")), cut("people", "people", (v) => (v ? "yes" : "no")), cut("language", "lang"), cut("length", "seconds", (s) => (s < 25 ? "under 25 s" : s < 45 ? "25-45 s" : "over 45 s"))].join("\n")}

Best so far by TikTok average watch time: ${measured.filter((p) => p.ttWatch != null).sort((a, b) => b.ttWatch - a.ttWatch).slice(0, 3).map((p) => `${p.date.slice(5)} ${p.strategy} (${f(p.ttWatch)} s)`).join(", ") || "no data"}.
`;
writeFileSync("docs/social/scoreboard.md", out);
console.log(out);
