import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getTranslations } from "next-intl/server";
import { routing } from "@/i18n/routing";
import Tracking from "@/components/tracking/Tracking";
import RootDocument from "@/app/_components/RootDocument";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const BASE_URL = "https://meapica.shop";

const LOCALE_MAP: Record<string, string> = {
  es: "es_ES",
  ca: "ca_ES",
  en: "en_US",
  fr: "fr_FR",
};

const LANG_MAP: Record<string, string> = {
  es: "es",
  ca: "ca",
  en: "en",
  fr: "fr",
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "metadata" });

  const canonicalUrl = `${BASE_URL}/${locale}`;

  // Build hreflang alternates for all supported locales
  const languages: Record<string, string> = {};
  for (const loc of routing.locales) {
    languages[LANG_MAP[loc] || loc] = `${BASE_URL}/${loc}`;
  }
  // x-default points to the default locale
  languages["x-default"] = `${BASE_URL}/${routing.defaultLocale}`;

  return {
    metadataBase: new URL(BASE_URL),
    title: {
      default: t("title"),
      template: `%s | Meapica`,
    },
    description: t("description"),
    keywords: t("keywords"),
    authors: [{ name: "Meapica" }],
    creator: "Meapica",
    publisher: "Meapica",
    icons: {
      shortcut: "/favicon.ico",
      icon: [
        { url: "/images/favicon-32.png", sizes: "32x32", type: "image/png" },
        { url: "/images/favicon-16.png", sizes: "16x16", type: "image/png" },
      ],
      apple: "/images/apple-touch-icon.png",
    },
    manifest: "/manifest.json",
    alternates: {
      canonical: canonicalUrl,
      languages,
    },
    openGraph: {
      title: t("title"),
      description: t("description"),
      type: "website",
      url: canonicalUrl,
      siteName: "Meapica",
      locale: LOCALE_MAP[locale] || "es_ES",
      // Images are auto-generated by opengraph-image.tsx in this route segment
    },
    twitter: {
      card: "summary_large_image",
      title: t("title"),
      description: t("description"),
      // Images are auto-generated by twitter-image.tsx in this route segment
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
  };
}

// Marketing pages render the seasonal banner (Navbar) from the date they were
// rendered on: re-render at most hourly so static pages never serve a stale
// season (the home and /christmas-delivery already do; dynamic pages unaffected).
export const revalidate = 3600;

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as (typeof routing.locales)[number])) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <RootDocument lang={locale}>
      <NextIntlClientProvider messages={messages}>
        {children}
        <Tracking />
      </NextIntlClientProvider>
    </RootDocument>
  );
}
